<style>
    .highcharts-legend{display: none;}
    .highcharts-title{display: none;}
</style>
<div id="container" style=" width: 100%; height: 465px; margin: 0 auto"></div>
            <div class="row chart-info">
              <div class="col-xs-4" style="text-align:center;"><span class="title">From Date</span><span class="number"><?php if(isset($perf1[0]['oldestDate']) && trim($perf1[0]['oldestDate'])!= ''){ echo $this->humanDateFormat($perf1[0]['oldestDate']); } else { echo "-"; } ?></span></div>
              <div class="col-xs-4" style="text-align:center;padding-left:5px;;"><span class="title">To Date</span><span class="number"><?php if(isset($perf1[0]['newestDate']) && trim($perf1[0]['newestDate'])!= ''){ echo $this->humanDateFormat($perf1[0]['newestDate']); } else { echo "-"; } ?></span></div>
              <div class="col-xs-4" style="text-align:center;"><span class="title">No. of Audits</span><span class="number"><?php echo $perf1[0]['totalDataPoints']; ?></span></div>
            </div>
<script>
    $(document).ready(function(){
      	//initialize the javascript
        radar_chart();
    });
    function radar_chart(){
	$('#container').highcharts({

        chart: {
            polar: true,
            type: 'line'
        },

        title: {
            text: 'Audit Performance',
            //x: -80
        },

        pane: {
            size: '90%'
        },

        xAxis: {
            categories: ["Personnel Training & Certification", "Physical", "Safety", "Pre-Testing", "Testing", "Post Testing Phase", "External Quality Audit"],
            tickmarkPlacement: 'on',
            lineWidth: 0
        },

	
        yAxis: {
            gridLineInterpolation: 'polygon',
            
        },

        tooltip: {
            shared: true,
            pointFormat: '<span style="color:{series.color}">X: <b>{point.y:0f}</b><br/>'
        },
        series: [
	    <?php
	    foreach ($auditRoundWiseData as $auditNo => $adata){
		?>
		{
		//name : 'Audit <?php echo $auditNo; ?>',
		name : 'Audit Performance',
        pointPlacement: 'on',
		data:[<?php echo round($adata['PERSONAL_SCORE'],2); ?>,
		                   <?php echo round($adata['PHYSICAL_SCORE'],2); ?>,
				   <?php echo round($adata['SAFETY_SCORE'],2); ?>,
				   <?php echo round($adata['PRETEST_SCORE'],2); ?>,
				   <?php echo round($adata['TEST_SCORE'],2); ?>,
				   <?php echo round($adata['POST_SCORE'],2); ?>,
				   <?php echo round($adata['EQA_SCORE'],2); ?>,],
		},
		<?php
	    }
	    ?>
        ]

    });
    }
</script>