<?php
// Extend the TCPDF class to create custom Header and Footer
$configFile = CONFIG_PATH . DIRECTORY_SEPARATOR . "label.php";
$fileContents=file_get_contents($configFile);
//Convert the JSON string back into an array.
$decoded = json_decode($fileContents, true);
$language = $configData['language'];
class MYPDF extends TCPDF {
    
    public function setSchemeName($header,$logo) {
	$this->header = $header;
	$this->logo = $logo;
    }
	
    //Page header
    public function Header() {
        // Logo
        if(trim($this->logo)!="" && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo'. DIRECTORY_SEPARATOR.$this->logo)){
	    $image_file = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo'. DIRECTORY_SEPARATOR.$this->logo;
	    $extension = strtolower(pathinfo(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo'. DIRECTORY_SEPARATOR.$this->logo,PATHINFO_EXTENSION));
	    $this->Image($image_file, 12,3,20, '',strtoupper($extension), '', 'T', false, 300, 'L', false, false, 0, false, false, false);
	}
        // Set font
        $this->SetFont('helvetica', 'B', 12);
        // Title
        $this->writeHTMLCell(0,'',33,10,$this->header,0,1,false,true,'C',true);
        $this->writeHTMLCell(180,'',15,20,'<br/><hr/>',0,1,false,true,'C',true);
    }

    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', 'I', 8);
        // Page number
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

$pdf->setSchemeName(ucwords($configData['header']),$configData['logo']);
// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('ODK DASHBOARD');
$pdf->SetTitle('SPI-RT Checklist');
$pdf->SetSubject('ODK DASHBOARD');
$pdf->SetKeywords('ODK DASHBOARD');


// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}
// ---------------------------------------------------------

// set font
$pdf->SetFont('times', '', 10);

// add a page
$pdf->AddPage();
//$pdf->SetY(20,true,false);

$partA='<p style="font-weight:bold;line-height:24px;">'.$decoded[$language]['/SPI_RT/TESTSITE/FACILITY/info2:label'].'</p>';
//$partA.='<br/>';

$pdf->writeHTML($partA, true, 0, true, 0);

$pdf->writeHTMLCell('',12,'','','<p>'.$decoded[$language]['/SPI_RT/TESTSITE/FACILITY/info2:hint'].'</p>',0,1,false,true,'L',true);
if($language=='Portuguese'){
	$langDateFormat='(dd/mm/aaaa)';
}else if($language=='Spanish'){
	$langDateFormat='(dd/mm/aaaa)';
}
else{
	$langDateFormat='(dd/mm/yyyy)';
}

$fId = (isset($formData['facilityInfo']['ffId']))?ucwords($formData['facilityInfo']['ffId']):'';
$fName = (isset($formData['facilityInfo']['fName']))?ucwords($formData['facilityInfo']['fName']):'';
$testingTab='<table border="1" cellspacing="0" cellpadding="5">';
$testingTab.='<tr>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/assesmentofaudit:label'].'</b>'.$langDateFormat.': '.$this->humanDateFormat($formData['assesmentofaudit']).'</td>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/auditroundno:label'].'</b> '.$formData['auditroundno'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/facilityname:label'].'</b> '.$fName.'</td>';
if($language=='Portuguese'){
$testingTab.='<td><b>Identificacao do local de testagem </b>(se aplicavel): '.$fId.'</td>';
}else if($language=='Spanish'){
$testingTab.='<td><b>Tipo de sitio de pruebas </b>(seleccione uno): '.$fId.'</td>';
}
else{
$testingTab.='<td><b>Testing Facility ID</b>(if applicable) : '.$fId.'</td>';	
}
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/testingpointname:label'].'</b> '.$formData['testingpointname'].'</td>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/testingpointtype:label'].'</b> '.$formData['testingpointtype'];
$testingTab.=((isset($formData['testingpointtype_other']) && $formData['testingpointtype_other'] != "") ? " - " . $formData['testingpointtype_other']: "").'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td colspan="2"><b>'.$decoded[$language]['/SPI_RT/TESTSITE/locationaddress:label'].'</b> '.$formData['locationaddress'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/level:label'].'</b> <br/>'.$formData['level'];
$testingTab.=((isset($formData['level_other']) && $formData['level_other'] != "") ? " Other - " . $formData['level_other'] : "").':'.$formData['level_name'];
$testingTab.='</td>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/affiliation:label'].'</b><br/>'.$formData['affiliation'];
$testingTab.=((isset($formData['affiliation_other']) && $formData['affiliation_other'] != "") ? " Other : " . $formData['affiliation_other'] : "");
$testingTab.='</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/NumberofTester:label'].'</b>'.$formData['NumberofTester'].'</td>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/avgMonthTesting:label'].'</b>'.$formData['avgMonthTesting'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/name_auditor_lead:label'].'</b>'.$formData['name_auditor_lead'].'</td>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/name_auditor2:label'].'</b>'.$formData['name_auditor2'].'</td>';
$testingTab.='</tr>';

$testingTab.='</table>';

$pdf->writeHTML($testingTab, true, 0, true, 0);

$partBHeading='<b>'.$decoded[$language]['/SPI_RT/SPIRT/info4:label'].'</b>';

$pdf->writeHTML($partBHeading, true, 0, true, 0);


$partBCont='<br/><div>'.$decoded[$language]['/SPI_RT/SPIRT/info4:hint'].'</div>';

$pdf->writeHTML($partBCont, true, 0, true, 0);

$partBTable='<table border="1" cellspacing="0" cellpadding="5" style="width:100%;">';
$partBTable.="<tr>";
$language;
if($language=='Portuguese'){
	$partBTable.='<td style="text-align:center;font-weight:bold;width:52%;">SECÇÃO</td>';
}
else{
	$partBTable.='<td style="text-align:center;font-weight:bold;width:52%;">SECTION</td>';
}

$partBTable.='<td style="text-align:center;font-weight:bold;width:7%;">'.$decoded[$language]['/SPI_RT/PERSONAL/PER_G_1_10/PERSONAL_Q_1_10/1:label'].'</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:8%;">'.$decoded[$language]['/SPI_RT/PERSONAL/PER_G_1_3/PERSONAL_Q_1_3/0.5:label'].'</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:7%;">'.$decoded[$language]['/SPI_RT/PERSONAL/PER_G_1_8/PERSONAL_Q_1_8/0:label'].'</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:18%;">'.$decoded[$language]['/SPI_RT/PERSONAL/PER_G_1_5/PERSONAL_C_1_5:label'].'</td>';
if($language=='Portuguese'){
	$partBTable.='<td style="text-align:center;font-weight:bold;width:8%;">Pontuação</td>';
}
elseif($language=='Spanish'){
	$partBTable.='<td style="text-align:center;font-weight:bold;width:8%;">Punteo</td>';
}
else{
	$partBTable.='<td style="text-align:center;font-weight:bold;width:8%;">Score</td>';	
}

$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/PERSONAL:label'].'</td>';
//$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">10</td>';
$partBTable.='</tr>';

    for($i=1;$i<11;$i++)
    {
	$partBTable.='<tr>';
	
	$partBTable.='<td style="width:52%;">'.$decoded[$language]['/SPI_RT/PERSONAL/PER_G_1_'.$i.'/PERSONAL_Q_1_'.$i.':label'].'</td>';
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['PERSONAL_Q_1_'.$i]) && $formData['PERSONAL_Q_1_'.$i] == 1 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['PERSONAL_Q_1_'.$i]) && $formData['PERSONAL_Q_1_'.$i] == 0.5 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['PERSONAL_Q_1_'.$i]) && $formData['PERSONAL_Q_1_'.$i] == "0" ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td>'.($formData['PERSONAL_C_1_'.$i]).'</td>';
	$partBTable.='<td style="text-align:center;">'.($formData['PERSONAL_Q_1_'.$i]).'</td>';
	$partBTable.='</tr>';
    }

$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/PERSONAL/PERSONAL_Display:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['PERSONAL_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/PHYSICAL:label'].'</td>';
//$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">5</td>';
$partBTable.='</tr>';

    for($i=1;$i<6;$i++)
    {
	
	$partBTable.='<tr>';
	
	$partBTable.='<td>'.$decoded[$language]['/SPI_RT/PHYSICAL/PHY_G_2_'.$i.'/PHYSICAL_Q_2_'.$i.':label'].'</td>';
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['PHYSICAL_Q_2_'.$i]) && $formData['PHYSICAL_Q_2_'.$i] == 1 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['PHYSICAL_Q_2_'.$i]) && $formData['PHYSICAL_Q_2_'.$i] == 0.5 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['PHYSICAL_Q_2_'.$i]) && $formData['PHYSICAL_Q_2_'.$i] == "0" ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td>'.($formData['PHYSICAL_C_2_'.$i]).'</td>';
	$partBTable.='<td style="text-align:center;">'.($formData['PHYSICAL_Q_2_'.$i]).'</td>';
	$partBTable.='</tr>';

    }

$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/PHYSICAL/PHYSICAL_Display:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['PHYSICAL_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/SAFETY:label'].'</td>';
//$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">11</td>';
$partBTable.='</tr>';

    for($i=1;$i<12;$i++)
    {
	$partBTable.='<tr>';
	
	$partBTable.='<td>'.$decoded[$language]['/SPI_RT/SAFETY/SAF_3_'.$i.'/SAFETY_Q_3_'.$i.':label'].'</td>';
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['SAFETY_Q_3_'.$i]) && $formData['SAFETY_Q_3_'.$i] == 1 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['SAFETY_Q_3_'.$i]) && $formData['SAFETY_Q_3_'.$i] == 0.5 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['SAFETY_Q_3_'.$i]) && $formData['SAFETY_Q_3_'.$i] == "0" ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td>'.($formData['SAFETY_C_3_'.$i]).'</td>';
	$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_'.$i]).'</td>';
	$partBTable.='</tr>';
    }
$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/SAFETY/SAFETY_DISPLAY:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['SAFETY_SCORE'].'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/PRETEST:label'].'</td>';
//$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">12</td>';
$partBTable.='</tr>';
    
    for($i=1;$i<13;$i++)
    {
    $partBTable.='<tr>';
    
    $partBTable.='<td>'.$decoded[$language]['/SPI_RT/PRETEST/PRE_4_'.$i.'/PRE_Q_4_'.$i.':label'].'</td>';
    $partBTable.='<td style="text-align:center;">';
    $partBTable.=(isset($formData['PRE_Q_4_'.$i]) && $formData['PRE_Q_4_'.$i] == 1 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
    $partBTable.='</td>';
    
    $partBTable.='<td style="text-align:center;">';
    $partBTable.=(isset($formData['PRE_Q_4_'.$i]) && $formData['PRE_Q_4_'.$i] == 0.5 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
    $partBTable.='</td>';
    
    $partBTable.='<td style="text-align:center;">';
    $partBTable.=(isset($formData['PRE_Q_4_'.$i]) && $formData['PRE_Q_4_'.$i] == "0" ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
    $partBTable.='</td>';
    
    $partBTable.='<td>'.($formData['PRE_C_4_'.$i]).'</td>';
    $partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_'.$i]).'</td>';
    $partBTable.='</tr>';
    }

$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/PRETEST/PRETEST_Display:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['PRETEST_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/TEST:label'].'</td>';
//$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">9</td>';
$partBTable.='</tr>';

    for($i=1;$i<10;$i++)
    {
	$partBTable.='<tr>';
	
	$partBTable.='<td>'.$decoded[$language]['/SPI_RT/TEST/TEST_5_'.$i.'/TEST_Q_5_'.$i.':label'].'</td>';
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['TEST_Q_5_'.$i]) && $formData['TEST_Q_5_'.$i] == 1 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['TEST_Q_5_'.$i]) && $formData['TEST_Q_5_'.$i] == 0.5 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['TEST_Q_5_'.$i]) && $formData['TEST_Q_5_'.$i] == "0" ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td>'.($formData['TEST_C_5_'.$i]).'</td>';
	$partBTable.='<td style="text-align:center;">'.($formData['TEST_Q_5_1']).'</td>';
	$partBTable.='</tr>';
    }
$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/TEST/TEST_DISPLAY:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['TEST_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/POSTTEST:label'].'</td>';
//$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">9</td>';
$partBTable.='</tr>';

    for($i=1;$i<10;$i++)
    {
    $partBTable.='<tr>';
    
    $partBTable.='<td>'.$decoded[$language]['/SPI_RT/POSTTEST/POST_6_'.$i.'/POST_Q_6_'.$i.':label'].'</td>';
    $partBTable.='<td style="text-align:center;">';
    $partBTable.=(isset($formData['POST_Q_6_'.$i]) && $formData['POST_Q_6_'.$i] == 1 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
    $partBTable.='</td>';
    
    $partBTable.='<td style="text-align:center;">';
    $partBTable.=(isset($formData['POST_Q_6_'.$i]) && $formData['POST_Q_6_'.$i] == 0.5 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
    $partBTable.='</td>';
    
    $partBTable.='<td style="text-align:center;">';
    $partBTable.=(isset($formData['POST_Q_6_'.$i]) && $formData['POST_Q_6_'.$i] == "0" ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
    $partBTable.='</td>';
    
    $partBTable.='<td>'.($formData['POST_C_6_'.$i]).'</td>';
    $partBTable.='<td style="text-align:center;">'.($formData['POST_Q_6_'.$i]).'</td>';
    $partBTable.='</tr>';
    }
$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/POSTTEST/POST_DISPLAY:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['POST_SCORE'].'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/EQA:label'].'</td>';
//$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">8/14</td>';
$partBTable.='</tr>';

    for($i=1;$i<9;$i++)
    {
	$partBTable.='<tr>';
	
	$partBTable.='<td>'.$decoded[$language]['/SPI_RT/EQA/EQA_7_'.$i.'/EQA_Q_7_'.$i.':label'].'</td>';
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['EQA_Q_7_'.$i]) && $formData['EQA_Q_7_'.$i] == 1 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['EQA_Q_7_'.$i]) && $formData['EQA_Q_7_'.$i] == 0.5 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['EQA_Q_7_'.$i]) && $formData['EQA_Q_7_'.$i] == "0" ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td>'.($formData['EQA_C_7_'.$i]).'</td>';
	$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_'.$i]).'</td>';
	$partBTable.='</tr>';
    }

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="text-align:center;font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/EQA/sampleretesting:label'].'</td>';
$partBTable.='</tr>';

    for($i=9;$i<15;$i++)
    {
	$partBTable.='<tr>';
	
	$partBTable.='<td>'.$decoded[$language]['/SPI_RT/EQA/SAMPLEREF/EQA_7_'.$i.'/EQA_Q_7_'.$i.':label'].'</td>';
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['EQA_Q_7_'.$i]) && $formData['EQA_Q_7_'.$i] == 1 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['EQA_Q_7_'.$i]) && $formData['EQA_Q_7_'.$i] == 0.5 ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['EQA_Q_7_'.$i]) && $formData['EQA_Q_7_'.$i] == "0" ) ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td>'.($formData['EQA_C_7_'.$i]).'</td>';
	$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_'.$i]).'</td>';
	$partBTable.='</tr>';
    }
$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/EQA/EQA_DISPLAY:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['EQA_SCORE'].'</td>';
$partBTable.='</tr>';

$partBTable.='</table>';
if($language=='Portuguese'){
$partBTable.='<p>*A area marcada com asteriscos so é aplicavel para os locais onde as amostras retestadas sao executadas.</p>';
}
else if($language=='Spanish'){
$partBTable.='<p>*Lo que aparece marcado con un asterisco son solo aplicables a sitios donde la repetición de las pruebas se hace.</p>';
}else{
$partBTable.='<p>*Those marked with an asterisk are only applicable to sites where sample retesting is performed.</p>';	
}

$pdf->writeHTML($partBTable, true, 0, true, 0);

$partC='<br/><p style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/scoring/info5:label'].'</p>';
$partC.='<br/><span>'.$decoded[$language]['/SPI_RT/scoring/info6:label'].'</span>';
$partC.='<p>'.$decoded[$language]['/SPI_RT/scoring/info10:label'].'</p>';
$partC.='<p>'.$decoded[$language]['/SPI_RT/scoring/info11:label'].'</p>';

$pdf->writeHTML($partC, true, 0, true, 0);

$summaryExp=explode(PHP_EOL,$decoded[$language]['/SPI_RT/SUMMARY/info17:label']);
$totPointScored='';
$totExpectScored='';
$perScored='';
if(isset($summaryExp[8]) && trim($summaryExp[8])!=""){
	$totPointScored=$summaryExp[8];
}
if(isset($summaryExp[9]) && trim($summaryExp[9])!=""){
	$totExpectScored=$summaryExp[9];
}
if(isset($summaryExp[10]) && trim($summaryExp[10])!=""){
	$expPerScored=explode("=",$summaryExp[10]);
	$perScored=(string) $expPerScored[0];
}

$partCTable='<table border="1" cellspacing="0" cellpadding="5">';

$partCTable.='<tr style="font-weight:bold;text-align:center;">';
if($language=='Portuguese'){
$partCTable.='<td style="width:15%">NIVEL</td>';
}
else if($language=='Spanish'){
$partCTable.='<td style="width:15%">Nivel</td>';
}else{
$partCTable.='<td style="width:15%">Levels</td>';	
}


if($language=='Portuguese'){
$partCTable.='<td  style="width:25%">PONTUACAO EM %</td>';
$partCTable.='<td  style="width:60%">DESCRIÇAO DOS RESULTADOS</td>';
}
else if($language=='Spanish'){
$partCTable.='<td  style="width:25%">% Puntaje</td>';
$partCTable.='<td  style="width:60%">Descripción de los resultados</td>';
}
else{
$partCTable.='<td  style="width:25%">'.$perScored.'</td>';
$partCTable.='<td  style="width:60%">Description of results</td>';	
}
$partCTable.='</tr>';

$level0=explode("-",$decoded[$language]['/SPI_RT/SUMMARY/info21:label']);
$level1=explode("-",$decoded[$language]['/SPI_RT/SUMMARY/info22:label']);
if(count($level1)>2){
	$level1[1]=$level1[1]." - ".$level1[2];
}
$level2=explode("-",$decoded[$language]['/SPI_RT/SUMMARY/info23:label']);
if(count($level2)>2){
	$level2[1]=$level2[1]." - ".$level2[2];
}
$level3=explode("-",$decoded[$language]['/SPI_RT/SUMMARY/info24:label']);
if(count($level3)>2){
	$level3[1]=$level3[1]." - ".$level3[2];
}
$level4=explode("-",$decoded[$language]['/SPI_RT/SUMMARY/info25:label']);

if($language=='Spanish'){
	$level0[0]="Nivel 0";
	$level0[1]="Menos de 40% ";
	$level1[0]="Nivel 1";
	$level2[0]="Nivel 2";
	$level3[0]="Nivel 3";
	$level4[0]="Nivel 4";
	$level4[1]="90% a más";
}

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#C00000;">'.$level0[0].'</td>';
$partCTable.='<td>'.$level0[1].'</td>';
if($language=='Portuguese'){
$partCTable.='<td>Necessidade de melhoria em todas as areas e remediaçoes imediatas</td>';
}
else if($language=='Spanish'){
$partCTable.='<td>Necesita mejorar en todas las áreas y es necesaria corrección inmediata</td>';
}else{
$partCTable.='<td>Needs improvement in all areas and immediate remediation</td>';	
}

$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#E36C0A;">'.$level1[0].'</td>';
$partCTable.='<td>'.$level1[1].'</td>';
if($language=='Portuguese'){
$partCTable.='<td>Necessidade de melhorias em areas especificas</td>';
}
else if($language=='Spanish'){
	$partCTable.='<td>Necesita mejorar en áreas específicas</td>';
}
else{
$partCTable.='<td>Needs improvement in specific areas</td>';	
}
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#FFFF00;">'.$level2[0].'</td>';
$partCTable.='<td>'.$level2[1].'</td>';
if($language=='Portuguese'){
$partCTable.='<td>Parcialmente admissivel ou aceitavel</td>';
}
else if($language=='Spanish'){
	$partCTable.='<td>Parcialmente elegible</td>';
}
else{
$partCTable.='<td>Partially eligible</td>';	
}
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#92D050;">'.$level3[0].'</td>';
$partCTable.='<td>'.$level3[1].'</td>';
if($language=='Portuguese'){
$partCTable.='<td>Proximo da certificaçao nacional</td>';
}
else if($language=='Spanish'){
$partCTable.='<td>Cercano a sitio nacional certificado</td>';
}
else{
$partCTable.='<td>Close to national site certification</td>';	
}
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#00B050;">'.$level4[0].'</td>';
$partCTable.='<td>'.$level4[1].'</td>';
if($language=='Portuguese'){
$partCTable.='<td>Admissivel a certificaçao nacional</td>';
}
else if($language=='Spanish'){
$partCTable.='<td>Elegible para ser certificado</td>';
}
else{
$partCTable.='<td>Eligible to national site certification</td>';	
}
$partCTable.='</tr>';

$partCTable.='</table>';

$pdf->writeHTML($partCTable,true,0,true,0);
$summationExp=explode(PHP_EOL,$decoded[$language]['/SPI_RT/SUMMARY/info12:label']);
$facilityName='';
if(isset($summationExp[0]) && trim($summationExp[0])!=""){
$heading=$summationExp[0];	
}
if(isset($summationExp[2]) && trim($summationExp[2])!=""){
$facilityName=$summationExp[2];
}
if(isset($summationExp[3]) && trim($summationExp[3])!=""){
$auditorName=$summationExp[3];
}
if(isset($summationExp[4]) && trim($summationExp[4])!=""){
  $textPointName=$summationExp[4];
}
$staffAuditedName = '';
$noOfTester = '';
if(isset($summationExp[5]) && trim($summationExp[5])!= ""){
    $expStaffAuditedName=explode(":",$summationExp[5]);
    $staffAuditedName=$expStaffAuditedName[0];
    $noOfTester=$expStaffAuditedName[1];
}
if($language=='Spanish'){
    $heading="PARTE D: Informe resumido del evaluador de la auditoría SPI-RT";
}

$partDTitle='<p style="font-weight:bold;line-height:30px;">'.$heading.'</p>';
$pdf->writeHTML($partDTitle,true,0,true,0);

$partDtableBox1='<table cellspacing="0" cellpadding="2">';
$partDtableBox1.="<tr><td>".$facilityName.$fName."</td></tr>";

$partDtableBox1.="<tr><td>";
if($language=='Portuguese'){
$partDtableBox1.="Tipo de local:";
}
else if($language=='Spanish'){
$partDtableBox1.="Tipo de sitio:";
}
else{
$partDtableBox1.="Site Type:";
}
$partDtableBox1.=$formData['testingpointtype'];

$partDtableBox1.=((isset($formData['testingpointtype_other']) && $formData['testingpointtype_other'] != "") ? " - " . $formData['testingpointtype_other']: "");
$partDtableBox1.="</td></tr>";
$partDtableBox1.="<tr><td>".$staffAuditedName.":".$formData['staffaudited']."</td></tr>";
$partDtableBox1.='</table>';
$pdf->writeHTMLCell(50,26,'','',$partDtableBox1,1, 0, 0, true, 'L');

$partDtableBox2='<table cellspacing="0" cellpadding="5">';
$partDtableBox2.="<tr><td>".$noOfTester.": ".$formData['NumberofTester']."</td></tr><tr><td>".$decoded[$language]['/SPI_RT/durationaudit:label'].$formData['durationaudit']."</td></tr>";
$partDtableBox2.='</table>';

$pdf->writeHTMLCell(50,26,70,'',$partDtableBox2,1,0, 0, true, 'L',true);

$scorePer=round($formData['AUDIT_SCORE_PERCANTAGE']);
$level='';
$colorCode='';
if($scorePer<40){
  $level=$level0[0];
  //$level="Level 0";
  $colorCode="background-color:#C00000";
}elseif($scorePer>=40 && $scorePer<=59){
  //$level="Level 1";
  $level=$level1[0];
  $colorCode="background-color:#E36C0A";
}elseif($scorePer>=60 && $scorePer<=79){
  //$level="Level 2";
  $level=$level2[0];
  $colorCode="background-color:#FFFF00";
}elseif($scorePer>=80 && $scorePer<=89){
  //$level="Level 3";
  $level=$level3[0];
  $colorCode="background-color:#92D050";
}elseif($scorePer>=90){
  //$level="Level 4";
  $level=$level4[0];
  $colorCode="background-color:#00B050";
}
					  
$partDtableBox3='<table cellspacing="0" cellpadding="5">';
$partDtableBox3.="<tr><td>".$totPointScored.$formData['FINAL_AUDIT_SCORE']."</td></tr>";
$partDtableBox3.="<tr><td>".$totExpectScored.$formData['MAX_AUDIT_SCORE']."</td></tr>";
$partDtableBox3.='<tr><td>'.$perScored."= ".round($formData['AUDIT_SCORE_PERCANTAGE'],2).'% &nbsp; <span style="'.$colorCode.'">  &nbsp;&nbsp;'.$level.'  &nbsp;&nbsp;</span></td></tr>';
$partDtableBox3.='</table>';

$pdf->writeHTMLCell(70,26,125,'',$partDtableBox3,1,1, 0, true, 'L',true);

// set recommend
$recommend = explode("-",$decoded[$language]['/SPI_RT/correctiveaction/action:label']);
$timeLine = explode("-",$decoded[$language]['/SPI_RT/correctiveaction/timeline:label']);

$partDTable='<br/><br/><table border="1" cellspacing="0" cellpadding="5" style="width:100%">';
$partDTable.='<tr>';
$partDTable.='<td rowspan="2" style="font-weight:bold;text-align:center;width:9%"><br/><br/>'.$decoded[$language]['/SPI_RT/correctiveaction/sectionno:label'].'</td>';
$partDTable.='<td rowspan="2" style="font-weight:bold;text-align:center;width:22%"><br/><br/>'.$decoded[$language]['/SPI_RT/correctiveaction/deficiency:label'].'</td>';
$partDTable.='<td colspan="2" style="font-weight:bold;text-align:center;width:20%">'.$decoded[$language]['/SPI_RT/correctiveaction/correction:label'].'</td>';
$partDTable.='<td rowspan="2" style="font-weight:bold;text-align:center;width:23%">'.$decoded[$language]['/SPI_RT/correctiveaction/auditorcomment:label'].'</td>';
$partDTable.='<td colspan="2" style="font-weight:bold;text-align:center;width:26%">'.$recommend[0].'</td>';
$partDTable.='</tr>';
$partDTable.='<tr>';
$partDTable.='<td style="font-weight:bold;text-align:center;width:12%;">'.$decoded[$language]['/SPI_RT/correctiveaction/correction/Immediate:label'].'</td>';
$partDTable.='<td style="font-weight:bold;text-align:center;width:8%;">'.$decoded[$language]['/SPI_RT/correctiveaction/correction/Followup:label'].'</td>';
$partDTable.='<td style="font-weight:bold;text-align:center;">'.$recommend[1].'</td>';
$partDTable.='<td style="font-weight:bold;text-align:center;">'.$timeLine[1].'</td>';
$partDTable.='</tr>';
if(isset($formData['correctiveaction']) && $formData['correctiveaction'] != ""  && $formData['correctiveaction'] != "[]"){
    $correctiveActions = json_decode($formData['correctiveaction'],true);
    foreach($correctiveActions as $ca) {
        $partDTable.='<tr>';
        $partDTable.='<td style="text-align:center;">'.$ca['sectionno'].'</td>';
        $partDTable.='<td>'.$ca['deficiency'].'</td>';
        $partDTable.='<td style="text-align:center;">';
        $partDTable.=($ca['correction'] == 'Immediate' ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "" );
        $partDTable.='</td>';
        $partDTable.='<td style="text-align:center;">';
        $partDTable.=($ca['correction'] == 'Followup' ? '<img src="'.APPLICATION_PATH.'/img/black-tick.png'.'" width="20">' : "" );
        $partDTable.='</td>';
        $partDTable.='<td>'.$ca['auditorcomment'].'</td>';
        $partDTable.='<td>'.$ca['action'].'</td>';
        $partDTable.='<td>'.$ca['timeline'].'</td>';
        $partDTable.='</tr>';
    }
}else {
    $partDTable.='<tr>';
    $partDTable.='<td colspan="7">'.$decoded[$language]['/SPI_RT/PERSONAL/PER_G_1_8/PERSONAL_Q_1_8/0:label'].' '.$decoded[$language]['SPI_RT/correctiveaction:label'].'</td>';
    $partDTable.='</tr>';
}
$partDTable.='</table><br/><br/><br/>';
$pdf->writeHTML($partDTable,true,0,true,0);

$signBox1='<table cellspacing="0" cellpadding="4">';
$signBox1.='<tr><td>'.$decoded[$language]['/SPI_RT/staffaudited:label'].'</td></tr>';
$signBox1.='<tr><td>'.$decoded[$language]['/SPI_RT/personincharge:label'].$formData["personincharge"].'</td></tr>';
$signBox1.='</table>';
$pdf->writeHTMLCell(90,18,'','',$signBox1,1, 0, 0, true, 'L');

$signBox2='<table cellspacing="0" cellpadding="4">';

if($language=='Spanish'){
$signBox2.='<tr><td>Nombre y firma del auditor:</td></tr>';
}else{
$signBox2.='<tr><td>'.$decoded[$language]['/SPI_RT/SUMMARY/info26:label'].'</td></tr>';	
}

if($language=='Portuguese'){
$signBox2.="<tr><td>Date ".$langDateFormat.":</td></tr>";
}
else if($language=='Spanish'){
$signBox2.="<tr><td>Fecha ".$langDateFormat.":</td></tr>";
}
else{
$signBox2.="<tr><td>Date ".$langDateFormat.":</td></tr>";	
}
$signBox2.='</table>';
$pdf->writeHTMLCell(80,18,115,'',$signBox2,1,1, 0, true, 'L');

//Close and output PDF document
$fileName = "SPI-RT-CHECKLIST-".date('d-M-Y-H-i-s').".pdf";
if(isset($tempId)){
$filePath = TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR. "audit-email". DIRECTORY_SEPARATOR . $tempId. DIRECTORY_SEPARATOR . $fileName;
$pdf->Output($filePath, "F");    
}else{
$filePath = TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR.$fileName;
//$pdf->Output('example_003.pdf', 'I');
$pdf->Output($filePath, "I");
}
//echo $fileName;
//============================================================+
// END OF FILE
//============================================================+
