<style>
        th.details-control {
    background: url('<?php echo $this->basePath('assets/img/details_open.png'); ?>') no-repeat center center;
    cursor: pointer;
}
tr.shown th.details-control {
    background: url('<?php echo $this->basePath('assets/img/details_close.png'); ?>') no-repeat center center;
}
</style>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<div class="am-content">
        <div class="page-head">
          <h2>Edit SPI RT Version 3</h2>
        </div>
        <div class="main-content">
         <div class="widget widget-fullwidth widget-small" style="padding:5px;">
         <div class="row">
            <div class="col-sm-12">
              <div class="panel panel-default">
                <div class="panel-body">
                  <form role="form" class="form-horizontal" name="editSPIRT" id="editSPIRT" method="post" action="<?php echo $this->url('spi-v3-form', array('action' => 'edit')); ?>" autocomplete="off" >
                   <h4><b>PART A: CHARACTERISTICS OF THE FACILITY OR TESTING POINT AUDITED</b></h4>
                   <p>Before completing the checklist, it is important to characterize the testing point to be audited. Please provide relevant information in the summary table below.</p>
                    <div class="form-group">
                      <label for="auditDate" class="col-sm-2 control-label">Date of Audit (dd/mm/yyyy)</label>
                      <div class=" col-lg-4">
                        <input type="text" placeholder="Enter Date" name="auditDate" class="form-control datepicker" value="<?php echo $this->humanDateFormat($formData['assesmentofaudit']); ?>" readonly>
                      </div>
                      <label for="auditRound" class="col-sm-2 control-label">Audit Round No.</label>
                      <div class=" col-lg-4">
                        <input type="text" placeholder="Audit Round No" name="auditRound" class="form-control" value="<?php echo $formData['auditroundno']; ?>">
                        <input type="hidden" name="formId" id="formId" class="form-control" value="<?php echo base64_encode($formData['id']); ?>">
                      </div>
                    </div>
                    
                    <div class="form-group">
                      <label for="testingFacility" class="col-sm-2 control-label">Testing Facility</label>
                      <div class=" col-lg-4">
                        <select id="testingFacility" name="testingFacility" class="form-control" onchange="getFacilityInfo();">
                                <option value="">  -- Select -- </option>
                                <?php
                                if(isset($facilities['allName']) && count($facilities['allName']) > 0){
                                        foreach($facilities['allName'] as $facilities){
                                ?>
                                  <option value="<?php echo base64_encode($facilities['id']); ?>" <?php echo(isset($formData['facilityInfo']->fId) && $formData['facilityInfo']->fId == $facilities['id'])?'selected="selected"':''; ?>><?php echo ucwords($facilities['facility_name']); ?></option>
                                <?php } } ?>
                        </select>
                      </div>
                      <label for="testingFacilityName" class="col-sm-2 control-label">Testing Facility Name</label>
                      <div class=" col-lg-4">
                        <input type="text" placeholder="Testing Facility Name" name="testingFacilityName" id="testingFacilityName" class="form-control" value="<?php echo(isset($formData['facilityInfo']->fName))?$formData['facilityInfo']->fName:''; ?>" onblur="copyFacilityName(this.value)">
                      </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="testingFacilityId" class="col-sm-2 control-label">Testing Facility ID</label>
                        <div class=" col-lg-4">
                          <input type="text" placeholder="Testing Facility ID" name="testingFacilityId" id="testingFacilityId" class="form-control" value="<?php echo(isset($formData['facilityInfo']->ffId))?$formData['facilityInfo']->ffId:''; ?>">
                        </div>
                        <label for="email" class="col-sm-2 control-label">Email</label>
                        <div class=" col-lg-4">
                          <input type="text" placeholder="Email" name="email" id="email" class="form-control isEmail" value="<?php echo(isset($formData['facilityInfo']->fEmail))?$formData['facilityInfo']->fEmail:''; ?>">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="contactPerson" class="col-sm-2 control-label">Name of the Contact Person</label>
                        <div class=" col-lg-4">
                          <input type="text" placeholder="Name of the Contact Person" name="contactPerson" id="contactPerson" class="form-control" value="<?php echo(isset($formData['facilityInfo']->fCPerson))?$formData['facilityInfo']->fCPerson:''; ?>">
                        </div>
                        <label for="district" class="col-sm-2 control-label">District</label>
                        <div class=" col-lg-4">
                          <!--<input type="text" placeholder="District" name="district" id="district" class="form-control" value="< ?php echo(isset($formData['facilityInfo']->fDistrict))?$formData['facilityInfo']->fDistrict:''; ?>">-->
                          <select name="district" id="district" class="form-control" title="Please choose district" onchange="showTextBox(this,'districtTextBox')">
                                <option value="">-- Select --</option>
                                <?php
                                        foreach($districtList as $district){
                                                ?>
                                                <option value="<?php echo $district['name'];?>" <?php echo(isset($formData['facilityInfo']->fDistrict) && $formData['facilityInfo']->fDistrict==$district['name'])?"selected='selected'":'' ?>><?php echo trim($district['name']);?></option>
                                                <?php
                                        }
                                ?>
                                <option value='other'>Other</option>
                                
                          </select>
                          <input type="text" name="districtTextBox" id="districtTextBox" style="display:none;" class="form-control" placeholder="Please enter district"/>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="province" class="col-sm-2 control-label">Province</label>
                        <div class=" col-lg-4">
                          <!--<input type="text" placeholder="Province" name="province" id="province" class="form-control" value="< ?php echo(isset($formData['facilityInfo']->fProvince))?$formData['facilityInfo']->fProvince:''; ?>">-->
                          <select name="province" id="province" class="form-control" title="Please choose province" onchange="showTextBox(this,'provinceTextBox')">
                                <option value="">-- Select --</option>
                                <?php
                                        foreach($provinceList as $province){
                                                ?>
                                                <option value="<?php echo $province['province'];?>" <?php echo(isset($formData['facilityInfo']->fProvince) && $formData['facilityInfo']->fProvince==$province['province'])?"selected='selected'":'' ?>><?php echo trim($province['province']);?></option>
                                                <?php
                                        }
                                ?>
                                <option value='other'>Other</option>
                          </select>
                          <input type="text" name="provinceTextBox" id="provinceTextBox" style="display:none;" class="form-control" placeholder="Please enter province"/>
                        </div>
                        <label for="latitude" class="col-sm-2 control-label">Latitude</label>
                        <div class=" col-lg-4">
                          <input type="text" placeholder="Latitude" name="latitude" id="latitude" class="form-control checkNum" value="<?php echo(isset($formData['facilityInfo']->fLatitude))?$formData['facilityInfo']->fLatitude:''; ?>">
                        </div>
                    </div>
                    
                    <div class="form-group ">
                       <label for="longitude" class="col-sm-2 control-label">Longitude</label>
                        <div class=" col-lg-4">
                          <input type="text" placeholder="Longitude" name="longitude" id="longitude" class="form-control checkNum" value="<?php echo(isset($formData['facilityInfo']->fLongitude))?$formData['facilityInfo']->fLongitude:''; ?>">
                        </div> 
                      <label for="testingPointName" class="col-sm-2 control-label">Testing Point Name</label>
                        <div class="col-lg-4">
                                <input type="text" placeholder="Testing Point Name" name="testingPointName" class="form-control" value="<?php echo $formData['testingpointname']; ?>">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="testingPointType" class="col-sm-2 control-label">Type of testing point</label>
                        <div class="col-lg-4">
                                <input type="text" placeholder="Type of testing point" name="testingPointType" class="form-control" value="<?php echo $formData['testingpointtype']; ?>" onblur="copySiteType(this.value)">
                        </div>
                      <label for="testingPointTypeOther" class="col-sm-2 control-label">Testing point type other</label>
                        <div class="col-lg-4">
                                <input type="text" placeholder="Testing point type other" name="testingPointTypeOther" class="form-control" value="<?php echo $formData['testingpointtype_other']; ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="location" class="col-sm-2 control-label">Location/Address</label>
                        <div class="col-lg-4">
                                <textarea class="form-control" name="location" rows="5"><?php echo $formData['locationaddress']; ?></textarea>
                        </div>
                        <label for="level" class="col-sm-2 control-label">Level</label>
                        <div class="col-lg-4">
                                <input type="text" placeholder="Level" name="level" class="form-control" value="<?php echo $formData['level']; ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="levelOther" class="col-sm-2 control-label">Level Other</label>
                        <div class="col-lg-4">
                                <input type="text" placeholder="Level Other" name="levelOther" class="form-control" value="<?php echo $formData['level_other']; ?>">
                        </div>
                      <label for="levelName" class="col-sm-2 control-label">Level Name</label>
                        <div class="col-lg-4">
                                <input type="text" placeholder="Level Other" name="levelName" class="form-control" value="<?php echo $formData['level_name']; ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="affiliation" class="col-sm-2 control-label">Affiliation</label>
                        <div class="col-lg-4">
                                <input type="text" placeholder="Affiliation" name="affiliation" class="form-control" value="<?php echo $formData['affiliation']; ?>">
                        </div>
                      <label for="affiliationOther" class="col-sm-2 control-label">Affiliation Other</label>
                        <div class="col-lg-4">
                                <input type="text" placeholder="Affiliation" name="affiliationOther" class="form-control" value="<?php echo $formData['affiliation_other']; ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="numberOfTester" class="col-sm-2 control-label">Number of Testers</label>
                        <div class="col-lg-4">
                                <input type="text" placeholder="Number of Testers" name="numberOfTester" class="form-control" value="<?php echo $formData['NumberofTester']; ?>" onblur="copyNoOfTest(this.value)">
                        </div>
                      <label for="averageTestedPerMonth" class="col-sm-2 control-label">Average tested per month</label>
                        <div class="col-lg-4">
                                <input type="text" placeholder="Average tested per month" name="averageTestedPerMonth" class="form-control" value="<?php echo $formData['avgMonthTesting']; ?>">
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="nameOfAuditor1" class="col-sm-2 control-label">Name of the Auditor 1</label>
                        <div class="col-lg-4">
                                <input type="text" placeholder="Name of the Auditor 1" name="nameOfAuditor1" class="form-control" value="<?php echo $formData['name_auditor_lead']; ?>">
                        </div>
                      <label for="nameOfAuditor2" class="col-sm-2 control-label">Name of the Auditor 2</label>
                        <div class="col-lg-4">
                                <input type="text" placeholder="Name of the Auditor 2" name="nameOfAuditor2" class="form-control" value="<?php echo $formData['name_auditor2']; ?>">
                        </div>
                    </div>
                    <br/>
                    <div class="form-group col-lg-12">
                    <h4><b>PART B. SPI- RT Checklist</b></h4>
                    <div>For each of the sections listed below, please check <b>Yes, Partial or No</b>, where applicable. Indicate
                    "<b>Yes</b>" only when all elements are satisfactorily present. Provide comments for each "<b>Partial</b>" or "<b>No</b>" response. State N/A in the comments section if "not applicable" where appropriate (*).</div>
                    <br/>
                    </div>
                    
                    <table cellspacing="0" cellpadding="5" class="table table-bordered">
                     <tr id="personal1">
                        <th style="text-align:center;width:3%" class="details-control" onclick="$('#personal').slideToggle('slow'),addShowClass('shown','personal1');">
                             
                        </th>
                       <th  style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#personal').slideToggle('slow'),addShowClass('shown','personal1');">1.0 PERSONNEL TRAINING AND CERTIFICATION</a>
                       </th>
                        <th style="text-align:center;width:5%">10</th>
                     </tr>
                     <tr id="personal" style="display: none;">
                       <td colspan="7">
                        <table class="table table-bordered">
                         <tr>
                         <td style="text-align:center;font-weight:bold;width:45%;" colspan="2">SECTION</td>
                         <th style="text-align:center;width:3%;">YES</th>
                         <th style="text-align:center;width:4%;">Partial</th>
                         <th style="text-align:center;width:3%;">NO</th>
                         <th style="text-align:center;width:40%;">Comments</th>
                         <th style="text-align:center;width:5%;">Score</th>
                         </tr>
                     <tr>
                      <td style="width:3%;">1.1</td>
                      <td style="width:42%;">Have all testers received a comprehensive training on HIV rapid testing using the nationally approved curriculum?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_1']) && $formData['PERSONAL_Q_1_1'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_1']) && $formData['PERSONAL_Q_1_1'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_1']) && $formData['PERSONAL_Q_1_1'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="personal_c_1_1"><?php echo ($formData['PERSONAL_C_1_1']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_1']); ?></td>
                     </tr>
                     
                     <tr>
                      <td>1.2</td>
                      <td>Are the testers trained on the use of standardized HIV testing registers/logbooks?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_2']) && $formData['PERSONAL_Q_1_2'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_2']) && $formData['PERSONAL_Q_1_2'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_2']) && $formData['PERSONAL_Q_1_2'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="personal_c_1_2"><?php echo ($formData['PERSONAL_C_1_2']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_2']); ?></td>
                     </tr>
                     
                     <tr>
                      <td>1.3</td>
                      <td>Are the testers trained on external quality assessment (EQA) or proficiency testing (PT) process?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_3']) && $formData['PERSONAL_Q_1_3'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_3']) && $formData['PERSONAL_Q_1_3'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_3']) && $formData['PERSONAL_Q_1_3'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="personal_c_1_3"><?php echo ($formData['PERSONAL_C_1_3']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_3']); ?></td>
                     </tr>
                     
                     <tr>
                      <td>1.4</td>
                      <td>Are the testers trained on quality control (QC) process?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_4']) && $formData['PERSONAL_Q_1_4'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_4']) && $formData['PERSONAL_Q_1_4'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_4']) && $formData['PERSONAL_Q_1_4'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="personal_c_1_4"><?php echo ($formData['PERSONAL_C_1_4']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_4']); ?></td>
                     </tr>
                     
                     <tr>
                      <td>1.5</td>
                      <td>Are the testers trained on safety and waste management procedures and practices?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_5']) && $formData['PERSONAL_Q_1_5'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_5']) && $formData['PERSONAL_Q_1_5'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_5']) && $formData['PERSONAL_Q_1_5'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="personal_c_1_5"><?php echo ($formData['PERSONAL_C_1_5']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_5']); ?></td>
                     </tr>
                     
                     <tr>
                      <td>1.6</td>
                      <td>Have all testers received a refresher training within the last two years?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_6']) && $formData['PERSONAL_Q_1_6'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_6']) && $formData['PERSONAL_Q_1_6'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_6']) && $formData['PERSONAL_Q_1_6'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="personal_c_1_6"><?php echo ($formData['PERSONAL_C_1_6']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_6']); ?></td>
                     </tr>
                     
                     <tr>
                      <td>1.7</td>
                      <td>Are there records indicating all testers have demonstrated competency in HIV rapid testing prior to client testing?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_7']) && $formData['PERSONAL_Q_1_7'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_7']) && $formData['PERSONAL_Q_1_7'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_7']) && $formData['PERSONAL_Q_1_7'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="personal_c_1_7"><?php echo ($formData['PERSONAL_C_1_7']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_7']); ?></td>
                     </tr>
                     
                     <tr>
                      <td>1.8</td>
                      <td>Have all testers been certified through a national certification program?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_8']) && $formData['PERSONAL_Q_1_8'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_8']) && $formData['PERSONAL_Q_1_8'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_8']) && $formData['PERSONAL_Q_1_8'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="personal_c_1_8"><?php echo ($formData['PERSONAL_C_1_8']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_8']); ?></td>
                     </tr>
                     
                     <tr>
                      <td>1.9</td>
                      <td>Are only certified testers allowed to perform HIV testing?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_9']) && $formData['PERSONAL_Q_1_9'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_9']) && $formData['PERSONAL_Q_1_9'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_9']) && $formData['PERSONAL_Q_1_9'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="personal_c_1_9"><?php echo ($formData['PERSONAL_C_1_9']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_9']); ?></td>
                     </tr>
                     
                     <tr>
                      <td>1.10</td>
                      <td>Are all testers required to be re-certified periodically (e.g., every two years)?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_10']) && $formData['PERSONAL_Q_1_10'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_10']) && $formData['PERSONAL_Q_1_10'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PERSONAL_Q_1_10']) && $formData['PERSONAL_Q_1_10'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="personal_c_1_10"><?php echo ($formData['PERSONAL_C_1_10']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_10']); ?></td>
                     </tr>
                     
                     <tr>
                      <td colspan="6" style="font-weight:bold;">1.0 PERSONNEL TRAINING AND CERTIFICATION SCORE </td>
                      <td style="text-align:center;"><?php echo $formData['PERSONAL_SCORE']; ?></td>
                     </tr>
                     </table>
                     </td>
                     </tr>
                    </table>
                    
                    <table cellspacing="0" cellpadding="5" class="table table-bordered">
                     
                     <tr id="physical1">
                        <th style="text-align:center;width:3%" class="details-control" onclick="$('#physical').slideToggle('slow'),addShowClass('shown','physical1');">
                             
                        </th>
                      <th style="width:93%">
                       <a href="javascript:void(0);" onclick="$('#physical').slideToggle('slow');">2.0 PHYSICAL FACILITY </a>
                      </th>
                      <th style="text-align:center;width:5%">5</th>
                     </tr>
                     <tr id="physical" style="display: none;">
                       <td colspan="3">
                        <table class="table table-bordered">
                         <tr>
                          <td style="text-align:center;font-weight:bold;width:45%;" colspan="2">SECTION</td>
                          <th style="text-align:center;width:3%;">YES</th>
                          <th style="text-align:center;width:4%;">Partial</th>
                          <th style="text-align:center;width:3%;">NO</th>
                          <th style="text-align:center;width:40%;">Comments</th>
                          <th style="text-align:center;width:5%;">Score</th>
                          </tr>
                     <tr>
                      <td>2.1</td>
                      <td>Is there a designated area for HIV testing?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_1']) && $formData['PHYSICAL_Q_2_1'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_1']) && $formData['PHYSICAL_Q_2_1'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_1']) && $formData['PHYSICAL_Q_2_1'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="physical_c_2_1"><?php echo ($formData['PHYSICAL_C_2_1']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PHYSICAL_Q_2_1']); ?></td>
                     </tr>                     
                     <tr>
                      <td>2.2</td>
                      <td>Is the testing area clean and organized for HIV rapid testing?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_2']) && $formData['PHYSICAL_Q_2_2'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_2']) && $formData['PHYSICAL_Q_2_2'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_2']) && $formData['PHYSICAL_Q_2_2'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="physical_c_2_2"><?php echo ($formData['PHYSICAL_C_2_2']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PHYSICAL_Q_2_2']); ?></td>
                     </tr>
                     <tr>
                      <td>2.3</td>
                      <td>Is sufficient lighting available in the designated testing area?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_3']) && $formData['PHYSICAL_Q_2_3'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_3']) && $formData['PHYSICAL_Q_2_3'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_3']) && $formData['PHYSICAL_Q_2_3'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="physical_c_2_3"><?php echo ($formData['PHYSICAL_C_2_3']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PHYSICAL_Q_2_3']); ?></td>
                     </tr>
                     <tr>
                      <td>2.4</td>
                      <td>Are the test kits kept in a temperature controlled environment based on the manufacturers' instructions?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_4']) && $formData['PHYSICAL_Q_2_4'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_4']) && $formData['PHYSICAL_Q_2_4'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_4']) && $formData['PHYSICAL_Q_2_4'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="physical_c_2_4"><?php echo ($formData['PHYSICAL_C_2_4']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PHYSICAL_Q_2_4']); ?></td>
                     </tr>
                     <tr>
                      <td>2.5</td>
                      <td>Is there sufficient and secure storage space for test kits and other consumables?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_5']) && $formData['PHYSICAL_Q_2_5'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_5']) && $formData['PHYSICAL_Q_2_5'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['PHYSICAL_Q_2_5']) && $formData['PHYSICAL_Q_2_5'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="physical_c_2_5"><?php echo ($formData['PHYSICAL_C_2_5']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo ($formData['PHYSICAL_Q_2_5']); ?></td>
                     </tr>
                     <tr>
                      <td colspan="6" style="font-weight:bold;">2.0 PHYSICAL FACILITY SCORE </td>
                      <td style="text-align:center;"><?php echo $formData['PHYSICAL_SCORE']; ?></td>
                     </tr>
                     </table>
                     </td>
                     </tr>
                    </table>
                    
                    <table cellspacing="0" cellpadding="5" class="table table-bordered">
                     <tr id="safetyTable1">
                        <th style="text-align:center;width:3%" class="details-control" onclick="$('#safetyTable').slideToggle('slow'),addShowClass('shown','safetyTable1');">
                             
                        </th>
                       <th  style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#safetyTable').slideToggle('slow'),addShowClass('shown','safetyTable1');">3.0 SAFETY</a>
                       </th>
                        <th style="text-align:center;width:5%">11</th>
                     </tr>
                     <tr id="safetyTable" style="display: none;">
                       <td colspan="3">
                       <table cellspacing="0" cellpadding="5" class="table table-bordered">
                    <tr>
                          <td style="text-align:center;font-weight:bold;width:45%;" colspan="2">SECTION</td>
                          <th style="text-align:center;width:3%;">YES</th>
                          <th style="text-align:center;width:4%;">Partial</th>
                          <th style="text-align:center;width:3%;">NO</th>
                          <th style="text-align:center;width:40%;">Comments</th>
                          <th style="text-align:center;width:5%;">Score</th>
                     </tr>
                     <tr>
                      <td>3.1</td>
                      <td>Are there SOPs and/or job aides in place to implement safety practices?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_1']) && $formData['SAFETY_Q_3_1'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_1']) && $formData['SAFETY_Q_3_1'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_1']) && $formData['SAFETY_Q_3_1'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="safety_c_3_1"><?php echo ($formData['SAFETY_C_3_1']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_1']; ?></td>
                     </tr>
                     <tr>
                      <td>3.2</td>
                      <td>Are there SOPs and/or job aides in place on how to dispose of infectious and non-infectious waste?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_2']) && $formData['SAFETY_Q_3_2'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_2']) && $formData['SAFETY_Q_3_2'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_2']) && $formData['SAFETY_Q_3_2'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="safety_c_3_2"><?php echo ($formData['SAFETY_C_3_2']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_2']; ?></td>
                     </tr>
                     <tr>
                      <td>3.3</td>
                      <td>Are there SOPs and/or job aides in place to manage spills of blood and other body fluids?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_3']) && $formData['SAFETY_Q_3_3'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_3']) && $formData['SAFETY_Q_3_3'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_3']) && $formData['SAFETY_Q_3_3'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="safety_c_3_3"><?php echo ($formData['SAFETY_C_3_3']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_3']; ?></td>
                     </tr>
                     <tr>
                      <td>3.4</td>
                      <td>Are there SOPs and/or job aides in place to address accidental exposure to potentially infectious body fluids through a needle stick injury, splash or other sharps injury?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_4']) && $formData['SAFETY_Q_3_4'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_4']) && $formData['SAFETY_Q_3_4'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_4']) && $formData['SAFETY_Q_3_4'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="safety_c_3_4"><?php echo ($formData['SAFETY_C_3_4']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_4']; ?></td>
                     </tr>
                     <tr>
                      <td>3.5</td>
                      <td>Is personal protective equipment (PPE) always available to testers?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_5']) && $formData['SAFETY_Q_3_5'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_5']) && $formData['SAFETY_Q_3_5'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_5']) && $formData['SAFETY_Q_3_5'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="safety_c_3_5"><?php echo ($formData['SAFETY_C_3_5']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_5']; ?></td>
                     </tr>
                     <tr>
                      <td>3.6</td>
                      <td>Is PPE consistently used by all testers?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_6']) && $formData['SAFETY_Q_3_6'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_6']) && $formData['SAFETY_Q_3_6'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_6']) && $formData['SAFETY_Q_3_6'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="safety_c_3_6"><?php echo ($formData['SAFETY_C_3_6']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_6']; ?></td>
                     </tr>
                     <tr>
                      <td>3.7</td>
                      <td>Is PPE properly used by all testers through the testing process?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_7']) && $formData['SAFETY_Q_3_7'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_7']) && $formData['SAFETY_Q_3_7'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_7']) && $formData['SAFETY_Q_3_7'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="safety_c_3_7"><?php echo ($formData['SAFETY_C_3_7']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_7']; ?></td>
                     </tr>
                     <tr>
                      <td>3.8</td>
                      <td>Is there clean water and soap available for hand washing?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_8']) && $formData['SAFETY_Q_3_8'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_8']) && $formData['SAFETY_Q_3_8'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_8']) && $formData['SAFETY_Q_3_8'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="safety_c_3_8"><?php echo ($formData['SAFETY_C_3_8']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_8']; ?></td>
                     </tr>
                     <tr>
                      <td>3.9</td>
                      <td>Is there an appropriate disinfectant to clean the work area available?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_9']) && $formData['SAFETY_Q_3_9'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_9']) && $formData['SAFETY_Q_3_9'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_9']) && $formData['SAFETY_Q_3_9'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="safety_c_3_9"><?php echo ($formData['SAFETY_C_3_9']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_9']; ?></td>
                     </tr>
                     <tr>
                      <td>3.10</td>
                      <td>Are sharps, infectious, and non-infectious waste handled properly?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_10']) && $formData['SAFETY_Q_3_10'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_10']) && $formData['SAFETY_Q_3_10'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_10']) && $formData['SAFETY_Q_3_10'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="safety_c_3_10"><?php echo ($formData['SAFETY_C_3_10']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_10']; ?></td>
                     </tr>
                     <tr>
                      <td>3.11</td>
                      <td>Are infectious and non-infectious waste containers emptied regularly per the SOP and/or job aides?</td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_11']) && $formData['SAFETY_Q_3_11'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_11']) && $formData['SAFETY_Q_3_11'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td style="text-align:center;">
                       <?php echo (isset($formData['SAFETY_Q_3_11']) && $formData['SAFETY_Q_3_11'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                      </td>
                      <td><textarea class="form-control" name="safety_c_3_11"><?php echo ($formData['SAFETY_C_3_11']); ?></textarea></td>
                      <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_11']; ?></td>
                     </tr>
                     <tr>
                      <th colspan="6">3.0 SAFETY SCORE  </th>
                      <td style="text-align:center;"><?php echo $formData['SAFETY_SCORE']; ?></td>
                     </tr>
                    </table>
                       </td>
                     </tr>
                    </table>
                    
                    <table cellspacing="0" cellpadding="5" class="table table-bordered">
                     <tr id="preTestingTable1">
                        <th style="text-align:center;width:3%" class="details-control" onclick="$('#preTestingTable').slideToggle('slow'),addShowClass('shown','preTestingTable1');">
                             
                        </th>
                       <th  style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#preTestingTable').slideToggle('slow'),addShowClass('shown','preTestingTable1');">4.0 PRE-TESTING PHASE</a>
                       </th>
                        <th style="text-align:center;width:5%">12</th>
                     </tr>
                     <tr id="preTestingTable" style="display: none;">
                      <td colspan="3">
                       <table cellspacing="0" cellpadding="5" class="table table-bordered">
                       <tr>
                             <td style="text-align:center;font-weight:bold;width:45%;" colspan="2">SECTION</td>
                             <th style="text-align:center;width:3%;">YES</th>
                             <th style="text-align:center;width:4%;">Partial</th>
                             <th style="text-align:center;width:3%;">NO</th>
                             <th style="text-align:center;width:40%;">Comments</th>
                             <th style="text-align:center;width:5%;">Score</th>
                        </tr>
                        <tr>
                        <td>4.1</td>
                        <td>Are there national testing guidelines specific to the program (e.g. HTS, PMTCT, TB, etc.) available at the testing point?</td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_1']) && $formData['PRE_Q_4_1'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_1']) && $formData['PRE_Q_4_1'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_1']) && $formData['PRE_Q_4_1'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td><textarea class="form-control" name="pre_c_4_1"><?php echo ($formData['PRE_C_4_1']); ?></textarea></td>
                        <td style="text-align:center;"><?php echo $formData['PRE_Q_4_1']; ?></td>
                       </tr>
                       <tr>
                        <td>4.2</td>
                        <td>Is the national HIV testing algorithm being used?</td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_2']) && $formData['PRE_Q_4_2'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_2']) && $formData['PRE_Q_4_2'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_2']) && $formData['PRE_Q_4_2'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td><textarea class="form-control" name="pre_c_4_2"><?php echo ($formData['PRE_C_4_2']); ?></textarea></td>
                        <td style="text-align:center;"><?php echo $formData['PRE_Q_4_2']; ?></td>
                       </tr>
                       <tr>
                        <td>4.3</td>
                        <td>Is there a process in place for an alternative HIV testing algorithm in case of expired or shortage of test kit(s)?</td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_3']) && $formData['PRE_Q_4_3'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_3']) && $formData['PRE_Q_4_3'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_3']) && $formData['PRE_Q_4_3'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td><textarea class="form-control" name="pre_c_4_3"><?php echo ($formData['PRE_C_4_3']); ?></textarea></td>
                        <td style="text-align:center;"><?php echo $formData['PRE_Q_4_3']; ?></td>
                       </tr>
                       <tr>
                        <td>4.4</td>
                        <td>Are there SOPs and/or job aides in place for each HIV rapid test used in the testing algorithm?</td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_4']) && $formData['PRE_Q_4_4'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_4']) && $formData['PRE_Q_4_4'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_4']) && $formData['PRE_Q_4_4'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td><textarea class="form-control" name="pre_c_4_4"><?php echo ($formData['PRE_C_4_4']); ?></textarea></td>
                        <td style="text-align:center;"><?php echo $formData['PRE_Q_4_4']; ?></td>
                       </tr>
                       <tr>
                        <td>4.5</td>
                        <td>Are only nationally approved HIV rapid kits available for use currently?</td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_5']) && $formData['PRE_Q_4_5'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_5']) && $formData['PRE_Q_4_5'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_5']) && $formData['PRE_Q_4_5'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td><textarea class="form-control" name="pre_c_4_5"><?php echo ($formData['PRE_C_4_5']); ?></textarea></td>
                        <td style="text-align:center;"><?php echo $formData['PRE_Q_4_5']; ?></td>
                       </tr>
                       <tr>
                        <td>4.6</td>
                        <td>Are all the test kits  currently in use within the expiration date?</td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_6']) && $formData['PRE_Q_4_6'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_6']) && $formData['PRE_Q_4_6'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_6']) && $formData['PRE_Q_4_6'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td><textarea class="form-control" name="pre_c_4_6"><?php echo ($formData['PRE_C_4_6']); ?></textarea></td>
                        <td style="text-align:center;"><?php echo $formData['PRE_Q_4_6']; ?></td>
                       </tr>
                       <tr>
                        <td>4.7</td>
                        <td>Are test kits labeled with date received and initials?</td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_7']) && $formData['PRE_Q_4_7'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_7']) && $formData['PRE_Q_4_7'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_7']) && $formData['PRE_Q_4_7'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td><textarea class="form-control" name="pre_c_4_7"><?php echo ($formData['PRE_C_4_7']); ?></textarea></td>
                        <td style="text-align:center;"><?php echo $formData['PRE_Q_4_7']; ?></td>
                       </tr>
                       <tr>
                        <td>4.8</td>
                        <td>Is there a process in place for stock management?</td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_8']) && $formData['PRE_Q_4_8'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_8']) && $formData['PRE_Q_4_8'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_8']) && $formData['PRE_Q_4_8'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td><textarea class="form-control" name="pre_c_4_8"><?php echo ($formData['PRE_C_4_8']); ?></textarea></td>
                        <td style="text-align:center;"><?php echo $formData['PRE_Q_4_8']; ?></td>
                       </tr>
                       <tr>
                        <td>4.9</td>
                        <td>Are job aides on client sample collection available and posted at the testing point?</td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_9']) && $formData['PRE_Q_4_9'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_9']) && $formData['PRE_Q_4_9'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_9']) && $formData['PRE_Q_4_9'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td><textarea class="form-control" name="pre_c_4_9"><?php echo ($formData['PRE_C_4_9']); ?></textarea></td>
                        <td style="text-align:center;"><?php echo $formData['PRE_Q_4_9']; ?></td>
                       </tr>
                       <tr>
                        <td>4.10</td>
                        <td>Are there sufficient supplies available for client sample collection?</td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_10']) && $formData['PRE_Q_4_10'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_10']) && $formData['PRE_Q_4_10'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_10']) && $formData['PRE_Q_4_10'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td><textarea class="form-control" name="pre_c_4_10"><?php echo ($formData['PRE_C_4_10']); ?></textarea></td>
                        <td style="text-align:center;"><?php echo $formData['PRE_Q_4_10']; ?></td>
                       </tr>
                       <tr>
                        <td>4.11</td>
                        <td>Are there national guidelines describing how client identification should be recorded in the HIV testing register?</td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_11']) && $formData['PRE_Q_4_11'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_11']) && $formData['PRE_Q_4_11'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_11']) && $formData['PRE_Q_4_11'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td><textarea class="form-control" name="pre_c_4_11"><?php echo ($formData['PRE_C_4_11']); ?></textarea></td>
                        <td style="text-align:center;"><?php echo $formData['PRE_Q_4_11']; ?></td>
                       </tr>
                       <tr>
                        <td>4.12</td>
                        <td>Are client identifiers recorded in the HIV testing register per national guidelines and on test devices?</td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_12']) && $formData['PRE_Q_4_12'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_12']) && $formData['PRE_Q_4_12'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td style="text-align:center;">
                         <?php echo (isset($formData['PRE_Q_4_12']) && $formData['PRE_Q_4_12'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                        </td>
                        <td><textarea class="form-control" name="pre_c_4_12"><?php echo ($formData['PRE_C_4_12']); ?></textarea></td>
                        <td style="text-align:center;"><?php echo $formData['PRE_Q_4_12']; ?></td>
                       </tr>
                       <tr>
                       <th colspan="6">4.0 PRE-TESTING PHASE SCORE</th>
                       <td style="text-align:center;"><?php echo $formData['PRETEST_SCORE']; ?></td>
                       </tr>
                       </table>
                      </td>
                     </tr>
                    </table>
                    
                    <table cellspacing="0" cellpadding="5" class="table table-bordered">
                     <tr id="testingPhaseTable1">
                        <th style="text-align:center;width:3%" class="details-control" onclick="$('#testingPhaseTable').slideToggle('slow'),addShowClass('shown','testingPhaseTable1');">
                             
                        </th>
                       <th  style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#testingPhaseTable').slideToggle('slow'),addShowClass('shown','testingPhaseTable1');">5.0 TESTING PHASE</a>
                       </th>
                        <th style="text-align:center;width:5%">9</th>
                     </tr>
                     <tr id="testingPhaseTable" style="display: none;">
                      <td colspan="3">
                       <table cellspacing="0" cellpadding="5" class="table table-bordered">
                         <tr>
                             <td style="text-align:center;font-weight:bold;width:45%;" colspan="2">SECTION</td>
                             <th style="text-align:center;width:3%;">YES</th>
                             <th style="text-align:center;width:4%;">Partial</th>
                             <th style="text-align:center;width:3%;">NO</th>
                             <th style="text-align:center;width:40%;">Comments</th>
                             <th style="text-align:center;width:5%;">Score</th>
                         </tr>
                         <tr>
                          <td>5.1</td>
                          <td>Are SOPs and/or job aides on HIV testing procedures available and posted at the testing point?</td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_1']) && $formData['TEST_Q_5_1'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_1']) && $formData['TEST_Q_5_1'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_1']) && $formData['TEST_Q_5_1'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td><textarea class="form-control" name="test_c_5_1"><?php echo ($formData['TEST_C_5_1']); ?></textarea></td>
                          <td style="text-align:center;"><?php echo $formData['TEST_Q_5_1']; ?></td>
                         </tr>
                         <tr>
                          <td>5.2</td>
                          <td>Are timers available and used routinely for HIV rapid testing?</td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_2']) && $formData['TEST_Q_5_2'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_2']) && $formData['TEST_Q_5_2'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_2']) && $formData['TEST_Q_5_2'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td><textarea class="form-control" name="test_c_5_2"><?php echo ($formData['TEST_C_5_2']); ?></textarea></td>
                          <td style="text-align:center;"><?php echo $formData['TEST_Q_5_2']; ?></td>
                         </tr>
                         <tr>
                          <td>5.3</td>
                          <td>Are sample collection devices (e.g., capillary tube, loop, disposable pipettes, etc.) used accurately?</td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_3']) && $formData['TEST_Q_5_3'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_3']) && $formData['TEST_Q_5_3'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_3']) && $formData['TEST_Q_5_3'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td><textarea class="form-control" name="test_c_5_3"><?php echo ($formData['TEST_C_5_3']); ?></textarea></td>
                          <td style="text-align:center;"><?php echo $formData['TEST_Q_5_3']; ?></td>
                         </tr>
                         <tr>
                          <td>5.4</td>
                          <td>Are testing procedures adequately followed?</td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_4']) && $formData['TEST_Q_5_4'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_4']) && $formData['TEST_Q_5_4'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_4']) && $formData['TEST_Q_5_4'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td><textarea class="form-control" name="test_c_5_4"><?php echo ($formData['TEST_C_5_4']); ?></textarea></td>
                          <td style="text-align:center;"><?php echo $formData['TEST_Q_5_4']; ?></td>
                         </tr>
                         <tr>
                          <td>5.5</td>
                          <td>Are positive and negative quality control (QC) specimens routinely used (e.g., daily or weekly) according to country guidelines?</td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_5']) && $formData['TEST_Q_5_5'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_5']) && $formData['TEST_Q_5_5'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_5']) && $formData['TEST_Q_5_5'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td><textarea class="form-control" name="test_c_5_5"><?php echo ($formData['TEST_C_5_5']); ?></textarea></td>
                          <td style="text-align:center;"><?php echo $formData['TEST_Q_5_5']; ?></td>
                         </tr>
                         <tr>
                          <td>5.6</td>
                          <td>Are QC results properly recorded?</td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_6']) && $formData['TEST_Q_5_6'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_6']) && $formData['TEST_Q_5_6'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_6']) && $formData['TEST_Q_5_6'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td><textarea class="form-control" name="test_c_5_6"><?php echo ($formData['TEST_C_5_6']); ?></textarea></td>
                          <td style="text-align:center;"><?php echo $formData['TEST_Q_5_6']; ?></td>
                         </tr>
                         <tr>
                          <td>5.7</td>
                          <td>Are incorrect/invalid QC results properly recorded?</td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_7']) && $formData['TEST_Q_5_7'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_7']) && $formData['TEST_Q_5_7'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_7']) && $formData['TEST_Q_5_7'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td><textarea class="form-control" name="test_c_5_7"><?php echo ($formData['TEST_C_5_7']); ?></textarea></td>
                          <td style="text-align:center;"><?php echo $formData['TEST_Q_5_7']; ?></td>
                         </tr>
                         <tr>
                          <td>5.8</td>
                          <td>Are appropriate steps taken and documented when QC results are incorrect and/or invalid?</td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_8']) && $formData['TEST_Q_5_8'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_8']) && $formData['TEST_Q_5_8'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_8']) && $formData['TEST_Q_5_8'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td><textarea class="form-control" name="test_c_5_8"><?php echo ($formData['TEST_C_5_8']); ?></textarea></td>
                          <td style="text-align:center;"><?php echo $formData['TEST_Q_5_8']; ?></td>
                         </tr>
                         <tr>
                          <td>5.9</td>
                          <td>Are QC records reviewed by the person in charge routinely?</td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_9']) && $formData['TEST_Q_5_9'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_9']) && $formData['TEST_Q_5_9'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td style="text-align:center;">
                           <?php echo (isset($formData['TEST_Q_5_9']) && $formData['TEST_Q_5_9'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                          </td>
                          <td><textarea class="form-control" name="test_c_5_9"><?php echo ($formData['TEST_C_5_9']); ?></textarea></td>
                          <td style="text-align:center;"><?php echo $formData['TEST_Q_5_9']; ?></td>
                         </tr>
                         
                         <tr>
                          <th colspan="6">5.0 TESTING PHASE SCORE</th>
                          <td style="text-align:center;"><?php echo $formData['TEST_SCORE']; ?></td>
                         </tr>
                       </table>
                      </td>
                     </tr>
                    </table>
                    
                    <table cellspacing="0" cellpadding="5" class="table table-bordered">
                     <tr id="postTestingTable1">
                        <th style="text-align:center;width:3%" class="details-control" onclick="$('#postTestingTable').slideToggle('slow'),addShowClass('shown','postTestingTable1');">
                             
                        </th>
                       <th  style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#postTestingTable').slideToggle('slow'),addShowClass('shown','postTestingTable1');">6.0 POST TESTING PHASE - DOCUMENTS AND RECORDS</a>
                       </th>
                        <th style="text-align:center;width:5%">9</th>
                     </tr>
                     <tr id="postTestingTable" style="display: none;">
                      <td colspan="3">
                        <table cellspacing="0" cellpadding="5" class="table table-bordered">
                         <tr>
                               <td style="text-align:center;font-weight:bold;width:45%;" colspan="2">SECTION</td>
                               <th style="text-align:center;width:3%;">YES</th>
                               <th style="text-align:center;width:4%;">Partial</th>
                               <th style="text-align:center;width:3%;">NO</th>
                               <th style="text-align:center;width:40%;">Comments</th>
                               <th style="text-align:center;width:5%;">Score</th>
                          </tr>
                          <tr>
                           <td>6.1</td>
                           <td>Is there a national standardized HIV rapid testing register/logbook available and in use?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_1']) && $formData['POST_Q_6_1'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_1']) && $formData['POST_Q_6_1'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_1']) && $formData['POST_Q_6_1'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="post_C_6_1"><?php echo ($formData['POST_C_6_1']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['POST_Q_6_1']; ?></td>
                          </tr>
                          <tr>
                           <td>6.2</td>
                           <td>Does the HIV testing register/logbook include all of the key quality elements?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_2']) && $formData['POST_Q_6_2'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_2']) && $formData['POST_Q_6_2'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_2']) && $formData['POST_Q_6_2'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="post_C_6_2"><?php echo ($formData['POST_C_6_2']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['POST_Q_6_2']; ?></td>
                          </tr>
                          <tr>
                           <td>6.3</td>
                           <td>Are all the elements in the register/ logbook recorded/captured correctly? (e.g., client demographics, kit names, lot numbers, expiration dates, tester name, individual and final HIV results, etc.)?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_3']) && $formData['POST_Q_6_3'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_3']) && $formData['POST_Q_6_3'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_3']) && $formData['POST_Q_6_3'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="post_C_6_3"><?php echo ($formData['POST_C_6_3']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['POST_Q_6_3']; ?></td>
                          </tr>
                          <tr>
                           <td>6.4</td>
                           <td>Is the total summary at the end of each page of the register/logbooks complied accurately?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_4']) && $formData['POST_Q_6_4'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_4']) && $formData['POST_Q_6_4'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_4']) && $formData['POST_Q_6_4'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="post_C_6_4"><?php echo ($formData['POST_C_6_4']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['POST_Q_6_4']; ?></td>
                          </tr>
                          <tr>
                           <td>6.5</td>
                           <td>Are invalid test results recorded in the register/logbook?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_5']) && $formData['POST_Q_6_5'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_5']) && $formData['POST_Q_6_5'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_5']) && $formData['POST_Q_6_5'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="post_C_6_5"><?php echo ($formData['POST_C_6_5']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['POST_Q_6_5']; ?></td>
                          </tr>
                          <tr>
                           <td>6.6</td>
                           <td>Are invalid tests repeated and results properly recorded in the register/logbook?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_6']) && $formData['POST_Q_6_6'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_6']) && $formData['POST_Q_6_6'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_6']) && $formData['POST_Q_6_6'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="post_C_6_6"><?php echo ($formData['POST_C_6_6']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['POST_Q_6_6']; ?></td>
                          </tr>
                          <tr>
                           <td>6.7</td>
                           <td>Are all client documents and records securely kept throughout all phases of the testing process?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_7']) && $formData['POST_Q_6_7'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_7']) && $formData['POST_Q_6_7'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_7']) && $formData['POST_Q_6_7'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="post_C_6_7"><?php echo ($formData['POST_C_6_7']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['POST_Q_6_7']; ?></td>
                          </tr>
                          <tr>
                           <td>6.8</td>
                           <td>Are all registers/logbooks and other documents kept in a secure location when not in use?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_8']) && $formData['POST_Q_6_8'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_8']) && $formData['POST_Q_6_8'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_8']) && $formData['POST_Q_6_8'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="post_C_6_8"><?php echo ($formData['POST_C_6_8']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['POST_Q_6_8']; ?></td>
                          </tr>
                          <tr>
                           <td>6.9</td>
                           <td>Are registers/logbooks properly labeled and archived when full?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_9']) && $formData['POST_Q_6_9'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_9']) && $formData['POST_Q_6_9'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['POST_Q_6_9']) && $formData['POST_Q_6_9'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="post_C_6_9"><?php echo ($formData['POST_C_6_9']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['POST_Q_6_9']; ?></td>
                          </tr>
                          
                          <tr>
                          <th colspan="6">6.0 POST TESTING PHASE - DOCUMENTS AND RECORDS SCORE</th>
                          <td style="text-align:center;"><?php echo $formData['POST_SCORE']; ?></td>
                         </tr>
                        </table>
                      </td>
                     </tr>
                    </table>
                    
                    <table cellspacing="0" cellpadding="5" class="table table-bordered">
                     <tr id="externalTable1">
                        <th style="text-align:center;width:3%" class="details-control" onclick="$('#externalTable').slideToggle('slow'),addShowClass('shown','externalTable1');">
                             
                        </th>
                       <th  style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#externalTable').slideToggle('slow'),addShowClass('shown','externalTable1');">7.0 EXTERNAL QUALITY AUDIT (PT, SUPERVISION AND RETESTING)</a>
                       </th>
                        <th style="text-align:center;width:5%">8/14</th>
                     </tr>
                     <tr id="externalTable" style="display: none;">
                      <td colspan="3">
                        <table cellspacing="0" cellpadding="5" class="table table-bordered">
                         <tr>
                               <td style="text-align:center;font-weight:bold;width:45%;" colspan="2">SECTION</td>
                               <th style="text-align:center;width:3%;">YES</th>
                               <th style="text-align:center;width:4%;">Partial</th>
                               <th style="text-align:center;width:3%;">NO</th>
                               <th style="text-align:center;width:40%;">Comments</th>
                               <th style="text-align:center;width:5%;">Score</th>
                          </tr>
                         <tr>
                           <td>7.1</td>
                           <td>Is the testing point enrolled in an EQA/PT program?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_1']) && $formData['EQA_Q_7_1'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_1']) && $formData['EQA_Q_7_1'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_1']) && $formData['EQA_Q_7_1'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_1"><?php echo ($formData['EQA_C_7_1']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_1']; ?></td>
                          </tr>
                         <tr>
                           <td>7.2</td>
                           <td>Do all testers at the testing point test the EQA/PT samples?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_2']) && $formData['EQA_Q_7_2'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_2']) && $formData['EQA_Q_7_2'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_2']) && $formData['EQA_Q_7_2'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_2"><?php echo ($formData['EQA_C_7_2']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_2']; ?></td>
                          </tr>
                         <tr>
                           <td>7.3</td>
                           <td>Does the person in charge at the testing point review the /PT results before submission to NRL or designee?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_3']) && $formData['EQA_Q_7_3'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_3']) && $formData['EQA_Q_7_3'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_3']) && $formData['EQA_Q_7_3'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_3"><?php echo ($formData['EQA_C_7_3']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_3']; ?></td>
                          </tr>
                         <tr>
                           <td>7.4</td>
                           <td>Is an EQA/PT report received from NRL and reviewed by testers and/or the person in charge at the testing point?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_4']) && $formData['EQA_Q_7_4'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_4']) && $formData['EQA_Q_7_4'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_4']) && $formData['EQA_Q_7_4'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_4"><?php echo ($formData['EQA_C_7_4']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_4']; ?></td>
                         </tr>
                         <tr>
                           <td>7.5</td>
                           <td>Does the testing point implement corrective action in case of unsatisfactory results?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_5']) && $formData['EQA_Q_7_5'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_5']) && $formData['EQA_Q_7_5'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_5']) && $formData['EQA_Q_7_5'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_5"><?php echo ($formData['EQA_C_7_5']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_5']; ?></td>
                         </tr>
                         <tr>
                           <td>7.6</td>
                           <td>Does the testing point receive periodic supervisory visits?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_6']) && $formData['EQA_Q_7_6'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_6']) && $formData['EQA_Q_7_6'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_6']) && $formData['EQA_Q_7_6'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_6"><?php echo ($formData['EQA_C_7_6']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_6']; ?></td>
                         </tr>
                         <tr>
                           <td>7.7</td>
                           <td>Is feedback provided during supervisory visit and documented?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_7']) && $formData['EQA_Q_7_7'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_7']) && $formData['EQA_Q_7_7'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_7']) && $formData['EQA_Q_7_7'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_7"><?php echo ($formData['EQA_C_7_7']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_7']; ?></td>
                         </tr>
                         <tr>
                           <td>7.8</td>
                           <td>If testers need to be retrained, are they being retrained during the supervisory visit?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_8']) && $formData['EQA_Q_7_8'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_8']) && $formData['EQA_Q_7_8'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_8']) && $formData['EQA_Q_7_8'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_8"><?php echo ($formData['EQA_C_7_8']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_8']; ?></td>
                         </tr>
                         <tr>
                          <th colspan="7">
                           If the country external quality assessment program includes retesting of serum or DBS, proceed with questions 7.9 –7.14. Otherwise, STOP here.
                          </th>
                         </tr>
                         <tr>
                           <td>7.9*</td>
                           <td>Does the site collect samples for retesting according to country guidelines (e.g., collection of every 20<sup>th</sup> client serum or DBS sample)?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_9']) && $formData['EQA_Q_7_9'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_9']) && $formData['EQA_Q_7_9'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_9']) && $formData['EQA_Q_7_9'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_9"><?php echo ($formData['EQA_C_7_9']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_9']; ?></td>
                         </tr>
                         <tr>
                           <td>7.10*</td>
                           <td>Are the serum or DBS samples collected for retesting properly documented?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_10']) && $formData['EQA_Q_7_10'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_10']) && $formData['EQA_Q_7_10'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_10']) && $formData['EQA_Q_7_10'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_10"><?php echo ($formData['EQA_C_7_10']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_10']; ?></td>
                         </tr>
                         <tr>
                           <td>7.11*</td>
                           <td>Are serum or DBS samples collected properly (e.g., at least 3 complete circles or correct volume and correct tubes, etc.)?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_11']) && $formData['EQA_Q_7_11'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_11']) && $formData['EQA_Q_7_11'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_11']) && $formData['EQA_Q_7_11'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_11"><?php echo ($formData['EQA_C_7_11']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_11']; ?></td>
                         </tr>
                         <tr>
                           <td>7.12*</td>
                           <td>Are serum or DBS samples stored properly (e.g., away from sunlight, separated by glassine paper, desiccant, or at 4&deg;C or 20&deg;C, etc.)?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_12']) && $formData['EQA_Q_7_12'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_12']) && $formData['EQA_Q_7_12'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_12']) && $formData['EQA_Q_7_12'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_12"><?php echo ($formData['EQA_C_7_12']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_12']; ?></td>
                         </tr>
                         <tr>
                           <td>7.13*</td>
                           <td>Are the identifiers of serum or DBS samples sent for retesting properly recorded?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_13']) && $formData['EQA_Q_7_13'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_13']) && $formData['EQA_Q_7_13'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_13']) && $formData['EQA_Q_7_13'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_13"><?php echo ($formData['EQA_C_7_13']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_13']; ?></td>
                         </tr>
                         <tr>
                           <td>7.14*</td>
                           <td>Are the serum or DBS results received from the referral lab properly documented and recorded in the HIV testing register/logbook?</td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_14']) && $formData['EQA_Q_7_14'] == 1 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_14']) && $formData['EQA_Q_7_14'] == 0.5 ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td style="text-align:center;">
                            <?php echo (isset($formData['EQA_Q_7_14']) && $formData['EQA_Q_7_14'] == "0" ) ? "<img src='".$this->basePath('assets/img/black-tick.png')."' width='20'>" : ""; ?>
                           </td>
                           <td><textarea class="form-control" name="eqa_c_7_14"><?php echo ($formData['EQA_C_7_14']); ?></textarea></td>
                           <td style="text-align:center;"><?php echo $formData['EQA_Q_7_14']; ?></td>
                         </tr>
                         
                         <tr>
                          <th colspan="6">7.0 EXTERNAL QUALITY AUDIT (PT, SUPERVISION AND RETESTING) SCORE </th>
                          <td style="text-align:center;"><?php echo $formData['EQA_SCORE']; ?></td>
                         </tr>
                         <tr>
                      <td colspan="7">*Those marked with an asterisk are only applicable to sites where sample retesting is performed.</td>
                        </tr>
                        </table>
                      </td>
                     </tr>
                     </table>
                    <h4><b>PART C: SCORING CRITERIA</b></h4>
                    <p>Each element marked will be assigned a point value:</p>
                    <div style="margin-left:10px;">
                     <p>* Items marked "Yes" receive 1 point each.</p>
                     <p>* Items marked "Partial" receive 0.5 point each.</p>
                     <p>* Items marked "No" receive 0 point each.</p>
                    </div>
                    <p>Total points scored for each section should be tallied and recorded at the end of the section.</p>
                    <p>The overall total points obtained by each HIV testing point audited will be weighed to correspond to a specific performance level.</p>
                    
                    <table class="table table-bordered" cellspacing="0" cellpadding="5">
                     <tr style="text-align:center;">
                      <th>Levels</th>
                      <th>% Score</th>
                      <th>Description of results</th>
                     </tr>
                     <tr>
                      <td style="background-color:#C00000;color:#000000;">Level 0</td>
                      <td>Less than 40%</td>
                      <td>Needs improvement in all areas and immediate remediation</td>
                     </tr>
                     <tr>
                      <td style="background-color:#E36C0A;color:#000000;">Level 1</td>
                      <td>40% - 59%</td>
                      <td>Needs improvement in specific areas</td>
                     </tr>
                     <tr>
                      <td style="background-color:#FFFF00;color:#000000;">Level 2</td>
                      <td>60% - 79%</td>
                      <td>Partially eligible</td>
                     </tr>
                     <tr>
                      <td style="background-color:#92D050;color:#000000;">Level 3</td>
                      <td>80% - 89%</td>
                      <td>Close to national site certification</td>
                     </tr>
                     <tr>
                      <td style="background-color:#00B050;color:#000000;">Level 4</td>
                      <td>90% or higher</td>
                      <td>Eligible to national site certification</td>
                     </tr>
                    </table>
                    
                    <h4><b>Part D. Auditor's Summation Report for SPI-RT Audit</b></h4>
                    
                    <div class="form-group col-lg-6">
                      <label>Facility Name</label>
                      <p class="form-control" id="facilityName"><?php echo $formData['facilityInfo']->fName; ?></p>
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Site Type</label>
                      <p class="form-control" id="siteType"><?php echo $formData['testingpointtype']; ?></p>
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Staff Audited Name</label>
                      <input type="text" placeholder="Staff Audited Name" name="staffAuditedName" class="form-control" value="<?php echo $formData['staffaudited']; ?>">
                    </div>
                    <div class="form-group col-lg-6">
                      <label>No. of Tester(s)</label>
                      <p class="form-control" id="noOfTesterId"><?php echo $formData['NumberofTester']; ?></p>
                    </div>
                    
                    <div class="form-group col-lg-6">
                      <label>Duration of Audit</label>
                      <input type="text" placeholder="Duration of Audit" name="durationaudit" class="form-control" value="<?php echo $formData['durationaudit']; ?>">
                    </div>
                    
                    <div class="form-group col-lg-6">
                      <label>Total points scored (exclude N/A)</label>
                      <p class="form-control"><?php echo $formData['FINAL_AUDIT_SCORE']; ?></p>
                    </div>
                    
                    
                    <div class="form-group col-lg-6">
                      <label>Total score expected </label>
                      <p class="form-control"><?php echo $formData['MAX_AUDIT_SCORE']; ?></p>
                    </div>
                    <div class="form-group col-lg-3">
                      <label>% Score </label>
                      <p class="form-control"><?php echo round($formData['AUDIT_SCORE_PERCANTAGE'],2); ?></p>
                    </div>
                    <div class="form-group col-lg-3">
                      <label>&nbsp;</label>
                      <?php
                      $level='';
                      $colorCode='';
                      $scorePer=round($formData['AUDIT_SCORE_PERCANTAGE']);
                      if($scorePer<40){
                        $level="Level 0";
                        $colorCode="background-color:#C00000";
                      }elseif($scorePer>=40 && $scorePer<=59){
                        $level="Level 1";
                        $colorCode="background-color:#E36C0A";
                      }elseif($scorePer>=60 && $scorePer<=79){
                        $level="Level 2";
                        $colorCode="background-color:#FFFF00";
                      }elseif($scorePer>=80 && $scorePer<=89){
                        $level="Level 3";
                        $colorCode="background-color:#92D050";
                      }elseif($scorePer>=90){
                        $level="Level 4";
                        $colorCode="background-color:#00B050";
                      }
                      ?>
                      <p class="form-control" style="color:#000000;<?php echo $colorCode; ?>; border:0;"><?php echo $level; ?></p>
                    </div>
                    
                    <table id="correctiveActionTable" class="table table-bordered" cellspacing="0" cellpadding="5" style="width:100%">
                     <tr>
                      <th rowspan="2" style="text-align:center;width:3%">Section No.</th>
                      <th rowspan="2" style="text-align:center;width:20%">Deficiency/Issue observed</th>
                      <th colspan="2" style="text-align:center;width:8%">Correction <br/>Actions</th>
                      <th rowspan="2" style="text-align:center;width:33%">Auditor's <br/>Comments</th>
                      <th colspan="2" style="text-align:center;width:36%">Recommendations</th>
                      <th rowspan="2">Add/<br/>Remove</th>
                     </tr>
                     <tr>
                      <th style="text-align:center;width:4%;">Immediate</th>
                      <th style="text-align:center;width:4%;">Follow up</th>
                      <th style="text-align:center;width:30%;">Actions</th>
                      <th style="text-align:center;width:4%;">Timeline / Person responsible</th>
                     </tr>
                     <?php
                     $i=3;
                     if(isset($formData['correctiveaction']) && trim($formData['correctiveaction'])!= "" && $formData['correctiveaction'] != "[]" && is_array(json_decode($formData['correctiveaction'],true))){
                      $correctiveActions = json_decode($formData['correctiveaction'],true);
                      foreach($correctiveActions as $ca) {
                      ?>
                      <tr>
                       <td style="text-align:center;">
                        <input type="text" name="sectionNo[]" class="form-control" value="<?php echo $ca['sectionno']; ?>">
                        <input type="hidden" name="rowId[]" class="form-control" value="<?php echo $i; ?>">
                       </td>
                       <td>
                        <input type="text" name="deficiency[]" class="form-control" value="<?php echo $ca['deficiency']; ?>">
                       </td>
                       <td align="center">
						   <input type="radio" class="isRequired" name="correction<?php echo $i; ?>" value="Immediate" <?php if($ca['correction']=='Immediate'){ echo "checked"; } ?> title="Please select the corrective action">
                       </td>
                       <td align="center">
						   <input type="radio" class="isRequired" name="correction<?php echo $i; ?>" value="Followup" <?php if($ca['correction']=='Followup'){ echo "checked"; } ?> title="Please select the corrective action">
						</td>
                       <td><textarea class="form-control" name="auditorComment[]"><?php echo $ca['auditorcomment']; ?></textarea></td>
                       <td><textarea class="form-control" name="action[]"><?php echo $ca['action']; ?></textarea></td>
                       <td>
                        <input type="text" name="timeline[]" class="form-control" value="<?php echo $ca['timeline']; ?>">
                       </td>
                       <td align="center">
							<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a>
							<a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>
						</td>
                      </tr>
                      <?php
                      $i++;
                      }
                      ?>
                      
                      <?php
                     }else{
                     ?>
                     <tr>
						<td style="text-align:center;">
							<input type="text" name="sectionNo[]" class="form-control">
							<input type="hidden" name="rowId[]" class="form-control" value="3">
						</td>
						<td>
                        <input type="text" name="deficiency[]" class="form-control">
						</td>
						<td style="text-align:center;">
							<input type="radio" name="correction3" value="Immediate">
						</td>
						<td style="text-align:center;">
							<input type="radio" name="correction3" value="Followup">
						</td>
						<td><textarea class="form-control" name="auditorComment[]"></textarea></td>
						<td><textarea class="form-control" name="action[]"></textarea></td>
						<td>
                        <input type="text" name="timeline[]" class="form-control">
                        </td>
                        <td align="center">
							<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a>
							<a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>
						</td>
                      </tr>
                     <?php
                     }
                     ?>
                    </table>
                    <div class="spacer  col-lg-12">
                     
                     <button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Save</button>
                     <a href="<?php echo $this->url('spi-v3-form', array('action' => 'manage-facility')); ?>" class="btn btn-space btn-default">Cancel</a> 
                    </div>
                   
                  </form>
                </div>
              </div>
            </div>
        </div>

        <br/>
        
            
            
        </div>
</div>
<script src="<?php echo $this->basePath('assets/js/bootstrap-typeahead.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
<script type="text/javascript">
 duplicateName = true;
 rowCount='<?php echo $i; ?>';
 function validateNow() {
        flag = deforayValidator.init({
            formId: 'editSPIRT'
        });
        if (flag) {
            if (duplicateName) {
                document.getElementById('editSPIRT').submit();
            }
        }
 }

$(function() {
        
        //$('.datepicker').datepicker({
        //    changeMonth: true,
        //    changeYear: true,
        //    dateFormat: 'dd-M-yy',
        //    yearRange: <?php echo ( date('Y') - 50); ?> + ":" + "<?php echo (date('Y')) ?>"
        //});
});

function copyFacilityName(objVal) {
    $("#facilityName").html(objVal);
}
function copySiteType(objVal) {
    $("#siteType").html(objVal);
}
function copyNoOfTest(objVal) {
    $("#noOfTesterId").html(objVal);
}

	function insRow() {
		rowCount++;
		rl = document.getElementById("correctiveActionTable").rows.length;
		var a = document.getElementById("correctiveActionTable").insertRow(rl);
		a.setAttribute("style", "display:none;");
		a.setAttribute("class", "data");
		var b = a.insertCell(0);
		var c = a.insertCell(1);
		var d = a.insertCell(2);
		var e = a.insertCell(3);
		var f = a.insertCell(4);
		var g = a.insertCell(5);
		var h = a.insertCell(6);
		var i = a.insertCell(7);
		
		d.setAttribute("align", "center");
		e.setAttribute("align", "center");
		i.setAttribute("align", "center");
		
		rl = document.getElementById("correctiveActionTable").rows.length - 1;
		b.innerHTML = '<input type="text" class="form-control" id="sectionNo' + rowCount + '" name="sectionNo[]" /><input type="hidden" name="rowId[]" class="form-control" value="'+rowCount+'">';
		c.innerHTML = '<input type="text" class="form-control" id="deficiency' + rowCount + '" name="deficiency[]" />';
		d.innerHTML = '<input type="radio" class="isRequired" name="correction'+rowCount+'" value="Immediate" title="Please select the corrective action">';
		e.innerHTML = '<input type="radio" class="isRequired" name="correction'+rowCount+'" value="Followup" title="Please select the corrective action">';
		f.innerHTML = '<textarea class="form-control" name="auditorComment[]"></textarea>';
		g.innerHTML = '<textarea class="form-control" name="action[]"></textarea>';
		h.innerHTML = '<input type="text" name="timeline[]" class="form-control">';
		i.innerHTML = '<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>';
		$(a).fadeIn(800);
		
	}
	
	function removeRow(el) {
		$(el).fadeOut("slow", function() {
		    el.parentNode.removeChild(el);
		    rl = document.getElementById("correctiveActionTable").rows.length;
		    if (rl == 2) {
			insRow();
		    }
		});
     }
     
     function addShowClass(className,idName){
        $('#'+idName).toggleClass(className);
     }
     
     function getFacilityInfo(){
        if($('#testingFacility').val() != ''){
            $.blockUI();    
           $.post("<?php echo $this->url('spi-facility', array('action' => 'get-facility-details')); ?>", {id:$('#testingFacility').val()},
           function (data) {
             splitData = data.split('##');
             if(splitData.length == 8){
                $('#testingFacilityName').val(splitData[1]);
                $('#testingFacilityId').val(splitData[0]);
                $('#email').val(splitData[2]);
                $('#contactPerson').val(splitData[3]);
                $('#district').val(splitData[4]);
                $('#province').val(splitData[5]);
                $('#latitude').val(splitData[6]);
                $('#longitude').val(splitData[7]);
                copyFacilityName(splitData[1]);
             }else{
                $('#testingFacilityName').val('');
                $('#testingFacilityId').val('');
                $('#email').val('');
                $('#contactPerson').val('');
                $('#district').val('');
                $('#province').val('');
                $('#latitude').val('');
                $('#longitude').val('');
                copyFacilityName('');
             }
             $.unblockUI();
           });
        }else{
             $('#testingFacilityName').val('');
             $('#testingFacilityId').val('');
             $('#email').val('');
             $('#contactPerson').val('');
             $('#district').val('');
             $('#province').val('');
             $('#latitude').val('');
             $('#longitude').val('');
             copyFacilityName('');
        }
     }
     function showTextBox(obj,textBoxId) {
        if (obj.value=='other') {
            $("#"+textBoxId).show();
            $("#"+obj.id).hide();
        }else{
            $("#"+textBoxId).hide().val('');
            $("#"+obj.id).show();    
        }
      }
</script>
