<?php
//
//header( 'Content-Type: text/csv' );
//header( 'Content-Disposition: attachment;filename=SPI-RT--CHECKLIST-version-3-'.time().'.csv');
//
//$response = array();
//
//            
//$out = fopen('php://output', 'w');
//
//$header = $allSubmissions[0];
//unset($header['id']);
//unset($header['content']);
//unset($header['token']);
//fputcsv($out, array_keys($header));
//
//
//foreach($allSubmissions as $data){
// unset($data['id']);
// unset($data['content']);
// unset($data['token']);
// fputcsv($out, $data);
//}
//
//fclose($out);

echo $allSubmissions;
?>