<?php
//\Zend\Debug\Debug::dump($perflast30);die;
if($perflast30[0]['totalDataPoints']>0){
?>
<div class="row chart-container">
                  <div class="col-md-12">
				  <div id="widget-top-2" style="width: 100%;"></div>
                  </div>
                </div>
		  <div class="row chart-info">
		    <div class="col-xs-4" style="text-align:center;"><span class="title">From Date</span><span class="number"><?php echo $this->humanDateFormat($perflast30[0]['oldestDate']) ?></span></div>
		    <div class="col-xs-4" style="text-align:center;padding-left:5px;"><span class="title">To Date</span><span class="number"><?php echo $this->humanDateFormat($perflast30[0]['newestDate']) ?></span></div>
		    <div class="col-xs-4" style="text-align:center;"><span class="title">No. of Audits</span><span class="number"><?php echo $perflast30[0]['totalDataPoints']; ?></span></div>
                </div>
<script type="text/javascript">
		var color1 = "red";
		var color2 = "orange";
		var color3 = "yellow";
		var color4 = "#8DD63E";
		var color5 = "#528A16";
var chart;
		//Get the template css colors into js vars
		function getColor( c ){
		  var tmp = $("<div>", { class: c }).appendTo("body");
		  var color = tmp.css("background-color");
		  tmp.remove();
	  
		  return color;
		}
  
		var colors = {};
		colors.primary = getColor('clr-primary');
        colors.success = getColor('clr-success');
        colors.info    = getColor('clr-info');
        colors.warning = getColor('clr-warning');
        colors.danger  = getColor('clr-danger');
        colors.alt1    = getColor('clr-alt1');
        colors.alt2    = getColor('clr-alt2');
        colors.alt3    = getColor('clr-alt3');
        colors.alt4    = getColor('clr-alt4');
    function widget_top_2(){
		<?php
		
			$perflast30[0]['level0'] = ($perflast30[0]['level0'] > 0) ? $perflast30[0]['level0'] : 0;
			$perflast30[0]['level1'] = ($perflast30[0]['level1'] > 0) ? $perflast30[0]['level1'] : 0;
			$perflast30[0]['level2'] = ($perflast30[0]['level2'] > 0) ? $perflast30[0]['level2'] : 0;
			$perflast30[0]['level3'] = ($perflast30[0]['level3'] > 0) ? $perflast30[0]['level3'] : 0;
			$perflast30[0]['level4'] = ($perflast30[0]['level4'] > 0) ? $perflast30[0]['level4'] : 0;
			
	  	?>
			
	  var data = [
		 {
		  y: <?php echo $perflast30[0]['level0']; ?>,
		  color: color1,
		  name: "Level 0 (Below 40)",
		  number:"No.Of Audits <?php echo $perflast30[0]['level0']; ?>",
		  url:'/view-data?source=ap&level=level0&drange='+$("#spiRTv3").val()
	  },
		 {
		  y: <?php echo $perflast30[0]['level1']; ?>,
		  color: color2,
		  name: "Level 1 (40-59)",
		  number:"No.Of Audits <?php echo $perflast30[0]['level1']; ?>",
		  url:'/view-data?source=ap&level=level1&drange='+$("#spiRTv3").val()
	  },
		 {
		  y: <?php echo $perflast30[0]['level2']; ?>,
		  color: color3,
		  name: "Level 2 (60-79)",
		  number:"No.Of Audits <?php echo $perflast30[0]['level2']; ?>",
		  url:'/view-data?source=ap&level=level2&drange='+$("#spiRTv3").val()
	  },
		 {
		  y: <?php echo $perflast30[0]['level3']; ?>,
		  color: color4,
		  name: "Level 3 (80-89)",
		  number:"No.Of Audits <?php echo $perflast30[0]['level3']; ?>",
		  url:'/view-data?source=ap&level=level3&drange='+$("#spiRTv3").val()
	  },
		 {
		  y: <?php echo $perflast30[0]['level4']; ?>,
		  color: color5,
		  name: "Level 4 (90 and above)",
		  number:"No.Of Audits <?php echo $perflast30[0]['level4']; ?>",
		  url:'/view-data?source=ap&level=level4&drange='+$("#spiRTv3").val()
	  },
	  
	  ];
	  <?php $total = $perflast30[0]['level0'] + $perflast30[0]['level1'] + $perflast30[0]['level2'] + $perflast30[0]['level3'] + $perflast30[0]['level4'];?>
	  $('#widget-top-2').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },title: {
                text: ''
            },
			exporting:{
            chartOptions:{
                subtitle: {
                    text:'Total Audits:- <?php echo $total;?>',
                }
            }
        },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}% ({point.number})</b>'
            },
	    legend: {
            layout: 'vertical',
            align: 'center',
            verticalAlign: 'bottom',
            backgroundColor: '#f3f3f3',
            borderWidth: 0,
            useHTML: true,
            itemMarginBottom: 10,
            labelFormatter: function () {
                return '<div style="width:260px"><span style="float:left;">' + this.name + '</span><span style="float:right; ">'+ this.percentage.toFixed(1)+'% (No.of Audits '+Highcharts.numberFormat(this.y, 0)+')</span></div>';
            }
        },
	    
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: false
                    },
                    showInLegend: true,
					shadow: false,
				    center: ['50%', '50%']					
                }
            },
            series: [{
                name: 'Audit Performance',
                colorByPoint: true,
		point: {
		events: {
                     click: function(e) {
                        window.open(e.point.url, '_blank');
                        e.preventDefault();
                     }
		  }
		},
                data: data
            }]
        });  
	  
	  
	  
	  
    }
    $(document).ready(function(){
        widget_top_2();
    });
    
</script>
<?php }else{
   echo "<div style='height:470px;text-align:center;'><h3>No data available</h3></div>";
}?>