
<div style="width:100%;height:340px" id="volumeChart"></div>
<?php
//\Zend\Debug\Debug::dump($testingVolume);
?>
<script>
    $(function () {
  <?php
	$counter = 0;
	$barData = array();
	$volumeData = array();
	$labNameData = array();
	
	foreach($testingVolume as $row) {
	  if($counter == 10) break;
	  if($row['AUDIT_SCORE_PERCANTAGE'] < 40){
		$color = '#FF0000';
		$level = 0;
	  }else if($row['AUDIT_SCORE_PERCANTAGE'] >= 40 && $row['AUDIT_SCORE_PERCANTAGE'] <60){
		$color = '#FFA500';
		$level = 1;
	  }else if($row['AUDIT_SCORE_PERCANTAGE'] >= 60 && $row['AUDIT_SCORE_PERCANTAGE'] <80){
		$color = '#FFFF00';
		$level = 2;
	  }else if($row['AUDIT_SCORE_PERCANTAGE'] >= 80 && $row['AUDIT_SCORE_PERCANTAGE'] <90){
		$color = '#8DD63E';
		$level = 3;
	  }else if($row['AUDIT_SCORE_PERCANTAGE'] >= 90){
		$color = '#528A16';
		$level = 4;
	  }
	  
	  $levelData[] = "{ y : ".$level. ", color : '".$color."' }"; 
	  $volumeData[] = (isset($row['avgMonthTesting']) ? $row['avgMonthTesting'] : 0); 
	  $testerData[] = (isset($row['NumberofTester']) ? $row['NumberofTester'] : 0); 
	  $labNameData[] = ("'Date : ".$this->humanDateFormat($row['assesmentofaudit'])."<br>' + ' ' + 'Facility Name : ".addslashes($row['facilityname'])." <br> Testing Point Name : ".addslashes($row['testingpointname'])."<br>'"); 
	  $counter++;
	}
?>
$('#volumeChart').highcharts({
        chart: {
            zoomType: 'xy'
        },
        title: {
            text: ''
        },
        subtitle: {
            text: ''
        },
        xAxis: [{
            categories: [<?php echo implode(",",$labNameData); ?>],
            crosshair: true,
			labels:
			{
			  enabled: false
			}
        }],
        yAxis: [{ // Primary yAxis
            labels: {
                format: '{value}',
                style: {
                    color: 'black'
                }
            },
            title: {
                text: 'No. of Testers',
                style: {
                    color: 'black'
                }
            },
            opposite: true

        }, { // Secondary yAxis
            gridLineWidth: 0,
            title: {
                text: 'Level',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            },
            labels: {
                format: '{value}',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            },
			min : 0,
			max : 4,
            opposite: true

        }, { // Tertiary yAxis
            gridLineWidth: 0,
            title: {
                text: 'Testing Volume',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            labels: {
                format: '{value}',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            }
        }],
        tooltip: {
            shared: true
        },
        plotOptions: {
            column: {
                pointPadding: 0,
                borderWidth: 0
            }
        },		
        legend: {
            enabled: true
        },
        series: [ {
            name: 'Testing Volume',
            type: 'column',
            yAxis: 2,
            data: [<?php echo implode(",",$volumeData); ?>],
			color: {
			  pattern : "<?php echo $this->basePath('assets/img/pattern3.png'); ?>",
			  width: 6,
			  height: 6
			},	
            tooltip: {
                valueSuffix: ' Tests'
            }

        }, {
            name: 'Testers',
            type: 'column',
            data: [<?php echo implode(",",$testerData); ?>],
            tooltip: {
                valueSuffix: ' Tests'
            },
			color: '#3598DC',

        },{
            name: 'Level',
            type: 'column',
            yAxis: 1,
            data: [<?php echo implode(",",$levelData); ?>],
            tooltip: {
                valueSuffix: ' '
            }

        }]
    });
});
</script>