<?php
$editAction = '{"sClass":"center details-control","bSortable":false},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
?>
<div class="am-content">
        <div class="page-head">
          <h2>SPI RT V3 - Data Validation</h2>
		  <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
        </div>
        <div class="main-content">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">
				<div class="row">
                    <div class="col-sm-12">
                      <div class="panel panel-default">
                        <div class="panel-body">
                          <form role="form" name="addImportFile" id="addImportFile" method="post" enctype="multipart/form-data" action="<?php echo $this->url('spi-v3-form', array('action' => 'validate-spiv3-data')); ?>"  >
                            <div class="form-group col-lg-6">
                              <label>Import File<span class="mandatory">*</span> </label>
                              <input type="file" class="form-control isRequired" name="fileName" id="fileName" title="Please choose file">
							  <code>Upload csv file</code>
                            </div>
                            <div class="spacer col-lg-12">
                                <button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
                                <a href="javascript:void(0)" onclick="window.location.reload();" class="btn btn-space btn-default">Reset</a> 
                            </div>
                          </form>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
        <br>
        <br>
		<div class="widget widget-fullwidth widget-small" style="padding:15px;">
				
				<div class="col-sm-12">
						<div class="col-sm-3" id="totalDataCount"></div>
						<div class="col-sm-3" id="newDataCount"></div>
				</div>
				<div class="col-sm-12" style="padding-top:15px;">
						<div class="col-sm-3">&nbsp;</div>
						<div class="col-sm-6">
								<div class="col-sm-1">
								<label>Token:</label>
								</div>
								<div class="col-sm-5">
								<select class="form-control" name="token" id="token" title="Please choose token">
										<option value="">-- Select --</option>
										<?php
										$selected = '';
										if(count($tokenResults)==1){
												$selected = "selected";
										}
										foreach($tokenResults as $token){
												?>
												<option value="<?php echo $token['token'];?>" <?php echo $selected;?>><?php echo $token['token'];?></option>
												<?php
										}
										?>
								</select>
								</div>
						</div>
				</div>
				<div>
				<a class="btn btn-space btn-primary" id="addValidateData" href="javascript:void(0)" style="visibility:hidden;" onclick="insertValidateData()">Import Selected Audit(s)</a>
				</div>
		<table id="validateData" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
              <thead>
                <tr>
                  <th><input type="checkbox" id="checkAllValidateData" onclick="checkAllValidateData()"/></th>
                  <th>Facility Name</th>
                  <th style="width:8%;">Audit Round No.</th>
                  <th style="width:10%;">Audit Date</th>
                  <th style="width:10%;">Testing Point Name</th>
                  <th style="width:6%;">Testing Point Type</th>
                  <th style="width:8%;">Level</th>
                  <th>Affiliation</th>
                  <th style="width:5%;">Audit Score %</th>
                  <th style="width:8%;">Status</th>
                </tr>
              </thead>
              <tbody>
              <tr>
                   <td colspan="10" class="dataTables_empty">Loading data from server</td>
               </tr>
              </tbody>
            </table>
				<input type="hidden" name="checkedValidateSpiv3Data" id="checkedValidateSpiv3Data"/>
        </div>
		</div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
<script type="text/javascript">
		selectedDataId = [];
		selectedData = [];
		table = null;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'addImportFile'
        });
        if (flag) {
		var fup = document.getElementById('fileName');
		var fileName = fup.value;
		var ext = fileName.substring(fileName.lastIndexOf('.') + 1);
		if(ext != "csv") {
			alert("Upload csv file only");
			return false;
		}
				document.getElementById('addImportFile').submit();
        }
    }
	$(document).ready(function () {
		table = $('#validateData').DataTable({
        "bProcessing": true,
        "bServerSide": true,
         "aoColumns": [
                <?php echo $editAction;?>
            ],
         "iDisplayLength": 50,
         "pageLength": 50,
         "aaSorting": [[ 3, "desc" ]],
		 "fnDrawCallback": function() {
		var checkBoxes=document.getElementsByName("chk[]");
                len = checkBoxes.length;
                for(c=0;c<len;c++){
                    if (jQuery.inArray(checkBoxes[c].id, selectedDataId) != -1 ){
						checkBoxes[c].setAttribute("checked",true);
                    }
                }
	    },
         "sAjaxSource": "<?php echo $this->url('spi-v3-form',array('action' => 'validate-spiv3-details')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": function(json){
                      //$.unblockUI();
                      $("#totalDataCount").html("<b>Total No. of Audits in CSV : </b>"+json.newData);
                      $("#newDataCount").html("<b>Total No. of Audits in ODKDash : </b>"+json.totalData);
                      fnCallback(json);
                     }
                });
            }
    } );
	});
	function checkAllValidateData() {
		$(".checkSpiv3Data").each(function(){
                    $(this).prop('checked', false);
                    selectedData.splice( $.inArray(this.value, selectedData), 1 );
                    selectedDataId.splice( $.inArray(this.id, selectedDataId), 1 );
                });
		if ($("#checkAllValidateData").is(':checked')) {
                $(".checkSpiv3Data").each(function(){
                    $(this).prop('checked', true);
                        selectedData.push(this.value);
                        selectedDataId.push(this.id);
                });
            } else{
	       $(".checkSpiv3Data").each(function(){
                    $(this).prop('checked', false);
                    selectedData.splice( $.inArray(this.value, selectedData), 1 );
                    selectedDataId.splice( $.inArray(this.id, selectedDataId), 1 );
                });
	    }
	    $("#checkedValidateSpiv3Data").val(selectedData.join());
		if (selectedData.length>0) {
				$("#addValidateData").css("visibility","visible");
        }else{
				$("#addValidateData").css("visibility","hidden");
		}
    }
	function getValidateId(obj){
		if ($(obj).is(':checked')) {
		    if($.inArray(obj.value, selectedData) == -1){
			selectedData.push(obj.value);
			selectedDataId.push(obj.id);
		    }
		} else {
		    selectedData.splice( $.inArray(obj.value, selectedData), 1 );
		    selectedDataId.splice( $.inArray(obj.id, selectedDataId), 1 );
		    $("#checkAllValidateData").attr("checked",false);
		}
		$("#checkedValidateSpiv3Data").val(selectedData.join());
		if (selectedData.length>0) {
				$("#addValidateData").css("visibility","visible");
        }else{
				$("#addValidateData").css("visibility","hidden");
		}
    }
	function insertValidateData() {
        validateId = $("#checkedValidateSpiv3Data").val();
        token = $("#token").val();
		if (validateId!='' && token!='') {
				conf = confirm("Are you sure want to import these audit(s)?");
				if (conf) {
						$.blockUI();
						$.post("<?php echo $this->url('spi-v3-form',array('action'=>'add-spiv3-validate-data')); ?>",{validateId:validateId,token:token},
						function(data){
							alert("Added successfully");
							selectedData = [];
							selectedDataId = [];
							$("#checkedValidateSpiv3Data").val('');
							$("#token").val('');
							$("#checkAllValidateData").attr('checked',false);
							table.draw();
							$("#addValidateData").css("visibility","hidden");
							$.unblockUI();
						});
				}
        }else{
			alert("Please choose atleat one row and token!");
		}
    }
</script>