<div id="zero-count-barchart" height="280px"></div>
<script>
    $(document).ready(function(){
      	//initialize the javascript
	
        zeroCountsBarChart();
    });
    function zeroCountsBarChart(){
	
<?php


					  $counter = 0;
					  
					  $barData = array();
					  $category = array();
					  //$fullQuestions = array();
					  foreach($zeroCounts as $col => $val) {
						if($counter == $limitBar) break;
						
						$barData[] = "{ y : ".$val. " , fullquestion : '".$spiV3Labels[$col][1]."' }"; 
						$category[] = "'".$spiV3Labels[$col][0]."'"; 
						//$fullQuestions[$spiV3Labels[$col][0]] = "'".$spiV3Labels[$col][1]."'";
						$counter++;
					  }
					  //$fullQuestions = json_encode($fullQuestions);
					?>		
	
	

$('#zero-count-barchart').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: ''
        },
        subtitle: {
            text: ''
        },
        xAxis: {
            categories: [<?php echo implode(",",$category); ?>],
            crosshair: true,
			labels:
			{
			  enabled: true
			}
        },
		 legend: {
            enabled: false
        },
        yAxis: {
            min: 0,
            title: {
                text: 'No. of <strong><em>Zeroes</em></strong>'
            }
        },
        tooltip: {
		   formatter: function() {return ' ' +
                '<strong>'+this.point.fullquestion + '</strong><br /><br />' +
                this.series.name + ' : ' + this.point.y + '<br />';
            },
			useHTML : true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Responses scoring a Zero',
            data: [<?php echo implode(",",$barData); ?>]
        }]
    });	
    }
</script>