<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<style>
		.select2-container .select2-selection--single{height:40px;}
		.select2-container--default.select2-container--open .select2-selection--single .select2-selection__arrow b:after{content:""}
		.select2-container--default .select2-selection--single .select2-selection__arrow b:after{content:""}
		.select2-container--default .select2-selection--single .select2-selection__arrow b:before{content:""}
		.select2-container--default .select2-selection--single .select2-selection__arrow b{margin-top:8px;}
</style>
<div class="am-content">
        <div class="page-head">
          <h2>Edit Facility</h2>
        </div>
        
        
        <div class="main-content">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">
				<div class="row">
            <div class="col-sm-12">
              <div class="panel panel-default">
                <div class="panel-body">
                  <form role="form" name="editFacilityInfo" id="editFacilityInfo" method="post" action="<?php echo $this->url('spi-facility', array('action' => 'edit')); ?>" autocomplete="off" >
                    <div class="form-group col-lg-6">
                      <label>Facility Id</label>
                      <input type="text" placeholder="Facility Id" class="form-control isRequired" name="facilityId" id="facilityId" title="Please enter the facility id" value="<?php echo $result->facility_id; ?>">
                      <input type="hidden" class="form-control isRequired" name="rowId" id="rowId" value="<?php echo base64_encode($result->id); ?>">
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Facility Name</label>
                      <input type="text" placeholder="Facility Name" class="form-control isRequired" name="facilityName" id="facilityName" title="Please enter the facility name" value="<?php echo $result->facility_name; ?>" onblur="checkNameValidation('spi_rt_3_facilities','facility_name', this,'<?php echo "id##" .$result->id; ?>','Already exist this name . Please choose another name.')">
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Email</label>
                      <input type="text" placeholder="Email" class="form-control isEmail" name="email" id="email" value="<?php echo $result->email; ?>">
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Name of the Contact Person</label>
                      <input type="text" placeholder="Name of the Contact Person" class="form-control" name="contactPerson" id="contactPerson" value="<?php echo $result->contact_person; ?>">
                    </div>
					<div class="form-group col-lg-6">
                      <label>Province</label>
					  <select class="select2" id="province" name="province" style="width: 300px;"></select>
                      <!--<input type="text" placeholder="Province" class="form-control" name="province" id="province" value="">-->
                    </div>
					<div class="form-group col-lg-6">
                      <label>District</label>
					  <select class="select2 form-control" id="district" name="district" style="width: 300px;"></select>
                      <!--<input type="text" placeholder="District" class="form-control" name="district" id="district" value="">-->
                    </div>
					<div class="form-group col-lg-6">
                      <label>Latitude</label>
                      <input type="text" placeholder="Latitude" class="form-control" name="latitude" id="latitude" value="<?php echo $result->latitude; ?>">
                    </div>
					<div class="form-group col-lg-6">
                      <label>Longitude</label>
                      <input type="text" placeholder="Longitude" class="form-control" name="longitude" id="longitude" value="<?php echo $result->longitude; ?>">
                    </div>
                    <div class="spacer  col-lg-12">
                      <button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
                     <a href="<?php echo $this->url('spi-facility', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a> 
                    </div>
                  </form>
                </div>
              </div>
            </div>
        </div>

            </div>
        
        <br>
        <br>
 
        </div>
</div>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
		duplicateName = true;
		$(document).ready(function(){
		var data = [{id: '<?php echo $result->district;?>', text:'<?php echo ucwords($result->district);?>'}];
		$('#district').select2({data: data});
		
		var data = [{id: '<?php echo $result->province;?>', text: '<?php echo ucwords($result->province);?>'}];
		$('#province').select2({data: data});
		$("#province").select2({
		width: '100%',
		placeholder: "Enter Province Name",
		minimumInputLength: 2,
		allowClear: true,
		//multiple:true,
	    ajax: {
	      url: "<?php echo $this->url('spi-facility', array('action' => 'search-province-list')); ?>",
	      dataType: 'json',
	      delay: 250,
	      data: function (params) {
		  return {
			q: params.term, // search term
			//q12: $("#searchDate").val(), // search term
			page: params.page
		  };
	      },
	      processResults: function (data, params) {
		  params.page = params.page || 1;
		  return {
			results: data.result,
			pagination: {
			  more: (params.page * 30) < data.total_count
			}
		  };
	      },
	      cache: true
	    },
	    escapeMarkup: function (markup) { return markup; }
		});
		
		$("#district").select2({
		width: '100%',
		placeholder: "Enter District Name",
		minimumInputLength: 2,
		allowClear: true,
		//multiple:true,
	    ajax: {
	      url: "<?php echo $this->url('spi-facility', array('action' => 'search-district-list')); ?>",
	      dataType: 'json',
	      delay: 150,
	      data: function (params) {
		  return {
			q: params.term, // search term
			//q12: $("#searchDate").val(), // search term
			page: params.page
		  };
	      },
	      processResults: function (data, params) {
		  params.page = params.page || 1;
		  return {
			results: data.result,
			pagination: {
			  more: (params.page * 30) < data.total_count
			}
		  };
	      },
	      cache: true
	    },
	    escapeMarkup: function (markup) { return markup; }
		});
		});
		function validateNow() {
			   flag = deforayValidator.init({
				   formId: 'editFacilityInfo'
			   });
			   if (flag) {
				   if (duplicateName) {
					   document.getElementById('editFacilityInfo').submit();
				   }
			   }
		}
</script>