<style>
    .moveButtons{line-height: 35px;}
    /*.updateButton{padding:15px 0px 0px 45px;}*/
    .btn{font-weight: bold;}
    .ui-multiselect-filter input{color: #333 !important;}
    #upFaciltyName{width: 75%;}
    #facilityName{width: 100%;}
    .main-content{margin-top:15px;}
    .panel-body{height: 250px;}
    ul li span{padding: 4px; vertical-align: middle;}
    body{
	overflow-x:hidden;
    }
</style>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<div class="main-content">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">
                <div class="row" id="pendingFacilityName" >
                    <div class="col-sm-12">
                      <div class="panel panel-default">
                        <div class="panel-body" style="height:auto !important;">
                            <table class="col-lg-12">
                                <tr>
                                    <td class="col-lg-6">
                                        <b>Facility Name</b><span class="mandatory">*</span>
                                    </td>
                                    <td class="col-lg-6" align="center">
                                        <select id="facilityName" name="facilityName" onchange="getEditField(this.value);" class="form-control">
                                            <option value="">--select--</option>
                                            <?php
                                            foreach($facilityName['allName'] as $name){
                                                ?>
                                                <option value="<?php echo $name['facility_id']."##".$name['facility_name'];?>"><?php echo $name['facility_name'];?></option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                   </td>
                                </tr>
                                <tr>
                                    <td colspan="2"><hr></td>
                                </tr>
				<tr class="editFC" style="display:none;">
				    <td class="col-lg-6"><b>Facility Id</b> <span class="mandatory">*</span></td>
				    <td class="col-lg-6"><input type="text" name="facilityId" id="facilityId" class="form-control"/></td>
				</tr>
				<tr class="editFC" style="display:none;">
                                    <td colspan="2"><hr></td>
                                </tr>
				<tr class="editFC" style="display:none;">
				    <td class="col-lg-6"><b>Facility Name</b> <span class="mandatory">*</span></td>
				    <td class="col-lg-6"><input type="hidden" name="defaultFacilityName" id="defaultFacilityName"/><input type="text" name="editFacilityName" id="editFacilityName" class="form-control"/></td>
				</tr>
				<tr class="editFC" style="display:none;">
                                    <td colspan="2"><hr></td>
                                </tr>
				<tr>
                                    <td class="col-lg-6">
                                        <b>All Facility Name</b><span class="mandatory">*</span>
                                    </td>
                                    <td class="col-lg-6">
                                        <select id="upFaciltyName" name="upFaciltyName[]" class="" multiple="multiple">
                                            <?php
                                            foreach($facilityName['allName'] as $name){
                                                $facilityId = '';
                                                if($name['facility_id']!=''){
                                                 $facilityId = $name['facility_id']." - ".$name['facility_name'];
                                                }else{
                                                    $facilityId = $name['facility_name'];  
                                                }
                                                ?>
                                                <option value="<?php echo $name['facility_name'];?>"><?php echo $facilityId;?></option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                   </td>
                                </tr>
                                <tr>
                                    <td colspan="2"><hr>&nbsp;&nbsp;</td>
                                </tr>
                                <tr>
				    <td colspan="2" class="updateButton">
					<button type="button" onclick="updateFacilityName()" class="btn btn-space btn-primary">Merge Facility Name</button>
				    </td>
				</tr>
                            </table>
                        </div>
                      </div>
                    </div>
		    
                </div>
            </div>
            </div>
<script>
    $(document).ready(function(){
	$('#upFaciltyName').multipleSelect({
	    filter: true,
	    minimumCountSelected:'2',
	    placeholder:'Please select facility name',
            width: '100%'
        });
    });
    
    function updateFacilityName(){
        var fName = $("#facilityName").val();
        var facilityId = $("#facilityId").val();
        var dafaultFacilityName = $("#defaultFacilityName").val();
        var editFacilityName = $("#editFacilityName").val();
        var upFaciltyName = $("#upFaciltyName").val();
	
	//console.log(upFaciltyName);
        if(fName!='' && upFaciltyName!='' && upFaciltyName!=null){
	    if($.trim(facilityId)== ''){
		alert("Please enter facility id");
		$("#facilityId").focus();
		return false;
	    }else if($.trim(editFacilityName)== ''){
		alert("Please enter facility name");
		$("#editFacilityName").focus();
		return false;
	    }
	    var cnfm = confirm("Do you wish to merge facility names?");
	    if(cnfm){
		$.post("<?php echo $this->url('spi-v3-form',array('action'=>'merge-facility-name')); ?>",{fName:fName,facilityId:facilityId,dafaultFacilityName:dafaultFacilityName,editFacilityName:editFacilityName,upFaciltyName:upFaciltyName},
		function(data) {
		    if (data>0) {
		      alert("Facility name merged successfully");
		      parent.closeModal();
		      parent.window.location.href=window.parent.location.href;
		    }else{
		      alert("We have experienced the problem..Please try again later!");
		      parent.closeModal();
		      parent.window.location.href=window.parent.location.href;
		    }
		});
	    }
        }else{
            alert("Please choose facility name");
        }
    }
    
    function getEditField(objVal){
	var facilityId = '';
	if($.trim(objVal)!= ''){
	    splitObjVal = objVal.split("##");
	    $(".editFC").show();
	    $("#facilityId").val(splitObjVal[0]);
	    $("#defaultFacilityName").val(splitObjVal[1]);
	    $("#editFacilityName").val(splitObjVal[1]);
	}else{
	    $(".editFC").hide();
	    $("#facilityId").val("");
	    $("#defaultFacilityName").val("");
	    $("#editFacilityName").val("");
	}
    }
</script>