<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<style>
    .center{
        text-align:center;
    }
</style>
<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>Recommendations</h2>
            </div>
        </div>
    </div>

    <div class="main-content">
        <ul class="nav nav-tabs" id="recommendationTab" role="tablist">
            <li class="nav-item active">
              <input type="hidden" id="selectdeselect"/>  
              <a class="nav-link active" id="recommend-tab" data-toggle="tab" href="#recommend" role="tab" aria-controls="recommend" aria-selected="true">Waiting for Recommendation</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="recommended-tab" data-toggle="tab" href="#recommended" role="tab" aria-controls="recommended" aria-selected="false">Already Recommened</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="approved-tab" data-toggle="tab" href="#approved" role="tab" aria-controls="approved" aria-selected="false">Certification Approved</a>
            </li>
        </ul>
        <div class="tab-content" id="recommendationContent">
          <div class="tab-pane active" id="recommend" role="tabpanel" aria-labelledby="recommend-tab">
            <table id="recommendTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
                <thead>
                    <tr>
                        <th  style="width:4%;"># </th>
                        <th  style="width:10%;">Professional Registration No.<br>(if available) </th>
                        <th  style="width:10%;">Certification Registration no. </th>
                        <th  style="width:10%;">Certification ID  </th>
                        <th  style="width:10%;">Provider </th>
                        <th  style="width:10%;">Written Exam<br>Score </th>
                        <th  style="width:10%;">Practical Exam<br>Score </th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
          </div>
          <div class="tab-pane fade" id="recommended" role="tabpanel" aria-labelledby="recommended-tab">
            <table id="recommendedTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                <thead>
                    <tr>
                        <th  style="width:10%;"> Professional Registration No.<br>(if available) </th>
                        <th  style="width:10%;"> Certification Registration no. </th>
                        <th  style="width:10%;">Certification ID  </th>
                        <th  style="width:10%;">Provider</th>
                        <th  style="width:10%;"> Final Decision</th>
                        <th  style="width:10%;">Certificate Issuer</th>
                        <th  style="width:10%;">Date Certificate Issued</th>
                        <th  style="width:10%;">Date Certificate Sent</th>
                        <th  style="width:10%;">Type of Certification</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                     if(isset($recommended) && count($recommended) > 0){
                      foreach ($recommended as $certification){ ?>
                        <tr>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification['professional_reg_no']); ?></div></td>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification['certification_reg_no']); ?></div></td>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification['certification_id']); ?></div></td>
                            <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification['last_name'] . ' ' . $certification['first_name'] . ' ' . $certification['middle_name']); ?></div></td>
                            <td><div style="width:100px;height:40px;overflow:auto; color: red"><?php echo $this->escapeHtml($certification['final_decision']); ?></div></td>
                            <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification['certification_issuer']); ?></div></td>
                            <td><div style="width:100px;height:40px;overflow:auto;"><?php echo date("d-m-Y", strtotime($this->escapeHtml($certification['date_certificate_issued']))); ?></div></td>
                            <?php
                            if (isset($certification['date_certificate_sent']) && $certification['date_certificate_sent']!= null && $certification['date_certificate_sent']!= '' && $certification['date_certificate_sent']!= '0000-00-00') {
                                echo ' <td>' . date("d-m-Y", strtotime($this->escapeHtml($certification['date_certificate_sent']))) . '</td>';
                            } else {
                                echo ' <td></td>';
                            };
                            ?>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification['certification_type']); ?></div></td>  
                        </tr>
                        <?php } } else { ?>
                           <tr><td colspan="9">No data available in table</td></tr>
                        <?php } ?>
                </tbody>
            </table>
          </div>
          <div class="tab-pane fade" id="approved" role="tabpanel" aria-labelledby="approved-tab">
            <table id="approvedTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                <thead>
                    <tr>
                        <th  style="width:10%;"> Professional Registration No.<br>(if available) </th>
                        <th  style="width:10%;"> Certification Registration no. </th>
                        <th  style="width:10%;">Certification ID  </th>
                        <th  style="width:10%;">Provider</th>
                        <th  style="width:10%;"> Final Decision</th>
                        <th  style="width:10%;">Certificate Issuer</th>
                        <th  style="width:10%;">Date Certificate Issued</th>
                        <th  style="width:10%;">Date Certificate Sent</th>
                        <th  style="width:10%;">Type of Certification</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if(isset($approved) && count($approved) > 0){
                       foreach ($approved as $certification){ ?>
                        <tr>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification['professional_reg_no']); ?></div></td>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification['certification_reg_no']); ?></div></td>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification['certification_id']); ?></div></td>
                            <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification['last_name'] . ' ' . $certification['first_name'] . ' ' . $certification['middle_name']); ?></div></td>
                            <td><div style="width:100px;height:40px;overflow:auto; color: red"><?php echo $this->escapeHtml($certification['final_decision']); ?></div></td>
                            <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification['certification_issuer']); ?></div></td>
                            <td><div style="width:100px;height:40px;overflow:auto;"><?php echo date("d-m-Y", strtotime($this->escapeHtml($certification['date_certificate_issued']))); ?></div></td>
                            <?php
                            if (isset($certification['date_certificate_sent']) && $certification['date_certificate_sent']!= null && $certification['date_certificate_sent']!= '' && $certification['date_certificate_sent']!= '0000-00-00') {
                                echo ' <td>' . date("d-m-Y", strtotime($this->escapeHtml($certification['date_certificate_sent']))) . '</td>';
                            } else {
                                echo ' <td></td>';
                            };
                            ?>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification['certification_type']); ?></div></td>  
                        </tr>
                    <?php } } else { ?>
                        <tr><td colspan="9">No data available in table</td></tr>
                    <?php } ?>
                </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" language="javascript">
$('#recommendationTab a').on('click', function (e) {
  e.preventDefault()
  $(this).tab('show')
})

var recommendTable = null;
recommendationRow = [];
$(document).ready(function () {
    recommendInit();
    recommendedInit();
    approvedInit();
});

function recommendInit(){
    recommendTable = $('#recommendTable').DataTable({
        "bScrollCollapse": false,
        "bRetrieve": false,
        "bDestroy": true,
                    "pageLength": 50,
        "aoColumns": [
                {"sClass":"center","bSortable":false},
		{"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":"center"},
                {"sClass":"center"}
        ],
        "aaSorting": [[ 1, "asc" ]],
        "fnDrawCallback": function( oSettings ) {
            $('input:checkbox').each(function () {
                if($.inArray(this.value, recommendationRow)!= -1){
                    $('#'+this.id).prop('checked',true);
                }
                if($('#selectdeselect').val() == 'deselect'){
                    $('#'+this.id).prop('checked',false);
                }
            });
        },
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?php echo $this->url('examination',array('action' => 'index')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
            $.ajax({
                "dataType": 'json',
                "type": "POST",
                "url": sSource,
                "data": aoData,
                "success": fnCallback
            });
        }
    });
}

function recommendedInit(){
   $('#recommendedTable').dataTable();
}

function approvedInit(){
   $('#approvedTable').dataTable();
}

function selectForRecommendation(obj){
    var rowId = $(obj).attr('id');
    var rowValue = $(obj).attr('value');
    if($('#'+rowId).is(':checked')){
       recommendationRow.push(rowValue);
    }else{
       var examIndex = recommendationRow.indexOf(rowValue);
       recommendationRow.splice(examIndex, 1);
    }
    if(recommendationRow.length == 0){
       $('#certificationIssuer,.manageRecommendation').hide();
       $('.selectdeselect').attr('onclick','selectForAllRecommendation()');
       $('.selectdeselect').text('Select All');
    }else{
        $('#certificationIssuer,.manageRecommendation').show();
        $('.selectdeselect').attr('onclick','deSelectForAllRecommendation()');
        $('.selectdeselect').text('Deselect All');
    }
    $('.selectedRows').html(recommendationRow.length+' Row(s) Selected');
}

function selectForAllRecommendation(){
  recommendationRow = [];  
  $('#selectdeselect').val('select');
  $('.recommendationRow').prop('checked',true);

  var recommendIDs = $("#recommendTable input:checkbox:checked").map(function(){
      return $(this).val();
    }).get();
  recommendationRow = recommendIDs;
  if(recommendationRow.length > 0){
        $('#certificationIssuer,.manageRecommendation').show();
        $('.selectdeselect').attr('onclick','deSelectForAllRecommendation()');
        $('.selectdeselect').text('Deselect All'); 
        $('.selectedRows').html(recommendationRow.length+' Row(s) Selected');
  }else{
    alert('Data not available');
  }
}

function deSelectForAllRecommendation(){
    recommendationRow = [];
    $('#certificationIssuer,.manageRecommendation').hide();
    $('#selectdeselect').val('deselect');
    $('.recommendationRow').prop('checked',false);
    $('.selectdeselect').attr('onclick','selectForAllRecommendation()');
    $('.selectdeselect').text('Select All');
    $('.selectedRows').html(recommendationRow.length+' Row(s) Selected');
}

function manageRecommendation(){
   if(recommendationRow.length == 0){
        alert('Please select atleast one exam and then submit');
        return false;
    }else if($.trim($('#certificationIssuer').val()) == ''){
        alert('Please enter certificate issuer name');
        $('#certificationIssuer').focus();
        return false;
    }else{
        $.post("<?php echo $this->url('certification',array('action'=>'recommend')); ?>", {recommendationRow:recommendationRow,certificationIssuer:$('#certificationIssuer').val()},
        function(data){
            deSelectForAllRecommendation();
            recommendTable.draw();
        });
    }
}

//Insert a raw HTML into data table
var count_elem = document.getElementById('recommendTable');
var div = document.createElement('div');
div.innerHTML = '<span class="selectedRows">0  Row(s) Selected</span>&nbsp;&nbsp;&nbsp;&nbsp;<a class="btn btn-dark selectdeselect" href="javascript:void(0);" onclick="selectForAllRecommendation();" style="padding:4px;">Select All</a>&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" id="certificationIssuer" placeholder="Certificate Issuer" style="display:none;margin-right:1%;"/><a class="btn btn-primary manageRecommendation" href="javascript:void(0);" onclick="manageRecommendation();" style="display:none;padding:4px;">Submit</a>';
count_elem.parentNode.insertBefore(div, count_elem);
</script>