<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<style>
    .center{
        text-align:center;
    }
</style>
<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>Recommendations</h2>
            </div>
        </div>
    </div>

    <div class="main-content">
        <ul class="nav nav-tabs" id="recommendationTab" role="tablist">
            <li class="nav-item active">
              <input type="hidden" id="selectdeselect"/>  
              <a class="nav-link active" id="recommend-tab" data-toggle="tab" href="#recommend" role="tab" aria-controls="recommend" aria-selected="true" onclick="recommendInit();">Waiting for Recommendation</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="recommended-tab" data-toggle="tab" href="#recommended" role="tab" aria-controls="recommended" aria-selected="false" onclick="recommendedInit();">Already Recommened</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="approved-tab" data-toggle="tab" href="#approved" role="tab" aria-controls="approved" aria-selected="false" onclick="approvedInit();">Certification Approved</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="pending-tab" data-toggle="tab" href="#pending" role="tab" aria-controls="pending" aria-selected="true" onclick="pendingTestsInit();">Incomplete Tests</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="failed-tab" data-toggle="tab" href="#failed" role="tab" aria-controls="failed" aria-selected="false" onclick="failedTestsInit();">Failed Tests</a>
            </li>
        </ul>
        <div class="tab-content" id="recommendationContent">
          <div class="tab-pane active" id="recommend" role="tabpanel" aria-labelledby="recommend-tab">
            <table id="recommendTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
                <thead>
                    <tr>
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'recommend')) { ?>
                          <th  style="width:4%;"># </th>
                        <?php } ?>
                        <th  style="width:10%;">Tester </th>
                        <th  style="width:10%;">Professional Registration No.<br>(if available) </th>
                        
                        <th  style="width:10%;">Certification Registration no. </th>
                        <th  style="width:10%;">Certification ID  </th>
                        
                        <th  style="width:10%;">Written Exam<br>Score </th>
                        <th  style="width:10%;">Practical Exam<br>Score </th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
          </div>
          <div class="tab-pane fade" id="recommended" role="tabpanel" aria-labelledby="recommended-tab">
            <table id="recommendedTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                <thead>
                    <tr>
                    <th  style="width:10%;">Tester</th>
                        <th  style="width:10%;"> Professional Registration No.<br>(if available) </th>
                        <th  style="width:10%;"> Certification Registration no. </th>
                        <th  style="width:10%;">Certification ID  </th>
                        
                        <th  style="width:10%;"> Final Decision</th>
                        <th  style="width:10%;">Certificate Recommended By</th>
                        <th  style="width:10%;">Date Certificate Issued</th>
                        <th  style="width:10%;">Date Certificate Sent</th>
                        <th  style="width:10%;">Type of Certification</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                        </td>
                    </tr>
                </tbody>
            </table>
          </div>
          <div class="tab-pane fade" id="approved" role="tabpanel" aria-labelledby="approved-tab">
            <table id="approvedTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                <thead>
                    <tr>
                        <th  style="width:10%;">Tester</th>
                        <th  style="width:10%;"> Professional Registration No.<br>(if available) </th>
                        <th  style="width:10%;"> Certification Registration no. </th>
                        <th  style="width:10%;">Certification ID  </th>
                        
                        <th  style="width:10%;"> Final Decision</th>
                        <th  style="width:10%;">Certificate Recommended By</th>
                        <th  style="width:10%;">Date Certificate Issued</th>
                        <th  style="width:10%;">Date Certificate Sent</th>
                        <th  style="width:10%;">Type of Certification</th>
                    <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'pdf')) { ?>
                        <th  style="width:10%;">PDF</th>
                    <?php } ?>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
          </div>
          <div class="tab-pane fade" id="pending" role="tabpanel" aria-labelledby="pending-tab">
            <table id="pendingTestTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                <thead>
                    <tr>
                        <th  style="width:10%;">Tester </th>
                        <th  style="width:10%;">Region</th>
                        <th  style="width:10%;">District</th>
                        <th  style="width:10%;">Phone</th>
                        <th  style="width:10%;">Email</th>
                        <th  style="width:10%;">Writen Exam Date</th>
                        <th  style="width:10%;">Writen Test Score</th>
                        <th  style="width:10%;">Practical Exam Date</th>
                        <th  style="width:10%;">Practical Test Score</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
          </div>
          <div class="tab-pane fade" id="failed" role="tabpanel" aria-labelledby="failed-tab">
            <table id="failedTestTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                <thead>
                    <tr>
                        <th  style="width:10%;">Tester </th>
                        <th  style="width:10%;">Region</th>
                        <th  style="width:10%;">District</th>
                        <th  style="width:10%;">Phone</th>
                        <th  style="width:10%;">Email</th>
                        <th  style="width:10%;">Writen Exam Date</th>
                        <th  style="width:10%;">Writen Test Score</th>
                        <th  style="width:10%;">Practical Exam Date</th>
                        <th  style="width:10%;">Practical Test Score</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" language="javascript">
$('#recommendationTab a').on('click', function (e) {
  e.preventDefault()
  $(this).tab('show')
})

var recommendTable = null;
recommendationRow = [];
$(document).ready(function () {
    recommendInit();
    recommendedInit();
    approvedInit();
    pendingTestsInit();
    failedTestsInit();
});

function recommendInit(){
    recommendTable = $('#recommendTable').DataTable({
        "bAutoWidth": false,
        "bScrollCollapse": false,
        "bRetrieve": false,
        "bDestroy": true,
        "pageLength": 50,
        "aoColumns": [
               <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'recommend')) { ?>
                {"sClass":"center","bSortable":false},
               <?php } ?>
		{"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":"center"},
                {"sClass":"center"}
        ],
        //"aaSorting": [[ < ?php echo ($acl->isAllowed($role, 'Certification\Controller\Certification', 'recommend'))?2:1; ?>, "asc" ]],
        "aaSorting": [],
        "fnDrawCallback": function( oSettings ) {
            $('input:checkbox').each(function () {
                if($.inArray(this.value, recommendationRow)!= -1){
                    $('#'+this.id).prop('checked',true);
                }
                if($('#selectdeselect').val() == 'deselect'){
                    $('#'+this.id).prop('checked',false);
                }
            });
        },
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?php echo $this->url('examination',array('action' => 'index')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
            $.ajax({
                "dataType": 'json',
                "type": "POST",
                "url": sSource,
                "data": aoData,
                "success": fnCallback
            });
        }
    });
}

function recommendedInit(){
   $('#recommendedTable').dataTable({
    "bAutoWidth": false,
        "bScrollCollapse": false,
        "bRetrieve": false,
        "bDestroy": true,
        "pageLength": 50,
        "aoColumns": [
		{"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":""}
        ],
        "aaSorting": [],
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?php echo $this->url('examination',array('action' => 'recommended')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
            $.ajax({
                "dataType": 'json',
                "type": "POST",
                "url": sSource,
                "data": aoData,
                "success": fnCallback
            });
        }
    });
}

function approvedInit(){
   $('#approvedTable').dataTable({
    "bAutoWidth": false,
        "bScrollCollapse": false,
        "bRetrieve": false,
        "bDestroy": true,
        "pageLength": 50,
        "aoColumns": [
		{"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":""},
            <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'pdf')) { ?>
                {"sClass":"center"}
            <?php } ?>
        ],
        "aaSorting": [],
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?php echo $this->url('examination',array('action' => 'approved')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
            $.ajax({
                "dataType": 'json',
                "type": "POST",
                "url": sSource,
                "data": aoData,
                "success": fnCallback
            });
        }
    });
}

function pendingTestsInit(){
  $('#pendingTestTable').dataTable({
    "bAutoWidth": false,
        "bScrollCollapse": false,
        "bRetrieve": false,
        "bDestroy": true,
        "pageLength": 10,
        "aoColumns": [
		{"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""}
        ],
        "aaSorting": [[ 0, "asc" ]],
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?php echo $this->url('examination',array('action' => 'pending')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
            $.ajax({
                "dataType": 'json',
                "type": "POST",
                "url": sSource,
                "data": aoData,
                "success": fnCallback
            });
        }
    });
}

function failedTestsInit(){
  $('#failedTestTable').dataTable({
    "bAutoWidth": false,
        "bScrollCollapse": false,
        "bRetrieve": false,
        "bDestroy": true,
        "pageLength": 10,
        "aoColumns": [
		{"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""}
        ],
        "aaSorting": [[ 0, "asc" ]],
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?php echo $this->url('examination',array('action' => 'failed')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
            $.ajax({
                "dataType": 'json',
                "type": "POST",
                "url": sSource,
                "data": aoData,
                "success": fnCallback
            });
        }
    });
}

function selectForRecommendation(obj){
    var rowId = $(obj).attr('id');
    var rowValue = $(obj).attr('value');
    if($('#'+rowId).is(':checked')){
       recommendationRow.push(rowValue);
    }else{
       var examIndex = recommendationRow.indexOf(rowValue);
       recommendationRow.splice(examIndex, 1);
    }
    if(recommendationRow.length == 0){
       $('#certificationIssuer,.manageRecommendation').hide();
       $('.selectdeselect').attr('onclick','selectForAllRecommendation()');
       $('.selectdeselect').text('Select All');
    }else{
        $('#certificationIssuer,.manageRecommendation').show();
        $('.selectdeselect').attr('onclick','deSelectForAllRecommendation()');
        $('.selectdeselect').text('Deselect All');
    }
    $('.selectedRows').html(recommendationRow.length+' Row(s) Selected');
}

function selectForAllRecommendation(){
    recommendationRow = [];  
    $('#selectdeselect').val('select');
    $('.recommendationRow').prop('checked',true);
  
    var recommendIDs = $("#recommendTable input:checkbox:checked").map(function(){
        return $(this).val();
      }).get();
    recommendationRow = recommendIDs;
    if(recommendationRow.length > 0){
          $('#certificationIssuer,.manageRecommendation').show();
          $('.selectdeselect').attr('onclick','deSelectForAllRecommendation()');
          $('.selectdeselect').text('Deselect All'); 
          $('.selectedRows').html(recommendationRow.length+' Row(s) Selected');
    }else{
      alert('Selection not available');
    }
}

function deSelectForAllRecommendation(){
    recommendationRow = [];
    $('#certificationIssuer,.manageRecommendation').hide();
    $('#selectdeselect').val('deselect');
    $('.recommendationRow').prop('checked',false);
    $('.selectdeselect').attr('onclick','selectForAllRecommendation()');
    $('.selectdeselect').text('Select All');
    $('.selectedRows').html(recommendationRow.length+' Row(s) Selected');
}

function manageRecommendation(){
   if(recommendationRow.length == 0){
        alert('Please select atleast one row and then submit');
        return false;
    }else if($.trim($('#certificationIssuer').val()) == ''){
        alert('Please enter certificate issuer name');
        $('#certificationIssuer').focus();
        return false;
    }else{
        $.post("<?php echo $this->url('certification',array('action'=>'recommend')); ?>", {recommendationRow:recommendationRow,certificationIssuer:$('#certificationIssuer').val()},
        function(data){
            deSelectForAllRecommendation();
            recommendTable.draw();
        });
    }
}

<?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'recommend')) { ?>
//Insert a raw HTML into data table
var count_elem = document.getElementById('recommendTable');
var div = document.createElement('div');
div.innerHTML = '<a class="btn btn-dark selectdeselect" href="javascript:void(0);" onclick="selectForAllRecommendation();" style="padding:4px;margin-bottom: 1vh;">Select All</a>&nbsp;&nbsp;&nbsp;&nbsp;<span class="selectedRows">0 Row(s) Selected</span>&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" id="certificationIssuer" placeholder="Certificate Issuer" style="display:none;margin-right:1%;"/><a class="btn btn-primary manageRecommendation" href="javascript:void(0);" onclick="manageRecommendation();" style="display:none;padding:4px;margin-bottom: 1vh;">Submit</a>';
count_elem.parentNode.insertBefore(div, count_elem);
<?php } ?>
</script>