<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-8">
                <h2>Pending/Other Tests</h2>
            </div>
        </div>
    </div>

    <div class="main-content">
        <ul class="nav nav-tabs" id="pendingOtherTab" role="tablist">
            <li class="nav-item active">
              <a class="nav-link active" id="pending-tab" data-toggle="tab" href="#pending" role="tab" aria-controls="pending" aria-selected="true" onclick="pendingTestsInit();">Incomplete Tests</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="failed-tab" data-toggle="tab" href="#failed" role="tab" aria-controls="failed" aria-selected="false" onclick="failedTestsInit();">Failed Tests</a>
            </li>
        </ul>
        <div class="tab-content" id="pendingOtherContent">
          <div class="tab-pane active" id="pending" role="tabpanel" aria-labelledby="pending-tab">
            <table id="pendingTestTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                <thead>
                    <tr>
                        <th  style="width:10%;">Provider </th>
                        <th  style="width:10%;">Region</th>
                        <th  style="width:10%;">District</th>
                        <th  style="width:10%;">Phone</th>
                        <th  style="width:10%;">Email</th>
                        <th  style="width:10%;">Writen Exam Date</th>
                        <th  style="width:10%;">Writen Test Score</th>
                        <th  style="width:10%;">Practical Exam Date</th>
                        <th  style="width:10%;">Practical Test Score</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
          </div>
          <div class="tab-pane fade" id="failed" role="tabpanel" aria-labelledby="failed-tab">
            <table id="failedTestTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                <thead>
                    <tr>
                        <th  style="width:10%;">Provider </th>
                        <th  style="width:10%;">Region</th>
                        <th  style="width:10%;">District</th>
                        <th  style="width:10%;">Phone</th>
                        <th  style="width:10%;">Email</th>
                        <th  style="width:10%;">Writen Exam Date</th>
                        <th  style="width:10%;">Writen Test Score</th>
                        <th  style="width:10%;">Practical Exam Date</th>
                        <th  style="width:10%;">Practical Test Score</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" language="javascript">
$('#pendingOtherTab a').on('click', function (e) {
  e.preventDefault()
  $(this).tab('show')
})

$(document).ready(function () {
   pendingTestsInit();
   failedTestsInit();
});

function pendingTestsInit(){
  $('#pendingTestTable').dataTable({
    "bAutoWidth": false,
        "bScrollCollapse": false,
        "bRetrieve": false,
        "bDestroy": true,
        "pageLength": 10,
        "aoColumns": [
		{"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""}
        ],
        "aaSorting": [[ 0, "asc" ]],
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?php echo $this->url('examination',array('action' => 'pending')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
            $.ajax({
                "dataType": 'json',
                "type": "POST",
                "url": sSource,
                "data": aoData,
                "success": fnCallback
            });
        }
    });
}

function failedTestsInit(){
  $('#failedTestTable').dataTable({
    "bAutoWidth": false,
        "bScrollCollapse": false,
        "bRetrieve": false,
        "bDestroy": true,
        "pageLength": 10,
        "aoColumns": [
		{"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""}
        ],
        "aaSorting": [[ 0, "asc" ]],
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?php echo $this->url('examination',array('action' => 'failed')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
            $.ajax({
                "dataType": 'json',
                "type": "POST",
                "url": sSource,
                "data": aoData,
                "success": fnCallback
            });
        }
    });
}
</script>