<?php

use Zend\Debug\Debug;
use Zend\Session\Container;
$sessionLogin = new Container('credo');
// Debug::dump($country);die;
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">

    <div class="page-head">
        <div class="row">
            <div class="col-sm-8"> <h2>Incomplete/Pending Examination Reports</h2></div>
        </div>
    </div>
    <div class="main-content">
        <ul class="nav nav-tabs" id="examinationTab" role="tablist">
            <li class="nav-item active">
                <a class="nav-link active" id="online-tab" data-toggle="tab" href="#online-test" role="tab" aria-controls="online-test" aria-selected="false" >Incomplete Online Written Tests</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="practical-tab" data-toggle="tab" href="#practical-test" role="tab" aria-controls="practical-test" aria-selected="true" >Pending Practical Tests</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="written-tab" data-toggle="tab" href="#written-test" role="tab" aria-controls="written-test" aria-selected="false">Pending Written Tests</a>
            </li>
        </ul>
        <div class="tab-content" id="examinationContent">
            <div class="tab-pane active" id="online-test" role="tabpanel" aria-labelledby="online-tab">
                <div class="widget widget-small">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <form action="<?php $this->url('examination', array('action' => 'xls')); ?>" name="form" method="post" >
                                    <div class="col-lg-6">
                                        <label for="Country">Country</label>
                                        <select name="country" class="form-control" autocomplete="off" id="Country" onclick="emptyInput(this)" onchange="showRegion(this.value,'online')">
                                            <option value="" selected>Please Choose a Country</option>
                                            <?php foreach($country as $crow) { ?>
                                                <option value="<?php echo $crow['country_id'];?>" <?php echo ($crow['country_id'] == 1)?"selected='selected'":'';?>><?php echo $crow['country_name'];?></option>
                                            <?php } ?>
                                        </select>                            
                                    </div>

                                    <div class="col-lg-6">
                                        <label for="Region">Province</label>
                                        <select name="region" class="form-control" autocomplete="off" id="Region" onclick="emptyInput(this)" onchange="showDistrict(this.value,'online')">
                                            <option value="">Please choose a Country</option>
                                        </select>                                                                    
                                    </div>
                                    <div class="col-lg-6">
                                        <label for="District">Districts</label>
                                        <select name="district" class="form-control" id="District" autocomplete="off" onclick="emptyInput(this)">
                                            <option value="">Please Choose a District</option>
                                        </select>                                                                    
                                    </div>
                                    <input type="hidden" id="Exam" name="Exam" value="online-exam">
                                    <div class="col-lg-12" style="margin-top: 30px;text-align:center;">
                                        <a class="btn btn-space btn-primary" href="javascript:void(0);" onclick="getReportOnlineTest('online-exam');">GET REPORT</a>
                                        <!-- <button type="submit" class="btn btn-space btn-primary">DOWNLOAD REPORT</button> -->
                                        <a class="btn btn-space btn-default" role="button" href="<?php echo $this->url('examination', array('action' => 'xls')); ?>" >CANCEL</a>
                                    </div>
                                </form>
                                <div id="online-exam"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="practical-test" role="tabpanel" aria-labelledby="practical-tab">
                <div class="widget widget-small">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <form action="<?php $this->url('examination', array('action' => 'xls')); ?>" name="form" method="post" >
                                    <div class="col-lg-6">
                                        <label for="Country">Country</label>
                                        <select name="country" class="form-control" autocomplete="off" id="Country" onclick="emptyInput(this)" onchange="showRegion(this.value,'practical')">
                                            <option value="" selected>Please Choose a Country</option>
                                            <?php foreach($country as $crow) { ?>
                                                <option value="<?php echo $crow['country_id'];?>" <?php echo ($crow['country_id'] == 1)?"selected='selected'":'';?>><?php echo $crow['country_name'];?></option>
                                            <?php } ?>
                                        </select>                            
                                    </div>

                                    <div class="col-lg-6">
                                        <label for="Region">Province</label>
                                        <select name="region" class="form-control" autocomplete="off" id="Region" onclick="emptyInput(this)" onchange="showDistrict(this.value,'practical')">
                                            <option value="">Please choose a Country</option>
                                        </select>                                                                    
                                    </div>
                                    <div class="col-lg-6">
                                        <label for="District">Districts</label>
                                        <select name="district" class="form-control" id="District" autocomplete="off" onclick="emptyInput(this)">
                                            <option value="">Please Choose a District</option>
                                        </select>                                                                    
                                    </div>
                                    <input type="hidden" id="Exam" name="Exam" value="practical-exam">
                                    <div class="col-lg-12" style="margin-top: 30px;text-align:center;">
                                        <a class="btn btn-space btn-primary" href="javascript:void(0);" onclick="getReportOnlineTest('practical-exam');">GET REPORT</a>
                                        <!-- <button type="submit" class="btn btn-space btn-primary">DOWNLOAD REPORT</button> -->
                                        <a class="btn btn-space btn-default" role="button" href="<?php echo $this->url('examination', array('action' => 'xls')); ?>" >CANCEL</a>
                                    </div>
                                </form>
                                <div id="practical-exam"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="written-test" role="tabpanel" aria-labelledby="written-tab">
                <div class="widget widget-small">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <form action="<?php $this->url('examination', array('action' => 'xls')); ?>" name="form" method="post" >
                                    <div class="col-lg-6">
                                        <label for="Country">Country</label>
                                        <select name="country" class="form-control" autocomplete="off" id="Country" onclick="emptyInput(this)" onchange="showRegion(this.value,'written')">
                                            <option value="" selected>Please Choose a Country</option>
                                            <?php foreach($country as $crow) { ?>
                                                <option value="<?php echo $crow['country_id'];?>" <?php echo ($crow['country_id'] == 1)?"selected='selected'":'';?>><?php echo $crow['country_name'];?></option>
                                            <?php } ?>
                                        </select>                            
                                    </div>

                                    <div class="col-lg-6">
                                        <label for="Region">Province</label>
                                        <select name="region" class="form-control" autocomplete="off" id="Region" onclick="emptyInput(this)" onchange="showDistrict(this.value,'written')">
                                            <option value="">Please choose a Country</option>
                                        </select>                                                                    
                                    </div>
                                    <div class="col-lg-6">
                                        <label for="District">Districts</label>
                                        <select name="district" class="form-control" id="District" autocomplete="off" onclick="emptyInput(this)">
                                            <option value="">Please Choose a District</option>
                                        </select>                                                                    
                                    </div>
                                    <input type="hidden" id="Exam" name="Exam" value="written-exam">
                                    <div class="col-lg-12" style="margin-top: 30px;text-align:center;">
                                        <a class="btn btn-space btn-primary" href="javascript:void(0);" onclick="getReportOnlineTest('written-exam');">GET REPORT</a>
                                        <!-- <button type="submit" class="btn btn-space btn-primary">DOWNLOAD REPORT</button> -->
                                        <a class="btn btn-space btn-default" role="button" href="<?php echo $this->url('examination', array('action' => 'xls')); ?>" >CANCEL</a>
                                    </div>
                                </form>
                                <div id="written-exam"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

    <script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


    <script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/certification.js'); ?>"></script>
    <script>
    $(document).ready(function () {
        $("#Country").val(1);
        showRegion(1,'online');
        showRegion(1,'practical');
        showRegion(1,'written');
    });
    function showRegion(str,type) {
        if (str == "") {
            if(type == 'online'){
                $(".region-online").html("<option value=''>Please Choose a Region</option>");
                $(".district-online").html("<option value=''>Please Choose a Region</option>");
            }
            if(type == 'practical'){
                $(".region-practical").html("<option value=''>Please Choose a Region</option>");
                $(".district-practical").html("<option value=''>Please Choose a Region</option>");
            }
            if(type == 'written'){
                $(".region-written").html("<option value=''>Please Choose a Region</option>");
                $(".district-written").html("<option value=''>Please Choose a Region</option>");
            }

            return false;
        }else{
            $.post("<?php echo $this->url('provider', array('action' => 'region')); ?>", {q: str},
            function(data) {
                if(type == 'online'){
                    $(".region-online").html(data);
                    $(".district-online").html("<option value=''>Please Choose a District</option>");
                }
                if(type == 'practical'){
                    $(".region-practical").html(data);
                    $(".district-practical").html("<option value=''>Please Choose a District</option>");
                }
                if(type == 'written'){
                    $(".region-written").html(data);
                    $(".district-written").html("<option value=''>Please Choose a District</option>");
                }
            });
        }
    }
    
    function showDistrict(str,type) {
        if (str == "") {
            if(type == 'online'){
                $(".district-online").html("Please Choose a Region First");
            }
            if(type == 'practical'){
                $(".district-practical").html("Please Choose a Region First");
            }
            if(type == 'written'){
                $(".district-written").html("Please Choose a Region First");
            }
            return;
        } else {
            $.post("<?php echo $this->url('provider', array('action' => 'district')); ?>", {q: str},
            function(data) {
                if(type == 'online'){
                    $(".district-online").html(data);
                }
                if(type == 'practical'){
                    $(".district-practical").html(data);
                }
                if(type == 'written'){
                    $(".district-written").html(data);
                }
            });
        }
    }

    function getReportOnlineTest(exam){
        $('#'+exam).html('');
        $.blockUI();
        $.post("<?php echo $this->url('examination', array('action' => 'get-report')); ?>", {
            Region: $('#Region').val(),District: $('#District').val(),Country: $('#Country').val(),Exam: exam
        },function(data) {
            $('#'+exam).html(data);
            var table = $('#'+exam+'-table').DataTable({
                "aProcessing": true,
                "aServerSide": true,
                "aaSorting": [],
            });
        });
        $.unblockUI();
    }
    </script>