<?php

use Zend\Debug\Debug;
use Zend\Session\Container;
$sessionLogin = new Container('credo');
// Debug::dump($country);die;

$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
$editActionVal = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">

    <div class="page-head">
        <div class="row">
            <div class="col-sm-8"> <h2>Incomplete/Pending Examination Reports</h2></div>
        </div>
    </div>
    <div class="main-content">
        <ul class="nav nav-tabs" id="examinationTab" role="tablist">
            <li class="nav-item active">
                <a class="nav-link active" id="online-tab" data-toggle="tab" href="#online-test" role="tab" aria-controls="online-test" aria-selected="false" >Incomplete Online Written Tests</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="practical-tab" data-toggle="tab" href="#practical-test" role="tab" aria-controls="practical-test" aria-selected="true" >Pending Practical Tests</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="written-tab" data-toggle="tab" href="#written-test" role="tab" aria-controls="written-test" aria-selected="false">Pending Written Tests</a>
            </li>
        </ul>
        <div class="tab-content" id="examinationContent">
            <div class="tab-pane active" id="online-test" role="tabpanel" aria-labelledby="online-tab">
                <div class="widget widget-small">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <form action="<?php $this->url('examination', array('action' => 'xls')); ?>" name="form" method="post" >
                                    <div class="col-lg-6">
                                        <label for="Country">Country</label>
                                        <select name="country" class="form-control" autocomplete="off" id="Country" onclick="emptyInput(this)" onchange="showRegion(this.value,'online')">
                                            <option value="" selected>Please Choose a Country</option>
                                            <?php foreach($country as $crow) { ?>
                                                <option value="<?php echo $crow['country_id'];?>" <?php echo ($crow['country_id'] == 1)?"selected='selected'":'';?>><?php echo $crow['country_name'];?></option>
                                            <?php } ?>
                                        </select>                            
                                    </div>

                                    <div class="col-lg-6">
                                        <label for="Region">Province</label>
                                        <select name="region" class="form-control" autocomplete="off" id="Region" onclick="emptyInput(this)" onchange="showDistrict(this.value,'online')">
                                            <option value="">Please choose a Country</option>
                                        </select>                                                                    
                                    </div>
                                    <div class="col-lg-6">
                                        <label for="District">Districts</label>
                                        <select name="district" class="form-control" id="District" autocomplete="off" onclick="emptyInput(this)">
                                            <option value="">Please Choose a District</option>
                                        </select>                                                                    
                                    </div>
                                    <input type="hidden" id="Exam" name="Exam" value="online-exam">
                                    <div class="col-lg-12" style="margin-top: 30px;text-align:center;">
                                    <input type="hidden" id="certificationExpiryVal" name="certificationExpiryVal" value="didNotRecertify">
                                        <!-- <a class="btn btn-space btn-primary" href="javascript:void(0);" onclick="getReportOnlineTest('online-exam');">GET REPORT</a> -->
                                        <a class="btn btn-space btn-primary" href="javascript:void(0);"  onclick="searchAllOrderData();">GET REPORT</a>
                                        <button type="submit" class="btn btn-space btn-primary">DOWNLOAD REPORT</button>
                                        <a class="btn btn-space btn-danger" role="button" href="<?php echo $this->url('examination', array('action' => 'xls')); ?>" >CLEAR</a>
                                    </div>
                                </form>
                                <div id="online-exam">
                                <table id="online-exam-table" class="datatables table table-bordered table-responsive table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th style="width: 20%;">Test Started Date time</th>
                                            <th style="width: 20%;">Tester Name</th>
                                            <th style="width: 20%;">Professional No</th>
                                            <th style="width: 20%;">Phone</th>
                                            <th style="width: 20%;">Email</th>
                                            <th style="width: 20%;">Region</th>
                                            <th style="width: 20%;">District</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                     
                                    </tbody>
                                </table>
                        </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="practical-test" role="tabpanel" aria-labelledby="practical-tab">
                <div class="widget widget-small">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <form action="<?php $this->url('examination', array('action' => 'xls')); ?>" name="form" method="post" >
                                    <div class="col-lg-6">
                                        <label for="Country">Country</label>
                                        <select name="countrytab2" class="form-control" autocomplete="off" id="Countrytab2" onclick="emptyInput(this)" onchange="showRegion(this.value,'practical')">
                                            <option value="" selected>Please Choose a Country</option>
                                            <?php foreach($country as $crow) { ?>
                                                <option value="<?php echo $crow['country_id'];?>" <?php echo ($crow['country_id'] == 1)?"selected='selected'":'';?>><?php echo $crow['country_name'];?></option>
                                            <?php } ?>
                                        </select>                            
                                    </div>

                                    <div class="col-lg-6">
                                        <label for="Region">Province</label>
                                        <select name="regiontab2" class="form-control" autocomplete="off" id="Regiontab2" onclick="emptyInput(this)" onchange="showDistrict(this.value,'practical')">
                                            <option value="">Please choose a Country</option>
                                        </select>                                                                    
                                    </div>
                                    <div class="col-lg-6">
                                        <label for="District">Districts</label>
                                        <select name="districttab2" class="form-control" id="Districttab2" autocomplete="off" onclick="emptyInput(this)">
                                            <option value="">Please Choose a District</option>
                                        </select>                                                                    
                                    </div>
                                    <input type="hidden" id="Exam" name="Exam" value="practical-exam">
                                    <div class="col-lg-12" style="margin-top: 30px;text-align:center;">
                                        <!-- <a class="btn btn-space btn-primary" href="javascript:void(0);" onclick="getReportOnlineTest('practical-exam');">GET REPORT</a> -->
                                        <a class="btn btn-space btn-primary" href="javascript:void(0);"  onclick="searchAllOrderData();">GET REPORT</a>
                                        <button type="submit" class="btn btn-space btn-primary">DOWNLOAD REPORT</button>
                                        <a class="btn btn-space btn-default" role="button" href="<?php echo $this->url('examination', array('action' => 'xls')); ?>" >CANCEL</a>
                                    </div>
                                </form>
                                <div id="practical-exam">
                                <table id="practical-exam-table" class="datatables table table-bordered table-responsive table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th style="width: 20%;">Tester Name</th>
                                            <th style="width: 20%;">Professional No</th>
                                            <th style="width: 20%;">Phone</th>
                                            <th style="width: 20%;">Email</th>
                                            <th style="width: 20%;">Region</th>
                                            <th style="width: 20%;">District</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                       
                                    </tbody>
                                </table>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="written-test" role="tabpanel" aria-labelledby="written-tab">
                <div class="widget widget-small">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <form action="<?php $this->url('examination', array('action' => 'xls')); ?>" name="form" method="post" >
                                    <div class="col-lg-6">
                                        <label for="Country">Country</label>
                                        <select name="countrytab3" class="form-control" autocomplete="off" id="Countrytab3" onclick="emptyInput(this)" onchange="showRegion(this.value,'written')">
                                            <option value="" selected>Please Choose a Country</option>
                                            <?php foreach($country as $crow) { ?>
                                                <option value="<?php echo $crow['country_id'];?>" <?php echo ($crow['country_id'] == 1)?"selected='selected'":'';?>><?php echo $crow['country_name'];?></option>
                                            <?php } ?>
                                        </select>                            
                                    </div>

                                    <div class="col-lg-6">
                                        <label for="Region">Province</label>
                                        <select name="regiontab3" class="form-control" autocomplete="off" id="Regiontab3" onclick="emptyInput(this)" onchange="showDistrict(this.value,'written')">
                                            <option value="">Please choose a Country</option>
                                        </select>                                                                    
                                    </div>
                                    <div class="col-lg-6">
                                        <label for="District">Districts</label>
                                        <select name="districttab3" class="form-control" id="Districttab3" autocomplete="off" onclick="emptyInput(this)">
                                            <option value="">Please Choose a District</option>
                                        </select>                                                                    
                                    </div>
                                    <input type="hidden" id="Exam" name="Exam" value="written-exam">
                                    <div class="col-lg-12" style="margin-top: 30px;text-align:center;">
                                        <!-- <a class="btn btn-space btn-primary" href="javascript:void(0);" onclick="getReportOnlineTest('written-exam');">GET REPORT</a> -->
                                        <a class="btn btn-space btn-primary" href="javascript:void(0);"  onclick="searchAllOrderData();">GET REPORT</a>
                                        <button type="submit" class="btn btn-space btn-primary">DOWNLOAD REPORT</button>
                                        <a class="btn btn-space btn-default" role="button" href="<?php echo $this->url('examination', array('action' => 'xls')); ?>" >CANCEL</a>
                                    </div>
                                </form>
                                <div id="written-exam">

                                <table id="written-exam-table" class="datatables table table-bordered table-responsive table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th style="width: 20%;">Tester Name</th>
                                            <th style="width: 20%;">Professional No</th>
                                            <th style="width: 20%;">Phone</th>
                                            <th style="width: 20%;">Email</th>
                                            <th style="width: 20%;">Region</th>
                                            <th style="width: 20%;">District</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                       
                                    </tbody>
                                </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

    <script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


    <script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/certification.js'); ?>"></script>
    <script>
    aTable = null;
	bTable = null;
	cTable = null;
    $(document).ready(function () {
        $("#Country").val(1);
        $("#Countrytab2").val(1);
        $("#Countrytab3").val(1);
        showRegion(1,'online');
        showRegion(1,'practical');
        showRegion(1,'written');
        aTable =$('#practical-exam-table').dataTable({
                "bAutoWidth": false,
                    "bProcessing": true,
                    "bServerSide": true,
                    "bStateSave": true,
                    "aoColumns": [
                    <?php echo $editAction;?>
                        ],
                "aaSorting": [[0, "asc" ]],
                    "sAjaxSource": "<?php echo $this->url('examination',array('action' => 'get-report')); ?>",
                    "fnServerData": function ( sSource, aoData, fnCallback ) {
                            aoData.push({ "name": "Region", "value":  $("[name=region]").val() });
                            aoData.push({ "name": "District", "value": $("[name=district]").val() });
                            aoData.push({ "name": "Country", "value":$("[name=country]").val() });
                            aoData.push({ "name": "Exam", "value": 'practical-exam' });
                            $.ajax({
                                "dataType": 'json',
                                "type": "POST",
                                "url": sSource,
                                "data": aoData,
                                "success": fnCallback
                            });
                        }
                });

		bTable = $('#written-exam-table').dataTable({
                "bAutoWidth": false,
                    "bProcessing": true,
                    "bServerSide": true,
                    "bStateSave": true,
                    "aoColumns": [
                    <?php echo $editAction;?>
                        ],
                "aaSorting": [[0, "asc" ]],
                    "sAjaxSource": "<?php echo $this->url('examination',array('action' => 'get-report')); ?>",
                    "fnServerData": function ( sSource, aoData, fnCallback ) {
                        aoData.push({ "name": "Region", "value":  $("[name=regiontab2]").val() });
                            aoData.push({ "name": "District", "value": $("[name=districttab2]").val() });
                            aoData.push({ "name": "Country", "value":$("[name=countrytab2]").val() });
                            aoData.push({ "name": "Exam", "value": 'written-exam' });
                            $.ajax({
                                "dataType": 'json',
                                "type": "POST",
                                "url": sSource,
                                "data": aoData,
                                "success": fnCallback
                            });
                        }
                });

		cTable = $('#online-exam-table').dataTable({
                "bAutoWidth": false,
                    "bProcessing": true,
                    "bServerSide": true,
                    "bStateSave": true,
                    "aoColumns": [
                    <?php echo $editActionVal;?>
                        ],
                "aaSorting": [[0, "asc" ]],
                    "sAjaxSource": "<?php echo $this->url('examination',array('action' => 'get-report')); ?>",
                    "fnServerData": function ( sSource, aoData, fnCallback ) {
                        aoData.push({ "name": "Region", "value":  $("[name=regiontab3]").val() });
                            aoData.push({ "name": "District", "value": $("[name=districttab3]").val() });
                            aoData.push({ "name": "Country", "value":$("[name=countrytab3]").val() });
                            aoData.push({ "name": "Exam", "value": 'online-exam' });
                            $.ajax({
                                "dataType": 'json',
                                "type": "POST",
                                "url": sSource,
                                "data": aoData,
                                "success": fnCallback
                            });
                        }
                });
    });
    function showRegion(str,type) {
        if (str == "") {
            if(type == 'online'){
                $(".region-online").html("<option value=''>Please Choose a Region</option>");
                $(".district-online").html("<option value=''>Please Choose a Region</option>");
            }
            if(type == 'practical'){
                $(".region-practical").html("<option value=''>Please Choose a Region</option>");
                $(".district-practical").html("<option value=''>Please Choose a Region</option>");
            }
            if(type == 'written'){
                $(".region-written").html("<option value=''>Please Choose a Region</option>");
                $(".district-written").html("<option value=''>Please Choose a Region</option>");
            }

            return false;
        }else{
            $.post("<?php echo $this->url('provider', array('action' => 'region')); ?>", {q: str},
            function(data) {
                if(type == 'online'){
                    $(".region-online").html(data);
                    $(".district-online").html("<option value=''>Please Choose a District</option>");
                }
                if(type == 'practical'){
                    $(".region-practical").html(data);
                    $(".district-practical").html("<option value=''>Please Choose a District</option>");
                }
                if(type == 'written'){
                    $(".region-written").html(data);
                    $(".district-written").html("<option value=''>Please Choose a District</option>");
                }
            });
        }
    }
    
    function showDistrict(str,type) {
        if (str == "") {
            if(type == 'online'){
                $(".district-online").html("Please Choose a Region First");
            }
            if(type == 'practical'){
                $(".district-practical").html("Please Choose a Region First");
            }
            if(type == 'written'){
                $(".district-written").html("Please Choose a Region First");
            }
            return;
        } else {
            $.post("<?php echo $this->url('provider', array('action' => 'district')); ?>", {q: str},
            function(data) {
                if(type == 'online'){
                    $(".district-online").html(data);
                }
                if(type == 'practical'){
                    $(".district-practical").html(data);
                }
                if(type == 'written'){
                    $(".district-written").html(data);
                }
            });
        }
    }

    // function getReportOnlineTest(exam){
    //     $('#'+exam).html('');
    //     $.blockUI();
    //     $.post("< ?php echo $this->url('examination', array('action' => 'get-report')); ?>", {
    //         Region: $('#Region').val(),District: $('#District').val(),Country: $('#Country').val(),Exam: exam
    //     },function(data) {
    //         $('#'+exam).html(data);
    //         var table = $('#'+exam+'-table').DataTable({
    //             "aProcessing": true,
    //             "aServerSide": true,
    //             "aaSorting": [],
    //         });
    //     });
    //     $.unblockUI();
    // }


    function searchAllOrderData(){
     $.blockUI();
     aTable.fnDraw();
     bTable.fnDraw();
     cTable.fnDraw();
      $.unblockUI();
}
    </script>