<div class="am-content">
	<div class="page-head">
		<h2>Dashboard Content</h2>
	</div>
	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<form role="form" class="form-horizontal" name="dashboardContentForm" id="dashboardContentForm" method="post" action="<?php echo $this->url('config', array('action' => 'dashboard-content')); ?>" enctype="multipart/form-data" autocomplete="off">
                            <div class="form-group">
                                <label for="dashboardContent" class="col-sm-2 control-label">Content <span class="mandatory">*</span></label>
                                <div class="col-lg-10">
                                    <textarea rows="9" id="dashboardContent" name="dashboardContent" class="form-control isRequired richtextarea" title="Please Enter the Content"><?php echo $result['global_value'] ?></textarea>
                                </div>
                            </div>
                            <div class="spacer col-lg-10 text-center">
                                    <input type="hidden" name="configId" id="configId" value="<?php echo base64_encode($result['config_id']);?>"/>
                                    <input type="button" class="btn btn-primary" value="Save" onclick="validateNow(); return false;">
                                    &nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url('config', array('action' => 'dashboard-content')); ?>" class="btn btn-default">Cancel</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath('assets/js/summernote.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/summernote.bootstrap.min.js'); ?>" type="text/javascript"></script>
<script>

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'dashboardContentForm'
        });
        if (flag) {
            document.getElementById('dashboardContentForm').submit();
        }
    }
</script>
