<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/jasny-bootstrap.min.css'); ?>"/>
<div class="am-content">
        <div class="page-head">
          <h2>Edit Global Config</h2>
        </div>
        <div class="main-content">
         <div class="widget widget-fullwidth widget-small" style="padding:5px;">
         <div class="row">
            <div class="col-sm-12">
              <div class="panel panel-default">
                <div class="panel-body">
                  <form role="form" class="form-horizontal" name="editConfig" id="editConfig" method="post" action="<?php echo $this->url('config', array('action' => 'edit-global')); ?>" enctype="multipart/form-data" autocomplete="off" >
                    <!--<div class="form-group">
                      <label for="header" class="col-sm-2 control-label">Header</label>
                        <div class="col-lg-4">
                            <textarea row="3" name="header" id="header" class="form-control" placeholder="Header" title="Please enter header">< ?php echo $config['header'] ?></textarea>
                        </div>
                    </div>-->
                    <div class="form-group">
                      <label class="col-sm-2 control-label">Logo</label>
                        <div class="col-lg-4">
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                  <?php
                                  if(isset($config['logo']) && trim($config['logo'])!= '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo" . DIRECTORY_SEPARATOR . $config['logo'])){
                                  ?>
                                   <img src="/uploads/logo/<?php echo $config['logo']; ?>" alt="Logo image"/>
                                  <?php } else { ?>
                                   <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=No image"/>
                                  <?php } ?>
                                </div>
                                <div>
                                  <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
                                  <input type="file" id="logo" name="logo" title="Please select logo image" onchange="getNewImage('<?php echo $config['logo']; ?>');">
                                  </span>
                                  <?php
                                  if(isset($config['logo']) && trim($config['logo'])!= '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo" . DIRECTORY_SEPARATOR . $config['logo'])){
                                  ?>
                                    <a id="clearImage" href="javascript:void(0);" class="btn btn-default" data-dismiss="fileupload" onclick="clearImage('<?php echo $config['logo']; ?>')">Clear</a>
                                  <?php } ?>
                                  <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                                </div>
                            </div>
                            
                            <div class="box-body">
                              Please make sure logo image size of: <code>170x175</code>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="country-name" class="col-sm-2 control-label">Country or Instance name<span class="mandatory">*</span></label>
                        <div class="col-lg-4">
                            <input name="country-name" id="country-name" class="form-control isRequired" placeholder="Country/Instance Name" title="Please enter country/instance name" value="<?php echo $config['country-name']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="latitude" class="col-sm-2 control-label">Latitude</label>
                        <div class="col-lg-4">
                            <input name="latitude" id="latitude" class="form-control " placeholder="Latitude" title="Please enter latitude" value="<?php echo $config['latitude']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="longitude" class="col-sm-2 control-label">Longitude</label>
                        <div class="col-lg-4">
                            <input name="longitude" id="longitude" class="form-control " placeholder="Longitude" title="Please enter longitude" value="<?php echo $config['longitude']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="registrar-name" class="col-sm-2 control-label">Registrar Name</label>
                        <div class="col-lg-4">
                            <input name="registrar-name" id="registrar-name" class="form-control " placeholder="Registrar name" title="Please enter Registrar name" value="<?php echo $config['registrar-name']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="registrar-title" class="col-sm-2 control-label">Registrar Title</label>
                        <div class="col-lg-4">
                            <input name="registrar-title" id="registrar-title" class="form-control " placeholder="Registrar title" title="Please enter Registrar title" value="<?php echo $config['registrar-title']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                      <label class="col-sm-2 control-label">Registrar Digital Signature</label>
                        <div class="col-lg-4">
                        <div class="fileinput fileinput-signature fileinput-new" data-provides="fileinput">
                                <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                  <?php
                                  if(isset($config['registrar-digital-signature']) && trim($config['registrar-digital-signature'])!= '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "digital_signature" . DIRECTORY_SEPARATOR . $config['registrar-digital-signature'])){
                                  ?>
                                   <img src="/uploads/digital_signature/<?php echo $config['registrar-digital-signature']; ?>" alt="Digital Signature Image"/>
                                  <?php } else { ?>
                                   <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=No image"/>
                                  <?php } ?>
                                </div>
                                <div>
                                  <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
                                  <input type="file" id="digitalSignature" name="digitalSignature" title="Please select digital signature" onchange="getNewSignatureImage('<?php echo $config['registrar-digital-signature']; ?>');">
                                  </span>
                                  <?php
                                  if(isset($config['registrar-digital-signature']) && trim($config['registrar-digital-signature'])!= '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "digital_signature" . DIRECTORY_SEPARATOR . $config['registrar-digital-signature'])){
                                  ?>
                                    <a id="clearSignatureImage" href="javascript:void(0);" class="btn btn-default" data-dismiss="fileupload" onclick="clearSignatureImage('<?php echo $config['registrar-digital-signature']; ?>')">Clear</a>
                                  <?php } ?>
                                  <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                                </div>
                            </div>
                            
                            <div class="box-body">
                              Please make sure logo image size of: <code>160x85</code>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="month-valid" class="col-sm-2 control-label">Months certification is valid<span class="mandatory">*</span></label>
                        <div class="col-lg-4">
                            <input name="month-valid" id="month-valid" class="form-control isNumeric isRequired" placeholder="Month(s)" title="Please enter month(s)" value="<?php echo $config['month-valid']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="month-flex-limit" class="col-sm-2 control-label">Flex limit of months allowed for recertification after validity period<span class="mandatory">*</span></label>
                        <div class="col-lg-4">
                            <input name="month-flex-limit" id="month-flex-limit" class="form-control isNumeric isRequired" placeholder="Month(s)" title="Please enter month(s)" value="<?php echo $config['month-flex-limit']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="month-prior-to-certification" class="col-sm-2 control-label">Number of months allowed to administer exam prior to recertification<span class="mandatory">*</span></label>
                        <div class="col-lg-4">
                            <input name="month-prior-to-certification" id="month-prior-to-certification" class="form-control isNumeric isRequired" placeholder="Month(s)" title="Please enter month(s)" value="<?php echo $config['month-prior-to-certification']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="certificate-prefix" class="col-sm-2 control-label">Certification No. Prefix</label>
                        <div class="col-lg-4">
                            <input name="certificate-prefix" id="certificate-prefix" class="form-control" placeholder="Certificate Number Prefix" title="Please enter certificate number prefix" value="<?php echo $config['certificate-prefix']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="region" class="col-sm-2 control-label">Translate Region As <span class="mandatory">*</span></label>
                        <div class="col-lg-4">
                            <input name="region" id="region" class="form-control isRequired" placeholder="Region" title="Please enter region" value="<?php echo $config['region']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="districts" class="col-sm-2 control-label">Translate Districts As <span class="mandatory">*</span></label>
                        <div class="col-lg-4">
                            <input name="districts" id="districts" class="form-control isRequired" placeholder="Districts" title="Please enter districts" value="<?php echo $config['districts']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="facilities" class="col-sm-2 control-label">Translate Facilities As <span class="mandatory">*</span></label>
                        <div class="col-lg-4">
                            <input name="facilities" id="facilities" class="form-control isRequired" placeholder="Facilities" title="Please enter facilities" value="<?php echo $config['facilities']; ?>" />
                        </div>
                    </div>
                    <div class="form-group">
                      <label for="facilities" class="col-sm-2 control-label">Translate Registrate and Title As <span class="mandatory">*</span></label>
                        <div class="col-lg-4">
                            <input name="translate-register-title" id="translate-register-title" class="form-control isRequired" placeholder="Translate Registrate and Title As" title="Translate Registrate and Title As" value="<?php echo $config['translate-register-title']; ?>" />
                        </div>
                    </div>
                    <hr>
                    <div class="spacer col-lg-5" align="center">
                     <input type="hidden" name="removedLogoImage" id="removedLogoImage"/>  
                     <input type="hidden" name="removedSignatureImage" id="removedSignatureImage"/>  
                     <button type="button" onclick="validateNow();" class="btn btn-space btn-primary">Update</button>
                     <a href="<?php echo $this->url('config', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a> 
                    </div>
                    </form>
                </div>
              </div>
            </div>
         </div>
         </div>
        </div>
</div>
<script>
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'editConfig'
        });
        if (flag) {
            document.getElementById('editConfig').submit();
        }
    }
    
    function clearImage(img){
        $('.fileinput').fileinput('clear');
        $('#clearImage').hide();
        $("#offerImage").addClass("isRequired");
        $("#removedLogoImage").val(img);
     }
     
     function getNewImage(img){
        $('#clearImage').hide();
        $("#removedLogoImage").val(img);
     }

     function clearSignatureImage(img){
        $('.fileinput-signature').fileinput('clear');
        $('#clearSignatureImage').hide();
        $("#removedSignatureImage").val(img);
     }
     
     function getNewSignatureImage(img){
        $('#clearSignatureImage').hide();
        $("#removedSignatureImage").val(img);
     }
</script>