<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<div class="am-content">
	<div class="page-head">
		<h2>Add Online Tests</h2>
	</div>
	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <form name="addTestQuestion" id="addTestQuestion" method="post" action="<?php echo $this->url('test-question', array('action' => 'add')); ?>" autocomplete="off" >
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="form-group col-lg-6">
                                    <label for="questionCode" class="col-sm-3 control-label">Question Code<span class="mandatory">*</span></label>
                                    <input type="text" class="form-control isRequired" id="questionCode" name="questionCode" placeholder="Enter question code" title="Please enter the question code" onblur="checkNameValidation('test_questions', 'question_code', this, null, 'Entered question code already exist. Please enter an another question code.')"/>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="questionSection" class="col-sm-3 control-label">Question<span class="mandatory">*</span></label>
                                    <input type="text" class="form-control isRequired" id="questionSection" name="questionSection" placeholder="Enter question" title="Please enter the question" onblur="checkNameValidation('test_questions', 'question', this, null, 'Entered question already exist. Please enter an another question.')"/>
                                </div>
                                
                                <div class="form-group col-lg-6">
                                <label for="section" class="col-sm-3 control-label">Section<span class="mandatory">*</span></label>
                                    <select class="form-control isRequired" name="section" id="section" title="Please select section">
                                        <option value="">--Select--</option>
                                        <?php foreach($sectionResult as $section) { ?>
                                            <option value="<?php echo base64_encode($section['section_id']); ?>"><?php echo $section['section_name']; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="section" class="col-sm-3 control-label">Status<span class="mandatory">*</span></label>
                                    <select class="form-control isRequired" name="status" id="status" title="Please select option status">
                                        <option value="">--Select--</option>
                                        <option value="active">Active</option>
                                        <option value="inactive">Inactive</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <section class="content-header" style="margin-left: 20px;">
                    <h4><strong>Add Options</strong></h4>
                </section>
                <div class="row form-group">
                    <div class="table-responsive" style=" padding: 15px; ">
                        <table id="questionTable" class="table table-bordered table-condensed table">
                            <thead>
                                <tr>
                                    <th style="width: 80%;">Options<span class="mandatory">*</span></th>
                                    <th style="width: 100%;">Status<span class="mandatory">*</span></th>
                                    <th style="padding: 15px !important;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <input class="col-md-1" onclick="optionChecked(1);" type="checkbox" data-id="1" name="optionSelect1" id="optionSelect1" title="Choose correct options in this list">
                                        <input type="hidden" name="selectedCheckBox[]" id="selectedCheckBox1" value="no"/>
                                        <input type="text" style=" height: 35px; " class="col-md-11 isRequired" id="option1" name="option[]" placeholder="Enter the Option" title="Please enter the option value" onblur="optionValidate(this,'1');">
                                    </td>

                                    <td>
                                        <select class="form-control isRequired" id="optionStatus1" name="optionStatus[]" title="Please select the Option Status">
                                            <option value=""> -- Select -- </option>
                                            <option value="active">Active</option>
                                            <option value="inactive">Inactive</option>
                                        </select>
                                    </td>

                                    <td style="text-align: center">
                                        <a href="javascript:void(0);" class="btn btn-info btn-xs" onclick= "insRow()";><i class="fa fa-plus"> </i></a>&nbsp;<a class="btn btn-round btn-danger btn-xs" onclick= "removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"> </i></a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="spacer col-lg-12">
                        <button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
                        <a href="<?php echo $this->url('test-question', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a> 
                    </div>
                </div>
            </form>
		</div>
	</div>
</div>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
    duplicateName = true;
    var rowCount = 1;
    var optionsList = [];
    function validateNow() {
		flag = deforayValidator.init({
            formId: 'addTestQuestion'
		});
		if (flag) {
            if (duplicateName) {
                document.getElementById('addTestQuestion').submit();
            }
		}
    }
    /* new ins and remove row */
    function insRow() {
        ++rowCount;
        // var checkName = "document_keyword', 'keyword', this,null, 'The keyword value that you entered already exist . Please try another name..'";
        var statusList = "<option> -- Select -- </option><option value='active'>Active</option><option value='inactive'>Inactive</option>"

        rl = document.getElementById("questionTable").rows.length;
        var a = document.getElementById("questionTable").insertRow(rl);
        a.setAttribute("style", "display:none;");
        a.setAttribute("class", "data");
        var b = a.insertCell(0);
        var c = a.insertCell(1);
        var d = a.insertCell(2);

        d.setAttribute("align", "center");

        b.innerHTML = '<input type="hidden" name="selectedCheckBox[]" id="selectedCheckBox' + rowCount + '" value="no"/><input class="col-md-1" onclick="optionChecked(' + rowCount + ');" data-id="' + rowCount + '" type="checkbox" name="optionSelect' + rowCount + '" id="optionSelect' + rowCount + '" title="Choose correct options in this list"><input class="col-md-11" style=" height: 35px; " type="text" class="form-control isRequired" id="option' + rowCount + '" name="option[]" placeholder="Enter the Option" title="Please enter the option value" onblur="optionValidate(this,'+rowCount+');">';
        c.innerHTML = '<select class="form-control isRequired" id="optionStatus' + rowCount + '" name="optionStatus[]" title="Please select the Option Status">'+statusList+'</select>';
        d.innerHTML = '<a href="javascript:void(0);" class="btn btn-info btn-xs" id="addBlock" onclick= "insRow()";><i class="fa fa-plus"> </i></a>&nbsp;<a class="btn btn-round btn-danger btn-xs" onclick= "removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"> </a>';

        $(a).fadeIn(800);
    }

    function removeRow(el) {
        $(el).fadeOut("slow", function() {
            el.parentNode.removeChild(el);
            rl = document.getElementById("questionTable").rows.length;
            if (rl == 1) {
                insRow();
            }
        });
    }

    function checkOption(row,obj){
      rl = document.getElementById("questionTable").rows.length;
        for(var i=1; i < rl; i++){
            if(obj.id!= "option"+i){
              if(obj.value==$("#option"+i).val()){
                    alert("Already option available,Please enter another one");
                    obj.value="";
                    break;
                }
            }
        }
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
        function(data) {
            if (data > 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
            }
            else {
                duplicateName = true;
            }
        });
    }

    /* options duplication */

    function optionValidate(obj, row_id) {
        var optionName = document.getElementsByName("option[]");
        cur_value = obj.value;
        j = 0;
        for (i = 0; i < optionName.length; i++) {
            if (cur_value == optionName[i].value) {
                j++;
                if (j == 2) {}
            }
        }
        if (j > 1) {
            if(obj.value != ''){

                alert("This option already exist.");
                obj.value = "";
                obj.focus();
            }
        }
    }
    function optionChecked(rowId) {
        if($("#optionSelect"+rowId).prop('checked') == true) {
            $("#selectedCheckBox"+rowId).val('yes');
        }else{
            $("#selectedCheckBox"+rowId).val('no');
        }
    }
</script>