<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<div class="am-content">
	<div class="page-head">
		<h2>Add Online Tests</h2>
	</div>
	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <form role="form" name="addFacilityInfo" id="addFacilityInfo" method="post" action="<?php echo $this->url('test-question', array('action' => 'edit')); ?>" autocomplete="off" >
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="form-group col-lg-6">
                                    <label for="questionCode" class="col-sm-3 control-label">Question Code<span class="mandatory">*</span></label>
                                <input type="text" value="<?php echo $questionResult['question_code']; ?>" class="form-control isRequired" id="questionCode" name="questionCode" placeholder="Enter question code" title="Please enter the question code" onblur="checkNameValidation('test_questions', 'question_code', this, '<?php echo "question_id##" .$questionResult['question_id']; ?>', 'Entered question code already exist. Please enter an another question code.')"/>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="questionSection" class="col-sm-3 control-label">Question<span class="mandatory">*</span></label>
                                    <input type="text" value="<?php echo $questionResult['question']; ?>" class="form-control isRequired" id="questionSection" name="questionSection" placeholder="Enter question" title="Please enter the question" onblur="checkNameValidation('test_questions', 'question', this, '<?php echo "question_id##" .$questionResult['question_id']; ?>', 'Entered question already exist. Please enter an another question.')"/>
                                </div>
                                
                                <div class="form-group col-lg-6">
                                <label for="section" class="col-sm-3 control-label">Section<span class="mandatory">*</span></label>
                                    <select class="form-control isRequired" name="section" id="section" title="Please select section">
                                        <option value="">--Select--</option>
                                        <?php foreach($sectionResult as $section) { ?>
                                            <option value="<?php echo base64_encode($section['section_id']); ?>" <?php echo(($section['section_id'] == $questionResult['section']) ? "selected='selected'" : ""); ?>><?php echo $section['section_name']; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="section" class="col-sm-3 control-label">Status<span class="mandatory">*</span></label>
                                    <select class="form-control isRequired" name="status" id="status" title="Please select option status">
                                        <option value="">--Select--</option>
                                        <option value="active" <?php if ($questionResult['status']== 'active') { echo 'selected=selected'; } ?>>Active</option>
                                        <option value="inactive" <?php if ($questionResult['status'] == 'inactive') { echo 'selected=selected'; } ?>>Inactive</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" value="<?php echo base64_encode($questionResult['question_id']); ?>" name="questionId">
                    <input type="hidden" name="deletedQuestionList" id="deletedQuestionList"/>
                </div>
                <section class="content-header" style="margin-left: 20px;">
                    <h4><strong>Add Options</strong></h4>
                </section>
                <div class="row form-group">
                    <div class="table-responsive" style=" padding: 15px; ">
                        <table id="questionTable" class="table table-bordered table-condensed table">
                            <thead>
                                <tr>
                                    <th style="width: 80%;">Options<span class="mandatory">*</span></th>
                                    <th style="width: 100%;">Status<span class="mandatory">*</span></th>
                                    <th style="padding: 15px !important;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $count = 1;
                                $corectOptAry = explode(",",$questionResult['correct_option']);
                                foreach($optionResult as $option){ ?>
                                    <tr>
                                        <td>
                                            <input class="col-md-1" onclick="optionChecked('<?php echo $count;?>');" type="checkbox" data-id="<?php echo $count; ?>" name="optionSelect[]" id="optionSelect<?php echo $count; ?>" title="Choose correct options in this list" <?php echo(in_array($option['option_id'],$corectOptAry))?'checked="checked"':''; ?>>
                                            <input type="hidden" name="selectedCheckBox[]" id="selectedCheckBox<?php echo $count;?>" value="<?php echo(in_array($option['option_id'],$corectOptAry))?'yes':'no'; ?>"/>
                                            <input class="col-md-11" style=" height: 35px; " type="text" value="<?php echo $option['option']; ?>" class="form-control isRequired" id="option<?php echo $count; ?>" name="option[]" placeholder="Enter the Option" title="Please enter the option value"  onblur="optionValidate(this,'<?php echo $count; ?>');">
                                        </td>

                                        <td>
                                            <select class="form-control isRequired" id="optionStatus<?php echo $count; ?>" name="optionStatus[]" title="Please select the Option Status" onchange="updateStatus()">
                                                <option value=""> -- Select -- </option>
                                                <option value="active" <?php if ($option['status']== 'active') { echo 'selected=selected'; } ?>>Active</option>
                                                <option value="inactive" <?php if ($option['status'] == 'inactive') { echo 'selected=selected'; } ?>>Inactive</option>
                                            </select>
                                        </td>

                                        <td style="text-align: center">
                                            <input type="hidden" value="<?php echo base64_encode($option['option_id']); ?>" name="optionId[]">
                                            <a href="javascript:void(0);" class="btn btn-info btn-xs" onclick= "insRow()";><i class="fa fa-plus"> </i></a>&nbsp;<a class="btn btn-round btn-danger btn-xs" id="<?php echo base64_encode($option['option_id']); ?>" onclick= "removeRow(this.parentNode.parentNode);deleteOption(this.id);"><i class="fa fa-minus"> </i></a>
                                        </td>
                                    </tr>
                                <?php $count++; } ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="spacer col-lg-12">
                        <button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
                        <a href="<?php echo $this->url('test-question', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a> 
                    </div>
                </div>
            </form>
		</div>
	</div>
</div>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
    duplicateName = true;
    var rowCount = 1;
    var optionsList = [];
    function validateNow() {
		flag = deforayValidator.init({
            formId: 'addFacilityInfo'
		});
		if (flag) {
            if (duplicateName) {
                document.getElementById('addFacilityInfo').submit();
            }
		}
    }
    /* new ins and remove row */
    function insRow() {
        var statusList = "<option> -- Select -- </option><option value='active'>Active</option><option value='inactive'>Inactive</option>"

        rl = document.getElementById("questionTable").rows.length;

        var a = document.getElementById("questionTable").insertRow(rl);
        a.setAttribute("style", "display:none;");
        a.setAttribute("class", "data");
        var b = a.insertCell(0);
        var c = a.insertCell(1);
        var d = a.insertCell(2);

        d.setAttribute("align", "center");

        b.innerHTML = '<input type="hidden" name="selectedCheckBox[]" id="selectedCheckBox' + rowCount + '" value="no"/><input class="col-md-1" onclick="optionChecked(this);" data-id="' + rowCount + '" type="checkbox" name="optionSelect' + rowCount + '" id="optionSelect' + rowCount + '" title="Choose correct options in this list"><input class="col-md-11" style=" height: 35px; " type="text" class="form-control isRequired" id="option' + rowCount + '" name="option[]" placeholder="Enter the Option" title="Please enter the option value" onblur="optionValidate(this,'+rowCount+');">';
        c.innerHTML = '<select class="form-control isRequired" id="optionStatus' + rowCount + '" name="optionStatus[]" title="Please select the Option Status">'+statusList+'</select>';
        d.innerHTML = '<a href="javascript:void(0);" class="btn btn-info btn-xs" id="addBlock" onclick= "insRow()";><i class="fa fa-plus"> </i></a>&nbsp;<a class="btn btn-round btn-danger btn-xs" onclick= "removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"> </a>';

        $(a).fadeIn(800);
    }

    function removeRow(el) {
        $(el).fadeOut("slow", function() {
            el.parentNode.removeChild(el);
            rl = document.getElementById("questionTable").rows.length;
            if (rl == 1) {
                insRow();
            }
            updateCorrectOption();
        });
        
    }
    function deleteOption(custId){
        deleteQuestionId.push(custId);
        $("#deletedQuestionList").val(deleteQuestionId);
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
        function(data) {
            if (data > 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
            }
            else {
                duplicateName = true;
            }
        });
    }
    /* options duplication */
    function optionValidate(obj, row_id) {
        var optionName = document.getElementsByName("option[]");
        cur_value = obj.value;
        j = 0;
        if(obj.value == ''){
            $('#optionSelect'+row_id).prop('checked', false);
            updateCorrectOption();
        }
        for (i = 0; i < optionName.length; i++) {
            if (cur_value == optionName[i].value) {
                j++;
                if (j == 2) {}
            }
        }
        if (j > 1) {
            if(obj.value != ''){

                alert("This option already exist.");
                obj.value = "";
                obj.focus();
            }
        }else{
            updateCorrectOption();
        }
    }

    function updateStatus()
    {
        var optionStatus = document.getElementsByName("optionStatus[]");
        j = 0;
        for (i = 0; i < optionStatus.length; i++) {
            if ('inactive' == optionStatus[i].value) {
                j++;
            }else{
                break;
            }
        }
        if(j == optionStatus.length){
            document.getElementById("status").value= 'inactive';
        }
    }

    function optionChecked(rowId) {
        if($("#optionSelect"+rowId).prop('checked') == true) {
            $("#selectedCheckBox"+rowId).val('yes');
        }else{
            $("#selectedCheckBox"+rowId).val('no');
        }
    }
</script>