<?php
    // \Zend\Debug\Debug::dump($sectionResult);
    // \Zend\Debug\Debug::dump($questionResult);
    // \Zend\Debug\Debug::dump($optionResult);die;
?>
<style type="text/css">
.layCek{
    display:inline-block;
    width:17px;
    height:17px;
    margin:-1px 3px 0 0;
    vertical-align:middle;
    cursor:pointer;
}
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Edit Questions<!--<small>Preview</small>--></h1>
    <!-- <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('home'); ?>"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="<?php echo $this->url('question', array('action' => 'index')); ?>"> Question Details</a></li>
        <li class="active">Edit Question</li>
    </ol> -->
</section>
<!-- Main content -->
<section class="content">

    <!-- left column -->
    <div class="">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header">
                <div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div>
            </div><!-- /.box-header -->
            <!-- form start -->
            <form role="form" class="form-horizontal" name="questionForm" id="questionForm"  method="post" action="<?php echo $this->url('question', array('action' => 'edit')); ?>" autocomplete="off">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="question" class="col-sm-3 control-label">Question<span class="mandatory">*</span></label>
                                <div class="col-sm-12" style="width:69%;">
                                    <input type="text" value="<?php echo $questionResult['question']; ?>" class="form-control isRequired" name="questionSection" id="questionSection" placeholder="Enter question" title="Please enter the question" onblur="checkNameValidation('questions', 'question', this, '<?php echo "question_id##" .$questionResult['question_id']; ?>', 'Entered question already exist. Please enter an another question.')"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="section" class="col-sm-3 control-label">Section<span class="mandatory">*</span></label>
                                <div class="col-sm-8" style="width:69%;">
                                <select class="form-control isRequired" name="section" id="section" title="Please select section">
                                    <option value="">--Select--</option>
                                    <?php foreach($sectionResult as $section) { ?>
                                        <option value="<?php echo base64_encode($section['section_id']); ?>" <?php echo(($section['section_id'] == $questionResult['section']) ? "selected='selected'" : ""); ?>><?php echo $section['section_name']; ?></option>
                                    <?php } ?>
                                </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <!-- <label for="coorect-option" class="col-sm-3 control-label">Correct Option<span class="mandatory">*</span></label> -->
                                <!-- <div class="col-sm-8" style="width:69%;"> -->
                                <!-- </div> -->
                                <label for="status" class="col-lg-3 control-label">Status<span class="mandatory">*</span></label>
                                <div class="col-lg-8" style="width:69%;">
                                    <select class="form-control isRequired" name="status" id="status" title="Please select question status">
                                        <option value="">--Select--</option>
                                        <option value="active" <?php if ($questionResult['status']== 'active') { echo 'selected=selected'; } ?>>Active</option>
                                        <option value="inactive" <?php if ($questionResult['status'] == 'inactive') { echo 'selected=selected'; } ?>>Inactive</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <!-- <div class="col-md-6">
                            <div class="form-group">
                                <label for="status" class="col-lg-3 control-label">Status<span class="mandatory">*</span></label>
                                <div class="col-lg-8" style="width:69%;">
                                    <select class="form-control isRequired" name="status" id="status" title="Please select question status">
                                        <option value="">--Select--</option>
                                        <option value="active" < ?php if ($questionResult['status']== 'active') { echo 'selected=selected'; } ?>>Active</option>
                                        <option value="inactive" < ?php if ($questionResult['status'] == 'inactive') { echo 'selected=selected'; } ?>>Inactive</option>
                                    </select>
                                </div>
                            </div>
                        </div> -->
                    </div>
                    <input type="hidden" value="<?php echo base64_encode($questionResult['question_id']); ?>" name="questionId">
                    <input type="hidden" name="deletedQuestionList" id="deletedQuestionList"/>
                </div><!-- /.box-body -->
                <section class="content-header" style="margin-left: 20px;">
                    <h4><strong>Edit Options</strong></h4>
                </section>
                <div class="table-responsive" style=" padding: 15px; ">
                    <table id="questionTable" class="table table-bordered table-condensed table">
                        <thead>
                            <tr>
                                <th>Options<span class="mandatory">*</span></th>
                                <th>Status<span class="mandatory">*</span></th>
                                <th style="width: 110px !important;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                                $count = 1;
                                $corectOptAry = explode(",",$questionResult['correct_option']);
                                foreach($optionResult as $option){ ?>
                                    <tr>
                                        <td>
                                            <input class="col-md-1" onclick="optionChecked('<?php echo $count;?>');" type="checkbox" data-id="<?php echo $count; ?>" name="optionSelect[]" id="optionSelect<?php echo $count; ?>" title="Choose correct options in this list" <?php echo(in_array($option['option_id'],$corectOptAry))?'checked="checked"':''; ?>>
                                            <input type="hidden" name="selectedCheckBox[]" id="selectedCheckBox<?php echo $count;?>" value="<?php echo(in_array($option['option_id'],$corectOptAry))?'yes':'no'; ?>"/>
                                            <input class="col-md-11" style=" height: 35px; " type="text" value="<?php echo $option['option']; ?>" class="form-control isRequired" id="option<?php echo $count; ?>" name="option[]" placeholder="Enter the Option" title="Please enter the option value"  onblur="optionValidate(this,'<?php echo $count; ?>');">
                                        </td>

                                        <td>
                                            <select class="form-control isRequired" id="optionStatus<?php echo $count; ?>" name="optionStatus[]" title="Please select the Option Status" onchange="updateStatus()">
                                                <option value=""> -- Select -- </option>
                                                <option value="active" <?php if ($option['status']== 'active') { echo 'selected=selected'; } ?>>Active</option>
                                                <option value="inactive" <?php if ($option['status'] == 'inactive') { echo 'selected=selected'; } ?>>Inactive</option>
                                            </select>
                                        </td>

                                        <td style="text-align: center">
                                            <input type="hidden" value="<?php echo base64_encode($option['option_id']); ?>" name="optionId[]">
                                            <a href="javascript:void(0);" class="btn btn-info btn-xs" onclick= "insRow()";><i class="fa fa-plus"> </i></a>&nbsp;<a class="btn btn-round btn-danger btn-xs" id="<?php echo base64_encode($option['option_id']); ?>" onclick= "removeRow(this.parentNode.parentNode);deleteOption(this.id);"><i class="fa fa-minus"> </i></a>
                                        </td>
                                    </tr>
                            <?php
                                    $count++;
                                }
                            ?>
                        </tbody>
                    </table>
                </div>
                <div class="box-footer">
                    <input type="button" class="btn btn-primary" value="Update" onclick="validateNow();return false;">
                    <a href="<?php echo $this->url('question', array('action' => 'index')); ?>" class="btn btn-default">Cancel</a>
                </div>
            </form>

        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->

<script type="text/javascript">
    duplicateName = true;
    var rowCount = <?php echo $count; ?>;
    var deleteQuestionId=[];
    var optionsList = [];

    function validateNow() {

        flag = deforayValidator.init({
            formId: 'questionForm'
        });
        // Check Option Matched or not end
        if (flag) {
            if( duplicateName){
                
                    $.blockUI();
                      document.getElementById('questionForm').submit();
                
            }else{

                alert("Select atleast one correct option in the options list");
            }
        }
    }

    /* new ins and remove row */
    function insRow() {
        var statusList = "<option> -- Select -- </option><option value='active'>Active</option><option value='inactive'>Inactive</option>"

        rl = document.getElementById("questionTable").rows.length;

        var a = document.getElementById("questionTable").insertRow(rl);
        a.setAttribute("style", "display:none;");
        a.setAttribute("class", "data");
        var b = a.insertCell(0);
        var c = a.insertCell(1);
        var d = a.insertCell(2);

        d.setAttribute("align", "center");

        b.innerHTML = '<input type="hidden" name="selectedCheckBox[]" id="selectedCheckBox' + rowCount + '" value="no"/><input class="col-md-1" onclick="optionChecked(this);" data-id="' + rowCount + '" type="checkbox" name="optionSelect' + rowCount + '" id="optionSelect' + rowCount + '" title="Choose correct options in this list"><input class="col-md-11" style=" height: 35px; " type="text" class="form-control isRequired" id="option' + rowCount + '" name="option[]" placeholder="Enter the Option" title="Please enter the option value" onblur="optionValidate(this,'+rowCount+');">';
        c.innerHTML = '<select class="form-control isRequired" id="optionStatus' + rowCount + '" name="optionStatus[]" title="Please select the Option Status">'+statusList+'</select>';
        d.innerHTML = '<a href="javascript:void(0);" class="btn btn-info btn-xs" id="addBlock" onclick= "insRow()";><i class="fa fa-plus"> </i></a>&nbsp;<a class="btn btn-round btn-danger btn-xs" onclick= "removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"> </a>';

        $(a).fadeIn(800);
    }

    function removeRow(el) {
        $(el).fadeOut("slow", function() {
            el.parentNode.removeChild(el);
            rl = document.getElementById("questionTable").rows.length;
            if (rl == 1) {
                insRow();
            }
            updateCorrectOption();
        });
        
    }
    function deleteOption(custId){
        deleteQuestionId.push(custId);
        $("#deletedQuestionList").val(deleteQuestionId);
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
        function(data) {
            if (data > 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
            }
            else {
                duplicateName = true;
            }
        });
    }


/* options duplication */

function optionValidate(obj, row_id) {
    var optionName = document.getElementsByName("option[]");
    cur_value = obj.value;
    j = 0;
    if(obj.value == ''){
        $('#optionSelect'+row_id).prop('checked', false);
        updateCorrectOption();
    }
    for (i = 0; i < optionName.length; i++) {
        if (cur_value == optionName[i].value) {
            j++;
            if (j == 2) {}
        }
    }
    if (j > 1) {
        if(obj.value != ''){

            alert("This option already exist.");
            obj.value = "";
            obj.focus();
        }
    }else{
        updateCorrectOption();
    }
}

function updateStatus()
{
    var optionStatus = document.getElementsByName("optionStatus[]");
    j = 0;
    for (i = 0; i < optionStatus.length; i++) {
        if ('inactive' == optionStatus[i].value) {
            j++;
        }else{
            break;
        }
    }
    if(j == optionStatus.length){
        document.getElementById("status").value= 'inactive';
    }
}

function optionChecked(rowId) {
    if($("#optionSelect"+rowId).prop('checked') == true) {
        $("#selectedCheckBox"+rowId).val('yes');
    }else{
        $("#selectedCheckBox"+rowId).val('no');
    }
}
</script>
