<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<div class="am-content">
	<div class="page-head">
		<h2>Upload Test question</h2>
	</div>
	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <form name="importexcelQuestion" id="importexcelQuestion" method="post" enctype="multipart/form-data" action="<?php echo $this->url('test-question', array('action' => 'import-excel')); ?>" autocomplete="off" >
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <fieldset>
                                <legend style="color: #00b3ee">Upload Test Questions File </legend>
                                    <div class="form-group col-lg-4">
                                        <input class="form-control isRequired" type="file" name="question_excel"  title="Please Select File"/>
                                    </div>
                                    <?php if(file_exists(UPLOAD_PATH.DIRECTORY_SEPARATOR.'test-questions'.DIRECTORY_SEPARATOR.'model.xlsx')){ ?> 
                                        <div class="form-group col-lg-2">
                                            <a href="/uploads/tester/model.xlsx" class="btn btn-space btn-danger"><i class="fa fa-download"></i>&nbsp;DOWNLOAD FORMAT</a>
                                        </div>
                                    <?php }?>
                                    <div class="form-group col-lg-6">
                                        <button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
                                        <a href="<?php echo $this->url('test-question', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a> 
                                    </div>
                                </fieldset>
                               
                            </div>
                        </div>
                    </div>
                </div>
        
            </form>
		</div>
	</div>
</div>

<script type="text/javascript">
    duplicateName = true;
    var rowCount = 1;
    var optionsList = [];
    function validateNow() {
		flag = deforayValidator.init({
            formId: 'importexcelQuestion'
		});
		if (flag) {
            if (duplicateName) {
                document.getElementById('importexcelQuestion').submit();
            }
		}
    }
    
    
</script>