<?php
use Zend\Session\Container;
$bsUserLogincontainer = new Container('bsUserLoginContainer');
$maxQuestion = $postResult['totalCount'];    

$score = ($postResult['post_test_score'] / $maxQuestion);
$total = round($score * 100);
if($total>=$configResult['0']['test_config_value']){
    $display = "display:block;";
    $passed= true;
}else{
    $display = "display:none;";
    $passed= false;
}
$preTestScore = ($postResult['preResult']['pre_test_score'] / $maxQuestion);
$preTestTotal = round($preTestScore * 100);
?>
<style type="text/css">
.pretest {
    margin: 50px 0px;
    width: 100%;
    padding: 10px 0px;
    font-size: 20px;
    text-align: center;
    border-bottom: solid #E34735;
    border-bottom-width: 1px;
}
.pretest > li {
    list-style: none;
    display: inline-block;
}
.postresult{
    color: black;
    border: solid;
    border-width: 1px;
    border-color: bisque;
    margin:auto;
    margin-bottom: 50px;
}
.letter{font-weight: bold !important; font-size:1.1em;}
/* table,td,tr{
		border-color:#777 !important;
		vertical-align: middle;
	} */
	td.trainer{ 
		background: #DEEDFC;
		color:#0a3c6f;
		text-align: center;
	}
	td.trainer a {
		color: #0a3c6f;
		font-weight:bold;
	}
	td.participant{
		background: #9ea4d4;
		color: #FFFFFF;
		text-align: center;
	}
	td.participant a{
		
		color: #FFFFFF;
		font-weight: bold;
	}
	td a:hover{
		text-decoration: underline;
	}
    .p-holder .progress {
   
    margin: 18px 0px !important;
    
}
thead{
    background-color: #f5f5f5;
}
</style>



<section class="page-section white short">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-xs-12">
                <div class="heading-holder skills">
                    <h1>Test Result</h1>
                    <?php if($display == "display:block;"){ ?>
                        <p class="text-left">
                            <a href="/biosafety/pdf?testId=<?php echo base64_encode($postResult['test_id']); ?>" target="_blank" class="btn btn-info"><i class="fa fa-download"></i> Download Certificate</a>
                        </p>
                    <?php }else if($configResult[2]['test_config_value'] == 'yes'){ ?>
                        
                        <p class="text-left">You need to score <?php echo $configResult['0']['test_config_value']; ?> percent or higher to qualify for the professional development credits. Please take the course again by clicking on this link</p>
                        <a class="btn btn-info" href="<?php echo $this->url('biosafety', array('action' => 'pretest'));?>">Take Test Again&nbsp;&nbsp;<i class="fa fa-arrow-right move"></i></a>
                            
                    <?php } ?>
                </div>
            </div>
            <div class="col-sm-6 col-xs-12">
                <table class="table table-borderless">
                <thead>
                    <tr>
                        <th scope="col">Post-Test Score</th>
                        <th scope="col">Pre-Test Score</th>                    
                    </tr>
                </thead>
                <tbody>
                    <tr>
                    <th scope="row"><canvas id="scorePiePost" width="100" height="100" style="max-width:100px;"></canvas></th>
                    <td><canvas id="scorePiePre" width="100" height="100" style="max-width:100px;"></canvas></td>
                    
                    </tr>
                    <tr>
                    <td scope="row text-center"><span style="font-size:3em;"><?php echo $total; ?></span>/100</td>
                    <td scope="row text-center"><span style="font-size:3em;"><?php echo $preTestTotal; ?></span>/100</td>
                    
                    </tr>
                    
                </tbody>
                </table>
                
                <div class="well">
                <?php if($passed) { ?>                       
                    <div class="alert alert-success" role="alert"><strong>Congratulations !</strong> You have received a satisfactory score.</div>
                <?php } else { ?>                        
                    <div class="alert alert-warning" role="alert">The minimum score required to pass the pre and post-tests is <b><?php echo $configResult['0']['test_config_value']; ?></b> percent <b>(Btw, are we referring to both tests or just the post test?)</b></div>
                <?php } ?>          
                
                </div>
                
            </div>
        </div>
    </div>
</section>

<div class="page-section white short" style="padding: 30px 0 !important;">
    <div class="container">
        <div class="col-xs-12 heading-short">
            <h1 class="short">Pre-Test Question</h1>            
        </div>
        <div class="col-xs-12">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>                        
                            <th>Sl.No</th>
                            <th>Question</th>
                            <th>Option (selected by you)</th>
                            <th>Option (correct option)</th>
                            <th>Score</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    $i = 1;
                    foreach($postResult['preTestQuestion'] as $preTest){
                        ?>
                        <tr>
                            <td>
                            <?php echo $i;?>
                            </td>
                            <td>
                                <?php echo $preTest['question_text'];?>
                            </td>
                            <td>
                                <?php
                                 $qList = json_decode($preTest['response_text'],true);
                                 foreach($qList as $optData){
                                     echo $optData."<br/>";
                                 }
                                 ?>
                            </td>
                            <td>
                                <?php echo $preTest['correct_option_text'];?>
                            </td>
                            <td>
                                <?php echo $preTest['score'];?>
                            </td>
                        </tr>
                        <?php
$i++;
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="page-section white short" style="padding: 30px 0 !important;">
    <div class="container">
        <div class="col-xs-12 heading-short">
            <h1 class="short">Post-Test Question</h1>            
        </div>
        <div class="col-xs-12">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>                        
                            <th>Sl.No</th>
                            <th>Question</th>
                            <th>Option (selected by you)</th>
                            <th>Option (correct option)</th>
                            <th>Score</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    $i = 1;
                    foreach($postResult['postTestQuestion'] as $preTest){
                        ?>
                        <tr>
                            <td>
                            <?php echo $i;?>
                            </td>
                            <td>
                                <?php echo $preTest['question_text'];?>
                            </td>
                            <td>
                                <?php
                                 $qList = json_decode($preTest['response_text'],true);
                                 foreach($qList as $optData){
                                     echo $optData."<br/>";
                                 }
                                 ?>
                            </td>
                            <td>
                                <?php echo $preTest['correct_option_text'];?>
                            </td>
                            <td>
                                <?php echo $preTest['score'];?>
                            </td>
                        </tr>
                        <?php
$i++;
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>










<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js" ></script>
            
<script>
new Chart(document.getElementById("scorePiePost"),{
    "type":"doughnut",
    "data":{
        "labels":[" Correct Responses "," Incorrect Responses "],
        "datasets":[{
            "label":"My First Dataset",
            "data":[<?php echo $postResult['post_test_score']; ?>,<?php echo $maxQuestion-$postResult['post_test_score']; ?>],
            "borderWidth" : 1,
            "backgroundColor":["rgb(54, 162, 235)",
            "rgb(255, 99, 132)"
            ]
        }]
    },
    options: {
        tooltips: false,
        legend : false,
        cutoutPercentage : 80
    }
});
new Chart(document.getElementById("scorePiePre"),{
    "type":"doughnut",
    "data":{
        "labels":[" Correct Responses "," Incorrect Responses "],
        "datasets":[{
            "label":"My First Dataset",
            "data":[<?php echo $postResult['preResult']['pre_test_score']; ?>,<?php echo $maxQuestion-$postResult['preResult']['pre_test_score']; ?>],
            "borderWidth" : 1,
            "backgroundColor":["rgb(54, 162, 235)",
            "rgb(255, 99, 132)"
            ]
        }]
    },
    options: {
        tooltips: false,
        legend : false,
        cutoutPercentage : 80
    }
});
</script>