<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>Add A new Practical Exam</h2>
            </div>
            <div class="col-sm-4 ">
                <?php // if ($acl->isAllowed($role, 'Application\Controller\Facility', 'add')) {  ?>
                <a href="<?php echo $this->url('practical-exam', array('action' => 'index')); ?>" class="btn btn-success pull-right" style="margin-left: 5px;"><i class="fa fa-list"></i>&nbsp;List of Practicals Exams</a>
                <?php // }  ?>

            </div>
        </div>
        <div class="row">
            <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
        </div>
        <div class="row">
            <span class="muted pull-right" style="font-size:15px; "><span class="mandatory" style="color: green;">*</span> indicates read only field</span>
        </div>
    </div>

    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >
                            <form action="<?php $this->url('practical-exam', array('action' => 'add')); ?>" method="POST" name="form" onsubmit="return validateForm()">
                                <?php
                                $form->prepare();
                                $form->get('exam_type')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'Type of Exam',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)',
                                ]);

                                $form->get('exam_admin')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'Exam Administrator',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)',
                                ]);
                                $form->get('provider_id')->setAttributes([
                                    'class' => 'form-control ',
                                    'id' => 'Tester',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'showAttempt(this.value)'
                                ]);

                                $form->get('direct_observation_score')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Direct Observation Score',
                                    'onclick' => 'emptyInput(this)',
                                ]);


                                $form->get('Sample_testing_score')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Sample Testing Score',
                                    'onclick' => 'emptyInput(this)',
                                ]);

                                $form->get('date')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'date',
                                    'onclick' => 'emptyInput(this)',
                                ]);

                                $form->get('written')->setAttributes([
                                    'value' => $this->written,
                                ]);

                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formHidden($form->get('practice_exam_id')->setAttribute('class', 'form-control')) ?>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('provider_id')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('provider_id')); ?>
                                    <?= $this->formElementErrors($form->get('provider_id')); ?>
                                </div>
                                <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('exam_type')); ?><span class="mandatory" style="color: green;">*</span>
                                    <?= $this->formElement($form->get('exam_type')); ?>
                                    <?= $this->formElementErrors($form->get('exam_type')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('exam_admin')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('exam_admin')); ?>
                                    <?= $this->formElementErrors($form->get('exam_admin')); ?>
                                </div>

                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('direct_observation_score')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('direct_observation_score')); ?>
                                    <?= $this->formElementErrors($form->get('direct_observation_score')); ?>
                                </div>

                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('Sample_testing_score')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('Sample_testing_score')); ?>
                                    <?= $this->formElementErrors($form->get('Sample_testing_score')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('date')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('date')); ?>
                                    <?= $this->formElementErrors($form->get('date')); ?>
                                </div>
                                <?php echo $this->formRow($form->get('written')) ?>

                                <div class="row" style="margin-left: 18px;"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                    <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('practical-exam', array('action' => 'index')); ?>" >CANCEL</a> </div>

                                <?php echo $this->form()->closeTag();
                                ?>


                            </form>

                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>
<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>

<script type="text/javascript">
                                var nombre = '<?PHP echo $nombre; ?>';
                                var id = '<?PHP echo $provider['id']; ?>';
                                var name = '<?PHP echo $provider['name']; ?>';
</script>
<script src="<?php echo $this->basePath('assets/js/personnel_certification/practical.js'); ?>" type="text/javascript"></script>

<script type="text/javascript">
                                function showAttempt(str) {

                                    if (str == "") {
                                        document.getElementById("Type of Exam").innerHTML = "";
                                        return;
                                    } else {
                                        if (window.XMLHttpRequest) {
                                            // code for IE7+, Firefox, Chrome, Opera, Safari
                                            xmlhttp = new XMLHttpRequest();
                                        } else {
                                            // code for IE6, IE5
                                            xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                                        }
                                        xmlhttp.onreadystatechange = function () {
                                            if (this.readyState == 4 && this.status == 200) {
                                                document.getElementById("Type of Exam").innerHTML = this.responseText;
                                            }

                                            if (document.getElementById("Type of Exam").value >= 4) {
                                                alert('This tester has already made three unsuccessful attempts');
                                                window.location = '<?php echo $this->url('practical-exam', array('action' => 'index')); ?>';
                                            }
                                        };
                                        xmlhttp.open("GET", "<?php echo $this->url('practical-exam', array('action' => 'attempt')); ?>?q=" + str, true);
                                        xmlhttp.send();
                                    }
                                }

</script>



