<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
$alertMsg = '';
if($nombre!= null){
    $nombreArray = explode('##',$nombre);
    if(count($nombreArray) > 1){
      $alertMsg = '<span>Last Certificate for <strong>'.$nombreArray[1].'</strong> was issued on '.$nombreArray[2].' You can do re-certification only after '.$nombreArray[3].' or before '.$nombreArray[4].'</span>';
    }else{
       $nombre = null; 
    }
}
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>Practical Exam</h2>
            </div>
            <div class="col-sm-4 ">
                <?php // if ($acl->isAllowed($role, 'Application\Controller\Facility', 'add')) {  ?>
                <a href="<?php echo $this->url('practical-exam', array('action' => 'index')); ?>" class="btn btn-success pull-right" style="margin-left: 5px;"><i class="fa fa-list"></i>&nbsp;List of Practicals Exams</a>
                <?php // }  ?>

            </div>
        </div>
        <div class="row">
        <span class="muted pull-right" style="font-size:15px;">
        <span class="mandatory">*</span> indicates required field
        &nbsp;&nbsp;&nbsp;&nbsp;
        <span class="mandatory" style="color: green;">*</span> indicates read only field
        </span>
    </div>
    </div>

    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >
                            <form action="<?php $this->url('practical-exam', array('action' => 'add')); ?>" method="POST" name="form" onsubmit="return validateForm()">
                                <?php
                                $form->prepare();
                                $form->get('exam_type')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'Type of Exam',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)',
                                ]);

                                $form->get('exam_admin')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'Exam Administrator',
                                    'autocomplete' => 'off',
                                    'placeholder' => 'Please enter examination admin name',
                                    'onclick' => 'emptyInput(this)',
                                ]);
                                $form->get('provider_id')->setAttributes([
                                    'class' => 'form-control ',
                                    'id' => 'Tester',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'showAttempt(this.value)'
                                ]);

                                $form->get('direct_observation_score')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Direct Observation Score',
                                    'placeholder' => 'Please enter direct observation score in %',
                                    'onclick' => 'emptyInput(this)',
                                ]);


                                $form->get('Sample_testing_score')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Sample Testing Score',
                                    'placeholder' => 'Please enter sample testing score in %',
                                    'onclick' => 'emptyInput(this)',
                                ]);

                                $form->get('date')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'date',
                                    'placeholder' => 'Please select a date',
                                    'onclick' => 'emptyInput(this)',
                                ]);

                                $form->get('written')->setAttributes([
                                    'value' => $this->written,
                                ]);

                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formHidden($form->get('practice_exam_id')->setAttribute('class', 'form-control')) ?>
                                <div class="form-group col-lg-12" id="alertMsg"><?php echo $alertMsg; ?></div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('provider_id')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('provider_id')); ?>
                                    <?= $this->formElementErrors($form->get('provider_id')); ?>
                                </div>
                                <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('exam_type')); ?><span class="mandatory" style="color: green;">*</span>
                                    <?= $this->formElement($form->get('exam_type')); ?>
                                    <?= $this->formElementErrors($form->get('exam_type')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('exam_admin')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('exam_admin')); ?>
                                    <?= $this->formElementErrors($form->get('exam_admin')); ?>
                                </div>

                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('direct_observation_score')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('direct_observation_score')); ?>
                                    <?= $this->formElementErrors($form->get('direct_observation_score')); ?>
                                </div>

                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('Sample_testing_score')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('Sample_testing_score')); ?>
                                    <?= $this->formElementErrors($form->get('Sample_testing_score')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('date')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('date')); ?>
                                    <?= $this->formElementErrors($form->get('date')); ?>
                                </div>
                                <?php echo $this->formRow($form->get('written')) ?>

                                <div class="row" style="margin-left: 18px;"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                    <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('practical-exam', array('action' => 'index')); ?>" >CANCEL</a> </div>

                                <?php echo $this->form()->closeTag();
                                ?>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <br>
        <div class="widget widget-fullwidth widget-small" style="padding:10px;padding-top:20px; ">

        <h1>Practical Exams </h1>
<table id="practicalExamsTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
                <thead>
                    <tr>
                        <th style="width: 10%;">Date</th>
                        <th style="width: 10%;">Type of Exam</th>
                        <th style="width: 10%;">Exam Administrator</th>
                        <th style="width: 10%;">Tester </th>
                        <th style="width: 10%;">Direct Observation Score (≥90%) </th>
                        <th style="width: 10%;">Sample Testing Score (=100%)</th>
                        <th style="width: 10%;">Practical Total Score</th>
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\PracticalExam', 'edit')) { ?>
                            <th>Edit</th>
                            <th>Another Attempt</th>
                        <?php } ?>
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\PracticalExam', 'delete')) { ?>
                            <th>Delete</th>
                        <?php } ?>
                    </tr>

                </thead>
                <tbody>
                    <?php foreach ($practicals as $exam) : ?>
                        <tr>
                            <td><div style="width:100px;height:40px;overflow:auto;"><?php echo date("d-m-Y", strtotime($this->escapeHtml($exam->date))); ?></div></td>
                            <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($exam->exam_type); ?></div></td>
                            <td><div style="width:200px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($exam->exam_admin); ?></div></td>
                            <td><div style="width:200px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($exam->last_name . ' ' . $exam->first_name . ' ' . $exam->middle_name); ?></div></td>
                            <td><div style="width:70px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($exam->direct_observation_score . ' %'); ?></div></td>
                            <td><div style="width:70px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($exam->Sample_testing_score . ' %'); ?></div></td>
                            <td><div style="width:70px;height:40px;overflow:auto; font-weight: bold"><?php echo $this->escapeHtml($exam->practical_total_score . ' %'); ?></div></td>
                            <?php if ($acl->isAllowed($role, 'Certification\Controller\PracticalExam', 'edit')) { ?>
                                <td>
                                    <div style="width:80px;height:40px;overflow:auto;"><a href="<?php echo $this->url('practical-exam', array('action' => 'edit', 'practice_exam_id' => base64_encode($exam->practice_exam_id))); ?>"><span class="glyphicon glyphicon-pencil"></span> Edit</a> </div>
                                </td>

                                <?php
                                if ($exam->direct_observation_score < 90 || $exam->Sample_testing_score < 100 || strcasecmp($exam->exam_type, '3rd attempt') == 0) {
                                    echo "<td><div style='width:120px;height:40px;overflow:auto;'><p><span class='glyphicon glyphicon-repeat'></span> Add written exam </div></td>";
                                } else {
                                    echo "<td><div style='width:120px;height:40px;overflow:auto;'><p><a href=" . $this->url('written-exam', array('action' => 'add'), array('query' => array(base64_encode('practice_exam_id') => base64_encode($exam->practice_exam_id)))) . "><span class='glyphicon glyphicon-repeat'></span> Add written exam</a> </div></td>";
                                }
                                ?>
                            <?php } ?>
                                <?php if ($acl->isAllowed($role, 'Certification\Controller\PracticalExam', 'delete')) { ?>
                                <td><div style="overflow:auto;">
                                         <a onclick="if (!confirm('Do you really want to remove this practical exam?')) {
                                                    alert('Canceled!');
                                                    return false;};"  href="<?php echo $this->url('practical-exam', array('action' => 'delete', 'practice_exam_id' => base64_encode($exam->practice_exam_id))); ?>"> <span class="glyphicon glyphicon-trash">&nbsp;Delete</span></a> 
                                   </div>
                                </td>
                            <?php } ?>

                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
</div>
    </div>

</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>
<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
    var nombre = '<?php echo $nombre; ?>';
    var id = '<?php echo (isset($provider['id']))?$provider['id']:''; ?>';
    var name = '<?php echo (isset($provider['name']))?$provider['name']:''; ?>';
</script>
<script src="<?php echo $this->basePath('assets/js/personnel_certification/practical.js'); ?>" type="text/javascript"></script>

<script type="text/javascript">
    function showAttempt(str) {
        if (str == "") {
            document.getElementById("Type of Exam").innerHTML = "";
            return;
        } else {
            if (window.XMLHttpRequest) {
                // code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            } else {
                // code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    var responseArray = this.responseText.split('##');
                    if(responseArray.length > 1){
                      $('#alertMsg').html('<span>Last Certificate for <strong>'+responseArray[1]+'</strong> was issued on '+responseArray[2]+'. You can do re-certification only after '+responseArray[3]+' or before '+responseArray[4]+'</span>');
                      document.getElementById("Type of Exam").innerHTML = "";
                    }else{
                        $('#alertMsg').html('');
                        document.getElementById("Type of Exam").innerHTML = this.responseText;
                        if (document.getElementById("Type of Exam").value >= 4) {
                            alert('This tester has already made three unsuccessful attempts');
                            window.location = '<?php echo $this->url('practical-exam', array('action' => 'index')); ?>';
                        }
                    }
                    
                }
            };
            xmlhttp.open("GET", "<?php echo $this->url('practical-exam', array('action' => 'attempt')); ?>?q=" + str, true);
            xmlhttp.send();
        }
    }
    
    $(document).ready(function () {
        <?php if(isset($written) && (int)$written > 0){ ?>
            showAttempt('<?php echo $provider['id']; ?>');
        <?php } ?>
        $('#practicalExamsTable').dataTable({
            "aProcessing": true,
            "aServerSide": true,
        })
    });
</script>