<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;

?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>" />

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>Practical Exams</h2>
            </div>
            <div class="col-sm-4">
                <?php if ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'import-excel')) { ?>
                    <a href="<?php echo $this->url('practical-exam', array('action' => 'import-excel')); ?>" class="btn btn-dark pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Import practical Exam</a>
                <?php } 
                    if ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'add')) { ?>
                    <a href="<?php echo $this->url('practical-exam', array('action' => 'add')); ?>" class="btn btn-dark pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Add a practical exam</a>
                <?php } ?>
            </div>
        </div>
        <div class="row">
            <span class="muted pull-right" style="font-size:15px;padding-left:10px;color: darkgray;">(Please ensure that the tester is <a href="/provider/">enrolled</a> before you record the Written Exam results)</span>
        </div>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <table id="practicalExamsTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
                <thead>
                    <tr>
                        <th style="width: 200px;">Tester </th>
                        <th style="width: 70px;">Date</th>
                        <th>No. of Attempts</th>
                        <th>Exam Administrator</th>
                        <th>Direct Observation Score (≥90%) </th>
                        <th>Sample Testing Score (=100%)</th>
                        <th>Practical Total Score</th>
                        <?php if ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'edit')) { ?>
                            <th>Edit</th>
                            <th style="width: 140px;">Another Attempt</th>
                        <?php } ?>
                        <?php if ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'delete')) { ?>
                            <th>Delete</th>
                        <?php } ?>
                    </tr>

                </thead>
                <tbody>
                    <?php foreach ($practicals as $exam) : ?>
                        <tr>
                            <td>
                                <div><?php echo $this->escapeHtml($exam->last_name . ' ' . $exam->first_name . ' ' . $exam->middle_name); ?></div>
                            </td>
                            <td>
                                <div><?php echo date("d-M-Y", strtotime($this->escapeHtml($exam->date))); ?></div>
                            </td>
                            <td>
                                <div><?php echo $this->escapeHtml($exam->exam_type); ?></div>
                            </td>
                            <td>
                                <div><?php echo $this->escapeHtml($exam->exam_admin); ?></div>
                            </td>
                            <td>
                                <div><?php echo $this->escapeHtml($exam->direct_observation_score . ' %'); ?></div>
                            </td>
                            <td>
                                <div><?php echo $this->escapeHtml($exam->Sample_testing_score . ' %'); ?></div>
                            </td>
                            <td>
                                <div style="font-weight: bold"><?php echo $this->escapeHtml($exam->practical_total_score . ' %'); ?></div>
                            </td>
                            <?php if ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'edit')) { ?>
                                <td>
                                    <div><a href="<?php echo $this->url('practical-exam', array('action' => 'edit', 'practice_exam_id' => base64_encode($exam->practice_exam_id))); ?>"><span class="glyphicon glyphicon-pencil"></span> Edit</a> </div>
                                </td>

                                <?php
                                if ($exam->direct_observation_score < 90 || $exam->Sample_testing_score < 100 || strcasecmp($exam->exam_type, '3rd attempt') == 0) {
                                    echo "<td><div><p><span class='glyphicon glyphicon-repeat'></span> Add written exam </div></td>";
                                } else {
                                    echo "<td><div><p><a href=" . $this->url('written-exam', array('action' => 'add'), array('query' => array(base64_encode('practice_exam_id') => base64_encode($exam->practice_exam_id)))) . "><span class='glyphicon glyphicon-repeat'></span> Add written exam</a> </div></td>";
                                }
                                ?>
                            <?php } ?>
                            <?php if ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'delete')) { ?>
                                <td>
                                    <div style="overflow:auto;">
                                        <a onclick="if (!confirm('Do you really want to remove this practical exam?')) {
                                                    alert('Canceled!');
                                                    return false;};" href="<?php echo $this->url('practical-exam', array('action' => 'delete', 'practice_exam_id' => base64_encode($exam->practice_exam_id))); ?>"> <span class="glyphicon glyphicon-trash">&nbsp;Delete</span></a>
                                    </div>
                                </td>
                            <?php } ?>

                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

        </div>
    </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>

<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" language="javascript">
    $(document).ready(function() {

        $('#practicalExamsTable').dataTable({
            "aProcessing": true,
            "aServerSide": true,
        })
    });
</script>
