<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
if (($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'edit')) && ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'delete'))) {
    $editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false}';
}elseif ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'edit')) {
    $editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false}';
}elseif ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'delete')) {
    $editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center",bSortable:false}';
}else{
    $editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}

?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>" />

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>Practical Exams</h2>
            </div>
            <div class="col-sm-4">
                <?php if ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'import-excel')) { ?>
                    <a href="<?php echo $this->url('practical-exam', array('action' => 'import-excel')); ?>" class="btn btn-dark pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Import practical Exam</a>
                <?php } 
                    if ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'add')) { ?>
                    <a href="<?php echo $this->url('practical-exam', array('action' => 'add')); ?>" class="btn btn-dark pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Add a practical exam</a>
                <?php } ?>
            </div>
        </div>
        <div class="row">
            <span class="muted pull-right" style="font-size:15px;padding-left:10px;color: darkgray;">(Please ensure that the tester is <a href="/provider/">enrolled</a> before you record the Written Exam results)</span>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <div class="col-md-3" style="margin-top:10px;">
                    <lable>Display</label>
                </div>
                <div class="col-md-9">
                    <select name="display" class="form-control" id="display">
                        <option value="yes">Not Recommended/Pending</option>
                        <option value="no">Recommended/Certified</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-5" style="margin-top:10px; align:center">
                <input type="button" onclick="searchRequestData();" value="Search" class="btn btn-primary btn-sm">
                <a class="btn  btn-sm btn-danger" role="button" href="/practical-exam">Reset</a>
            </div>
        </div>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <table id="practicalExamsTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
                <thead>
                    <tr>
                        <th style="width: 200px;">Tester </th>
                        <th style="width: 70px;">Date</th>
                        <th>No. of Attempts</th>
                        <th>Exam Administrator</th>
                        <th>Direct Observation Score (≥90%) </th>
                        <th>Sample Testing Score (=100%)</th>
                        <th>Practical Total Score</th>
                        <?php if ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'edit')) { ?>
                            <th>Edit</th>
                            <th style="width: 140px;">Another Attempt</th>
                        <?php } ?>
                        <?php if ($this->isAllowed($role, 'Certification\Controller\PracticalExamController', 'delete')) { ?>
                            <th>Delete</th>
                        <?php } ?>
                    </tr>

                </thead>
                <tbody>
                    <tr>
                        <td colspan="7" class="dataTables_empty">Loading data from server</td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>

<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" language="javascript">
     var writtenExamTable = null;
     let searchExecuted = false;

    $(document).ready(function() {

        practicalExamTable = $('#practicalExamsTable').DataTable({
			"bProcessing": true,
			"bServerSide": true,
            "autoWidth": true,
            "aoColumns": [
                <?php echo $editAction; ?>
            ],
            "order": [
                [0, 'asc']
            ],
			"sAjaxSource": "<?php echo $this->url('practical-exam', array('action' => 'index')); ?>",
			"fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({
                    "name": "display",
                    "value": $("#display").val()
                });
				$.ajax({
					"dataType": 'json',
					"type": "POST",
					"url": sSource,
					"data": aoData,
					"success": fnCallback
				});
			}
		});
    });
    function searchRequestData(){
        searchExecuted = true;
        $.blockUI();
        practicalExamTable.draw();
        $.unblockUI();
    }
</script>
