<?php
$tokenArray = array();
foreach($tokenResults as $token){
  $tokenArray[] = $token['token'];
}
?>
<link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/typeahead.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/tokenfield.min.css'); ?>"/>
<div class="am-content">
        <div class="page-head">
          <h2>Add User</h2>
	    <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
        </div>
        
        <div class="main-content">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">
	    <div class="row">
            <div class="col-sm-12">
              <div class="panel panel-default">
                <div class="panel-body">
                  <form role="form" name="addUserInformation" id="addUserInformation" method="post" action="<?php echo $this->url('users', array('action' => 'add')); ?>" autocomplete="off" >
                    <div class="form-group col-lg-6">
                      <label>First Name <span class="mandatory">*</span> </label>
                      <input type="text" placeholder="First Name" class="form-control isRequired" name="firstName" id="firstName" title="Please enter the first name" >
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Last Name </label>
                      <input type="text" placeholder="Last Name" class="form-control" name="lastName" id="lastName" title="Please enter the last name" >
                    </div>
					<div class="form-group col-lg-6">
                      <label>Login Id <span class="mandatory">*</span></label>
                      <input type="text" placeholder="Login Id" class="form-control isRequired" name="userName" id="userName" title="Please enter the user name" onblur="checkNameValidation('users','login', this, null, 'Already exist this name . Please choose another name.')" >
                    </div>
					<div class="form-group col-lg-6">
                      <label>Password <span class="mandatory">*</span></label>
                      <input type="password" placeholder="Password" class="form-control isRequired" name="password" id="password" title="Please enter the password" >
                    </div>
					<div class="form-group col-lg-6">
                      <label>Confirm Password <span class="mandatory">*</span></label>
                      <input type="password" placeholder="Confirm Password" class="form-control confirmPassword isRequired" name="password" id="confirmPassword" title="Please check your password and confirm password are same" >
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Email</label>
                      <input type="text" placeholder="Email" class="form-control isEmail" name="email" id="email" title="Please enter the email id" >
                    </div>
                   <div class="form-group col-lg-6">
                      <label>Role <span class="mandatory">*</span></label>
				<select class="form-control isRequired" name="roleId" id="roleId" title="Please select the role">
						<option value="">--Select--</option>
						<?php
						foreach($roleResults as $role){
						?>
						<option value="<?php echo $role['role_id']; ?>"><?php echo ucwords($role['role_name']); ?></option>
						<?php
						}
						?>
				</select>
                    </div>
		    <div class="form-group col-lg-6">
                      <label>Token (Note: You can add multiple token by comma separator values)</label>
                      <input type="text" placeholder="Enter token" class="form-control" name="token" id="token" title="Please enter token" >
                    </div>
			<div class="form-group col-lg-6" style="margin-right:50%;">
                      <label>Status <span class="mandatory">*</span></label>
				<select class="form-control isRequired" name="status" id="status" title="Please select the status">
					<option value="active">Active</option>
					<option value="inactive">Inactive</option>
				</select>
                    </div>
                    <div class="spacer col-lg-12">
                      <button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
                     <a href="<?php echo $this->url('users', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a> 
                    </div>
                  </form>
                </div>
              </div>
            </div>
        </div>
        </div>
        <br>
        <br>
        </div>
</div>
<script type="text/javascript">
	        $(document).ready(function() {
		      $('#token').tokenfield({
			autocomplete: {
			  source: <?php echo json_encode($tokenArray); ?>,
			  delay: 100
			},
			showAutocompleteOnFocus: false
		      })
		      
		      $('#token').on('tokenfield:createtoken', function (event) {
			var existingTokens = $(this).tokenfield('getTokens');
			$.each(existingTokens, function(index, token) {
			    if (token.value === event.attrs.value)
				event.preventDefault();
			});
		      });
		});
		
		duplicateName = true;
		function validateNow() {
			   flag = deforayValidator.init({
				   formId: 'addUserInformation'
			   });
			   if (flag) {
				   if (duplicateName) {
					   document.getElementById('addUserInformation').submit();
				   }
			   }
		}
		
		function checkNameValidation(tableName, fieldName, obj, fnct, msg){
			checkValue = document.getElementById(obj.id).value;
			$.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
			function(data) {
				if (data > 0)
				{
					alert(msg);
					duplicateName = false;
					document.getElementById(obj.id).value = "";
				}
				else {
					duplicateName = true;
				}
			});
		}
</script>