<?php
$userDistricts = array();
$userProvinces = array();
$userCountries = array();
$selectedProvinces = array();
$selectedCountries = array();
if(isset($result['userDistricts']) && count($result['userDistricts']) >0){
	foreach($result['userDistricts'] as $district){
	   $userDistricts[] = $district['location_id'];
	}
}else if(isset($result['userProvinces']) && count($result['userProvinces']) >0){
	foreach($result['userProvinces'] as $province){
	   $userProvinces[] = $province['location_id'];
	}
}else if(isset($result['userCountries']) && count($result['userCountries']) >0){
	foreach($result['userCountries'] as $country){
	   $userCountries[] = $country['country_id'];
	}
}

if(isset($result['selectedCountries']) && count($result['selectedCountries']) >0){
  $selectedCountries = $result['selectedCountries'];
}
if(isset($result['selectedProvinces']) && count($result['selectedProvinces']) >0){
   $selectedProvinces = $result['selectedProvinces'];
}
?>
<link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/typeahead.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<div class="am-content">
        <div class="page-head">
          <h2>Edit User</h2>
		<span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
        </div>
        <div class="main-content">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">
	    <div class="row">
            <div class="col-sm-12">
              <div class="panel panel-default">
                <div class="panel-body">
                  <form role="form" name="editUserInformation" id="editUserInformation" method="post" action="<?php echo $this->url('users', array('action' => 'edit')); ?>" autocomplete="off" >
		    <div class="row">
			<div class="form-group col-lg-6">
			  <label>First Name <span class="mandatory">*</span> </label>
			  <input type="text" placeholder="First Name" class="form-control isRequired" name="firstName" id="firstName" title="Please enter the first name" value="<?php echo $result->first_name; ?>">
			    <input type="hidden" class="form-control isRequired" id="userId" name="userId" value="<?php echo base64_encode($result->id); ?>"/>
			</div>
			<div class="form-group col-lg-6">
			  <label>Last Name </label>
			  <input type="text" placeholder="Last Name" class="form-control" name="lastName" id="lastName" title="Please enter the last name" value="<?php echo $result->last_name; ?>">
			</div>
		    </div>
		    <div class="row">
			<div class="form-group col-lg-6">
			   <label>Login Id <span class="mandatory">*</span></label>
			   <input type="text" placeholder="Login Id" class="form-control" name="userName" id="userName" title="Please enter the user name" onblur="checkNameValidation('users','login', this,'<?php echo "id##" .$result->id; ?>', 'Already exist this name . Please choose another name.')" value="<?php echo $result->login; ?>">
		        </div>
			<div class="form-group col-lg-6">
			   <label>Password </label>
			   <input type="password" placeholder="Password" class="form-control" name="password" id="password" title="Please enter the password" >
		        </div>
		    </div>
		    <div class="row">
			<div class="form-group col-lg-6">
			  <label>Email</label>
			  <input type="text" placeholder="Email" class="form-control isEmail" name="email" id="email" title="Please enter the email id" value="<?php echo $result->email; ?>">
			</div>
		       <div class="form-group col-lg-6">
			  <label>Role <span class="mandatory">*</span></label>
				    <select class="form-control isRequired" name="roleId" id="roleId" title="Please select the role" onchange="checkRole('change');">
					    <option data-access-level="" value="">--Select--</option>
					    <?php
					    foreach($roleResults as $role){
					    ?>
					    <option data-access-level="<?php echo $role['access_level']; ?>" value="<?php echo $role['role_id']; ?>" <?php if($result->role_id==$role['role_id']){echo 'selected=selected';}?>><?php echo ucwords($role['role_name']); ?></option>
					    <?php
					    }
					    ?>
				    </select>
			</div>
		    </div>
		    <div class="row">
			<div class="form-group col-lg-6">
			   
			   <label>Status <span class="mandatory">*</span></label>
				     <select class="form-control isRequired" name="status" id="status" title="Please select the status">
					     <option value="active" <?php if($result->status=='active'){echo 'selected=selected';}?>>Active</option>
					     <option value="inactive" <?php if($result->status=='inactive'){echo 'selected=selected';}?>>Inactive</option>
				     </select>
			 </div>
			<div class="form-group col-lg-6 accessLevel country province district" onchange="getCountryLocations('change');">
			     <label>Country <span class="mandatory">*</span></label>
			     <select class="form-control" name="country[]" id="country" multiple title="Please select country">
				     <?php
				     foreach($countryResult as $country){
				     ?>
					 <option value="<?php echo $country['country_id']; ?>" <?php echo (in_array($country['country_id'],$userCountries) || in_array($country['country_id'],$selectedCountries))?'selected="selected"':''; ?>><?php echo ucwords($country['country_name']); ?></option>
				     <?php
				     }
				     ?>
			     </select>
			 </div>
		   </div>
		    <div class="row">
			<div class="form-group col-lg-6 accessLevel province district" onchange="getProvinceDistricts('change');">
			   <label>Province/State <span class="mandatory">*</span></label>
			    <select class="form-control" name="province[]" id="province" multiple title="Please select province">
				    <?php
				    foreach($provinceResult as $province){
				    ?>
					<option value="<?php echo $province['location_id']; ?>" <?php echo (in_array($province['location_id'],$userProvinces) || in_array($province['location_id'],$selectedProvinces))?'selected="selected"':''; ?>><?php echo ucwords($province['location_name']); ?></option>
				    <?php
				    }
				    ?>
			    </select>
			</div>
			<div class="form-group col-lg-6 accessLevel district">
			    <label>District/County <span class="mandatory">*</span></label>
			    <select class="form-control" name="district[]" id="district" multiple title="Please select district">
				    <?php
				    foreach($districtResult as $district){
				    ?>
					<option value="<?php echo $district['location_id']; ?>" <?php echo in_array($district['location_id'],$userDistricts)?'selected="selected"':''; ?>><?php echo ucwords($district['location_name']); ?></option>
				    <?php
				    }
				    ?>
			    </select>
			</div>
		    </div>
                    <div class="spacer  col-lg-12">
                      <button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
                     <a href="<?php echo $this->url('users', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a> 
                    </div>
                  </form>
                </div>
              </div>
            </div>
        </div>
        </div>
        <br>
        <br>
        </div>
</div>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('#country').select2({
		    placeholder: "<?php echo $this->translate('Select Countries'); ?>",
		    width:'100%',
		    allowClear: true
		});
		$('#province').select2({
		    placeholder: "<?php echo $this->translate('Select Provinces/States'); ?>",
		    width:'100%',
		    allowClear: true
		});
		$('#district').select2({
		    placeholder: "<?php echo $this->translate('Select Districts/Counties'); ?>",
		    width:'100%',
		    allowClear: true
		});
		checkRole('load');
	});
	
	duplicateName = true;
	function validateNow() {
		   flag = deforayValidator.init({
			   formId: 'editUserInformation'
		   });
		   if (flag) {
			var accessLevel = $('#roleId').find(':selected').attr('data-access-level');
			if($('#country').val() == null || $('#country').val() == ''){
			     if(accessLevel == 2 || accessLevel == 3 || accessLevel == 4){
				     alert('Please select country');
				     return false;
			     }
			}else if($('#province').val() == null || $('#province').val() == ''){
			     if(accessLevel == 3 || accessLevel == 4){
				     alert('Please select province');
				     return false;
			     }
			}else if($('#district').val() == null || $('#district').val() == ''){
			     if(accessLevel == 4){
				     alert('Please select district');
				     return false;
			     }
			}
			if (duplicateName) {
				document.getElementById('editUserInformation').submit();
			}
		   }
	}
	
	function checkNameValidation(tableName, fieldName, obj, fnct, msg){
		var checkValue = document.getElementById(obj.id).value;
		$.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
		function(data) {
			if (data > 0)
			{
				alert(msg);
				duplicateName = false;
				document.getElementById(obj.id).value = "";
			}
			else {
				duplicateName = true;
			}
		});
	}
		
	function checkRole(frmSrc){
		var roleAccessLevel = (frmSrc == 'load')?'<?php echo $result->access_level; ?>':$('#roleId').find(':selected').attr('data-access-level');
		if(roleAccessLevel == 2){
		      $('.accessLevel').hide();
		      $('.country').show();
		      if(frmSrc == 'change') { $('#country').val('').change(); }
		}else if(roleAccessLevel == 3){
		      $('.accessLevel').hide();
		      $('.province').show();
		      if(frmSrc == 'change') { $('#country').val('').change(); $('#province').val('').change(); }
		}else if(roleAccessLevel == 4){
		      $('.accessLevel').hide();
		      $('.district').show();
		      if(frmSrc == 'change') { $('#country').val('').change(); $('#province').val('').change();  $('#district').val('').change();}
		}else{
		      $('.accessLevel').hide();
		      if(frmSrc == 'change') { $('#country').val('').change(); $('#province').val('').change();  $('#district').val('').change();}
		}
	}
	
	function getCountryLocations(frmSrc){
		var roleAccessLevel = (frmSrc == 'load')?'<?php echo $result->access_level; ?>':$('#roleId').find(':selected').attr('data-access-level');
		if(roleAccessLevel == 3 || roleAccessLevel == 4){
			var country = ($('#country').val() == null || $('#country').val() == '')?[]:$('#country').val();
			$.post("<?php echo $this->url('common', array('action' => 'get-country-locations')); ?>", {country: country},
			function(data) {
			    var dataArray = data.split("##");
			    if(frmSrc == 'change'){ $('#province').val('').change(); $('#district').val('').change(); }
			    $('#province').html(dataArray[0]);
			    $('#district').html(dataArray[1]);
			});
		}
	}
	
	function getProvinceDistricts(frmSrc){
		var province = ($('#province').val() == null || $('#province').val() == '')?[]:$('#province').val();
		$.post("<?php echo $this->url('common', array('action' => 'get-province-districts')); ?>", {province: province},
		function(data) {
		    if(frmSrc == 'change'){ $('#district').val('').change(); } 
		    $('#district').html(data);
		});
	}
</script>