<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl=$this->layout()->acl;
if ($acl->isAllowed($role, 'Application\Controller\Roles', 'edit')) {
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
}else{
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
?>
<div class="am-content">
        <div class="page-head">
          <div class="row">
				<div class="col-sm-8">
				<h2>Role List</h2>
				</div>
				<div class="col-sm-4">
						<?php
						if ($acl->isAllowed($role, 'Application\Controller\Roles', 'add')) {
						?>
						<a href="<?php echo $this->url('roles',array('action' => 'add'));?>" class="btn btn-dark pull-right" style=""><i class="fa fa-plus"></i>&nbsp;Add Role</a>
						<?php } ?>
				</div>
		  </div>
        </div>
        
        <div class="main-content">
             
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">

                <table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" id="roleDataTable">
					<thead>
					<tr>
						<th>Role Name</th>
						<th>Role Code</th>
						<th>Status</th>
						<?php if ($acl->isAllowed($role,'Application\Controller\Roles','edit')) { ?>
						<th>Action</th>
						<?php } ?>
					</tr>
					</thead>
					<tbody>
					<tr>
						 <td colspan="4" class="dataTables_empty">Loading data from server</td>
					</tr>
					</tbody>
				</table>
            </div>
        <br>
            
            
        </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/datatables.min.js'); ?>"></script>
<script type="text/javascript">
    var oTable = null;

 $(document).ready(function() {
	
        oTable = $('#roleDataTable').dataTable({
            "bScrollCollapse": true,
            "bRetrieve": true,                        
            "aoColumns": [
				<?php echo $editAction;?>
            ],
            "aaSorting": [[ 0, "desc" ]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('roles',array('action' => 'index')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
       
	} );
</script>