<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
$config = $this->GlobalConfigHelper();
$districtLabel = (isset($config['districts']) && trim($config['districts'])!= '')?ucwords($config['districts']):'District';
$facilityLabel = (isset($config['facilities']) && trim($config['facilities'])!= '')?ucwords($config['facilities']):'Facilities';
?>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>Manage <?php echo $facilityLabel; ?></h2>
            </div>
            <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>

        </div>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div style="margin-left: 10px; ">
                <div>
                    <form action="<?php $this->url('facility', array('action' => 'add')); ?>" name="form" method="post" onsubmit="return validateForm()">
                        <?php
                        $form->prepare();
                        $form->get('district')->setAttributes([
                            'class' => 'form-control',
                            'id' => 'District',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);
                        $form->get('facility_name')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => $facilityLabel.' Name',
                            'autocomplete' => 'off',
                            'id' => 'Facility Name',
                            'onclick' => 'emptyInput(this)',
//                           
                        ]);
                        $form->get('contact_person_name')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Contact Person Name',
                            'autocomplete' => 'off',
                            'id' => 'Contact Person Name',
                            'onclick' => 'emptyInput(this)',
    //                           
                        ]);
                        $form->get('phone_no')->setAttributes([
                            'class' => 'form-control checkNum',
                            'placeholder' => 'Phone Number',
                            'autocomplete' => 'off',
                            'id' => 'Phone Number',
                            'onclick' => 'emptyInput(this)',
    //                           
                        ]);
                        $form->get('email_id')->setAttributes([
                            'class' => 'form-control isEmail',
                            'placeholder' => 'Email ID',
                            'autocomplete' => 'off',
                            'id' => 'Email ID',
                            'onclick' => 'emptyInput(this)',
    //                           
                        ]);
                        $form->get('facility_address')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => $facilityLabel.' Address',
                            'autocomplete' => 'off',
                            'id' => 'Facility Address',
//                           
                        ]);
                        $form->get('latitude')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Latitude',
                            'autocomplete' => 'off',
                            'id' => 'latitude',
                            'onclick' => 'emptyInput(this)',
    //                           
                        ]);
                        $form->get('longitude')->setAttributes([
                            'class' => 'form-control',
                            'placeholder' => 'Longitude',
                            'autocomplete' => 'off',
                            'id' => 'Longitude',
                            'onclick' => 'emptyInput(this)',
    //                           
                        ]);

                        $form->get('submit')->setAttributes([
//                            
                        ]);


                        echo $this->form()->openTag($form);
                        ?>
                        <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>
                        <div class="row">
                            <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('district')); ?><span class="mandatory">*</span>
                                <?= $this->formElement($form->get('district')); ?>
                                <?= $this->formElementErrors($form->get('district')); ?>
                            </div>
                            <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('facility_name')); ?><span class="mandatory">*</span>
                                <?= $this->formElement($form->get('facility_name')); ?>
                                <?= $this->formElementErrors($form->get('facility_name')); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('contact_person_name')); ?>
                                <?= $this->formElement($form->get('contact_person_name')); ?>
                                <?= $this->formElementErrors($form->get('contact_person_name')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('phone_no')); ?>
                                <?= $this->formElement($form->get('phone_no')); ?>
                                <?= $this->formElementErrors($form->get('phone_no')); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('email_id')); ?>
                                <?= $this->formElement($form->get('email_id')); ?>
                                <?= $this->formElementErrors($form->get('email_id')); ?>
                            </div>
                            <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('facility_address')); ?>
                                <?= $this->formElement($form->get('facility_address')); ?>
                                <?= $this->formElementErrors($form->get('facility_address')); ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('latitude')); ?>
                                <?= $this->formElement($form->get('latitude')); ?>
                                <?= $this->formElementErrors($form->get('latitude')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('longitude')); ?>
                                <?= $this->formElement($form->get('longitude')); ?>
                                <?= $this->formElementErrors($form->get('longitude')); ?>
                            </div>
                        </div>
                        <div class="row col-sm-3" style="margin-top: 10px;">
                            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                            <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('facility', array('action' => 'index')); ?>" >Cancel</a> 
                        </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </form>
                </div>

                <div style="margin-top:120px;">
                    <table id="facility" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="margin: auto;">
                        <thead>
                            <tr>
                                <th style="width:33%;"><?php echo $facilityLabel; ?> Name </th>
                                <th style="width:33%;"><?php echo $facilityLabel; ?> Address</th>
                                <th style="width:33%;"><?php echo $districtLabel; ?></th>

                                <?php if ($acl->isAllowed($role, 'Certification\Controller\Facility', 'edit')) { ?>
                                    <th>Edit</th>
                                <?php } ?>
                                     <?php if ($acl->isAllowed($role, 'Certification\Controller\Facility', 'delete')) { ?>
                                        <th>Delete</th>
                                    <?php } ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($facilities as $facility) : ?>
                                <tr>
                                    <td><div style="width:200px;overflow:auto;"><?php echo ucfirst($this->escapeHtml($facility['facility_name'])); ?></div></td>
                                    <td><div style="width:200px;overflow:auto;"><?php echo ucfirst($this->escapeHtml($facility['facility_address'])); ?></div></td>
                                    <td><div style="width:200px;overflow:auto;"><?php echo (isset($facility['location_name']))?ucfirst($this->escapeHtml($facility['location_name'])):''; ?></div></td>
                                    <?php if ($acl->isAllowed($role, 'Certification\Controller\Facility', 'edit')) { ?>
                                        <td>
                                            <div style="width:80px;overflow:auto;"><a href="<?php echo $this->url('facility', array('action' => 'edit', 'id' => base64_encode($facility['id']))); ?>"> <span class="glyphicon glyphicon-pencil">Edit</span></a> </div>
                                        </td>
                                    <?php } ?>
                                        <?php if ($acl->isAllowed($role, 'Certification\Controller\Facility', 'delete')) { ?>
                                <td><div style="width:80px;overflow:auto;">
                                         <a onclick="if (!confirm('Do you really want to remove '+'<?php echo $this->escapeHtml($facility['facility_name']); ?> '+'?')) {
                                                    alert('Canceled!');
                                                    return false;};"  href="<?php echo $this->url('facility', array('action' => 'delete', 'id' => $facility['id'])); ?>"> <span class="glyphicon glyphicon-trash">&nbsp;Delete</span></a> 
                                  </div>
                                </td>
                            <?php } ?>
                                   

                                </tr>
                            <?php endforeach; ?>               
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<script>
districtLabel = '<?php echo $districtLabel; ?>';
facilityLabel = '<?php echo $facilityLabel; ?>';
</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src = "<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type = "text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/personnel_certification/facility.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" language="javascript">
    $(document).ready(function () {
        $('#facility').dataTable({
            "aProcessing": true,
            "aServerSide": true,
        })
    });
</script>