<?php
if($formData){
    // Extend the TCPDF class to create custom Header and Footer
    class MYPDF extends TCPDF {

    public function setSchemeName($header,$logo) {
	$this->header = $header;
	$this->logo = $logo;
    }
    
    //Page header
    public function Header() {
        // Logo
        if(trim($this->logo)!="" && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo'. DIRECTORY_SEPARATOR.$this->logo)){
	    $image_file = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo'. DIRECTORY_SEPARATOR.$this->logo;
	    $this->Image($image_file, 12,3,20, '', 'PNG', '', 'T', false, 300, 'L', false, false, 0, false, false, false);
	}
        // Set font
        $this->SetFont('helvetica', 'B', 12);
        $this->writeHTMLCell(0,'',54,10,$this->header,0,1,false,true,'C',true);
        $this->writeHTMLCell(180,'','','','<br/><hr/>',0,1,false,true,'C',true);
       
    }

    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', 'I', 8);
        // Page number
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

$pdf->setSchemeName(ucwords($configData['header']),$configData['logo']);
// set document information
$pdf->SetCreator('ODK DASHBOARD');
$pdf->SetAuthor('ODK DASHBOARD');
$pdf->SetTitle('SPI-RT V3 Checklist');
$pdf->SetSubject('SPI-RT V3 Checklist');
$pdf->SetKeywords('SPI-RT V3 Checklist');


// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}
// ---------------------------------------------------------

// set font
$pdf->SetFont('times', '', 10);

// add a page
$pdf->AddPage();
//$pdf->SetY(20,true,false);

$partA='<p style="font-weight:bold;line-height:24px;">PART A: CHARACTERISTICS OF THE FACILITY OR TESTING POINT AUDITED</p>';
//$partA.='<br/>';

$pdf->writeHTML($partA, true, 0, true, 0);

$pdf->writeHTMLCell('',12,'','','<p>Before completing the checklist, it is important to characterize the testing point to be audited. Please provide relevant information in the summary table below.</p>',0,1,false,true,'L',true);

$testingTab='<table border="1" cellspacing="0" cellpadding="5">';

$testingTab.='<tr>';
$testingTab.='<td><b>Date of Audit</b>(dd/mm/yyyy): '.$this->humanDateFormat($formData['assesmentofaudit']).'</td>';
$testingTab.='<td><b>Audit Round No:</b> '.$formData['auditroundno'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>Testing Facility Name:</b> '.$formData['facilityname'].'</td>';
$testingTab.='<td><b>Testing Facility ID</b>(if applicable) : '.$formData['facilityid'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>Testing Point Name:</b> '.$formData['testingpointname'].'</td>';
$testingTab.='<td><b>Type of testing point : </b>'.$formData['testingpointtype'];
$testingTab.=((isset($formData['testingpointtype_other']) && $formData['testingpointtype_other'] != "") ? " - " . $formData['testingpointtype_other']: "").'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td colspan="2"><b>Location/Address:</b> '.$formData['locationaddress'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>Level</b> <br/>'.$formData['level'];
$testingTab.=((isset($formData['level_other']) && $formData['level_other'] != "") ? " Other - " . $formData['level_other'] : "").':'.$formData['level_name'];
$testingTab.='</td>';
$testingTab.='<td><b>Affiliation</b><br/>'.$formData['affiliation'];
$testingTab.=((isset($formData['affiliation_other']) && $formData['affiliation_other'] != "") ? " Other : " . $formData['affiliation_other'] : "");
$testingTab.='</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>Number of Testers: </b>'.$formData['NumberofTester'].'</td>';
$testingTab.='<td><b>Average tested per month: </b>'.$formData['avgMonthTesting'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>Name of the Auditor 1: </b>'.$formData['name_auditor_lead'].'</td>';
$testingTab.='<td><b>Name of the Auditor 2: </b>'.$formData['name_auditor2'].'</td>';
$testingTab.='</tr>';

$testingTab.='</table>';

$pdf->writeHTML($testingTab, true, 0, true, 0);

$partBHeading="<b>PART B. SPI- RT Checklist</b>";

$pdf->writeHTML($partBHeading, true, 0, true, 0);


$partBCont="<br/><div>For each of the sections listed below, please check <b>Yes, Partial or No</b>, where applicable. Indicate";
$partBCont.='"<b>Yes</b>" only when all elements are satisfactorily present. Provide comments for each "<b>Partial</b>" or "<b>No</b>" response. State N/A in the comments section if "not applicable" where appropriate (*).</div>';

$pdf->writeHTML($partBCont, true, 0, true, 0);

$partBTable='<table border="1" cellspacing="0" cellpadding="5" style="width:100%;">';
$partBTable.="<tr>";
$partBTable.='<td style="text-align:center;font-weight:bold;width:52%;" colspan="2">SECTION</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:7%;">YES</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:8%;">Partial</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:7%;">NO</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:18%;">Comments</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:8%;">Score</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">1.0 PERSONNEL TRAINING AND CERTIFICATION </td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">10</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td style="width:7%;">1.1</td>';
$partBTable.='<td style="width:45%;">Have all testers received a comprehensive training on HIV rapid testing using the nationally approved curriculum?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_1']) && $formData['PERSONAL_Q_1_1'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_1']) && $formData['PERSONAL_Q_1_1'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_1']) && $formData['PERSONAL_Q_1_1'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PERSONAL_C_1_1']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PERSONAL_Q_1_1']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>1.2</td>';
$partBTable.='<td>Are the testers trained on the use of standardized HIV testing registers/logbooks?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_2']) && $formData['PERSONAL_Q_1_2'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_2']) && $formData['PERSONAL_Q_1_2'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_2']) && $formData['PERSONAL_Q_1_2'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PERSONAL_C_1_2']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PERSONAL_Q_1_2']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>1.3</td>';
$partBTable.='<td>Are the testers trained on external quality assessment (EQA) or proficiency testing (PT) process?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_3']) && $formData['PERSONAL_Q_1_3'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_3']) && $formData['PERSONAL_Q_1_3'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_3']) && $formData['PERSONAL_Q_1_3'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PERSONAL_C_1_3']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PERSONAL_Q_1_3']).'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td>1.4</td>';
$partBTable.='<td>Are the testers trained on quality control (QC) process?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_4']) && $formData['PERSONAL_Q_1_4'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_4']) && $formData['PERSONAL_Q_1_4'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_4']) && $formData['PERSONAL_Q_1_4'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PERSONAL_C_1_4']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PERSONAL_Q_1_4']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>1.5</td>';
$partBTable.='<td>Are the testers trained on safety and waste management procedures and practices?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_5']) && $formData['PERSONAL_Q_1_5'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_5']) && $formData['PERSONAL_Q_1_5'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_5']) && $formData['PERSONAL_Q_1_5'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PERSONAL_C_1_5']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PERSONAL_Q_1_5']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>1.6</td>';
$partBTable.='<td>Have all testers received a refresher training within the last two years?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_6']) && $formData['PERSONAL_Q_1_6'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_6']) && $formData['PERSONAL_Q_1_6'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_6']) && $formData['PERSONAL_Q_1_6'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PERSONAL_C_1_6']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PERSONAL_Q_1_6']).'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td>1.7</td>';
$partBTable.='<td>Are there records indicating all testers have demonstrated competency in HIV rapid testing prior to client testing?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_7']) && $formData['PERSONAL_Q_1_7'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_7']) && $formData['PERSONAL_Q_1_7'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_7']) && $formData['PERSONAL_Q_1_7'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PERSONAL_C_1_7']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PERSONAL_Q_1_7']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>1.8</td>';
$partBTable.='<td>Have all testers been certified through a national certification program?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_8']) && $formData['PERSONAL_Q_1_8'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_8']) && $formData['PERSONAL_Q_1_8'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_8']) && $formData['PERSONAL_Q_1_8'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PERSONAL_C_1_8']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PERSONAL_Q_1_8']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>1.9</td>';
$partBTable.='<td>Are only certified testers allowed to perform HIV testing?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_9']) && $formData['PERSONAL_Q_1_9'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_9']) && $formData['PERSONAL_Q_1_9'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_9']) && $formData['PERSONAL_Q_1_9'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PERSONAL_C_1_9']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PERSONAL_Q_1_9']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>1.10</td>';
$partBTable.='<td>Are all testers required to be re-certified periodically (e.g., every two years)?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_10']) && $formData['PERSONAL_Q_1_10'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_10']) && $formData['PERSONAL_Q_1_10'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PERSONAL_Q_1_10']) && $formData['PERSONAL_Q_1_10'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PERSONAL_C_1_10']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PERSONAL_Q_1_10']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;">1.0 PERSONNEL TRAINING AND CERTIFICATION SCORE </td>';
$partBTable.='<td style="text-align:center;">'.$formData['PERSONAL_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">2.0 PHYSICAL FACILITY </td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">5</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>2.1</td>';
$partBTable.='<td>Is there a designated area for HIV testing?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_1']) && $formData['PHYSICAL_Q_2_1'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_1']) && $formData['PHYSICAL_Q_2_1'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_1']) && $formData['PHYSICAL_Q_2_1'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PHYSICAL_C_2_1']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PHYSICAL_Q_2_1']).'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td>2.2</td>';
$partBTable.='<td>Is the testing area clean and organized for HIV rapid testing?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_2']) && $formData['PHYSICAL_Q_2_2'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_2']) && $formData['PHYSICAL_Q_2_2'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_2']) && $formData['PHYSICAL_Q_2_2'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PHYSICAL_C_2_2']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PHYSICAL_Q_2_2']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>2.3</td>';
$partBTable.='<td>Is sufficient lighting available in the designated testing area?</td>';
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_3']) && $formData['PHYSICAL_Q_2_3'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_3']) && $formData['PHYSICAL_Q_2_3'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_3']) && $formData['PHYSICAL_Q_2_3'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PHYSICAL_C_2_3']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PHYSICAL_Q_2_3']).'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td>2.4</td>';
$partBTable.="<td>Are the test kits kept in a temperature controlled environment based on the manufacturers' instructions?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_4']) && $formData['PHYSICAL_Q_2_4'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_4']) && $formData['PHYSICAL_Q_2_4'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_4']) && $formData['PHYSICAL_Q_2_4'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PHYSICAL_C_2_4']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PHYSICAL_Q_2_4']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>2.5</td>';
$partBTable.="<td>Is there sufficient and secure storage space for test kits and other consumables?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_5']) && $formData['PHYSICAL_Q_2_5'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_5']) && $formData['PHYSICAL_Q_2_5'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PHYSICAL_Q_2_5']) && $formData['PHYSICAL_Q_2_5'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PHYSICAL_C_2_5']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PHYSICAL_Q_2_5']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;">2.0 PHYSICAL FACILITY SCORE </td>';
$partBTable.='<td style="text-align:center;">'.$formData['PHYSICAL_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">3.0 SAFETY </td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">11</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>3.1</td>';
$partBTable.="<td>Are there SOPs and/or job aides in place to implement safety practices?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_1']) && $formData['SAFETY_Q_3_1'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_1']) && $formData['SAFETY_Q_3_1'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_1']) && $formData['SAFETY_Q_3_1'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['SAFETY_C_3_1']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_1']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>3.2</td>';
$partBTable.="<td>Are there SOPs and/or job aides in place on how to dispose of infectious and non-infectious waste?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_2']) && $formData['SAFETY_Q_3_2'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_2']) && $formData['SAFETY_Q_3_2'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_2']) && $formData['SAFETY_Q_3_2'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['SAFETY_C_3_2']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_2']).'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td>3.3</td>';
$partBTable.="<td>Are there SOPs and/or job aides in place to manage spills of blood and other body fluids?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_3']) && $formData['SAFETY_Q_3_3'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_3']) && $formData['SAFETY_Q_3_3'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_3']) && $formData['SAFETY_Q_3_3'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['SAFETY_C_3_3']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_3']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>3.4</td>';
$partBTable.="<td>Are there SOPs and/or job aides in place to address accidental exposure to potentially infectious body fluids through a needle stick injury, splash or other sharps injury?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_4']) && $formData['SAFETY_Q_3_4'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_4']) && $formData['SAFETY_Q_3_4'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_4']) && $formData['SAFETY_Q_3_4'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['SAFETY_C_3_4']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_4']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>3.5</td>';
$partBTable.="<td>Is personal protective equipment (PPE) always available to testers?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_5']) && $formData['SAFETY_Q_3_5'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_5']) && $formData['SAFETY_Q_3_5'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_5']) && $formData['SAFETY_Q_3_5'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['SAFETY_C_3_5']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_5']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>3.6</td>';
$partBTable.="<td>Is PPE consistently used by all testers?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_6']) && $formData['SAFETY_Q_3_6'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_6']) && $formData['SAFETY_Q_3_6'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_6']) && $formData['SAFETY_Q_3_6'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['SAFETY_C_3_6']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_6']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>3.7</td>';
$partBTable.="<td>Is PPE properly used by all testers through the testing process?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_7']) && $formData['SAFETY_Q_3_7'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_7']) && $formData['SAFETY_Q_3_7'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_7']) && $formData['SAFETY_Q_3_7'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['SAFETY_C_3_7']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_7']).'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td>3.8</td>';
$partBTable.="<td>Is there clean water and soap available for hand washing?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_8']) && $formData['SAFETY_Q_3_8'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_8']) && $formData['SAFETY_Q_3_8'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_8']) && $formData['SAFETY_Q_3_8'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['SAFETY_C_3_8']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_8']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>3.9</td>';
$partBTable.="<td>Is there an appropriate disinfectant to clean the work area available?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_9']) && $formData['SAFETY_Q_3_9'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_9']) && $formData['SAFETY_Q_3_9'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_9']) && $formData['SAFETY_Q_3_9'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['SAFETY_C_3_9']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_9']).'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td>3.10</td>';
$partBTable.="<td>Are sharps, infectious, and non-infectious waste handled properly?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_10']) && $formData['SAFETY_Q_3_10'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_10']) && $formData['SAFETY_Q_3_10'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_10']) && $formData['SAFETY_Q_3_10'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['SAFETY_C_3_10']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_10']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>3.11</td>';
$partBTable.="<td>Are infectious and non-infectious waste containers emptied regularly per the SOP and/or job aides?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_11']) && $formData['SAFETY_Q_3_11'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_11']) && $formData['SAFETY_Q_3_11'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['SAFETY_Q_3_11']) && $formData['SAFETY_Q_3_11'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['SAFETY_C_3_11']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_11']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;">3.0 SAFETY SCORE </td>';
$partBTable.='<td style="text-align:center;">'.$formData['SAFETY_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">4.0 PRE-TESTING PHASE </td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">12</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>4.1</td>';
$partBTable.="<td>Are there national testing guidelines specific to the program (e.g. HTS, PMTCT, TB, etc.) available at the testing point?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_1']) && $formData['PRE_Q_4_1'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_1']) && $formData['PRE_Q_4_1'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_1']) && $formData['PRE_Q_4_1'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PRE_C_4_1']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_1']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>4.2</td>';
$partBTable.="<td>Is the national HIV testing algorithm being used?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_2']) && $formData['PRE_Q_4_2'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_2']) && $formData['PRE_Q_4_2'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_2']) && $formData['PRE_Q_4_2'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PRE_C_4_2']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_2']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>4.3</td>';
$partBTable.="<td>Is there a process in place for an alternative HIV testing algorithm in case of expired or shortage of test kit(s)?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_3']) && $formData['PRE_Q_4_3'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_3']) && $formData['PRE_Q_4_3'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_3']) && $formData['PRE_Q_4_3'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PRE_C_4_3']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_3']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>4.4</td>';
$partBTable.="<td>Are there SOPs and/or job aides in place for each HIV rapid test used in the testing algorithm?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_4']) && $formData['PRE_Q_4_4'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_4']) && $formData['PRE_Q_4_4'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_4']) && $formData['PRE_Q_4_4'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PRE_C_4_4']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_4']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>4.5</td>';
$partBTable.="<td>Are only nationally approved HIV rapid kits available for use currently?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_5']) && $formData['PRE_Q_4_5'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_5']) && $formData['PRE_Q_4_5'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_5']) && $formData['PRE_Q_4_5'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PRE_C_4_5']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_5']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>4.6</td>';
$partBTable.="<td>Are all the test kits  currently in use within the expiration date?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_6']) && $formData['PRE_Q_4_6'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_6']) && $formData['PRE_Q_4_6'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_6']) && $formData['PRE_Q_4_6'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PRE_C_4_6']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_6']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>4.7</td>';
$partBTable.="<td>Are test kits labeled with date received and initials?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_7']) && $formData['PRE_Q_4_7'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_7']) && $formData['PRE_Q_4_7'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_7']) && $formData['PRE_Q_4_7'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PRE_C_4_7']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_7']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>4.8</td>';
$partBTable.="<td>Is there a process in place for stock management?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_8']) && $formData['PRE_Q_4_8'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_8']) && $formData['PRE_Q_4_8'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_8']) && $formData['PRE_Q_4_8'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PRE_C_4_8']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_8']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>4.9</td>';
$partBTable.="<td>Are job aides on client sample collection available and posted at the testing point?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_9']) && $formData['PRE_Q_4_9'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_9']) && $formData['PRE_Q_4_9'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_9']) && $formData['PRE_Q_4_9'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PRE_C_4_9']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_9']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>4.10</td>';
$partBTable.="<td>Are there sufficient supplies available for client sample collection?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_10']) && $formData['PRE_Q_4_10'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_10']) && $formData['PRE_Q_4_10'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_10']) && $formData['PRE_Q_4_10'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PRE_C_4_10']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_10']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>4.11</td>';
$partBTable.="<td>Are there national guidelines describing how client identification should be recorded in the HIV testing register?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_11']) && $formData['PRE_Q_4_11'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_11']) && $formData['PRE_Q_4_11'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_11']) && $formData['PRE_Q_4_11'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PRE_C_4_11']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_11']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>4.12</td>';
$partBTable.="<td>Are client identifiers recorded in the HIV testing register per national guidelines and on test devices?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_12']) && $formData['PRE_Q_4_12'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_12']) && $formData['PRE_Q_4_12'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['PRE_Q_4_12']) && $formData['PRE_Q_4_12'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['PRE_C_4_12']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_12']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;">4.0 PRE-TESTING PHASE SCORE </td>';
$partBTable.='<td style="text-align:center;">'.$formData['PRETEST_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">5.0 TESTING PHASE </td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">9</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>5.1</td>';
$partBTable.="<td>Are SOPs and/or job aides on HIV testing procedures available and posted at the testing point?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_1']) && $formData['TEST_Q_5_1'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_1']) && $formData['TEST_Q_5_1'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_1']) && $formData['TEST_Q_5_1'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['TEST_C_5_1']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['TEST_Q_5_1']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>5.2</td>';
$partBTable.="<td>Are timers available and used routinely for HIV rapid testing?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_2']) && $formData['TEST_Q_5_2'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_2']) && $formData['TEST_Q_5_2'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_2']) && $formData['TEST_Q_5_2'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['TEST_C_5_2']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['TEST_Q_5_2']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>5.3</td>';
$partBTable.="<td>Are sample collection devices (e.g., capillary tube, loop, disposable pipettes, etc.) used accurately?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_3']) && $formData['TEST_Q_5_3'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_3']) && $formData['TEST_Q_5_3'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_3']) && $formData['TEST_Q_5_3'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['TEST_C_5_3']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['TEST_Q_5_3']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>5.4</td>';
$partBTable.="<td>Are testing procedures adequately followed?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_4']) && $formData['TEST_Q_5_4'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_4']) && $formData['TEST_Q_5_4'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_4']) && $formData['TEST_Q_5_4'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['TEST_C_5_4']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['TEST_Q_5_4']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>5.5</td>';
$partBTable.="<td>Are positive and negative quality control (QC) specimens routinely used (e.g., daily or weekly) according to country guidelines?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_5']) && $formData['TEST_Q_5_5'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_5']) && $formData['TEST_Q_5_5'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_5']) && $formData['TEST_Q_5_5'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['TEST_C_5_5']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['TEST_Q_5_5']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>5.6</td>';
$partBTable.="<td>Are QC results properly recorded?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_6']) && $formData['TEST_Q_5_6'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_6']) && $formData['TEST_Q_5_6'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_6']) && $formData['TEST_Q_5_6'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['TEST_C_5_6']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['TEST_Q_5_6']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>5.7</td>';
$partBTable.="<td>Are incorrect/invalid QC results properly recorded?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_7']) && $formData['TEST_Q_5_7'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_7']) && $formData['TEST_Q_5_7'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_7']) && $formData['TEST_Q_5_7'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['TEST_C_5_7']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['TEST_Q_5_7']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>5.8</td>';
$partBTable.="<td>Are appropriate steps taken and documented when QC results are incorrect and/or invalid?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_8']) && $formData['TEST_Q_5_8'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_8']) && $formData['TEST_Q_5_8'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_8']) && $formData['TEST_Q_5_8'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['TEST_C_5_8']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['TEST_Q_5_8']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>5.9</td>';
$partBTable.="<td>Are QC records reviewed by the person in charge routinely?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_9']) && $formData['TEST_Q_5_9'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_9']) && $formData['TEST_Q_5_9'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['TEST_Q_5_9']) && $formData['TEST_Q_5_9'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['TEST_C_5_9']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['TEST_Q_5_9']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;">5.0 TESTING PHASE SCORE </td>';
$partBTable.='<td style="text-align:center;">'.$formData['TEST_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">6.0 POST TESTING PHASE - DOCUMENTS AND RECORDS</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">9</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>6.1</td>';
$partBTable.="<td>Is there a national standardized HIV rapid testing register/logbook available and in use?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_1']) && $formData['POST_Q_6_1'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_1']) && $formData['POST_Q_6_1'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_1']) && $formData['POST_Q_6_1'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['POST_C_6_1']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['POST_Q_6_1']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>6.2</td>';
$partBTable.="<td>Does the HIV testing register/logbook include all of the key quality elements?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_2']) && $formData['POST_Q_6_2'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_2']) && $formData['POST_Q_6_2'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_2']) && $formData['POST_Q_6_2'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['POST_C_6_2']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['POST_Q_6_2']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>6.3</td>';
$partBTable.="<td>Are all the elements in the register/ logbook recorded/captured correctly? (e.g., client demographics, kit names, lot numbers, expiration dates, tester name, individual and final HIV results, etc.)?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_3']) && $formData['POST_Q_6_3'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_3']) && $formData['POST_Q_6_3'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_3']) && $formData['POST_Q_6_3'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['POST_C_6_3']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['POST_Q_6_3']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>6.4</td>';
$partBTable.="<td>Is the total summary at the end of each page of the register/logbooks complied accurately?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_4']) && $formData['POST_Q_6_4'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_4']) && $formData['POST_Q_6_4'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_4']) && $formData['POST_Q_6_4'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['POST_C_6_4']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['POST_Q_6_4']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>6.5</td>';
$partBTable.="<td>Are invalid test results recorded in the register/logbook?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_5']) && $formData['POST_Q_6_5'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_5']) && $formData['POST_Q_6_5'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_5']) && $formData['POST_Q_6_5'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['POST_C_6_5']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['POST_Q_6_5']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>6.6</td>';
$partBTable.="<td>Are invalid tests repeated and results properly recorded in the register/logbook?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_6']) && $formData['POST_Q_6_6'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_6']) && $formData['POST_Q_6_6'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_6']) && $formData['POST_Q_6_6'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['POST_C_6_6']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['POST_Q_6_6']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>6.7</td>';
$partBTable.="<td>Are all client documents and records securely kept throughout all phases of the testing process?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_7']) && $formData['POST_Q_6_7'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_7']) && $formData['POST_Q_6_7'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_7']) && $formData['POST_Q_6_7'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['POST_C_6_7']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['POST_Q_6_7']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>6.8</td>';
$partBTable.="<td>Are all registers/logbooks and other documents kept in a secure location when not in use?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_8']) && $formData['POST_Q_6_8'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_8']) && $formData['POST_Q_6_8'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_8']) && $formData['POST_Q_6_8'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['POST_C_6_8']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['POST_Q_6_8']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>6.9</td>';
$partBTable.="<td>Are registers/logbooks properly labeled and archived when full?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_9']) && $formData['POST_Q_6_9'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_9']) && $formData['POST_Q_6_9'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['POST_Q_6_9']) && $formData['POST_Q_6_9'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['POST_C_6_9']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['POST_Q_6_9']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;">6.0 POST TESTING PHASE - DOCUMENTS AND RECORDS SCORE</td>';
$partBTable.='<td style="text-align:center;">'.$formData['POST_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;background-color:#dddbdb;">7.0 EXTERNAL QUALITY AUDIT (PT, SUPERVISION AND RETESTING) </td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">8/14</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.1</td>';
$partBTable.="<td>Is the testing point enrolled in an EQA/PT program?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_1']) && $formData['EQA_Q_7_1'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_1']) && $formData['EQA_Q_7_1'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_1']) && $formData['EQA_Q_7_1'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_1']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_1']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.2</td>';
$partBTable.="<td>Do all testers at the testing point test the EQA/PT samples?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_2']) && $formData['EQA_Q_7_2'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_2']) && $formData['EQA_Q_7_2'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_2']) && $formData['EQA_Q_7_2'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_2']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_2']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.3</td>';
$partBTable.="<td>Does the person in charge at the testing point review the /PT results before submission to NRL or designee?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_3']) && $formData['EQA_Q_7_3'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_3']) && $formData['EQA_Q_7_3'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_3']) && $formData['EQA_Q_7_3'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_3']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_3']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.4</td>';
$partBTable.="<td>Is an EQA/PT report received from NRL and reviewed by testers and/or the person in charge at the testing point?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_4']) && $formData['EQA_Q_7_4'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_4']) && $formData['EQA_Q_7_4'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_4']) && $formData['EQA_Q_7_4'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_4']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_4']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.5</td>';
$partBTable.="<td>Does the testing point implement corrective action in case of unsatisfactory results?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_5']) && $formData['EQA_Q_7_5'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_5']) && $formData['EQA_Q_7_5'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_5']) && $formData['EQA_Q_7_5'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_5']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_5']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.6</td>';
$partBTable.="<td>Does the testing point receive periodic supervisory visits?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_6']) && $formData['EQA_Q_7_6'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_6']) && $formData['EQA_Q_7_6'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_6']) && $formData['EQA_Q_7_6'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_6']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_6']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.7</td>';
$partBTable.="<td>Is feedback provided during supervisory visit and documented?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_7']) && $formData['EQA_Q_7_7'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_7']) && $formData['EQA_Q_7_7'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_7']) && $formData['EQA_Q_7_7'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_7']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_7']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.8</td>';
$partBTable.="<td>If testers need to be retrained, are they being retrained during the supervisory visit?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_8']) && $formData['EQA_Q_7_8'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_8']) && $formData['EQA_Q_7_8'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_8']) && $formData['EQA_Q_7_8'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_8']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_8']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="7" style="text-align:center;font-weight:bold;background-color:#dddbdb;">If the country external quality assessment program includes retesting of serum or DBS, proceed with questions 7.9 &#8211; 7.14. <br/>Otherwise, STOP here.</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.9*</td>';
$partBTable.="<td>Does the site collect samples for retesting according to country guidelines (e.g., collection of every 20<sup>th</sup> client serum or DBS sample)?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_9']) && $formData['EQA_Q_7_9'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_9']) && $formData['EQA_Q_7_9'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_9']) && $formData['EQA_Q_7_9'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_9']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_9']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.10*</td>';
$partBTable.="<td>Are the serum or DBS samples collected for retesting properly documented?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_10']) && $formData['EQA_Q_7_10'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_10']) && $formData['EQA_Q_7_10'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_10']) && $formData['EQA_Q_7_10'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_10']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_10']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.11*</td>';
$partBTable.="<td>Are serum or DBS samples collected properly (e.g., at least 3 complete circles or correct volume and correct tubes, etc.)?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_11']) && $formData['EQA_Q_7_11'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_11']) && $formData['EQA_Q_7_11'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_11']) && $formData['EQA_Q_7_11'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_11']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_11']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.12*</td>';
$partBTable.="<td>Are serum or DBS samples stored properly (e.g., away from sunlight, separated by glassine paper, desiccant, or at 4&deg;C or 20&deg;C, etc.)?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_12']) && $formData['EQA_Q_7_12'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_12']) && $formData['EQA_Q_7_12'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_12']) && $formData['EQA_Q_7_12'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_12']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_12']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.13*</td>';
$partBTable.="<td>Are the identifiers of serum or DBS samples sent for retesting properly recorded?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_13']) && $formData['EQA_Q_7_13'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_13']) && $formData['EQA_Q_7_13'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_13']) && $formData['EQA_Q_7_13'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_13']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_13']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td>7.14*</td>';
$partBTable.="<td>Are the serum or DBS results received from the referral lab properly documented and recorded in the HIV testing register/logbook?</td>";
$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_14']) && $formData['EQA_Q_7_14'] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_14']) && $formData['EQA_Q_7_14'] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td style="text-align:center;">';
$partBTable.=(isset($formData['EQA_Q_7_14']) && $formData['EQA_Q_7_14'] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
$partBTable.='</td>';

$partBTable.='<td>'.($formData['EQA_C_7_14']).'</td>';
$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_14']).'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="font-weight:bold;">7.0 EXTERNAL QUALITY AUDIT (PT, SUPERVISION AND RETESTING) SCORE </td>';
$partBTable.='<td style="text-align:center;">'.$formData['EQA_SCORE'].'</td>';
$partBTable.='</tr>';

$partBTable.='</table>';
$partBTable.='<p>*Those marked with an asterisk are only applicable to sites where sample retesting is performed.</p>';

$pdf->writeHTML($partBTable, true, 0, true, 0);

$partC='<br/><p style="font-weight:bold;">PART C: SCORING CRITERIA</p>';
$partC.='<br/><span>Each element marked will be assigned a point value:</span><br/>';
$partC.=' <span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; * Items marked "Yes" receive 1 point each.</span><br/>';
$partC.=' <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; * Items marked "Partial" receive 0.5 point each.</span><br/>';
$partC.=' <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; * Items marked "No" receive 0 point each.</span>';
$partC.='<p>Total points scored for each section should be tallied and recorded at the end of the section.</p>';
$partC.='<p>The overall total points obtained by each HIV testing point audited will be weighed to correspond to a specific performance level.</p>';

$pdf->writeHTML($partC, true, 0, true, 0);

$partCTable='<table border="1" cellspacing="0" cellpadding="5">';

$partCTable.='<tr style="font-weight:bold;text-align:center;">';
$partCTable.='<td style="width:15%">Levels</td>';
$partCTable.='<td  style="width:20%">% Score</td>';
$partCTable.='<td  style="width:65%">Description of results</td>';
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#C00000;">Level 0</td>';
$partCTable.='<td>Less than 40%</td>';
$partCTable.='<td>Needs improvement in all areas and immediate remediation</td>';
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#E36C0A;">Level 1</td>';
$partCTable.='<td>40% - 59%</td>';
$partCTable.='<td>Needs improvement in specific areas</td>';
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#FFFF00;">Level 2</td>';
$partCTable.='<td>60% - 79%</td>';
$partCTable.='<td>Partially eligible</td>';
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#92D050;">Level 3</td>';
$partCTable.='<td>80% - 89%</td>';
$partCTable.='<td>Close to national site certification</td>';
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#00B050;">Level 4</td>';
$partCTable.='<td>90% or higher</td>';
$partCTable.='<td>Eligible to national site certification</td>';
$partCTable.='</tr>';

$partCTable.='</table>';

$pdf->writeHTML($partCTable,true,0,true,0);

$partDTitle='<p style="font-weight:bold;line-height:30px;">Part D. Auditor\'s Summation Report for SPI-RT Audit</p>';
$pdf->writeHTML($partDTitle,true,0,true,0);

$partDtableBox1='<table cellspacing="0" cellpadding="2">';
$partDtableBox1.="<tr><td>Facility Name:".$formData['facilityname']."</td></tr><tr><td>Site Type:".$formData['testingpointtype'];
$partDtableBox1.=((isset($formData['testingpointtype_other']) && $formData['testingpointtype_other'] != "") ? " - " . $formData['testingpointtype_other']: "");
$partDtableBox1.="</td></tr>";
$partDtableBox1.="<tr><td>Staff Audited Name: ".$formData['staffaudited']."</td></tr>";
$partDtableBox1.='</table>';
$pdf->writeHTMLCell(50,26,'','',$partDtableBox1,1, 0, 0, true, 'L');

$partDtableBox2='<table cellspacing="0" cellpadding="5">';
$partDtableBox2.="<tr><td>No. of Tester(s): ".$formData['NumberofTester']."</td></tr><tr><td>Duration of Audit: ".$formData['durationaudit']."</td></tr>";
$partDtableBox2.='</table>';

$pdf->writeHTMLCell(50,26,70,'',$partDtableBox2,1,0, 0, true, 'L',true);

$scorePer=round($formData['AUDIT_SCORE_PERCANTAGE']);
$level='';
$colorCode='';
if($scorePer<40){
  $level="Level 0";
  $colorCode="background-color:#C00000";
}elseif($scorePer>=40 && $scorePer<=59){
  $level="Level 1";
  $colorCode="background-color:#E36C0A";
}elseif($scorePer>=60 && $scorePer<=79){
  $level="Level 2";
  $colorCode="background-color:#FFFF00";
}elseif($scorePer>=80 && $scorePer<=89){
  $level="Level 3";
  $colorCode="background-color:#92D050";
}elseif($scorePer>=90){
  $level="Level 4";
  $colorCode="background-color:#00B050";
}
					  
$partDtableBox3='<table cellspacing="0" cellpadding="5">';
$partDtableBox3.="<tr><td>Total points scored (exclude N/A) = ".$formData['FINAL_AUDIT_SCORE']."</td></tr>";
$partDtableBox3.="<tr><td>Total score expected = ".$formData['MAX_AUDIT_SCORE']."</td></tr>";
$partDtableBox3.='<tr><td>% Score = '.round($formData['AUDIT_SCORE_PERCANTAGE'],2).'% &nbsp; <span style="'.$colorCode.'">  &nbsp;&nbsp;'.$level.'  &nbsp;&nbsp;</span></td></tr>';
$partDtableBox3.='</table>';

$pdf->writeHTMLCell(70,26,125,'',$partDtableBox3,1,1, 0, true, 'L',true);

$partDTable='<br/><br/><table border="1" cellspacing="0" cellpadding="5" style="width:100%">';
$partDTable.='<tr>';
$partDTable.='<td rowspan="2" style="font-weight:bold;text-align:center;width:9%"><br/><br/>Section No.</td>';
$partDTable.='<td rowspan="2" style="font-weight:bold;text-align:center;width:22%"><br/><br/>Deficiency/Issue observed</td>';
$partDTable.='<td colspan="2" style="font-weight:bold;text-align:center;width:20%">Correction Actions</td>';
$partDTable.='<td rowspan="2" style="font-weight:bold;text-align:center;width:23%">Auditor\'s <br/>Comments</td>';
$partDTable.='<td colspan="2" style="font-weight:bold;text-align:center;width:26%">Recommendations</td>';
$partDTable.='</tr>';
$partDTable.='<tr>';
$partDTable.='<td style="font-weight:bold;text-align:center;width:12%;">Immediate</td>';
$partDTable.='<td style="font-weight:bold;text-align:center;width:8%;">Follow up</td>';
$partDTable.='<td style="font-weight:bold;text-align:center;">Actions</td>';
$partDTable.='<td style="font-weight:bold;text-align:center;">Timeline / Person responsible</td>';
$partDTable.='</tr>';
if(isset($formData['correctiveaction']) && $formData['correctiveaction'] != ""  && $formData['correctiveaction'] != "[]"){
    $correctiveActions = json_decode($formData['correctiveaction'],true);
    foreach($correctiveActions as $ca) {
        $partDTable.='<tr>';
        $partDTable.='<td style="text-align:center;">'.$ca['sectionno'].'</td>';
        $partDTable.='<td>'.$ca['deficiency'].'</td>';
        $partDTable.='<td style="text-align:center;">';
        $partDTable.=($ca['correction'] == 'Immediate' ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "" );
        $partDTable.='</td>';
        $partDTable.='<td style="text-align:center;">';
        $partDTable.=($ca['correction'] == 'Followup' ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "" );
        $partDTable.='</td>';
        $partDTable.='<td>'.$ca['auditorcomment'].'</td>';
        $partDTable.='<td>'.$ca['action'].'</td>';
        $partDTable.='<td>'.$ca['timeline'].'</td>';
        $partDTable.='</tr>';
    }
}else {
    $partDTable.='<tr>';
    $partDTable.='<td colspan="7">No Corrective Actions</td>';
    $partDTable.='</tr>';
}
$partDTable.='</table><br/><br/><br/>';
$pdf->writeHTML($partDTable,true,0,true,0);

$signBox1='<table cellspacing="0" cellpadding="4">';
$signBox1.="<tr><td>Staff Audited Signature:</td></tr>";
$signBox1.="<tr><td>Person in Charge Name and Signature : ".$formData['personincharge']."</td></tr>";
$signBox1.='</table>';
$pdf->writeHTMLCell(90,18,'','',$signBox1,1, 0, 0, true, 'L');

$signBox2='<table cellspacing="0" cellpadding="4">';
$signBox2.="<tr><td>Auditor Name and Signature:</td></tr>";
$signBox2.="<tr><td>Date (dd/mm/yyyy):</td></tr>";
$signBox2.='</table>';
$pdf->writeHTMLCell(80,18,115,'',$signBox2,1,1, 0, true, 'L');

//Close and output PDF document
$fileName = "SPI-RT-CHECKLIST-".date('d-M-Y-H-i-s').".pdf";
$filePath = TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR. "audit-email". DIRECTORY_SEPARATOR . $tempId. DIRECTORY_SEPARATOR . $fileName;
$pdf->Output($filePath, "F");
//echo $fileName;
//============================================================+
// END OF FILE
//============================================================+
}else{
    //No CASE
}