<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<div class="am-content">
        <div class="page-head">
          <h2>Email</h2>
	    <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
        </div>
        
        <div class="main-content">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">
	    <div class="row">
            <div class="col-sm-12">
              <div class="panel panel-default">
                <div class="panel-body">
                    <form role="form" name="addEailInformation" id="addEailInformation" method="post" enctype="multipart/form-data" action="<?php echo $this->url('email', array('action' => 'index')); ?>" autocomplete="off" >
                        <div class="row">
                            <div class="form-group col-lg-6">
                                <label>Facility <span class="mandatory">*</span></label>
                                <select class="form-control isRequired" name="facility" id="facility" title="Please select the facility" onchange="getSelectedFacilitesAudits(this.value);">
                                    <option value="">-- Select Facility --</option>
                                    <?php
                                    if(isset($facilityName['uniqueName']) && count($facilityName['uniqueName']) > 0) {
                                      foreach($facilityName['uniqueName'] as $facilities) {
                                    ?>
                                      <option value="<?php echo $facilities['facilityname']; ?>" <?php if(isset($facilityResult['fResult']->facility_name) && $facilityResult['fResult']->facility_name == $facilities['facilityname']) { ?> selected="selected"<?php } ?>><?php echo ucwords($facilities['facilityname']); ?></option>
                                    <?php } } ?>
                                </select>
                            </div>
                        </div>
			<div class="row facilityProfile" <?php if(!isset($facilityResult['fResult']->facility_name)) { ?>style="display:none;"<?php } ?>>
                            <div class="form-group col-lg-6">
                                <label>Facility Email Address <span class="mandatory">*</span></label>
				<input type="hidden" class="" name="facilityName" id="facilityName" <?php if(isset($facilityResult['fResult']->facility_name)) { ?>value="<?php echo $facilityResult['fResult']->facility_name; ?>"<?php } ?>/>
                                <input type="text" class="form-control isEmail isRequired" name="emailAddress" id="emailAddress" placeholder="Enter Email Address" title="Please enter facility email address" <?php if(isset($facilityResult['fResult']->facility_name)) { ?> value="<?php echo $facilityResult['fResult']->email; ?>"<?php } ?>/>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-lg-6">
                                <label>Choose Audits </label>
                                <div id="ajaxAudit">
                                    <select class="" name="audits[]" id="audits" multiple="multiple" title="Please select the audits">
					 <?php if(isset($facilityResult['auditsResult']) && count($facilityResult['auditsResult']) > 0) {
						foreach($facilityResult['auditsResult'] as $audits){
					?>
					  <option value="<?php echo $audits['id']; ?>" <?php echo ($ids == base64_encode($audits['id']))? 'selected=selected':''; ?>><?php echo $audits['testingpointname'].' - '.$audits['assesmentofaudit']; ?></option>
					<?php } } ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-lg-6">
                                <label>Message <span class="mandatory">*</span></label>
                                <textarea class="form-control isRequired" name="message" id="message" placeholder="Enter Your Message" title="Please type your message" style="min-width:550px;min-height:120px;max-width:550px;max-height:160px;"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-lg-6">
                                <label>Attachments </label>
                               <input type="file" class="" name="attchement[]" id="attchement" multiple="multiple" title="Please choose file"/>
                            </div>
                        </div>
                        <div class="spacer  col-lg-12">
                          <button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Send</button>
                         <a href="<?php echo $this->url('email', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a> 
                        </div>
                    </form>
                </div>
            </div>
        </div>
        </div>
        </div>
        <br>
        <br>
    </div>
</div>
<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function(){
        //initialize the javascript
        $(".select2").select2({
          width: '100%',
              placeholder: '',
              allowClear: true,
              tags : false
        });		
	$("#audits").multipleSelect({placeholder:'Please select audits',width: '100%'});
	
	<?php
	if(isset($ids) && trim($ids)!= ''){
	  $xplodeIds = explode("#",base64_decode($ids));
	  if(count($xplodeIds) >1){ ?>
	    if(getCookie('dpdf') == null || getCookie('dpdf')!= '<?php echo $ids; ?>' ) {
	    <?php for($d=1;$d<count($xplodeIds);$d++){ ?>
	        generatePdf('<?php echo $xplodeIds[0]; ?>','<?php echo $xplodeIds[$d]; ?>');
	    <?php } ?>
	      setCookie('dpdf','<?php echo $ids; ?>');
	    }
	<?php } }
	?>
    });
    
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'addEailInformation'
        });
        if (flag) {
            if (duplicateName) {
                document.getElementById('addEailInformation').submit();
            }
        }
    }
    
    function getSelectedFacilitesAudits(objValue){
        $.post("<?php echo $this->url('email', array('action' => 'get-facilities-audits')); ?>", {facilityName: objValue},
        function(data) {
            splitData = data.split("##");
	    if($.trim(objValue)== ''){
		$(".facilityProfile").hide();
	    }else{
		$(".facilityProfile").show();
	    }
            $("#facilityName").val(splitData[1]);
            $("#emailAddress").val(splitData[2]);
            $("#ajaxAudit").html(splitData[0]);
            $(".select2").select2({
              width: '100%',
                  placeholder: '',
                  allowClear: true,
                  tags : false
            });		
            $("#audits").multipleSelect({placeholder:'Please select audits',width: '100%'});
        });
    }
    
    function generatePdf(tId,auId){
	$.post("<?php echo $this->url('spi-v3-form', array('action' =>'download-pdf')); ?>", {tempId: tId,auditId:auId},
        function(data) {
		
	});
    }
</script>