<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-4"> <h2>Email</h2></div>
            <div class="col-sm-8">
                <div class="row">
                    <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span> 
                </div>

                <div class="row">
                    <span class="muted pull-right" style="font-size:15px; "><span class="mandatory" style="color: green;">*</span> indicates read only field</span>
                </div>
            </div>
        </div>
    </div>

    <d<div class="main-content">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-default">
                            <div class="panel-body" >
                                <div id="form">
                                <form action="<?php $this->url('certification-mail', array('action' => 'index')); ?>" name="form" method="post" enctype="multipart/form-data" onsubmit="return validateForm()">  
                                    <?php
                                    $form->prepare();
                                    if (!empty($due_date)) {
                                        $form->get('type')->setAttributes([
                                            'id' => 'Choice',
                                            'onclick' => "emptyInput(this)",
                                            'options' => [2 => 'Send Reminder']]);
                                    } elseif (empty($due_date) && !empty($key)) {
                                        $form->get('type')->setAttributes([
                                            'id' => 'Choice',
                                            'onclick' => "emptyInput(this)",
                                            'options' => [1 => 'Send Certificate']]);
                                    } else {
                                        $form->get('type')->setAttributes([
                                            'id' => 'Choice',
                                            'onclick' => "emptyInput(this)",
                                            'options' => [
                                                '' => 'Make a choice',1 => 'Send Certificate',
                                                2 => 'Send Reminder'],
                                            'onclick' => "setChoice()"
                                        ]);
                                    }



                                    $form->get('to_email')->setAttributes([
                                        'class' => 'form-control',
                                        'autocomplete' => 'off',
                                        'value' => $this->email,
                                        'id' => 'to'
                                    ]);


                                    $form->get('cc')->setAttributes([
                                        'class' => 'form-control',
                                        'autocomplete' => 'off',
                                        'id' => 'cc',
                                        'value' => $this->facility_in_charge_email
                                    ]);
                                    $form->get('bcc')->setAttributes([
                                        'class' => 'form-control',
                                        'autocomplete' => 'off',
                                    ]);
                                    $form->get('subject')->setAttributes([
                                        'class' => 'form-control',
                                        'autocomplete' => 'off',
                                        'id' => 'Subject',
                                        'rows' => 1,
                                        'onFocus' => "blur(this)"
                                    ]);
                                    $form->get('message')->setAttributes([
                                        'class' => 'form-control',
                                        'rows' => 9,
                                        'autocomplete' => 'off',
                                        'id' => 'Message',
                                        'onFocus' => "blur(this)"
                                    ]);
                                    $form->get('submit')->setAttributes([
                                    ]);


                                    echo $this->form()->openTag($form);
                                    ?>

                                    <div style="margin-left: 30px">
                                        <?php echo $this->formHidden($form->get('mail_id')->setAttribute('class', 'form-control')) ?>
                                        <?= $this->formLabel($form->get('type')); ?>
                                        <?= $this->formElement($form->get('type')); ?>
                                        <?= $this->formElementErrors($form->get('type')); ?>

                                        <div id="Recipient" class="row" style="margin-top: 30px;"></div>
                                        <div id="Recipient_name" class="row"></div>
                                        <div class="row">
                                            <div class="form-group col-lg-6">
                                                <?= $this->formLabel($form->get('to_email')); ?><span class="mandatory">*</span>
                                                <?= $this->formElement($form->get('to_email')); ?>
                                                <?= $this->formElementErrors($form->get('to_email')); ?>
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="form-group col-lg-6" > 
                                                <?= $this->formLabel($form->get('cc')); ?>
                                                <?= $this->formElement($form->get('cc')); ?>
                                                <?= $this->formElementErrors($form->get('cc')); ?>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="form-group col-lg-6 pull-left" > 
                                                <?= $this->formLabel($form->get('bcc')); ?>
                                                <?= $this->formElement($form->get('bcc')); ?>
                                                <?= $this->formElementErrors($form->get('bcc')); ?>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="form-group col-lg-6"> 
                                                <?= $this->formLabel($form->get('subject')); ?><span class="mandatory" style="color: green;">*</span>
                                                <?= $this->formElement($form->get('subject')); ?>
                                                <?= $this->formElementErrors($form->get('subject')); ?>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="form-group col-lg-6 "> 
                                                <?= $this->formLabel($form->get('message')); ?><span class="mandatory" style="color: green;">*</span>
                                                <?= $this->formElement($form->get('message')); ?>
                                                <?= $this->formElementErrors($form->get('message')); ?>
                                            </div>
                                        </div>
                                        <div style="margin-bottom: 20px; " id="div-file">
                                            <input type="hidden" name="MAX_FILE_SIZE"  />
                                            <INPUT TYPE="file" NAME="attachedfile" MAXLENGTH=50 id="file" onclick="emptyInput(this)"></div>
                                        <div class="row">
                                            <div style="margin-left: 18px;"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                                <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('certification-mail', array('action' => 'index')); ?>" >CANCEL</a> </div></div>
                                    </div>
                                    <?php
                                    echo $this->form()->closeTag();
                                    ?>
                                </form></div>
                                <div style="margin-top: 50px">
                                    <table id="example" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
                                        <thead>
                                            <tr>
                                                <th>Recipient</th>
                                                <th>Cc</th>
                                                <th>Bcc</th>
                                                <th>Type</th>
                                                <th>Date</th>

                                            </tr>

                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->list as $list) : ?>
                                                <tr>
                                                    <td><div style="width:250px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($list->to_email); ?></div></td>
                                                    <td><div style="width:250px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($list->cc); ?></div></td>
                                                    <td><div style="width:250px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($list->bcc); ?></div></td>
                                                    <td>
                                                        <?php
                                                        if ($list->type == '1') {
                                                            echo '<div style="width:150px;height:40px;overflow:auto;">Certificate sent</div>';
                                                        } elseif ($list->type == '2') {
                                                            echo '<div style="width:100px;height:40px;overflow:auto;"> Reminder sent  </div>';
                                                        };
                                                        ?>
                                                    </td>
                                                    <td><div style="width:180px;height:40px;overflow:auto;color:red"><?php echo date("d-m-Y", strtotime($this->escapeHtml($list->mail_date))); ?></div></td>
                                                </tr>
                                            <?php endforeach; ?>  
                                        </tbody> 
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <br>
            <br>

        </div>



        <script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>
        <script type="text/javascript" language="javascript">
                                                        var provider = '<?php echo $provider; ?>';
                                                        var due_date = '<?php echo $due_date; ?>';
                                                        var to = '<?php echo $email; ?>';
                                                        var cc = '<?php echo $facility_in_charge_email; ?>';
        </script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/mail.js'); ?>"></script>
        <script type="text/javascript" language="javascript">
                                                        $(document).ready(function () {

                                                            $('#example').dataTable({
                                                                "aProcessing": true,
                                                                "aServerSide": true,
                                                            })
                                                        });
        </script>


