<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="shortcut icon" href="<?php echo $this->basePath('assets/img/favicon.png'); ?>">
	<title>Error</title>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/stroke-7/style.css'); ?>" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/jquery.nanoscroller/css/nanoscroller.css'); ?>" />
	<!--[if lt IE 9]>
    <script src="<?php echo $this->basePath('assets/js/html5shiv.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/respond.min.js'); ?>" type="text/javascript"></script>
    <![endif]-->
	<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/style.css'); ?>" type="text/css" />
	<style>
		.am-error .error-number {
			display: block;
			color: #3598DC;
			font-size: 130px;
			font-family: 'Raleway', sans-serif;
			font-weight: 400;
			line-height: 120px;
			text-shadow: 6px 5px 0 rgba(0, 0, 0, 0);
			margin-bottom: 30px;
		}
		.am-splash-screen .am-wrapper .am-content a:hover {
			color: #3598DC;
		}
	</style>
</head>

<body class="am-splash-screen">
	<div class="am-wrapper am-error am-error-404">
		<div class="am-content">
			<div class="main-content" style="padding-top: 80px !important;">
				<div class="error-container">
					<div class="error-image"></div>
					<div class="error-number">
						<h1><?php echo $this->translate('An error occurred') ?></h1>
						<h2><?php echo $this->message ?></h2>
					</div>

					<p class="error-description">The page you are looking for might have been removed.</p>
					<div class="error-goback-text">Would you like to go <a href="/">home</a>?</div>

				</div>
			</div>
		</div>
	</div>
	<script src="<?php echo $this->basePath('assets/lib/jquery/jquery.min.js'); ?>" type="text/javascript"></script>
	<script src="<?php echo $this->basePath('assets/lib/jquery.nanoscroller/javascripts/jquery.nanoscroller.min.js'); ?>" type="text/javascript"></script>
	<script src="<?php echo $this->basePath('assets/js/main.js'); ?>" type="text/javascript"></script>
	<script src="<?php echo $this->basePath('assets/lib/bootstrap/dist/js/bootstrap.min.js'); ?>" type="text/javascript"></script>
	<script type="text/javascript">
		$(document).ready(function() {
			//initialize the javascript
			App.init();
		});
	</script>
</body>

</html>