<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-8">
                <h2>Add a new Tester</h2>
            </div>

            <div class="col-sm-4 ">
                <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'index')) {  ?>
                <a href="<?php echo $this->url('provider', array('action' => 'index')); ?>" class="btn btn-success pull-right" style="margin-left: 5px;"><i class="fa fa-list"></i>&nbsp;List of Testers</a>
                <?php }  ?>

            </div>
        </div>


        <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
    </div>

    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >
                            <form action="<?php $this->url('provider', array('action' => 'add')); ?>" name="form" method="post" onsubmit="return validateForm()">

                                <?php
                                $form->prepare();

                                $form->get('professional_reg_no')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Professional Registration No ',
                                    'autocomplete' => 'off',
                                ]);
                                $form->get('last_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Last Name',
                                    'autocomplete' => 'off',
                                    'id' => 'Last Name',
                                    'onclick' => 'emptyInput(this)',
                                    'onkeyup' => "myFunction()"
                                ]);

                                $form->get('first_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'First Name',
                                    'autocomplete' => 'off',
                                    'id' => 'First Name',
                                    'onclick' => 'emptyInput(this)',
                                    'onkeyup' => "myFunction()"
                                ]);

                                $form->get('middle_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Middle Name',
                                    'id' => 'Middle Name',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)',
                                    'onkeyup' => "myFunction()"
                                ]);

                                $form->get('region')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Region',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'showDistrict(this.value)'
                                ]);

                                $form->get('district')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'District',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'showFacilities(this.value)',
                                ]);

                                $form->get('type_vih_test')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Type of VIH Test',
                                    'id' => 'Type of VIH Test Modality/Point',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('phone')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Phone',
                                    'id' => 'Tester Phone Number',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)'
                                ]);
                                $form->get('email')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Email',
                                    'autocomplete' => 'off',
                                    'id' => 'Tester Email',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('prefered_contact_method')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Prefered Contact Method',
                                    'id' => 'Prefered Contact Method',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('current_jod')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Current Job',
                                    'id' => 'Current Job Title',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('time_worked')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Time Worked As Tester',
                                    'autocomplete' => 'off',
                                    'id' => 'Time worked as tester',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('test_site_in_charge_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Name',
                                    'autocomplete' => 'off',
                                    'id' => 'Testing site in charge Name',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('test_site_in_charge_phone')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Phone',
                                    'id' => 'Testing site in charge Phone',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('test_site_in_charge_email')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Email',
                                    'autocomplete' => 'off',
                                    'id' => 'Testing site in charge Email',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('facility_in_charge_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Name',
                                    'autocomplete' => 'off',
                                    'id' => 'Facility in charge Name',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('facility_in_charge_phone')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Phone',
                                    'autocomplete' => 'off',
                                    'id' => 'Facility in charge Phone',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('facility_in_charge_email')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Email',
                                    'autocomplete' => 'off',
                                    'id' => 'Facility in charge Email',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('facility_id')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Facility Name',
                                    'id' => 'Facility Name',
                                    'onclick' => 'emptyInput(this)',
                                ]);


                                $form->get('submit')->setAttributes([
                                ]);


                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>

                                <fieldset>


                                    <legend style="color: #00b3ee">TESTER IDENTIFICATION</legend>


                                    <div class="form-group col-lg-4"> 
                                        <?= $this->formLabel($form->get('professional_reg_no')); ?>
                                        <?= $this->formElement($form->get('professional_reg_no')); ?>
                                        <?= $this->formElementErrors($form->get('professional_reg_no')); ?>
                                    </div>
                                    <div class="form-group col-lg-4"> 
                                        <?= $this->formLabel($form->get('last_name')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('last_name')); ?>
                                        <?= $this->formElementErrors($form->get('last_name')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('first_name')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('first_name')); ?>
                                        <?= $this->formElementErrors($form->get('first_name')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('middle_name')); ?>
                                        <?= $this->formElement($form->get('middle_name')); ?>
                                        <?= $this->formElementErrors($form->get('middle_name')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('region')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('region')); ?>
                                        <?= $this->formElementErrors($form->get('region')); ?>
                                    </div>

                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('district')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('district')); ?>
                                        <?= $this->formElementErrors($form->get('district')); ?></div>

                                    <div class="form-group col-lg-4">  
                                        <?= $this->formLabel($form->get('type_vih_test')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('type_vih_test')); ?>
                                        <?= $this->formElementErrors($form->get('type_vih_test')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('phone')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('phone')); ?>
                                        <?= $this->formElementErrors($form->get('phone')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('email')); ?>
                                        <?= $this->formElement($form->get('email')); ?>
                                        <?= $this->formElementErrors($form->get('email')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('prefered_contact_method')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('prefered_contact_method')); ?>
                                        <?= $this->formElementErrors($form->get('prefered_contact_method')); ?>       
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('current_jod')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('current_jod')); ?>
                                        <?= $this->formElementErrors($form->get('current_jod')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('facility_id')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('facility_id')); ?>
                                        <?= $this->formElementErrors($form->get('facility_id')); ?>
                                    </div>


                                    <div class = " form-group col-lg-4">
                                        <div class = "input-group">
                                            <?= $this->formLabel($form->get('time_worked')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('time_worked')); ?>
                                            <?= $this->formElementErrors($form->get('time_worked')); ?>
                                            <div class = "input-group-btn">
                                                <select class="form-control" style="margin-bottom: -28px; width: 100px;" name="select_time" id="Time" onclick = 'emptyInput(this)'> 
                                                    <option value="">--Select--</option>
                                                    <option value="Years">Year(s)</option>
                                                    <option value="Months">Month(s)</option>
                                                    <option value="Weeks">Week(s)</option>
                                                    <option value="Days">Day(s)</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>

                                <fieldset>


                                    <legend style="color: #00b3ee">TESTING SITE IN CHARGE</legend>


                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('test_site_in_charge_name')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('test_site_in_charge_name')); ?>
                                        <?= $this->formElementErrors($form->get('test_site_in_charge_name')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('test_site_in_charge_phone')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('test_site_in_charge_phone')); ?>
                                        <?= $this->formElementErrors($form->get('test_site_in_charge_phone')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('test_site_in_charge_email')); ?>
                                        <?= $this->formElement($form->get('test_site_in_charge_email')); ?>
                                        <?= $this->formElementErrors($form->get('test_site_in_charge_email')); ?>
                                    </div>
                                </fieldset>

                                <fieldset>


                                    <legend style="color: #00b3ee">FACILITY IN CHARGE </legend>


                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('facility_in_charge_name')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('facility_in_charge_name')); ?>
                                        <?= $this->formElementErrors($form->get('facility_in_charge_name')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('facility_in_charge_phone')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('facility_in_charge_phone')); ?>
                                        <?= $this->formElementErrors($form->get('facility_in_charge_phone')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('facility_in_charge_email')); ?>
                                        <?= $this->formElement($form->get('facility_in_charge_email')); ?>
                                        <?= $this->formElementErrors($form->get('facility_in_charge_email')); ?>
                                    </div>
                                </fieldset>

                                <fieldset>
                                    <legend style="color: #00b3ee"></legend>
                                    <div class="form-group col-lg-4" style="margin-top: 30px"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                        <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('provider', array('action' => 'index')); ?>" >CANCEL</a> </div>
                                </fieldset>
                                <?php echo $this->form()->closeTag();
                                ?>
                            </form>


                            <div style="margin-top: 25px">

                                <table id="example" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" >
                                    <thead>
                                        <tr>
                                            <th>Certification Registration No</th>
                                            <th > Professional Registration No (if available)</th>
                                            <th style="width:10%;">Certification ID</th>
                                            <th style="width:10%;">Tester</th>
                                            <th style="width:10%;">Region</th>
                                            <th style="width:10%;">District</th>
                                            <th style="width:10%;">Type VIH Test Modality/ Point</th> 
                                            <th style="width:10%;">Phone</th>
                                            <th style="width:10%;" >E-mail</th>
                                            <th style="width:10%;">Prefered Contact Methode</th>
                                            <th style="width:10%;" >Current Job</th>
                                            <th>Time worked as tester</th>
                                            <th style="width:10%;" >Facility Name</th>
                                            <th style="width:10%;" >Facility Address</th>
                                            <th>Testing Site In charge Name</th>
                                            <th>Testing Site In charge  Phone</th>
                                            <th>Testing Site In charge Email</th>
                                            <th>Facility In charge Name </th>
                                            <th>Facility In charge Phone</th>
                                            <th>Facility In charge Email</th>

                                        </tr>


                                    </thead>
                                    <tbody>

                                        <?php foreach ($this->providers as $provider) : ?>
                                            <tr>
                                                <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->certification_reg_no); ?></div></td>
                                                <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->professional_reg_no); ?></div></td>
                                                <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->certification_id); ?></div></td>
                                                <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->last_name . ' ' . $provider->first_name . ' ' . $provider->middle_name); ?></div></td>
                                                <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->region_name); ?></div></td>
                                                <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->district_name); ?></div></td>
                                                <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->type_vih_test); ?></div></td>
                                                <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->phone); ?></div></td>
                                                <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->email); ?></div></td>
                                                <td><div style="width:80px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->prefered_contact_method); ?></div></td>
                                                <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->current_jod); ?></div></td>
                                                <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->time_worked); ?></div></td>
                                                <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->facility_name); ?></div></td>
                                                <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->facility_address); ?></div></td>
                                                <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->test_site_in_charge_name); ?></div></td>
                                                <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->test_site_in_charge_phone); ?></div></td>
                                                <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->test_site_in_charge_email); ?></div></td>
                                                <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->facility_in_charge_name); ?></div></td>
                                                <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->facility_in_charge_phone); ?></div></td>
                                                <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->facility_in_charge_email); ?></div></td>

                                            </tr>
                                            <?php
                                        endforeach;
                                        ?>
                                    </tbody>
                                </table>
                            </div>


                        </div>

                    </div>
                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>

</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/provider.js'); ?>"></script>
<script>

                                $(document).ready(function () {

                                    $('#example').dataTable({
                                        "aProcessing": true,
                                        "aServerSide": true,
                                    })
                                });

                                function showDistrict(str) {

                                    if (str == "") {
                                        document.getElementById("District").innerHTML = "";
                                        return;
                                    } else {
                                        if (window.XMLHttpRequest) {
                                            // code for IE7+, Firefox, Chrome, Opera, Safari
                                            xmlhttp = new XMLHttpRequest();
                                        } else {
                                            // code for IE6, IE5
                                            xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                                        }
                                        xmlhttp.onreadystatechange = function () {
                                            if (this.readyState == 4 && this.status == 200) {
                                                document.getElementById("District").innerHTML = this.responseText;
                                            }
                                        };
                                        xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'district')); ?>?q=" + str, true);
                                        xmlhttp.send();
                                    }
                                }

                                function showFacilities(str) {

                                    if (str == "") {
                                        document.getElementById("Facility Name").innerHTML = "";
                                        return;
                                    } else {
                                        if (window.XMLHttpRequest) {
                                            // code for IE7+, Firefox, Chrome, Opera, Safari
                                            xmlhttp = new XMLHttpRequest();
                                        } else {
                                            // code for IE6, IE5
                                            xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                                        }
                                        xmlhttp.onreadystatechange = function () {
                                            if (this.readyState == 4 && this.status == 200) {
                                                document.getElementById("Facility Name").innerHTML = this.responseText;
                                            }
                                        };
                                        xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'facility')); ?>?q=" + str, true);
                                        xmlhttp.send();
                                    }
                                }

                                function myFunction() {
                                    // Declare variables
                                    var input, filter, table, tr, td, i, last, first, middle;
                                    last = document.getElementById("Last Name").value.trim();
                                    first = document.getElementById("First Name").value.trim();
                                    middle = document.getElementById("Middle Name").value.trim();
                                    if (last && !first && !middle) {
                                        input = last;
                                    } else if (last && first && !middle) {
                                        input = last + ' ' + first;

                                    } else if (last && first && middle) {
                                        input = last + ' ' + first + ' ' + middle;

                                    }

                                    filter = input.toUpperCase();
                                    table = document.getElementById("example");
                                    tr = table.getElementsByTagName("tr");

                                    // Loop through all table rows, and hide those who don't match the search query
                                    for (i = 0; i < tr.length; i++) {
                                        td = tr[i].getElementsByTagName("td")[3];

                                        if (td) {
                                            if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                                                tr[i].style.display = "";
                                            } else {
                                                tr[i].style.display = "none";
                                            }
                                        }
                                    }
                                }



</script>





