<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;

$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<style>
    #shBtnManageColumns {
        font-size: 17px;
        font-weight: 600;
    }
</style>
<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-8">
                <h2>Add a new Tester</h2>
            </div>

            <div class="col-sm-4 ">
                <?php if ($this->isAllowed($role, 'Certification\Controller\ProviderController', 'index')) {  ?>
                    <a href="<?php echo $this->url('provider', array('action' => 'index')); ?>" class="btn btn-success pull-right" style="margin-left: 5px;"><i class="fa fa-list"></i>&nbsp;List of Testers</a>
                <?php }  ?>

            </div>
        </div>


        <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
    </div>

    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form action="<?php $this->url('provider', array('action' => 'add')); ?>" name="form" method="post" onsubmit="return validateForm()" enctype="multipart/form-data">

                                <?php
                                $form->prepare();

                                $form->get('professional_reg_no')->setAttributes([
                                    'class' => 'form-control professional_reg_no',
                                    'placeholder' => 'Professional Registration No ',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)',
                                    'onblur' => 'checkNameValidation("provider","professional_reg_no", this, null, "The professional reg.no that you entered already exist..Please enter different reg.no")'
                                ]);
                                $form->get('last_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Last Name',
                                    'autocomplete' => 'off',
                                    'id' => 'Last Name',
                                    'onclick' => 'emptyInput(this)',
                                    'onkeyup' => "myFunction()"
                                ]);

                                $form->get('first_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'First Name',
                                    'autocomplete' => 'off',
                                    'id' => 'First Name',
                                    'onclick' => 'emptyInput(this)',
                                    'onkeyup' => "myFunction()"
                                ]);

                                $form->get('middle_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Middle Name',
                                    'id' => 'Middle Name',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)',
                                    'onkeyup' => "myFunction()"
                                ]);

                                $form->get('country')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'Country',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'showRegion(this.value)'
                                ]);

                                $form->get('region')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'Region',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'showDistrict(this.value)'
                                ]);

                                $form->get('district')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'District',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'showFacilities(this.value)',
                                ]);

                                $form->get('type_vih_test')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Type of HIV Test',
                                    'id' => 'Type of HIV Test Modality/Point',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('phone')->setAttributes([
                                    'class' => 'form-control checkNum',
                                    'placeholder' => 'Phone',
                                    'id' => 'Tester Phone Number',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)',
                                    'onblur' => 'checkNameValidation("provider","phone", this, null, "The phone no. that you entered already exist..Please enter different phone no.")'
                                ]);
                                $form->get('email')->setAttributes([
                                    'class' => 'form-control testerEmail',
                                    'placeholder' => 'Email',
                                    'autocomplete' => 'off',
                                    'id' => 'Tester Email',
                                    'onclick' => 'emptyInput(this)',
                                    'onblur' => 'checkNameValidation("provider","email", this, null, "The email address that you entered already exist..Please enter different email address")'
                                ]);

                                $form->get('prefered_contact_method')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Prefered Contact Method',
                                    'id' => 'Prefered Contact Method',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'managePreferedContactEmail(this.value)'
                                ]);

                                $form->get('current_jod')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Current Job',
                                    'id' => 'Current Job Title',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('time_worked')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Time Worked As Tester',
                                    'autocomplete' => 'off',
                                    'id' => 'Time worked as tester',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('username')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Username for login',
                                    'autocomplete' => 'off',
                                    'id' => 'Username',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('password')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Password for login',
                                    'autocomplete' => 'off',
                                    'id' => 'Password',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('test_site_in_charge_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Name',
                                    'autocomplete' => 'off',
                                    'id' => 'Testing site in charge Name',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('test_site_in_charge_phone')->setAttributes([
                                    'class' => 'form-control checkNum',
                                    'placeholder' => 'Phone',
                                    'id' => 'Testing site in charge Phone',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('test_site_in_charge_email')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Email',
                                    'autocomplete' => 'off',
                                    'id' => 'Testing site in charge Email',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('facility_in_charge_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Name',
                                    'autocomplete' => 'off',
                                    'id' => 'Facility in charge Name',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('facility_in_charge_phone')->setAttributes([
                                    'class' => 'form-control checkNum',
                                    'placeholder' => 'Phone',
                                    'autocomplete' => 'off',
                                    'id' => 'Facility in charge Phone',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('facility_in_charge_email')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Email',
                                    'autocomplete' => 'off',
                                    'id' => 'Facility in charge Email',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('facility_id')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Facility Name',
                                    'id' => 'Facility Name',
                                    'onclick' => 'emptyInput(this)',
                                ]);
                                $form->get('profile_picture')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Upload Profile Picture',
                                    'id' => 'Profile Picture',
                                ]);


                                $form->get('submit')->setAttributes([]);


                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>

                                <fieldset>
                                    <legend style="color: #00b3ee">TESTER IDENTIFICATION</legend>
                                    <div class="row">
                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('professional_reg_no')); ?>
                                            <?= $this->formElement($form->get('professional_reg_no')); ?>
                                            <?php // $this->formElementErrors($form->get('professional_reg_no'));
                                            ?>
                                        </div>
                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('profile_picture')); ?>
                                            <?= $this->formFile($form->get('profile_picture')); ?>
                                            <?php // $this->formElementErrors($form->get('profile_picture'));
                                            ?>
                                            <div class="box-body"> <code>!</code>Please make sure profile image size of: <code>600x600.</code> </div>
                                        </div>
                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('first_name')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('first_name')); ?>
                                            <?php // $this->formElementErrors($form->get('first_name'));
                                            ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('last_name')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('last_name')); ?>
                                            <?php // $this->formElementErrors($form->get('last_name'));
                                            ?>
                                        </div>
                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('middle_name')); ?>
                                            <?= $this->formElement($form->get('middle_name')); ?>
                                            <?php // $this->formElementErrors($form->get('middle_name'));
                                            ?>
                                        </div>
                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('country')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('country')); ?>
                                            <?php // $this->formElementErrors($form->get('country'));
                                            ?>
                                        </div>
                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('region')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('region')); ?>
                                            <?php // $this->formElementErrors($form->get('region'));
                                            ?>
                                        </div>

                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('district')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('district')); ?>
                                            <?php // $this->formElementErrors($form->get('district'));
                                            ?></div>

                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('type_vih_test')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('type_vih_test')); ?>
                                            <?php // $this->formElementErrors($form->get('type_vih_test'));
                                            ?>
                                        </div>
                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('phone')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('phone')); ?>
                                            <?php // $this->formElementErrors($form->get('phone'));
                                            ?>
                                        </div>
                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('email')); ?><span class="mandatory testerEmailMandatorySection" style="display:none;">*</span>
                                            <?= $this->formElement($form->get('email')); ?>
                                            <?php // $this->formElementErrors($form->get('email'));
                                            ?>
                                        </div>
                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('prefered_contact_method')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('prefered_contact_method')); ?>
                                            <?php // $this->formElementErrors($form->get('prefered_contact_method'));
                                            ?>
                                        </div>
                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('current_jod')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('current_jod')); ?>
                                            <?php // $this->formElementErrors($form->get('current_jod'));
                                            ?>
                                        </div>
                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('facility_id')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('facility_id')); ?>
                                            <?php // $this->formElementErrors($form->get('facility_id'));
                                            ?>
                                        </div>

                                        <div class=" form-group col-lg-4">
                                            <div class="input-group">
                                                <?= $this->formLabel($form->get('time_worked')); ?><span class="mandatory">*</span>
                                                <?= $this->formElement($form->get('time_worked')); ?>
                                                <?php // $this->formElementErrors($form->get('time_worked'));
                                                ?>
                                                <div class="input-group-btn">
                                                    <select class="form-control" style="margin-bottom: -28px; width: 100px;" name="select_time" id="Time" onclick='emptyInput(this)'>
                                                        <option value="">--Select--</option>
                                                        <option value="Years">Year(s)</option>
                                                        <option value="Months">Month(s)</option>
                                                        <option value="Weeks">Week(s)</option>
                                                        <option value="Days">Day(s)</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('username')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('username')); ?>
                                            <?php // $this->formElementErrors($form->get('username'));
                                            ?>
                                        </div>

                                        <div class="form-group col-lg-4">
                                            <?= $this->formLabel($form->get('password')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('password')); ?>
                                            <?php // $this->formElementErrors($form->get('password'));
                                            ?>
                                        </div>
                                    </div>
                                </fieldset>

                                <fieldset>
                                    <legend style="color: #00b3ee">TESTING SITE IN CHARGE</legend>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('test_site_in_charge_name')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('test_site_in_charge_name')); ?>
                                        <?php // $this->formElementErrors($form->get('test_site_in_charge_name'));
                                        ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('test_site_in_charge_phone')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('test_site_in_charge_phone')); ?>
                                        <?php // $this->formElementErrors($form->get('test_site_in_charge_phone'));
                                        ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('test_site_in_charge_email')); ?>
                                        <?= $this->formElement($form->get('test_site_in_charge_email')); ?>
                                        <?php // $this->formElementErrors($form->get('test_site_in_charge_email'));
                                        ?>
                                    </div>
                                </fieldset>

                                <fieldset>


                                    <legend style="color: #00b3ee">FACILITY IN CHARGE </legend>


                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('facility_in_charge_name')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('facility_in_charge_name')); ?>
                                        <?php // $this->formElementErrors($form->get('facility_in_charge_name'));
                                        ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('facility_in_charge_phone')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('facility_in_charge_phone')); ?>
                                        <?php // $this->formElementErrors($form->get('facility_in_charge_phone'));
                                        ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('facility_in_charge_email')); ?>
                                        <?= $this->formElement($form->get('facility_in_charge_email')); ?>
                                        <?php // $this->formElementErrors($form->get('facility_in_charge_email'));
                                        ?>
                                    </div>
                                </fieldset>

                                <fieldset>
                                    <legend style="color: #00b3ee"></legend>
                                    <div class="form-group col-lg-4" style="margin-top: 30px"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                        <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('provider', array('action' => 'index')); ?>">CANCEL</a>
                                    </div>
                                </fieldset>
                                <?php echo $this->form()->closeTag();
                                ?>
                            </form>


                            <div style="margin-top: 25px">

                                <div class="well container">
                                    <div class="row" style="margin-bottom:15px;margin-left:9px;">
                                        <h3>Manage Columns &nbsp;<a href="javascript:void(0)" id="shBtnManageColumns">Show/hide</a></h3>
                                    </div>
                                    <div id="manageColumns">
                                    </div>
                                </div>
                                <table id="provider" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
                                    <thead>
                                        <tr class="allproviders">
                                            <th>Certification Registration No</th>
                                            <th> Professional Registration No (if available)</th>
                                            <th style="width:10%;">Certification ID</th>
                                            <th style="width:10%;">Certification Time</th>
                                            <th style="width:10%;">Tester</th>
                                            <th style="width:10%;">Region</th>
                                            <th style="width:10%;">District</th>
                                            <th style="width:10%;">Type of HIV Test Modality/ Point</th>
                                            <th style="width:10%;">Phone</th>
                                            <th style="width:10%;">E-mail</th>
                                            <th style="width:10%;">Prefered Contact Method</th>
                                            <th style="width:10%;">Current Job</th>
                                            <th>Time worked as tester</th>
                                            <th style="width:10%;">UserName</th>
                                            <th style="width:10%;">Facility Name</th>
                                            <th style="width:10%;">Facility Address</th>
                                            <th>Testing Site In charge Name</th>
                                            <th>Testing Site In charge Phone</th>
                                            <th>Testing Site In charge Email</th>
                                            <th>Facility In charge Name </th>
                                            <th>Facility In charge Phone</th>
                                            <th>Facility In charge Email</th>

                                        </tr>


                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td colspan="22" class="dataTables_empty">Loading data from server</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>

</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script>
    var time = "";
</script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/provider.js'); ?>"></script>
<script>
    oTable = null;
    $(document).ready(function() {
        /*
            The below snippet dynamically list toggleable button.
            It can show/hide columns
        */
        var listOfColumns = '';
        $('tr.allproviders').each(function() {
            $(this).find('th').each(function(index) {
                listOfColumns += '<a class="toggle-vis btn btn-primary btn-sm" data-column="' + index + '" onclick="toggleBtnClass(this)"> <span class="btn-label"><i class="glyphicon glyphicon-ok"></i></span> ' + $(this).text() + '</a> &nbsp;'
            });
        });
        $("#manageColumns").html(listOfColumns);
        /* Ends Here */

        //    var table = $('#provider').DataTable({
        //         "aProcessing": true,
        //         "aServerSide": true,
        //         "aaSorting": [],
        //     });

        oTable = $('#provider').dataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "bStateSave": true,
            "aoColumns": [
                <?php echo $editAction; ?>
            ],
            "aaSorting": [
                [0, "asc"]
            ],
            "sAjaxSource": "<?php echo $this->url('provider', array('action' => 'get-provider-data')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });


        $('a.toggle-vis').on('click', function(e) {
            e.preventDefault();
            // Get the column API object
            var column = table.column($(this).attr('data-column'));
            // Toggle the visibility
            column.visible(!column.visible());
            $("#provider_wrapper").css("overflow-x", "scroll");
        });
        $("#manageColumns").hide();
        $("#shBtnManageColumns").click(function() {
            $("#manageColumns").toggle('fast', 'linear');
        });

    });

    /* Toggles Color of button */
    function toggleBtnClass(btnObj) {
        $(btnObj).toggleClass("btn-default");
        var children = btnObj.childNodes;
        var iconTag = children[1].firstChild;
        $(iconTag).toggleClass("glyphicon-remove");
    }

    function showRegion(str) {
        if (str == "") {
            document.getElementById("Region").innerHTML = "<option value=''>Please Choose a Country First</option>";
            document.getElementById("District").innerHTML = "<option value=''>Please Choose a Region First</option>";
            document.getElementById("Facility Name").innerHTML = "<option value=''>Please Choose a District First</option>";
            return false;
        } else {
            $.post("<?php echo $this->url('provider', array('action' => 'region')); ?>", {
                    q: str
                },
                function(data) {
                    document.getElementById("Region").innerHTML = data;
                    document.getElementById("District").innerHTML = "<option value=''>Please Choose a Region First</option>";
                    document.getElementById("Facility Name").innerHTML = "<option value=''>Please Choose a District First</option>";
                });
        }
        //if (str == "") {
        //    document.getElementById("Region").innerHTML = "Please Choose a Country First";
        //    return;
        //} else {
        //    if (window.XMLHttpRequest) {
        //        // code for IE7+, Firefox, Chrome, Opera, Safari
        //        xmlhttp = new XMLHttpRequest();
        //    } else {
        //        // code for IE6, IE5
        //        xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
        //    }
        //    xmlhttp.onreadystatechange = function () {
        //        if (this.readyState == 4 && this.status == 200) {
        //            document.getElementById("Region").innerHTML = this.responseText;
        //            document.getElementById("District").innerHTML = "<option value=''>Please Choose a Region First</option>";
        //            document.getElementById("Facility Name").innerHTML = "<option value=''>Please Choose a District First</option>";
        //        }
        //    };
        //    xmlhttp.open("GET", "< ?php echo $this->url('provider', array('action' => 'region')); ?>?q=" + str, true);
        //    xmlhttp.send();
        //}
    }

    function showDistrict(str) {
        if (str == "") {
            document.getElementById("District").innerHTML = "Please Choose a Region First";
            return;
        } else {
            if (window.XMLHttpRequest) {
                // code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            } else {
                // code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("District").innerHTML = this.responseText;
                    document.getElementById("Facility Name").innerHTML = "<option value=''>Please Choose a District First</option>";
                }
            };
            xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'district')); ?>?q=" + str, true);
            xmlhttp.send();
        }
    }

    function showFacilities(str) {
        if (str == "") {
            document.getElementById("Facility Name").innerHTML = "Please Choose a District First";
            return;
        } else {
            if (window.XMLHttpRequest) {
                // code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            } else {
                // code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("Facility Name").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'facility')); ?>?q=" + str, true);
            xmlhttp.send();
        }
    }

    function myFunction() {
        // Declare variables
        var input, filter, table, tr, td, i, last, first, middle;
        last = document.getElementById("Last Name").value.trim();
        first = document.getElementById("First Name").value.trim();
        middle = document.getElementById("Middle Name").value.trim();
        if (last && !first && !middle) {
            input = last;
        } else if (last && first && !middle) {
            input = last + ' ' + first;

        } else if (last && first && middle) {
            input = last + ' ' + first + ' ' + middle;

        }

        filter = input.toUpperCase();
        table = document.getElementById("provider");
        tr = table.getElementsByTagName("tr");

        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[3];

            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

    function managePreferedContactEmail(preferedContactMethod) {
        if ($.trim(preferedContactMethod) == 'Email') {
            $('.testerEmailMandatorySection').show();
        } else {
            $('.testerEmailMandatorySection').hide();
        }
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
        var className = $(obj).attr('class').split(' ')[1];
        var checkValue = $('.' + className).val();
        if ($.trim(checkValue) != '') {
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
                    tableName: tableName,
                    fieldName: fieldName,
                    value: checkValue,
                    fnct: fnct
                },
                function(data) {
                    if (data > 0) {
                        alert(msg);
                        duplicateName = false;
                        $('.' + className).val('');
                    } else {
                        duplicateName = true;
                    }
                });
        }
    }
</script>
