<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">
        <h2>Edit Tester</h2>
        <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >

                            <form action="<?php $this->url('provider', array('action' => 'edit', 'id' => $this->id)); ?>" name="form" method="post" onsubmit="return validateForm()">

                                <?php
                                $form->prepare();

                                $form->get('professional_reg_no')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Professional Registration No ',
                                    'autocomplete' => 'off',
                                ]);
                                $form->get('last_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Last Name',
                                    'autocomplete' => 'off',
                                    'id' => 'Last Name',
                                    'onclick' => 'emptyInput(this)',
                                ]);

                                $form->get('first_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'First name',
                                    'autocomplete' => 'off',
                                    'id' => 'First Name',
                                    'onclick' => 'emptyInput(this)',
                                ]);

                                $form->get('middle_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Middle name',
                                    'id' => 'Middle Name',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('region')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Region',
                                    'autocomplete' => 'off',
                                    'id' => 'Region',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'showDistrict(this.value)',
                                ]);
                                $distict_id = (int) $this->district_id;
                                $form->get('district')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'District',
                                    'id' => 'District',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'showFacilities(this.value)',
                                    'options' => [$distict_id => $this->district_name]
                                ]);

                                $form->get('type_vih_test')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Type of VIH Test',
                                    'id' => 'Type of VIH Test Modality/Point',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('phone')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Phone',
                                    'id' => 'Tester Phone Number',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)'
                                ]);
                                $form->get('email')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Email',
                                    'autocomplete' => 'off',
                                    'id' => 'Tester Email',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('prefered_contact_method')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Prefered Contact Method',
                                    'id' => 'Prefered Contact Method',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('current_jod')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Current Job',
                                    'id' => 'Current Job Title',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('time_worked')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Time worked as tester',
                                    'autocomplete' => 'off',
                                    'id' => 'Time worked as tester',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('test_site_in_charge_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Name',
                                    'autocomplete' => 'off',
                                    'id' => 'Testing site in charge Name',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('test_site_in_charge_phone')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Phone',
                                    'id' => 'Testing site in charge Phone',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('test_site_in_charge_email')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Email',
                                    'autocomplete' => 'off',
                                    'id' => 'Testing site in charge Email',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('facility_in_charge_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Name',
                                    'autocomplete' => 'off',
                                    'id' => 'Facility in charge Name',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('facility_in_charge_phone')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Phone',
                                    'autocomplete' => 'off',
                                    'id' => 'Facility in charge Phone',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('facility_in_charge_email')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Email',
                                    'autocomplete' => 'off',
                                    'id' => 'Facility in charge Email',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('facility_id')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Facility Name',
                                    'id' => 'Facility Name',
                                    'onclick' => 'emptyInput(this)',
                                    'options' => [$this->facility_id => $this->facility_name]
                                ]);


                                $form->get('submit')->setAttributes([
                                ]);


                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>

                                <fieldset>


                                    <legend style="color: #00b3ee">TESTER IDENTIFICATION</legend>


                                    <div class="form-group col-lg-4"> 
                                        <?= $this->formLabel($form->get('professional_reg_no')); ?>
                                        <?= $this->formElement($form->get('professional_reg_no')); ?>
                                        <?= $this->formElementErrors($form->get('professional_reg_no')); ?>
                                    </div>
                                    <div class="form-group col-lg-4"> 
                                        <?= $this->formLabel($form->get('last_name')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('last_name')); ?>
                                        <?= $this->formElementErrors($form->get('last_name')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('first_name')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('first_name')); ?>
                                        <?= $this->formElementErrors($form->get('first_name')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('middle_name')); ?>
                                        <?= $this->formElement($form->get('middle_name')); ?>
                                        <?= $this->formElementErrors($form->get('middle_name')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('region')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('region')); ?>
                                        <?= $this->formElementErrors($form->get('region')); ?>
                                    </div>

                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('district')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('district')); ?>
                                        <?= $this->formElementErrors($form->get('district')); ?></div>

                                    <div class="form-group col-lg-4">  
                                        <?= $this->formLabel($form->get('type_vih_test')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('type_vih_test')); ?>
                                        <?= $this->formElementErrors($form->get('type_vih_test')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('phone')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('phone')); ?>
                                        <?= $this->formElementErrors($form->get('phone')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('email')); ?>
                                        <?= $this->formElement($form->get('email')); ?>
                                        <?= $this->formElementErrors($form->get('email')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('prefered_contact_method')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('prefered_contact_method')); ?>
                                        <?= $this->formElementErrors($form->get('prefered_contact_method')); ?>       
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('current_jod')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('current_jod')); ?>
                                        <?= $this->formElementErrors($form->get('current_jod')); ?>
                                    </div>
                                    <div class="form-group col-lg-3">
                                        <?= $this->formLabel($form->get('facility_id')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('facility_id')); ?>
                                        <?= $this->formElementErrors($form->get('facility_id')); ?>
                                    </div>


                                    <div class = " form-group col-lg-4">
                                        <div class = "input-group">
                                            <?= $this->formLabel($form->get('time_worked')); ?><span class="mandatory">*</span>
                                            <?= $this->formElement($form->get('time_worked')); ?>
                                            <?= $this->formElementErrors($form->get('time_worked')); ?>
                                            <div class = "input-group-btn">
                                                <select class="form-control" style="margin-bottom: -28px; width: 100px;" name="select_time" id="Time" onclick = 'emptyInput(this)'> 
                                                    <option value="">--Select--</option>
                                                    <option id="Years" value="Years">Year(s)</option>
                                                    <option id="Months" value="Months">Month(s)</option>
                                                    <option id="Weeks"value="Weeks">Week(s)</option>
                                                    <option id="Days" value="Days">Day(s)</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>

                                <fieldset>


                                    <legend style="color: #00b3ee">TESTING SITE IN CHARGE</legend>


                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('test_site_in_charge_name')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('test_site_in_charge_name')); ?>
                                        <?= $this->formElementErrors($form->get('test_site_in_charge_name')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('test_site_in_charge_phone')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('test_site_in_charge_phone')); ?>
                                        <?= $this->formElementErrors($form->get('test_site_in_charge_phone')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('test_site_in_charge_email')); ?>
                                        <?= $this->formElement($form->get('test_site_in_charge_email')); ?>
                                        <?= $this->formElementErrors($form->get('test_site_in_charge_email')); ?>
                                    </div>
                                </fieldset>

                                <fieldset>


                                    <legend style="color: #00b3ee">FACILITY IN CHARGE </legend>


                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('facility_in_charge_name')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('facility_in_charge_name')); ?>
                                        <?= $this->formElementErrors($form->get('facility_in_charge_name')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('facility_in_charge_phone')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('facility_in_charge_phone')); ?>
                                        <?= $this->formElementErrors($form->get('facility_in_charge_phone')); ?>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <?= $this->formLabel($form->get('facility_in_charge_email')); ?>
                                        <?= $this->formElement($form->get('facility_in_charge_email')); ?>
                                        <?= $this->formElementErrors($form->get('facility_in_charge_email')); ?>
                                    </div>
                                </fieldset>

                                <fieldset>
                                    <legend style="color: #00b3ee"></legend>



                                    <div class="form-group col-lg-4" style="margin-top: 30px"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                        <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('provider', array('action' => 'index')); ?>" >CANCEL</a> </div>
                                </fieldset>
                                <?php echo $this->form()->closeTag();
                                ?>                         
                            </form>


                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>

</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script>
                                                var time = "<?php echo $time2; ?>";
</script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/provider.js'); ?>"></script>

<script>
//    document.getElementById("Region").addEventListener("load", showDistrict(document.getElementById("Region").value));
                                                    function showDistrict(str) {

                                                        if (str == "") {
                                                            document.getElementById("District").innerHTML = "";
                                                            return;
                                                        } else {
                                                            if (window.XMLHttpRequest) {
                                                                // code for IE7+, Firefox, Chrome, Opera, Safari
                                                                xmlhttp = new XMLHttpRequest();
                                                            } else {
                                                                // code for IE6, IE5
                                                                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                                                            }
                                                            xmlhttp.onreadystatechange = function () {
                                                                if (this.readyState == 4 && this.status == 200) {
                                                                    document.getElementById("District").innerHTML = this.responseText;
                                                                }
                                                            };
                                                            xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'district')); ?>?q=" + str, true);
                                                            xmlhttp.send();
                                                        }
                                                    }

                                                    function showFacilities(str) {

                                                        if (str == "") {
                                                            document.getElementById("Facility Name").innerHTML = "";
                                                            return;
                                                        } else {
                                                            if (window.XMLHttpRequest) {
                                                                // code for IE7+, Firefox, Chrome, Opera, Safari
                                                                xmlhttp = new XMLHttpRequest();
                                                            } else {
                                                                // code for IE6, IE5
                                                                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                                                            }
                                                            xmlhttp.onreadystatechange = function () {
                                                                if (this.readyState == 4 && this.status == 200) {
                                                                    document.getElementById("Facility Name").innerHTML = this.responseText;
                                                                }
                                                            };
                                                            xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'facility')); ?>?q=" + str, true);
                                                            xmlhttp.send();
                                                        }
                                                    }


                                                   

</script>                              
