<div class="widget widget-fullwidth widget-small" style="padding:5px;">

            <table id="testReportTable" class="datatables table table-bordered table-responsive table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                <thead class="frezz">
                <tr class="allrecertifications">
                        <th style="width:10%;">Tester</th>
                        <th style="width:10%;">Professional Registration No.
                        <!-- <br>(if available) -->
                        </th>
                        <th style="width:10%;">Region</th>
                        <th style="width:10%;">District</th>
                        <th style="width:10%;">Facility</th>
                        <th style="width:10%;">Phone</th>
                        <th style="width:10%;">E-mail</th>
                        <th style="width:10%;">Type HIV testing modality/point</th>
                        <th style="width:10%;">Certification Registration No.</th>
                        <th style="width:10%;">Certification ID</th>
                    </tr>
                </thead>
                <tbody class="frezz">

                    <?php foreach ($this->result as $provider) {
                            // \Zend\Debug\Debug::dump($provider);die;
                    ?>
                        <tr>

                            <td><?php echo $this->escapeHtml($provider['first_name'] . ' ' . $provider['last_name ']); ?></td>
                            <td><?php echo $this->escapeHtml($provider['professional_reg_no']); ?></td>
                            <td><?php echo $this->escapeHtml($provider['region_name']); ?></td>
                            <td><?php echo $this->escapeHtml($provider['district_name']); ?></td>
                            <td><?php echo $this->escapeHtml($provider['facility_name']); ?></td>
                            <td><?php echo $this->escapeHtml($provider['phone']); ?></td>
                            <td><?php echo $this->escapeHtml($provider['email']); ?></td>
                            <td><?php echo $this->escapeHtml($provider['type_vih_test']); ?></td>
                            <td><?php echo $this->escapeHtml($provider['certification_reg_no']); ?></td>
                            <td><?php echo $this->escapeHtml($provider['certification_id']); ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>