<?php
use Zend\Debug\Debug;
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<style>
    #shBtnManageColumns {
        font-size: 17px;
        font-weight: 600;
    }
    .frezz th:last-child,
    .frezz td:last-child {
        position: sticky !important;
        right: -1%;
        z-index: 1;
        background-color: white;
        padding: 18px !important;
    }
    .show-msg{
        display: block;
        color: rgb(255, 0, 0);
        margin: auto;
        font-size: small;
        text-align: center;
        padding: 15px;
        background: antiquewhite;
        border-radius: 10px;
    }
</style>
<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-8">
                <h2>Import Testers</h2>
            </div>
            <div class="col-sm-4 ">
                <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'index')) {  ?>
                    <a href="<?php echo $this->url('provider', array('action' => 'index')); ?>" class="btn btn-success pull-right" style="margin-left: 5px;"><i class="fa fa-list"></i>&nbsp;List of Testers</a>
                <?php }  ?>
            </div>
        </div>
    </div>
    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form action="<?php $this->url('provider', array('action' => 'import_excel')); ?>" name="form" method="post" onsubmit="return validateForm()" enctype="multipart/form-data">
                                <fieldset>
                                    <legend style="color: #00b3ee">Upload Tester File </legend>
                                    <div class="form-group col-lg-4">
                                        <input class="form-control isRequired" type="file" name="tester_excel" title="Please Select File" />
                                    </div>
                                    <div class="form-group col-lg-8">
                                        <?php if(file_exists(UPLOAD_PATH.DIRECTORY_SEPARATOR.'tester'.DIRECTORY_SEPARATOR.'model.xlsx')){ ?> 
                                            <div class="form-group col-lg-4">
                                                <a href="/uploads/tester/model.xlsx" class="btn btn-space btn-danger"><i class="fa fa-download"></i>&nbsp;DOWNLOAD FORMAT</a>
                                            </div>
                                        <?php }?>
                                        <div class="form-group col-lg-4">
                                            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                            <a class="btn btn-space btn-default" role="button" href="<?php echo $this->url('provider', array('action' => 'index')); ?>">CANCEL</a> 
                                        </div>
                                        <div class="form-group col-lg-4">
                                            <span style="display: none;" class="show-msg"></span>
                                        </div>
                                    </div>
                                </fieldset>
                                <fieldset>
                                    <?php if(isset($result) && count($result) > 0){ ?>
                                        <table id="resultTable" class="table table-bordered table-responsive table-condensed table-striped table-hover table-fw-widget dataTable no-footer">
                                            <thead class="frezz">
                                                <tr>
                                                    <th>REG NO</th>
                                                    <th>FIRST NAME</th>
                                                    <th>LAST NAME</th>
                                                    <th>PROVINCE</th>
                                                    <th>DISTRICT</th>
                                                    <th>TYPE OF HIV TEST MODALITY/POINT</th>
                                                    <th>PHONE</th>
                                                    <th>EMAIL</th>
                                                    <th>CURRENT JOB TITLE</th>
                                                    <th>FACILITY NAME</th>
                                                    <?php $import = false; if (isset($acl) && $acl->isAllowed($role, "Certification\Controller\Provider", "import-manually")) { $import = true;?>
                                                        <th>ACTION</th>
                                                    <?php } ?>
                                                </tr>
                                            </thead>
                                            <tbody class="frezz">
                                                <?php foreach($result['data'] as $key => $row){ ?>
                                                    <tr class="row<?php echo ($key+1);?>">
                                                        <td>
                                                            <span name="rows[]" id="time<?php echo ($key+1);?>" style="display: none;"><?php echo $row['time_worked'];?></span>
                                                            <span name="rows[]" id="username<?php echo ($key+1);?>" style="display: none;"><?php echo $row['username'];?></span>
                                                            <span name="rows[]" id="password<?php echo ($key+1);?>" style="display: none;"><?php echo $row['password'];?></span>
                                                            <span name="rows[]" id="testName<?php echo ($key+1);?>" style="display: none;"><?php echo $row['test_site_in_charge_name'];?></span>
                                                            <span name="rows[]" id="testPhone<?php echo ($key+1);?>" style="display: none;"><?php echo $row['test_site_in_charge_phone'];?></span>
                                                            <span name="rows[]" id="testEmail<?php echo ($key+1);?>" style="display: none;"><?php echo $row['test_site_in_charge_email'];?></span>
                                                            <span name="rows[]" id="facilityName<?php echo ($key+1);?>" style="display: none;"><?php echo $row['facility_in_charge_name'];?></span>
                                                            <span name="rows[]" id="facilityPhone<?php echo ($key+1);?>" style="display: none;"><?php echo $row['facility_in_charge_phone'];?></span>
                                                            <span name="rows[]" id="facilityEmail<?php echo ($key+1);?>" style="display: none;"><?php echo $row['facility_in_charge_email'];?></span>
                                                            <span name="rows[]" id="moddleName<?php echo ($key+1);?>" style="display: none;"><?php echo $row['middle_name'];?></span>
                                                            <input type="text" name="rows[]" id="regNo<?php echo ($key+1);?>" value="<?php echo $row['professional_reg_no'];?>" class="form-control"/></span></td>
                                                        <td><span name="rows[]" id="firstName<?php echo ($key+1);?>"><?php echo $row['first_name'];?></span></td>
                                                        <td><span name="rows[]" id="lastName<?php echo ($key+1);?>"><?php echo $row['last_name'];?></span></td>
                                                        <td><span name="rows[]" id="region<?php echo ($key+1);?>"><?php echo $row['region'];?></span></td>
                                                        <td><span name="rows[]" id="district<?php echo ($key+1);?>"><?php echo $row['district'];?></span></td>
                                                        <td><span name="rows[]" id="typeVihTest<?php echo ($key+1);?>"><?php echo $row['type_vih_test'];?></span></td>
                                                        <td><span name="rows[]" id="phone<?php echo ($key+1);?>"><?php echo $row['phone'];?></span></td>
                                                        <td><input name="rows[]" id="email<?php echo ($key+1);?>" type="text" class="form-control" value="<?php echo $row['email'];?>"/></td>
                                                        <td><span name="rows[]" id="job<?php echo ($key+1);?>"><?php echo $row['current_jod'];?></span></td>
                                                        <td><input name="rows[]" id="facility<?php echo ($key+1);?>" type="text" class="form-control" value="<?php echo $row['facility_id'];?>"/></td>
                                                        <?php if($import){ ?>
                                                            <td><a href="javascript:void(0);" data-check="true" onclick="insertManual(this,<?php echo ($key+1);?>)" class="btn btn-sm btn-space btn-danger"><i class="fa fa-plus"></i>&nbsp;Insert</a></td>
                                                        <?php }?>
                                                    </tr>
                                                <?php }?>
                                            </tbody>
                                        </table>
                                    <?php }?>
                                </fieldset>
                                <?php echo $this->form()->closeTag(); ?>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script>
    $(document).ready(function () {
        var table = $('#resultTable').DataTable({
            "aProcessing": true,
            "aServerSide": true,
            "aaSorting": [],
        });
    });

    function insertManual(obj,no){
        if($(obj).attr('data-check') != 'false'){

            $.post("<?php echo $this->url('provider',array('action'=>'import-manually')); ?>",{
                regNo:$('#regNo'+no).val(),
                first:$('#firstName'+no).text(),
                last:$('#lastName'+no).text(),
                middle:$('#moddleName'+no).text(),
                region:$('#region'+no).text(),
                district:$('#district'+no).text(),
                vih:$('#typeVihTest'+no).text(),
                phone:$('#phone'+no).text(),
                email:$('#email'+no).val(),
                job:$('#job'+no).text(),
                facility:$('#facility'+no).val(),
                time:$('#time'+no).text(),
                username:$('#username'+no).text(),
                password:$('#password'+no).text(),
                testName:$('#testName'+no).text(),
                testPhone:$('#testPhone'+no).text(),
                testEmail:$('#testEmail'+no).text(),
                facilityName:$('#facilityName'+no).text(),
                facilityPhone:$('#facilityPhone'+no).text(),
                facilityEmail:$('#facilityEmail'+no).text()
            },
            function(data) {
                if(data == '' || data == false || data == null){
                    $(obj).attr('disabled',false);
                    $('.show-msg').text('Dublicate record not imported');
                    $('.show-msg').css('color','red');
                    $('.show-msg').css('background','antiquewhite')
                    $('.show-msg').show(500);
                } else{
                    $('.show-msg').text('Imported successfully');
                    $('.show-msg').css('color','green');
                    $('.show-msg').css('background','lightgreen')
                    $('.row'+no).css('background-color','rgba(53, 220, 112, 0.25)')
                    $(obj).attr('data-check','false');
                    $(obj).removeClass('btn-danger');
                    $(obj).addClass('btn-default');
                    $(obj).attr('disabled',true);
                }
            });
        }
    }
</script>