<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<style>
    #shBtnManageColumns{
        font-size: 17px;
        font-weight: 600;
    }
</style>
<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-8">
                <h2>Add a new Tester</h2>
            </div>

            <div class="col-sm-4 ">
                <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'index')) {  ?>
                <a href="<?php echo $this->url('provider', array('action' => 'index')); ?>" class="btn btn-success pull-right" style="margin-left: 5px;"><i class="fa fa-list"></i>&nbsp;List of Testers</a>
                <?php }  ?>

            </div>
        </div>


        <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
    </div>

    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >
                            <form action="<?php $this->url('provider', array('action' => 'import_excel')); ?>" name="form" method="post" onsubmit="return validateForm()">

                                <fieldset>


                                    <legend style="color: #00b3ee">Upload Tester </legend>

                                    <div class="form-group col-lg-4">
                                        <input class="form-control isRequired" type="file" name="tester_excel"  title="Please Select File"/>
                                    </div>
                                    <div class="form-group col-lg-8">
                                    
                                    <div class="form-group col-lg-4"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                        <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('provider', array('action' => 'index')); ?>" >CANCEL</a> </div>
                                    </div>
                                </fieldset>

                                <fieldset>
                                   
                                </fieldset>
                                <?php echo $this->form()->closeTag();
                                ?>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>

</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>

