<?php
use Zend\Debug\Debug;
use Zend\Session\Container;
// Debug::dump($result);die;
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
$mandatory = (isset($result['data']['mandatory']) && count($result['data']['mandatory']) > 0);
$duplicate = (isset($result['data']['duplicate']) && count($result['data']['duplicate']) > 0);
$imported = (isset($result['data']['imported']) && count($result['data']['imported']) > 0);
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<style>
    #shBtnManageColumns {
        font-size: 17px;
        font-weight: 600;
    }
    /* .frezz th:last-child,
    .frezz td:last-child {
        position: sticky !important;
        right: -1%;
        z-index: 1;
        background-color: white;
        padding: 18px !important;
    } */
    .show-msg{
        display: block;
        color: rgb(255, 0, 0);
        margin: auto;
        font-size: small;
        text-align: center;
        padding: 15px;
        background: antiquewhite;
        border-radius: 10px;
    }
    .alert {
        padding-left: 30px;
        margin-left: 15px;
        position: relative;
    }
    .alert-info {
        color: #31708f;
        background-color: #d9edf7;
        border-color: #bce8f1;
    }
    .alert-dismissable {
        padding-right: 35px;
    }
    .alert {
        padding: 15px;
        margin-bottom: 20px;
        border: 1px solid transparent;
        border-radius: 4px;
    }
    .alert > .fa, .alert > .glyphicon {
        position: absolute;
        left: -15px;
        top: -15px;
        width: 35px;
        height: 35px;
        -webkit-border-radius: 50%;
        -moz-border-radius: 50%;
        border-radius: 50%;
        line-height: 35px;
        text-align: center;
        background: inherit;
        border: inherit;
    }
/*     li.nav-item:hover {
        background: #d4e7f5;
        color: white !important;
    } */
    /* .nav-tabs > li a{
        color: white;
    } */
    /* .nav-tabs > li a:hover {
        background: transparent;
        color: #ffffff;
    } */
</style>
<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-8">
                <h2>Import Testers</h2>
            </div>
            <div class="col-sm-4 ">
                <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'index')) {  ?>
                    <a href="<?php echo $this->url('provider', array('action' => 'index')); ?>" class="btn btn-success pull-right" style="margin-left: 5px;"><i class="fa fa-list"></i>&nbsp;List of Testers</a>
                <?php }  ?>
            </div>
        </div>
    </div>
    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form action="<?php $this->url('provider', array('action' => 'import_excel')); ?>" name="form" method="post" onsubmit="return validateForm()" enctype="multipart/form-data">
                                <fieldset>
                                    <legend style="color: #00b3ee">Upload Tester File </legend>
                                    <div class="form-group col-lg-4">
                                        <input class="form-control isRequired" type="file" name="tester_excel" title="Please Select File" />
                                    </div>
                                    <div class="form-group col-lg-8">
                                        <?php if(file_exists(UPLOAD_PATH.DIRECTORY_SEPARATOR.'tester'.DIRECTORY_SEPARATOR.'model.xlsx')){ ?> 
                                            <div class="form-group col-lg-4">
                                                <a href="/uploads/tester/model.xlsx" class="btn btn-space btn-danger"><i class="fa fa-download"></i>&nbsp;DOWNLOAD FORMAT</a>
                                            </div>
                                        <?php }?>
                                        <div class="form-group col-lg-4">
                                            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                            <a class="btn btn-space btn-default" role="button" href="<?php echo $this->url('provider', array('action' => 'index')); ?>">CANCEL</a> 
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                            <?php if((isset($result['data']['mandatory']) && count($result['data']['mandatory']) > 0) || (isset($result['data']['duplicate']) && count($result['data']['duplicate']) > 0) || (isset($result['data']['imported']) && count($result['data']['imported']) > 0)){ ?>
                            <fieldset>
                                <div class="alert alert-dismissable">
                                    <div>Total number of records in the uploaded file : <?php echo (count($result['data']['mandatory'])+count($result['data']['duplicate'])+count($result['data']['imported']));?></div>
                                </div>
                                <ul class="nav nav-tabs" id="importTesterTab" role="tablist">
                                    <?php if(isset($result['data']['mandatory']) && count($result['data']['mandatory']) > 0){?>
                                    <li class="nav-item active" style="background: #ff00004a;color:white;">
                                        <a class="nav-link active" id="mandatory-tab" data-toggle="tab" href="#mandatory-tabpanel" role="tab" aria-controls="mandatory-tabpanel" aria-selected="false" >Not Imported - Mandatory Fields Missing (<?php echo count($result['data']['mandatory']);?>)</a>
                                    </li>
                                    <?php } if(isset($result['data']['duplicate']) && count($result['data']['duplicate']) > 0){ ?>
                                    <li class="nav-item" style="background: #ff00004a;color:white;">
                                        <a class="nav-link" id="duplicates-tab" data-toggle="tab" href="#duplicates-tabpanel" role="tab" aria-controls="duplicates-tabpanel" aria-selected="true" >Not Imported - Duplicates (<?php echo count($result['data']['duplicate']);?>)</a>
                                    </li>
                                    <?php } if(isset($result['data']['imported']) && count($result['data']['imported']) > 0){ ?>
                                    <li class="nav-item" style="background: #01ff0570;color:white;">
                                        <a class="nav-link" id="imported-tab" data-toggle="tab" href="#imported-tabpanel" role="tab" aria-controls="imported-tabpanel" aria-selected="false">Imported (<?php echo count($result['data']['imported']);?>)</a>
                                    </li>
                                    <?php } ?>
                                </ul>
                                <div class="tab-content" id="importTesterContent">
                                    <?php if(isset($result['data']['mandatory']) && count($result['data']['mandatory']) > 0){ ?>
                                        <div class="tab-pane <?php echo ($mandatory)?'active':'';?>" id="mandatory-tabpanel" role="tabpanel" aria-labelledby="mandatory-tab">
                                            <div class="alert alert-info alert-dismissable"><i class="fa fa-info"></i>
                                                <div>The following testers were NOT imported. Some key or Mandatory fields are missing in following testers. Please edit the excel and try again.</div>
                                            </div>
                                            <table id="mandatoryTable" class="table table-bordered table-responsive table-striped table-hover dataTable">
                                                <thead class="frezz">
                                                    <tr>
                                                        <th>REG NO</th>
                                                        <th>FIRST NAME</th>
                                                        <th>LAST NAME</th>
                                                        <th>PROVINCE</th>
                                                        <th>DISTRICT</th>
                                                        <th>TYPE OF HIV TEST MODALITY/POINT</th>
                                                        <th>PHONE</th>
                                                        <th>EMAIL</th>
                                                        <th>CURRENT JOB TITLE</th>
                                                        <th>FACILITY NAME</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php foreach($result['data']['mandatory'] as $key => $row){ ?>
                                                        <tr class="row<?php echo ($key+1);?>">
                                                            <td><span name="rows[]" id="regNo<?php echo ($key+1);?>"><?php echo $row['professional_reg_no'];?></span>
                                                            <td><span name="rows[]" id="firstName<?php echo ($key+1);?>"><?php echo $row['first_name'];?></span></td>
                                                            <td><span name="rows[]" id="lastName<?php echo ($key+1);?>"><?php echo $row['last_name'];?></span></td>
                                                            <td><span name="rows[]" id="region<?php echo ($key+1);?>"><?php echo $row['region'];?></span></td>
                                                            <td><span name="rows[]" id="district<?php echo ($key+1);?>"><?php echo $row['district'];?></span></td>
                                                            <td><span name="rows[]" id="typeVihTest<?php echo ($key+1);?>"><?php echo $row['type_vih_test'];?></span></td>
                                                            <td><span name="rows[]" id="phone<?php echo ($key+1);?>"><?php echo $row['phone'];?></span></td>
                                                            <td><span name="rows[]" id="email<?php echo ($key+1);?>"><?php echo $row['email'];?></td>
                                                            <td><span name="rows[]" id="job<?php echo ($key+1);?>"><?php echo $row['current_jod'];?></span></td>
                                                            <td><span name="rows[]" id="facility<?php echo ($key+1);?>"><?php echo $row['facility_id'];?></td>
                                                        </tr>
                                                    <?php }?>
                                                </tbody>
                                            </table>
                                        </div>
                                    <?php } if(isset($result['data']['duplicate']) && count($result['data']['duplicate']) > 0){ 
                                        $active = '';
                                        if(!$mandatory){
                                            if(!$duplicate){
                                                if($imported){
                                                    $active = 'active';
                                                }
                                            }
                                        }?>
                                        <div class="tab-pane <?php echo $active;?>" id="duplicates-tabpanel" role="tabpanel" aria-labelledby="duplicates-tab">
                                            <div class="alert alert-info alert-dismissable"><i class="fa fa-info"></i>
                                                <div>The following testers were NOT imported. Some of the testers information is repeated. Please edit the excel and try again. You can ignore this list if you added these testers by mistake.</div>
                                            </div>    
                                            <table id="duplicatesTable" class="table table-bordered table-responsive table-striped table-hover dataTable">
                                                <thead class="frezz">
                                                    <tr>
                                                        <th>REG NO</th>
                                                        <th>FIRST NAME</th>
                                                        <th>LAST NAME</th>
                                                        <th>PROVINCE</th>
                                                        <th>DISTRICT</th>
                                                        <th>TYPE OF HIV TEST MODALITY/POINT</th>
                                                        <th>PHONE</th>
                                                        <th>EMAIL</th>
                                                        <th>CURRENT JOB TITLE</th>
                                                        <th>FACILITY NAME</th>
                                                    </tr>
                                                </thead>
                                                <tbody class="duplicates">
                                                    <?php foreach($result['data']['duplicate'] as $key => $row){ ?>
                                                        <tr class="row<?php echo ($key+1);?>">
                                                            <td><span name="rows[]" id="regNo<?php echo ($key+1);?>"><?php echo $row['professional_reg_no'];?></span>
                                                            <td><span name="rows[]" id="firstName<?php echo ($key+1);?>"><?php echo $row['first_name'];?></span></td>
                                                            <td><span name="rows[]" id="lastName<?php echo ($key+1);?>"><?php echo $row['last_name'];?></span></td>
                                                            <td><span name="rows[]" id="region<?php echo ($key+1);?>"><?php echo $row['region'];?></span></td>
                                                            <td><span name="rows[]" id="district<?php echo ($key+1);?>"><?php echo $row['district'];?></span></td>
                                                            <td><span name="rows[]" id="typeVihTest<?php echo ($key+1);?>"><?php echo $row['type_vih_test'];?></span></td>
                                                            <td><span name="rows[]" id="phone<?php echo ($key+1);?>"><?php echo $row['phone'];?></span></td>
                                                            <td><span name="rows[]" id="email<?php echo ($key+1);?>"><?php echo $row['email'];?></td>
                                                            <td><span name="rows[]" id="job<?php echo ($key+1);?>"><?php echo $row['current_jod'];?></span></td>
                                                            <td><span name="rows[]" id="facility<?php echo ($key+1);?>"><?php echo $row['facility_id'];?></td>
                                                        </tr>
                                                    <?php }?>
                                                </tbody>
                                            </table>
                                        </div>
                                    <?php } if(isset($result['data']['imported']) && count($result['data']['imported']) > 0){ 
                                        $active = '';
                                        if(!$mandatory){
                                            if(!$duplicate){
                                                if($imported){
                                                    $active = 'active';
                                                }
                                            }
                                        }?>
                                        <div class="tab-pane <?php echo $active;?>" id="imported-tabpanel" role="tabpanel" aria-labelledby="imported-tab">
                                            <div class="alert alert-info alert-dismissable"><i class="fa fa-info"></i>
                                                <div>Following testers were imported successfully.</div>
                                            </div>    
                                            <table id="importedTable" class="table table-bordered table-responsive table-striped table-hover dataTable">
                                                <thead class="frezz">
                                                    <tr>
                                                        <th>REG NO</th>
                                                        <th>FIRST NAME</th>
                                                        <th>LAST NAME</th>
                                                        <th>PROVINCE</th>
                                                        <th>DISTRICT</th>
                                                        <th>TYPE OF HIV TEST MODALITY/POINT</th>
                                                        <th>PHONE</th>
                                                        <th>EMAIL</th>
                                                        <th>CURRENT JOB TITLE</th>
                                                        <th>FACILITY NAME</th>
                                                    </tr>
                                                </thead>
                                                <tbody class="imported">
                                                    <?php foreach($result['data']['imported'] as $key => $row){ ?>
                                                        <tr class="row<?php echo ($key+1);?>">
                                                            <td><span name="rows[]" id="regNo<?php echo ($key+1);?>"><?php echo $row['professional_reg_no'];?></span>
                                                            <td><span name="rows[]" id="firstName<?php echo ($key+1);?>"><?php echo $row['first_name'];?></span></td>
                                                            <td><span name="rows[]" id="lastName<?php echo ($key+1);?>"><?php echo $row['last_name'];?></span></td>
                                                            <td><span name="rows[]" id="region<?php echo ($key+1);?>"><?php echo $row['region'];?></span></td>
                                                            <td><span name="rows[]" id="district<?php echo ($key+1);?>"><?php echo $row['district'];?></span></td>
                                                            <td><span name="rows[]" id="typeVihTest<?php echo ($key+1);?>"><?php echo $row['type_vih_test'];?></span></td>
                                                            <td><span name="rows[]" id="phone<?php echo ($key+1);?>"><?php echo $row['phone'];?></span></td>
                                                            <td><span name="rows[]" id="email<?php echo ($key+1);?>"><?php echo $row['email'];?></td>
                                                            <td><span name="rows[]" id="job<?php echo ($key+1);?>"><?php echo $row['current_jod'];?></span></td>
                                                            <td><span name="rows[]" id="facility<?php echo ($key+1);?>"><?php echo $row['facility_id'];?></td>
                                                        </tr>
                                                    <?php }?>
                                                </tbody>
                                            </table>
                                        </div>
                                    <?php }?>
                                </div>
                            </fieldset>
                            <?php }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script>
    $(document).ready(function () {
        /* var table = $('#mandatoryTable,#duplicatesTable,#importedTable').DataTable({
            "aProcessing": true,
            "aServerSide": true,
            "aaSorting": [],
        }); */
    });
</script>