<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<style type="">
        .frezz th:last-child,
        .frezz td:last-child {
            position: sticky !important;
            right: -1%;
            z-index: 1;
            background-color: white;
            padding: 18px !important;
        }
    a.toggle-vis{
        margin: 4px 4px;
    }
    #shBtnManageColumns{
        font-size: 17px;
        font-weight: 600;
    }
    .text-danger{
        color:red !important;
    }
    .text-success{
        color:#086200 !important;
    }
    .lastcol{
        opacity:0.8;
    }
    .lastcol:hover{
        opacity:1;
    }
</style>
<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>List of Testers</h2>
                <!-- <span class="text-danger"></span>
                <span class="text-success"></span> -->
            </div>
            <div class="col-sm-4">
                <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'add')) { ?>
                    <a href="<?php echo $this->url('provider', array('action' => 'add')); ?>" class="btn btn-dark pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Add Tester</a>
                <?php } ?>

            </div>
        </div>
    </div>


    <div class="main-content">
    
    

    <div class="well container">
    <div class="row" style="margin-bottom:15px;margin-left:9px;">
        <h3>Manage Columns  &nbsp;<a href="javascript:void(0)" id="shBtnManageColumns">Show/hide</a></h3> 
    </div>
        <div id="manageColumns">

        </div>
    </div>
        <div class="widget widget-fullwidth widget-small" style="padding:5px;" >
            <table id="provider" class="datatables table table-bordered table-responsive table-condensed table-striped table-hover table-fw-widget">
                <thead class="frezz">
                    <tr class="allproviders">
                        <th>Certification Registration No.</th>
                        <th>Professional Registration No.<br>(if available)</th>
                        <th style="width:10%;">Certification ID</th>
                        <th style="width:10%;">Certification Time</th>
                        <th style="width:10%;">Tester</th>
                        <th style="width:10%;">Region</th>
                        <th style="width:10%;">District</th>
                        <th style="width:10%;">Type of HIV Test Modality/ Point</th> 
                        <th style="width:10%;">Phone</th>
                        <th style="width:10%;">E-mail</th>
                        <th style="width:10%;">Prefered Contact Method</th>
                        <th style="width:10%;" >Current Job</th>
                        <th>Time worked as tester</th>
                        <th style="width:10%;" >Facility Name</th>
                        <th style="width:10%;" >Facility Address</th>
                        <th>Testing Site In charge Name</th>
                        <th>Testing Site In charge  Phone</th>
                        <th>Testing Site In charge Email</th>
                        <th>Facility In charge Name </th>
                        <th>Facility In charge Phone</th>
                        <th>Facility In charge Email</th>

                        <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'edit')) { ?>
                            <th style="width:5%;">Edit</th>
                        <?php } ?>
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'delete')) { ?>
                            <th>Delete</th><?php } ?>
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'pdf')) { ?>
                            <th>PDF</th><?php } ?>
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'send-test-link')) { ?>
                            <th>Send Test Link</th><?php } ?>
                    </tr>


                </thead>
                <tbody class="frezz">

                    <?php foreach ($this->providers as $provider) {
                        // \Zend\Debug\Debug::dump($provider);die;
                        $certificationTime = '';
                        $startDate = '';
                        $endDate = '';
                        if(isset($provider->date_certificate_issued) && $provider->date_certificate_issued!= null && trim($provider->date_certificate_issued)!= '' && $provider->date_certificate_issued!= '0000-00-00' && $provider->date_certificate_issued!= '1970-01-01'){
                            $startDate = date('M Y',strtotime($provider->date_certificate_issued));
                        }
                        if(isset($provider->date_end_validity) && $provider->date_end_validity!= null && trim($provider->date_end_validity)!= '' && $provider->date_end_validity!= '0000-00-00' && $provider->date_end_validity!= '1970-01-01'){
                            $endDate = date('M Y',strtotime($provider->date_end_validity));
                        }
                        if(trim($startDate)!= '' && trim($endDate)!= ''){
                           $certificationTime = $startDate.' - '.$endDate;
                        }
                        ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($provider->certification_reg_no); ?></td>
                            <td><?php echo $this->escapeHtml($provider->professional_reg_no); ?></td>
                            <td><?php echo $this->escapeHtml($provider->certification_id); ?></td>
                            <td><?php echo $certificationTime; ?></td>
                            <td><a href="javascript:void(0);" style="cursor:pointer;text-decoration:underline;" onclick="getTestHistory('<?php echo base64_encode($provider->id); ?>');"><?php echo $this->escapeHtml($provider->last_name . ' ' . $provider->first_name . ' ' . $provider->middle_name); ?></a></td>
                            <td><?php echo $this->escapeHtml($provider->region_name); ?></td>
                            <td><?php echo $this->escapeHtml($provider->district_name); ?></td>
                            <td><?php echo $this->escapeHtml($provider->type_vih_test); ?></td>
                            <td><?php echo $this->escapeHtml($provider->phone); ?></td>
                            <td><?php echo $this->escapeHtml($provider->email); ?></td>
                            <td><?php echo $this->escapeHtml($provider->prefered_contact_method); ?></td>
                            <td><?php echo $this->escapeHtml($provider->current_jod); ?></td>
                            <td><?php echo $this->escapeHtml($provider->time_worked); ?></td>
                            <td><?php echo $this->escapeHtml($provider->facility_name); ?></td>
                            <td><?php echo $this->escapeHtml($provider->facility_address); ?></td>
                            <td><?php echo $this->escapeHtml($provider->test_site_in_charge_name); ?></td>
                            <td><?php echo $this->escapeHtml($provider->test_site_in_charge_phone); ?></td>
                            <td><?php echo $this->escapeHtml($provider->test_site_in_charge_email); ?></td>
                            <td><?php echo $this->escapeHtml($provider->facility_in_charge_name); ?></td>
                            <td><?php echo $this->escapeHtml($provider->facility_in_charge_phone); ?></td>
                            <td><?php echo $this->escapeHtml($provider->facility_in_charge_email); ?></td>

                            <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'edit')) { ?>
                                <td>
                                    
                                        <a class="btn btn-primary" href="<?php echo $this->url('provider', array('action' => 'edit', 'id' => base64_encode($provider->id))); ?>"><span class="glyphicon glyphicon-pencil">Edit</span></a> 
                                    
                                </td> 
                            <?php } ?>
                            <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'delete')) { ?>
                                <td>
                                    <?php if(!isset($provider->examid)){ ?>
                                        
                                            <a class="btn btn-primary" onclick="if (!confirm('Do you really want to remove ' + '<?php echo $this->escapeHtml($provider->last_name . ' ' . $provider->first_name . ' ' . $provider->middle_name); ?>' + ' ?')) {
                                                        alert('Canceled!');
                                                        return false;
                                                    }
                                                    ;"  href="<?php echo $this->url('provider', array('action' => 'delete', 'id' => $provider->id)); ?>"> <span class="glyphicon glyphicon-trash">&nbsp;Delete</span></a> 
                                    
                                    <?php } ?>
                                </td>
                            <?php } ?>
                            <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'pdf')) { ?>
                                <td>
                                <?php if(isset($provider->final_decision) && $provider->final_decision!= null && trim($provider->final_decision)!= ''){
                                    if (strcasecmp($provider->final_decision, 'Certified') == 0) { ?>
                                    
                                       <a href="<?php echo $this->url('certification', array('action' => 'pdf'), array('query' => array(base64_encode('id') => base64_encode($provider->certid), base64_encode('last') => base64_encode($provider->last_name), base64_encode('first') => base64_encode($provider->first_name), base64_encode('middle') => base64_encode($provider->middle_name), base64_encode('professional_reg_no') => base64_encode($provider->professional_reg_no), base64_encode('certification_id') => base64_encode($provider->certification_id), base64_encode('date_issued') => base64_encode($provider->date_certificate_issued)))); ?>" target="_blank"><span class="glyphicon glyphicon-download-alt"></span>&nbsp;PDF</a>
                                    
                                <?php } } ?>
                                </td>
                            <?php } ?>
                            <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'send-test-link')) { ?>
                                <td class="lastcol">
                                    
                                       <a href="javascript:void(0);" class="btn btn-primary" onclick="sendTestLink('<?php echo base64_encode($provider->id);?>','<?php echo $this->escapeHtml($provider->email);?>');"><span class="glyphicon glyphicon-envelope"></span>&nbsp;Send Test Link(<?php echo (isset($provider->link_send_count) && $provider->link_send_count > 0)?$provider->link_send_count:0;?>)</a>
                                    
                                </td>
                            <?php } ?>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<!-- <script type="text/javascript" src="< ?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script> -->
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
<script type="text/javascript" language="javascript">
    $(document).ready(function () {
        /* 
            The below snippet dynamically list toggleable button.
            It can show/hide columns
        */
        var listOfColumns = '';
        $('tr.allproviders').each(function(){  
            $(this).find('th').each(function(index){
                listOfColumns+='<a class="toggle-vis btn btn-primary btn-sm" data-column="'+index+'" onclick="toggleBtnClass(this)"> <span class="btn-label"><i class="glyphicon glyphicon-ok"></i></span> '+$(this).text()+'</a> &nbsp;'
            });
        }); 
        $("#manageColumns").html(listOfColumns);
        /* Ends Here */

       var table = $('#provider').DataTable({
            "aProcessing": true,
            "aServerSide": true,
            "aaSorting": [],
        });

        $('a.toggle-vis').on( 'click', function (e) {
            e.preventDefault(); 
            // Get the column API object
            var column = table.column( $(this).attr('data-column') ); 
            // Toggle the visibility
            column.visible( ! column.visible() );
            $("#provider_wrapper").css("overflow-x","scroll");
        });
        $("#manageColumns").hide();
        $("#shBtnManageColumns").click(function(){
            $("#manageColumns").toggle('fast','linear');
        });
                      
    });
    
    /* Toggles Color of button */
    function toggleBtnClass(btnObj){
        $(btnObj).toggleClass("btn-default");
        var children = btnObj.childNodes;
        var iconTag = children[1].firstChild;
        $(iconTag).toggleClass("glyphicon-remove");
    }

    function sendTestLink(id,email){
        if(confirm("Are you sure! Want to send the test link to this provider?")){
            $.blockUI();
            $.post("<?php echo $this->url('provider',array('action'=>'send-test-link')); ?>", {providerId:id,providerKey:email},
            function(data){
                if(data > 0){
                    alert('Link send to the '+email);
                }else{
                    alert('Link not send kindly check provider have the email id.');
                }
                $.unblockUI();
            });
        }
    }
</script>