<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>List of  Testers</h2>
            </div>
            <div class="col-sm-4">
                <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'add')) { ?>
                    <a href="<?php echo $this->url('provider', array('action' => 'add')); ?>" class="btn btn-dark pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Add Tester</a>
                <?php } ?>

            </div>
        </div>
    </div>


    <div class="main-content">

        <div class="widget widget-fullwidth widget-small" style="padding:5px;" >
            <table id="provider" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
                <thead>
                    <tr>
                        <th>Certification Registration No.</th>
                        <th> Professional Registration No.<br>(if available)</th>
                        <th style="width:10%;">Certification ID</th>
                        <th style="width:10%;">Tester</th>
                        <th style="width:10%;">Region</th>
                        <th style="width:10%;">District</th>
                        <th style="width:10%;">Type VIH Test Modality/ Point</th> 
                        <th style="width:10%;">Phone</th>
                        <th style="width:10%;">E-mail</th>
                        <th style="width:10%;">Prefered Contact Method</th>
                        <th style="width:10%;" >Current Job</th>
                        <th>Time worked as tester</th>
                        <th style="width:10%;" >Facility Name</th>
                        <th style="width:10%;" >Facility Address</th>
                        <th>Testing Site In charge Name</th>
                        <th>Testing Site In charge  Phone</th>
                        <th>Testing Site In charge Email</th>
                        <th>Facility In charge Name </th>
                        <th>Facility In charge Phone</th>
                        <th>Facility In charge Email</th>

                        <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'edit')) { ?>
                            <th style="width:5%;">Edit</th>
                        <?php } ?>
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'delete')) { ?>
                            <th>Delete</th><?php } ?>
                    </tr>


                </thead>
                <tbody>

                    <?php foreach ($this->providers as $provider) : ?>
                        <tr>
                            <td><div style="width:100px;overflow:auto;"><?php echo $this->escapeHtml($provider->certification_reg_no); ?></div></td>
                            <td><div style="width:100px;overflow:auto;"><?php echo $this->escapeHtml($provider->professional_reg_no); ?></div></td>
                            <td><div style="width:120px;overflow:auto;"><?php echo $this->escapeHtml($provider->certification_id); ?></div></td>
                            <td><div style="width:180px;overflow:auto;"><?php echo $this->escapeHtml($provider->last_name . ' ' . $provider->first_name . ' ' . $provider->middle_name); ?></div></td>
                            <td><div style="width:180px;overflow:auto;"><?php echo $this->escapeHtml($provider->region_name); ?></div></td>
                            <td><div style="width:180px;overflow:auto;"><?php echo $this->escapeHtml($provider->district_name); ?></div></td>
                            <td><div style="width:100px;overflow:auto;"><?php echo $this->escapeHtml($provider->type_vih_test); ?></div></td>
                            <td><div style="width:100px;overflow:auto;"><?php echo $this->escapeHtml($provider->phone); ?></div></td>
                            <td><div style="width:180px;overflow:auto;"><?php echo $this->escapeHtml($provider->email); ?></div></td>
                            <td><div style="width:80px;overflow:auto;"><?php echo $this->escapeHtml($provider->prefered_contact_method); ?></div></td>
                            <td><div style="width:120px;overflow:auto;"><?php echo $this->escapeHtml($provider->current_jod); ?></div></td>
                            <td><div style="width:120px;overflow:auto;"><?php echo $this->escapeHtml($provider->time_worked); ?></div></td>
                            <td><div style="width:180px;overflow:auto;"><?php echo $this->escapeHtml($provider->facility_name); ?></div></td>
                            <td><div style="width:180px;overflow:auto;"><?php echo $this->escapeHtml($provider->facility_address); ?></div></td>
                            <td><div style="width:180px;overflow:auto;"><?php echo $this->escapeHtml($provider->test_site_in_charge_name); ?></div></td>
                            <td><div style="width:120px;overflow:auto;"><?php echo $this->escapeHtml($provider->test_site_in_charge_phone); ?></div></td>
                            <td><div style="width:180px;overflow:auto;"><?php echo $this->escapeHtml($provider->test_site_in_charge_email); ?></div></td>
                            <td><div style="width:180px;overflow:auto;"><?php echo $this->escapeHtml($provider->facility_in_charge_name); ?></div></td>
                            <td><div style="width:120px;overflow:auto;"><?php echo $this->escapeHtml($provider->facility_in_charge_phone); ?></div></td>
                            <td><div style="width:180px;overflow:auto;"><?php echo $this->escapeHtml($provider->facility_in_charge_email); ?></div></td>

                            <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'edit')) { ?>
                                <td>
                                    <div style="width:70px;height:40px;overflow:auto;">
                                        <a href="<?php echo $this->url('provider', array('action' => 'edit', 'id' => base64_encode($provider->id))); ?>"><span class="glyphicon glyphicon-pencil">Edit</span></a> 
                                    </div>
                                </td> 
                            <?php } ?>
                            <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'delete')) { ?>
                                <td><div style="overflow:auto;">
                                        <a onclick="if (!confirm('Do you really want to remove ' + '<?php echo $this->escapeHtml($provider->last_name . ' ' . $provider->first_name . ' ' . $provider->middle_name); ?>' + ' ?')) {
                                                    alert('Canceled!');
                                                    return false;
                                                }
                                                ;"  href="<?php echo $this->url('provider', array('action' => 'delete', 'id' => $provider->id)); ?>"> <span class="glyphicon glyphicon-trash">&nbsp;Delete</span></a> 
                                    </div>
                                </td>
                            <?php } ?>

                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>


</div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>


<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" language="javascript">
    $(document).ready(function () {
        $('#provider').dataTable({
            "aProcessing": true,
            "aServerSide": true,
        })
    });
</script>