<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/bootstrap.min.css'); ?>" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/datatables.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<!--[if lt IE 9]>
<script src="<?php echo $this->basePath('assets/js/html5shiv.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/respond.min.js'); ?>" type="text/javascript"></script>
<![endif]-->
<style>
    table{
        font-size:14px;
    }
</style>
<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-8">
                <h2>Test History</h2>
            </div>
        </div>
    </div>

    <div class="main-content">
        <ul class="nav nav-tabs" id="testTab" role="tablist">
            <li class="nav-item active">
              <a class="nav-link active" id="written-tab" data-toggle="tab" href="#written" role="tab" aria-controls="written" aria-selected="true">Written Exams</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="practical-tab" data-toggle="tab" href="#practical" role="tab" aria-controls="practical" aria-selected="false">Practical Exams</a>
            </li>
        </ul>
        <div class="tab-content" id="testContent">
          <div class="tab-pane active" id="written" role="tabpanel" aria-labelledby="written-tab">
            <table id="writtenTestTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                <thead>
                    <tr>
                        <th  style="width:10%;">No. of Attempts</th>
                        <th  style="width:10%;">Exam Administered by</th>
                        <th  style="width:10%;">Date</th>
                        <th  style="width:10%;">Total Points (=25)</th>
                        <th  style="width:10%;">Final Score (>=80%)</th>
                    </tr>
                </thead>
                <tbody>
            <?php
            if(isset($result['writtenExamResult']) && count($result['writtenExamResult']) > 0){
                foreach ($result['writtenExamResult'] as $written) {
            ?>
            <tr>
                    <td><?php echo $this->escapeHtml($written['exam_type']); ?></td>
                    <td><?php echo $this->escapeHtml($written['exam_admin']); ?></td>
                    <td><?php echo date("d-M-Y", strtotime($this->escapeHtml($written['date']))); ?></div></td>
                    <td><?php echo $this->escapeHtml($written['total_points']); ?></td>
                    <td><?php echo $this->escapeHtml($written['final_score'] . ' %'); ?></td>
                </tr>
            <?php } } ?>
            </tbody>
            </table>
          </div>
          <div class="tab-pane fade" id="practical" role="tabpanel" aria-labelledby="practical-tab">
            <table id="practicalTestTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                <thead>
                    <tr>
                        <th style="width: 10%;">Date</th>
                        <th style="width: 10%;">Type of Exam</th>
                        <th style="width: 10%;">Exam Administrator</th>
                        <th style="width: 10%;">Direct Observation Score (>=90%) </th>
                        <th style="width: 10%;">Sample Testing Score (=100%)</th>
                        <th style="width: 10%;">Practical Total Score</th>
                    </tr>
                </thead>
                <tbody>
            <?php
            if(isset($result['practicalExamResult']) && count($result['practicalExamResult']) > 0){
                foreach ($result['practicalExamResult'] as $practical) {
            ?>
            <tr>
                    <td><div style="width:100px;height:40px;overflow:auto;"><?php echo date("d-M-Y", strtotime($this->escapeHtml($practical['date']))); ?></div></td>
                    <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($practical['exam_type']); ?></div></td>
                    <td><div style="width:200px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($practical['exam_admin']); ?></div></td>
                    <td><div style="width:70px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($practical['direct_observation_score'] . ' %'); ?></div></td>
                    <td><div style="width:70px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($practical['Sample_testing_score'] . ' %'); ?></div></td>
                    <td><div style="width:70px;height:40px;overflow:auto; font-weight: bold"><?php echo $this->escapeHtml($practical['practical_total_score'] . ' %'); ?></div></td>
                </tr>
            <?php } } ?>
            </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/lib/bootstrap/dist/js/bootstrap.min.js'); ?>"></script>
<script type="text/javascript" language="javascript">
$('#testTab a').on('click', function (e) {
  $(this).tab('show');
  e.preventDefault();
})

$(document).ready(function () {
   writtenTestsInit();
   practicalTestsInit();
});

function writtenTestsInit(){
    $('#writtenTestTable').dataTable({
        "aProcessing": true,
        "aServerSide": true,
        "aaSorting": [[ 2, "desc" ]]
    });
}

function practicalTestsInit(){
    $('#practicalTestTable').dataTable({
        "aProcessing": true,
        "aServerSide": true,
        "aaSorting": [[ 0, "desc" ]]
    });
}
</script>