<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<style>
    #shBtnManageColumnstab1{
        font-size: 17px;
        font-weight: 600;
    }
  
</style>
<div class="am-content">

    <div class="page-head">
        <div class="row">
            <div class="col-sm-4"> <h2>Tester Reports</h2></div>

        </div>
    </div>
    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >
                        <div class="row">
                            <form action="<?php $this->url('provider', array('action' => 'xls')); ?>" name="form" method="post" >

                                <?php
                                $form->prepare();
                                $form->get('country')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Country',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'showRegion(this.value)'
                                ]);
                                $form->get('region')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Region',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'showDistrict(this.value)'
                                ]);

                                $form->get('district')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'District',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)',
                                    'onchange' => 'showFacilities(this.value)',
                                ]);

                                $form->get('type_vih_test')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Type of HIV Test',
                                    'id' => 'Type of HIV Test Modality/Point',
                                    'onclick' => 'emptyInput(this)']);


                                $form->get('prefered_contact_method')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Prefered Contact Method',
                                    'id' => 'Prefered Contact Method',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('current_jod')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Current Job',
                                    'id' => 'Current Job Title',
                                    'onclick' => 'emptyInput(this)']);


                                $form->get('facility_id')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Facility Name',
                                    'id' => 'Facility Name',
                                    'onclick' => 'emptyInput(this)',
                                ]);
                                
                                $form->get('submit')->setAttributes([
                                ]);


                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>
                                <div class="form-group col-lg-6" style="display:none;">
                                    <?= $this->formLabel($form->get('country')); ?>
                                    <?= $this->formElement($form->get('country')); ?>
                                    <?= $this->formElementErrors($form->get('country')); ?>
                                </div>

                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('region')); ?>
                                    <?= $this->formElement($form->get('region')); ?>
                                    <?= $this->formElementErrors($form->get('region')); ?>
                                </div>

                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('district')); ?>
                                    <?= $this->formElement($form->get('district')); ?>
                                    <?= $this->formElementErrors($form->get('district')); ?></div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('facility_id')); ?>
                                    <?= $this->formElement($form->get('facility_id')); ?>
                                    <?= $this->formElementErrors($form->get('facility_id')); ?>
                                </div>
                                <div class="form-group col-lg-6">  
                                    <?= $this->formLabel($form->get('type_vih_test')); ?>
                                    <?= $this->formElement($form->get('type_vih_test')); ?>
                                    <?= $this->formElementErrors($form->get('type_vih_test')); ?>
                                </div>

                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('prefered_contact_method')); ?>
                                    <?= $this->formElement($form->get('prefered_contact_method')); ?>
                                    <?= $this->formElementErrors($form->get('prefered_contact_method')); ?>       
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('current_jod')); ?>
                                    <?= $this->formElement($form->get('current_jod')); ?>
                                    <?= $this->formElementErrors($form->get('current_jod')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label>Exclude Tester Name</label>
                                    <select name="exclude_tester_name" class="form-control" id="Exclude Tester Name" onclick="emptyInput(this)"><option value="">Please choose exclude tester name</option>
                                        <option value="yes">Yes</option>
                                        <option value="no">No</option>
                                    </select>
                                </div>
                                <div class="form-group col-lg-12" style="margin-top: 30px;text-align:center;">
                                    <!-- <button type="button" class="btn  btn-space btn-primary" onclik="getReport()" >GET REPORT</button> -->
                                    <a href="javascript:void(0)" onclick="getTestReport();" value="Filter" class="btn  btn-space btn-primary">GET REPORT</a>
                                    <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                    <a class="btn  btn-space btn-danger" role="button"  href="<?php echo $this->url('provider', array('action' => 'xls')); ?>" >CLEAR</a>
                                </div>
                                <?php echo $this->form()->closeTag();
                                ?>
                            </form>

                        </div>
                            <div class="row">
                            <div class="well container">
                                <div class="row" style="margin-bottom:15px;margin-left:9px;">
                                <h3>Manage Columns  &nbsp;<a href="javascript:void(0)" id="shBtnManageColumnstab1">Show/hide</a></h3> 
                                </div>
                                <div id="manageColumnstab1">
                                </div>
                            </div>
                            </div>
                            
                            <div id="testReport">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

    <script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


    <script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/certification.js'); ?>"></script>
    <script>
    $(document).ready(function () {
        $("#Country").val(1);
        showRegion(1);
        getTestReport();
    });
    function showRegion(str) {
            if (str == "") {
               document.getElementById("Region").innerHTML = "<option value=''>Please Choose a Country First</option>";
               document.getElementById("District").innerHTML = "<option value=''>Please Choose a Region First</option>";
               document.getElementById("Facility Name").innerHTML = "<option value=''>Please Choose a District First</option>";
              return false;
            }else{
                $.post("<?php echo $this->url('provider', array('action' => 'region')); ?>", {q: str},
                function(data) {
                   document.getElementById("Region").innerHTML = data;
                   document.getElementById("District").innerHTML = "<option value=''>Please Choose a Region First</option>";
                   document.getElementById("Facility Name").innerHTML = "<option value=''>Please Choose a District First</option>";
                });
            }
    }
    
    function showDistrict(str) {
        if (str == "") {
            document.getElementById("District").innerHTML = "Please Choose a Region First";
            return;
        } else {
            if (window.XMLHttpRequest) {
                // code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            } else {
                // code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("District").innerHTML = this.responseText;
                    document.getElementById("Facility Name").innerHTML = "<option value=''>Please Choose a District First</option>";
                }
            };
            xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'district')); ?>?q=" + str, true);
            xmlhttp.send();
        }
    }

    function showFacilities(str) {
        if (str == "") {
            document.getElementById("Facility Name").innerHTML = "Please Choose a District First";
            return;
        } else {
            if (window.XMLHttpRequest) {
                // code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            } else {
                // code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("Facility Name").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'facility')); ?>?q=" + str, true);
            xmlhttp.send();
        }
    }

    function getTestReport(){
        $('#testReport').html('');
        $.blockUI();
        $.post("<?php echo $this->url('provider', array('action' => 'get-tester-report')); ?>", 
        {
            region: $("[name=region]").val(),
            district: $("[name=district]").val(),
            facility_id: $("[name=facility_id]").val(),
            type_vih_test: $("[name=type_vih_test]").val(),
            prefered_contact_method: $("[name=prefered_contact_method]").val(),
            current_jod: $("[name=current_jod]").val(),
            exclude_tester_name: $("[name=exclude_tester_name]").val(),
        },
        function(data) {
            $('#testReport').html(data);



            var listOfColumnsTab1 = '';
        $('tr.allrecertifications').each(function(){  
            $(this).find('th').each(function(index){
                listOfColumnsTab1+='<a class="toggle-vis-allColumnsTab1 btn btn-primary btn-sm" data-column="'+index+'" style="margin-top: 5px;" onclick="toggleBtnClassTab1(this)"> <span class="btn-label"><i class="glyphicon glyphicon-ok"></i></span> '+$(this).text()+'</a> &nbsp;'
            });
        }); 
        $("#manageColumnstab1").html(listOfColumnsTab1);

            var table = $('#testReportTable').DataTable({
                "aProcessing": true,
                "aServerSide": true,
                "aaSorting": [],
            });



        $('a.toggle-vis-allColumnsTab1').on( 'click', function (e) {
                e.preventDefault(); 
                // Get the column API object
                var column = table.column( $(this).attr('data-column') ); 
                // Toggle the visibility
                column.visible( ! column.visible() );
                $("#provider_wrapper").css("overflow-x","scroll");
            });
            $("#manageColumnstab1").hide();
            $("#shBtnManageColumnstab1").click(function(){
                $("#manageColumnstab1").toggle('fast','linear');
            });

        });
        $.unblockUI();
    }


        /* Toggles Color of button */
    function toggleBtnClassTab1(btnObj){
    $(btnObj).toggleClass("btn-default");
    var children = btnObj.childNodes;
    var iconTag = children[1].firstChild;
    $(iconTag).toggleClass("glyphicon-remove");
    }

    </script>