<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
if (($this->isAllowed($role, 'Certification\Controller\WrittenExamController', 'edit')) && ($this->isAllowed($role, 'Certification\Controller\WrittenExamController', 'delete'))) {
    $editAction = ' {"sClass":"center details-control",bSortable:false},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false}';
}elseif ($this->isAllowed($role, 'Certification\Controller\WrittenExamController', 'edit')) {
    $editAction = ' {"sClass":"center details-control",bSortable:false},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false}';
}elseif ($this->isAllowed($role, 'Certification\Controller\WrittenExamController', 'delete')) {
    $editAction = ' {"sClass":"center details-control",bSortable:false},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false}';
}else{
    $editAction = ' {"sClass":"center details-control",bSortable:false},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center","bVisible": false},{"sClass":"center",bSortable:false},{"sClass":"center",bSortable:false}';
}
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>" />

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />


<style>
    td.details-control {
        background: url('/assets/img/details_open.png') no-repeat center center;
        cursor: pointer;
    }

    tr.shown td.details-control {
        background: url('/assets/img/details_close.png') no-repeat center center;
    }

    .table th {
        text-align: center;
    }

    .table td.center {
        text-align: center;
    }
</style>


<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>Written Exams </h2>
            </div>
            <div class="col-sm-4">
                <?php if ($this->isAllowed($role, 'Certification\Controller\WrittenExamController', 'import-excel')) { ?>
                    <a href="<?php echo $this->url('written-exam', array('action' => 'import-excel')); ?>" class="btn btn-dark pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Import Written Exam</a>
                <?php }
                    if ($this->isAllowed($role, 'Certification\Controller\WrittenExamController', 'add')) {  ?>
                    <a href="<?php echo $this->url('written-exam', array('action' => 'add')); ?>" class="btn btn-dark pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Add Written Exam</a>
                <?php }  ?>
            </div>
        </div>
        <div class="row">
            <span class="muted pull-right" style="font-size:15px;padding-left:10px;color: darkgray;">(Please ensure that the tester is <a href="/provider/">enrolled</a> before you record the Written Exam results)</span>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <div class="col-md-3" style="margin-top:10px;">
                    <lable>Display</label>
                </div>
                <div class="col-md-9">
                    <select name="display" class="form-control" id="display">
                        <option value="yes">Not Recommended/Pending</option>
                        <option value="no">Recommended/Certified</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-5" style="margin-top:10px; align:center">
                <input type="button" onclick="searchRequestData();" value="Search" class="btn btn-primary btn-sm">
                <a class="btn  btn-sm btn-danger" role="button" href="/written-exam">Reset</a>
            </div>
        </div>
    </div>
    
    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <table id="writtenExamTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
                <thead>
                    <tr>
                        <th></th>
                        <th style="width:17%;">Tester </th>
                        <th style="width:8%;">No. of Attempts </th>
                        <th style="width:15%;">Exam Administered by </th>
                        <th style="width:10%;">Date </th>
                        <th>1.<br> QA (points)<br><br> </th>
                        <th>2. <br>RT (points) <br><br></th>
                        <th>3.<br> Safety (points) <br><br></th>
                        <th>4.<br> Specimen Collection (points) </th>
                        <th>5.<br> Testing Algorithm (points) <br></th>
                        <th>6.<br> Record Keeping (points)</th>
                        <th>7.<br> EQA/PT (points)<br><br></th>
                        <th>8.<br> Ethics (points)<br><br> </th>
                        <th>9.<br> Inventory (points)<br><br> </th>
                        <th style="width:10%;">Total Points (=25)</th>
                        <th style="width:10%;">Final Score (≥80%)</th>


                        <?php if ($this->isAllowed($role, 'Certification\Controller\WrittenExamController', 'edit')) {  ?>
                            <th>Edit</th>
                            <th>Another Attempt</th>
                        <?php }  ?>
                        <?php if ($this->isAllowed($role, 'Certification\Controller\WrittenExamController', 'delete')) { ?>
                            <th>Delete</th>
                        <?php } ?>

                    </tr>

                </thead>
                <tbody>
                    <tr>
                        <td colspan="15" class="dataTables_empty">Loading data from server</td>
                    </tr>
                </tbody>
            </table>

    </div>
</div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>

<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" language="javascript">
    var writtenExamTable = null;
    let searchExecuted = false;


    function format(d) {
        return '<h5>&nbsp;' + d[1] + ' - ' + d[2] + ' (' + d[4] + ')' + '</h5>' +
            '<table class="table table-bordered table-condensed table-striped table-hover table-fw-widget">' +
            '<tr>' +
            '<th>QA (points)</th>' +
            '<th>RT (points)</th>' +
            '<th>Safety (points)</th>' +
            '<th>Specimen Collection (points)</th>' +
            '<th>Testing Algorithm (points)</th>' +
            '<th>Record Keeping (points)</th>' +
            '<th>EQA/PT (points)</th>' +
            '<th>Ethics (points)</th>' +
            '<th>Inventory (points)</th>' +
            '</tr>' +
            '<tr>' +
            '<td class="center">' + d[5] + '</td>' +
            '<td class="center">' + d[6] + '</td>' +
            '<td class="center">' + d[7] + '</td>' +
            '<td class="center">' + d[8] + '</td>' +
            '<td class="center">' + d[9] + '</td>' +
            '<td class="center">' + d[10] + '</td>' +
            '<td class="center">' + d[11] + '</td>' +
            '<td class="center">' + d[12] + '</td>' +
            '<td class="center">' + d[13] + '</td>' +
            '</tr>' +
            '</table>';
    }
    $(document).ready(function() {

        writtenExamTable = $('#writtenExamTable').DataTable({
			"bProcessing": true,
			"bServerSide": true,
            "aoColumns": [
                <?php echo $editAction; ?>
            ],
            "autoWidth": true,
            "order": [
                [1, 'asc']
            ],
			"sAjaxSource": "<?php echo $this->url('written-exam', array('action' => 'index')); ?>",
			"fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({
                    "name": "display",
                    "value": $("#display").val()
                });
				$.ajax({
					"dataType": 'json',
					"type": "POST",
					"url": sSource,
					"data": aoData,
					"success": fnCallback
				});
			}
		});

        // Array to track the ids of the details displayed rows
        var detailRows = [];

        $('#writtenExamTable tbody').on('click', 'td.details-control', function() {
            var tr = $(this).closest('tr');
            var row = writtenExamTable.row(tr);

            if (row.child.isShown()) {
                // This row is already open - close it
                row.child.hide();
                tr.removeClass('shown');
            } else {
                // Open this row
                row.child(format(row.data())).show();
                tr.addClass('shown');
            }
        });
    });
    function searchRequestData(){
        searchExecuted = true;
        $.blockUI();
        writtenExamTable.draw();
        $.unblockUI();
    }
</script>
