<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>
<head><script>history.forward();</script></head>


<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">

    <div class="page-head">
        <div class="row">
            <div class="col-sm-4"> <h2>Validate A Certification</h2></div>

            <div class="row">
                <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span> 
            </div>

            <div class="row">
                <span class="muted pull-right" style="font-size:15px; "><span class="mandatory" style="color: green;">*</span> indicates read only field</span>
            </div>
        </div>
    </div>
    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >


                            <form action="<?php $this->url('certification', array('action' => 'add')); ?>" name="form" method="post" onsubmit="return validateForm()">

                                <?php
                                $form->prepare();

                                $practical_score = $this->practical;
                                $written_score = $this->written;
                                $sample_testing = $this->sample;
                                $direct_observation = $this->direct;

                                if ($written_score >= 80 && $direct_observation >= 90 && $sample_testing = 100) {
                                    $form->get('final_decision')->setAttributes(['class' => 'form-control', 'value' => 'Certified', 'id'=>'decision','onFocus' => "this.blur()"]);
                                } elseif ($written_score < 80 && ($direct_observation < 90 || $sample_testing < 100)) {
                                    $form->get('final_decision')->setAttributes(['class' => 'form-control', 'value' => 'Failed','id'=>'decision','onFocus' => "this.blur()"]);
                                } else {
                                    $form->get('final_decision')->setAttributes(['class' => 'form-control', 'value' => 'Pending', 'id'=>'decision','onFocus' => "this.blur()"]);
                                }


                                $form->get('certification_issuer')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Certification Issued By',
                                    'id' => 'Certification Issued By',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('date_certificate_issued')->setAttributes([
                                    'class' => 'form-control',
                                    'value' => date('d-m-Y'),
                                    'onFocus' => "this.blur()"]);

                                if (empty($this->certification_id)) {
                                    $form->get('certification_type')->setAttributes([
                                        'class' => 'form-control',
                                        'placeholder' => 'Type of Certification',
                                        'autocomplete' => 'off',
                                        'value' => 'Initial',
                                        'onFocus' => "this.blur()"]);
                                } else {
                                    $form->get('certification_type')->setAttributes([
                                        'class' => 'form-control',
                                        'placeholder' => 'Type of Certification',
                                        'autocomplete' => 'off',
                                        'value' => 'Recertification',
                                        'onFocus' => "this.blur()"]);
                                }


                                $form->get('submit')->setAttributes([
                                ]);


                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>

                                <?php echo $this->formHidden($form->get('examination')->setAttributes(['class' => 'form-control', 'value' => $this->id])) ?>

                                <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('final_decision')); ?><span class="mandatory" style="color: green;">*</span>
                                    <?= $this->formElement($form->get('final_decision')); ?>
                                    <?= $this->formElementErrors($form->get('final_decision')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('certification_type')); ?><span class="mandatory" style="color: green;">*</span>
                                    <?= $this->formElement($form->get('certification_type')); ?>
                                    <?= $this->formElementErrors($form->get('certification_type')); ?></div>

                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('date_certificate_issued')); ?><span class="mandatory" style="color: green;">*</span>
                                    <?= $this->formElement($form->get('date_certificate_issued')); ?>
                                    <?= $this->formElementErrors($form->get('date_certificate_issued')); ?>
                                </div>
                                <div class="form-group col-lg-6" id="issued">
                                    <?= $this->formLabel($form->get('certification_issuer')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('certification_issuer')); ?>
                                    <?= $this->formElementErrors($form->get('certification_issuer')); ?>
                                </div>
                                <div class="form-group col-lg-6" style="margin-top: 30px"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                    <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('certification', array('action' => 'index')); ?>" >CANCEL</a> </div>
                                    <?php echo $this->form()->closeTag();
                                    ?>
                            </form>
                            

                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>

</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>

<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/certification.js'); ?>"></script>
