<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$editActionTab1 = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
$editActionTab2 = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
$editActionTab3 = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<style>
    #shBtnManageColumnstab1{
        font-size: 17px;
        font-weight: 600;
    }
    #shBtnManageColumnsTab2{
        font-size: 17px;
        font-weight: 600;
    }
    #shBtnManageColumnstab3{
        font-size: 17px;
        font-weight: 600;
    }
    
   
</style>
<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-4"> <h2> Expiry Certification Reports</h2></div>
        </div>
    </div>
    <div class="main-content">
    <ul class="nav nav-tabs" id="examinationTab" role="tablist">
            <li class="nav-item active">
                <a class="nav-link active" id="upForRecertification-tab" data-toggle="tab" href="#upForRecertification" role="tab" aria-controls="upForRecertification" aria-selected="false">Up for Recertification</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="remindersSent-tab" data-toggle="tab" href="#remindersSent" role="tab" aria-controls="remindersSent" aria-selected="true" >Reminders Sent</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="didNotRecertify-tab" data-toggle="tab" href="#didNotRecertify" role="tab" aria-controls="didNotRecertify" aria-selected="false">Did not recertify</a>
            </li>
        </ul>
        <div class="tab-content" id="examinationContent">
            <div class="tab-pane active" id="upForRecertification" role="tabpanel" aria-labelledby="online-tab">
                <div class="widget widget-fullwidth widget-small" style="padding:5px;">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                            <div class="well container">
                                            <div class="row" style="margin-bottom:15px;margin-left:9px;">
                                            <h3>Manage Columns  &nbsp;<a href="javascript:void(0)" id="shBtnManageColumnstab1">Show/hide</a></h3> 
                                            </div>
                                            <div id="manageColumnstab1">
                                            </div>
                                        </div>
                                <div class="panel-body" >

                                <form action="<?php $this->url('certification', array('action' => 'certification-expiry')); ?>" name="form" method="post" >
                                    <div class="col-lg-6">
                                        <label for="Country">Country</label>
                                        <select name="country" class="form-control" autocomplete="off" id="Country" onclick="emptyInput(this)" onchange="showRegion(this.value,'online')">
                                            <option value="" selected>Please Choose a Country</option>
                                            <?php foreach($country as $crow) { ?>
                                                <option value="<?php echo $crow['country_id'];?>" <?php echo ($crow['country_id'] == 1)?"selected='selected'":'';?>><?php echo $crow['country_name'];?></option>
                                            <?php } ?>
                                        </select>                            
                                    </div>

                                    <div class="col-lg-6">
                                        <label for="Region">Province</label>
                                        <select name="region" class="form-control" autocomplete="off" id="Region" onclick="emptyInput(this)" onchange="showDistrict(this.value,'online')">
                                            <option value="">Please choose a Country</option>
                                        </select>                                                                    
                                    </div>
                                    <div class="col-lg-6">
                                        <label for="District">Districts</label>
                                        <select name="district" class="form-control" id="District" autocomplete="off" onclick="emptyInput(this)">
                                            <option value="">Please Choose a District</option>
                                        </select>                                                                    
                                    </div>
                                    <input type="hidden" id="Exam" name="Exam" value="online-exam">
                                    <div class="col-lg-12" style="margin-top: 30px;text-align:center;">
                                    <input type="hidden" id="certificationExpiryVal" name="certificationExpiryVal" value="upForRecertification">
                                        
                                        <a class="btn btn-space btn-primary" href="javascript:void(0);"  onclick="searchAllOrderData();">GET REPORT</a>
                                        <button type="submit" class="btn btn-space btn-primary">DOWNLOAD REPORT</button>
                                        <a class="btn btn-space btn-default" role="button" href="<?php echo $this->url('examination', array('action' => 'xls')); ?>" >CANCEL</a>
                                    </div>
                                </form>

                                <div id="online-exam"></div>
                                    </br>

                                    </br>
                                    </br>
                                    <div id="upForRecertificationData">
                                    <table id="upForRecertification-table" class="datatables table table-bordered table-responsive table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                                        <thead>
                                        <tr class="allColumnsTab1">
                                            <th style="width:10%;">Tester</th>
                                                        <th style="width:10%;">Final Decision</th>
                                                        <th style="width:10%;">Region</th>
                                                        <th style="width:10%;">District</th>
                                                        <th style="width:10%;">Facility</th>
                                                        <th style="width:10%;">Type HIV testing modality/point</th>
                                                        <th style="width:10%;">Current job title</th>
                                                    </tr>
                                            </thead>
                                            <tbody>
                     
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="remindersSent" role="tabpanel" aria-labelledby="practical-tab">
                
                <div class="widget widget-fullwidth widget-small" style="padding:5px;">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                 <div class="well container">
                                    <div class="row" style="margin-bottom:15px;margin-left:9px;">
                                    <h3>Manage Columns  &nbsp;<a href="javascript:void(0)" id="shBtnManageColumnsTab2">Show/hide</a></h3> 
                                    </div>
                                    <div id="manageColumnsTab2">
                                    </div>
                                 </div>
                                <div class="panel-body" > 
                         
                                <form action="<?php $this->url('certification', array('action' => 'certification-expiry')); ?>" name="form" method="post" >
                                    <div class="col-lg-6">
                                        <label for="Country">Country</label>
                                        <select name="Country-tab2" class="form-control" autocomplete="off" id="Country-tab2" onclick="emptyInput(this)" onchange="showRegion2(this.value,'online')">
                                            <option value="" selected>Please Choose a Country</option>
                                            <?php foreach($country as $crow) { ?>
                                                <option value="<?php echo $crow['country_id'];?>" <?php echo ($crow['country_id'] == 1)?"selected='selected'":'';?>><?php echo $crow['country_name'];?></option>
                                            <?php } ?>
                                        </select>                            
                                    </div>

                                    <div class="col-lg-6">
                                        <label for="Region">Province</label>
                                        <select name="region-tab2" class="form-control" autocomplete="off" id="Region-tab2" onclick="emptyInput(this)" onchange="showDistrict2(this.value,'online')">
                                            <option value="">Please choose a Country</option>
                                        </select>                                                                    
                                    </div>
                                    <div class="col-lg-6">
                                        <label for="District">Districts</label>
                                        <select name="district-tab2" class="form-control" id="District-tab2" autocomplete="off" onclick="emptyInput(this)">
                                            <option value="">Please Choose a District</option>
                                        </select>                                                                    
                                    </div>
                                    
                                    <div class="col-lg-12" style="margin-top: 30px;text-align:center;">
                                    <input type="hidden" id="certificationExpiryVal" name="certificationExpiryVal" value="remindersSent">
                                        
                                        <a class="btn btn-space btn-primary" href="javascript:void(0);"  onclick="searchAllOrderData();">GET REPORT</a>
                                        <button type="submit" class="btn btn-space btn-primary">DOWNLOAD REPORT</button>
                                        <a class="btn btn-space btn-default" role="button" href="<?php echo $this->url('examination', array('action' => 'xls')); ?>" >CANCEL</a>
                                    </div>
                                </form>
                                <div id="online-exam"></div>  
                                </br>
                                </br>
                                </br>                                 
                                    <div id="remindersSentData">

                                    <table id="remindersSent-table" class="datatables table table-bordered table-responsive table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                                        <thead>
                                        <tr class="allColumnsTab2">
                                                    <th style="width:10%;">Tester</th>
                                                    <th style="width:10%;">Final Decision</th>
                                                    <th style="width:10%;">Region</th>
                                                    <th style="width:10%;">District</th>
                                                    <th style="width:10%;">Facility</th>
                                                    <th style="width:10%;">Type HIV testing modality/point</th>
                                                    <th style="width:10%;">Current job title</th>
                                                </tr>
                                        </thead>
                                        <tbody>
                              
                                        </tbody>
                                    </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="didNotRecertify" role="tabpanel" aria-labelledby="written-tab">
                <div class="widget widget-fullwidth widget-small" style="padding:5px;">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                            <div class="well container">
                                    <div class="row" style="margin-bottom:15px;margin-left:9px;">
                                    <h3>Manage Columns  &nbsp;<a href="javascript:void(0)" id="shBtnManageColumnsTab3">Show/hide</a></h3> 
                                    </div>
                                    <div id="manageColumnsTab3">
                                    </div>
                                 </div>
                              <div class="panel-body" >
                                <form action="<?php $this->url('certification', array('action' => 'certification-expiry')); ?>" name="form" method="post" >
                                    <div class="col-lg-6">
                                        <label for="Country">Country</label>
                                        <select name="country-tab3" class="form-control" autocomplete="off" id="Country-tab3" onclick="emptyInput(this)" onchange="showRegion3(this.value,'online')">
                                            <option value="" selected>Please Choose a Country</option>
                                            <?php foreach($country as $crow) { ?>
                                                <option value="<?php echo $crow['country_id'];?>" <?php echo ($crow['country_id'] == 1)?"selected='selected'":'';?>><?php echo $crow['country_name'];?></option>
                                            <?php } ?>
                                        </select>                            
                                    </div>

                                    <div class="col-lg-6">
                                        <label for="Region">Province</label>
                                        <select name="region-tab3" class="form-control" autocomplete="off" id="Region-tab3" onclick="emptyInput(this)" onchange="showDistrict3(this.value,'online')">
                                            <option value="">Please choose a Country</option>
                                        </select>                                                                    
                                    </div>
                                    <div class="col-lg-6">
                                        <label for="District">Districts</label>
                                        <select name="district-tab3" class="form-control" id="District-tab3" autocomplete="off" onclick="emptyInput(this)">
                                            <option value="">Please Choose a District</option>
                                        </select>                                                                    
                                    </div>
                                    <input type="hidden" id="Exam" name="Exam" value="online-exam">
                                    <div class="col-lg-12" style="margin-top: 30px;text-align:center;">
                                    
                                    <input type="hidden" id="certificationExpiryVal" name="certificationExpiryVal" value="didNotRecertify">
                                        
                                        <a class="btn btn-space btn-primary" href="javascript:void(0);"  onclick="searchAllOrderData();">GET REPORT</a>
                                        <button type="submit" class="btn btn-space btn-primary">DOWNLOAD REPORT</button>
                                        <a class="btn btn-space btn-default" role="button" href="<?php echo $this->url('examination', array('action' => 'xls')); ?>" >CANCEL</a>
                                    </div>
                                </form>
                                <div id="online-exam"></div>
                                    </br>
                                    </br>
                                    </br>
                                    <div id="didNotRecertifyData">

                                        <table id="didNotRecertify-table" class="datatables table table-bordered table-responsive table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                                            <thead>
                                            <tr class="allColumnsTab3">
                                            <th style="width:10%;">Tester</th>
                                                        <th style="width:10%;">Final Decision</th>
                                                        <th style="width:10%;">Region</th>
                                                        <th style="width:10%;">District</th>
                                                        <th style="width:10%;">Facility</th>
                                                        <th style="width:10%;">Type HIV testing modality/point</th>
                                                        <th style="width:10%;">Current job title</th>
                                                    </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
       
    </div>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

    <script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


    <script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/certification.js'); ?>"></script>
    <script>
    aTable = null;
	bTable = null;
	cTable = null;

    $(document).ready(function () {
        $("#Country").val(1);
        $("#Country-tab2").val(1);
        $("#Country-tab3").val(1);
        showRegion(1);
        showRegion2(1);
        showRegion3(1);
        

        var listOfColumnsTab1 = '';
        $('tr.allColumnsTab1').each(function(){  
            $(this).find('th').each(function(index){
                listOfColumnsTab1+='<a class="toggle-vis-allColumnsTab1 btn btn-primary btn-sm" data-column="'+index+'" onclick="toggleBtnClassTab1(this)"> <span class="btn-label"><i class="glyphicon glyphicon-ok"></i></span> '+$(this).text()+'</a> &nbsp;'
            });
        }); 
        $("#manageColumnstab1").html(listOfColumnsTab1);

        aTable =$('#upForRecertification-table').dataTable({
                "bAutoWidth": false,
                    "bProcessing": true,
                    "bServerSide": true,
                    "bStateSave": true,
                    "aoColumns": [
                    <?php echo $editActionTab1;?>
                        ],
                "aaSorting": [[0, "asc" ]],
                    "sAjaxSource": "<?php echo $this->url('certification',array('action' => 'get-expiry-certificate-reports')); ?>",
                    "fnServerData": function ( sSource, aoData, fnCallback ) {
                            aoData.push({ "name": "region", "value":  $("[name=region]").val() });
                            aoData.push({ "name": "district", "value": $("[name=district]").val() });
                            aoData.push({ "name": "country_id", "value":$("[name=country]").val() });
                            aoData.push({ "name": "expirycertification", "value": 'upForRecertification' });
                            $.ajax({
                                "dataType": 'json',
                                "type": "POST",
                                "url": sSource,
                                "data": aoData,
                                "success": fnCallback
                            });
                        }
                });


        $('a.toggle-vis-allColumnsTab1').on( 'click', function (e) {
            e.preventDefault(); 
            // Get the column API object
            var column = aTable.column( $(this).attr('data-column') ); 
            // Toggle the visibility
            column.visible( ! column.visible() );
            $("#provider_wrapper").css("overflow-x","scroll");
        });
        $("#manageColumnstab1").hide();
        $("#shBtnManageColumnstab1").click(function(){
            $("#manageColumnstab1").toggle('fast','linear');
        });



        var listOfColumnsTab2 = '';
        $('tr.allColumnsTab2').each(function(){  
            $(this).find('th').each(function(index){
                listOfColumnsTab2+='<a class="toggle-vis-allColumnsTab2 btn btn-primary btn-sm" data-column="'+index+'" onclick="toggleBtnClassTab2(this)"> <span class="btn-label"><i class="glyphicon glyphicon-ok"></i></span> '+$(this).text()+'</a> &nbsp;'
            });
        }); 
        $("#manageColumnsTab2").html(listOfColumnsTab2);

		bTable = $('#remindersSent-table').dataTable({
                "bAutoWidth": false,
                    "bProcessing": true,
                    "bServerSide": true,
                    "bStateSave": true,
                    "aoColumns": [
                    <?php echo $editActionTab2;?>
                        ],
                "aaSorting": [[0, "asc" ]],
                    "sAjaxSource": "<?php echo $this->url('certification',array('action' => 'get-expiry-certificate-reports')); ?>",
                    "fnServerData": function ( sSource, aoData, fnCallback ) {
                            aoData.push({ "name": "region", "value":  $("[name=region-tab2]").val() });
                            aoData.push({ "name": "district", "value": $("[name=district--tab2]").val() });
                            aoData.push({ "name": "country_id", "value":$("[name=country-tab2]").val() });
                            aoData.push({ "name": "expirycertification", "value": 'remindersSent' });
                            $.ajax({
                                "dataType": 'json',
                                "type": "POST",
                                "url": sSource,
                                "data": aoData,
                                "success": fnCallback
                            });
                        }
                });
         
        

        $('a.toggle-vis-allColumnsTab2').on( 'click', function (e) {
        e.preventDefault(); 
        // Get the column API object
        var columnTab2 = bTable.column( $(this).attr('data-column') ); 
        // Toggle the visibility
        columnTab2.visible( ! columnTab2.visible() );
        $("#provider_wrapper").css("overflow-x","scroll");
        });
        $("#manageColumnsTab2").hide();
        $("#shBtnManageColumnsTab2").click(function(){
            $("#manageColumnsTab2").toggle('fast','linear');
        });
        


        var listOfColumnsTab3 = '';
        $('tr.allColumnsTab3').each(function(){  
            $(this).find('th').each(function(index){
                listOfColumnsTab3+='<a class="toggle-vis-allColumnsTab3 btn btn-primary btn-sm" data-column="'+index+'" onclick="toggleBtnClassTab3(this)"> <span class="btn-label"><i class="glyphicon glyphicon-ok"></i></span> '+$(this).text()+'</a> &nbsp;'
            });
        }); 
        $("#manageColumnsTab3").html(listOfColumnsTab3);

		cTable = $('#didNotRecertify-table').dataTable({
                "bAutoWidth": false,
                    "bProcessing": true,
                    "bServerSide": true,
                    "bStateSave": true,
                    "aoColumns": [
                    <?php echo $editActionTab3;?>
                        ],
                "aaSorting": [[0, "asc" ]],
                    "sAjaxSource": "<?php echo $this->url('certification',array('action' => 'get-expiry-certificate-reports')); ?>",
                    "fnServerData": function ( sSource, aoData, fnCallback ) {
                            aoData.push({ "name": "region", "value":  $("[name=region-tab3]").val() });
                            aoData.push({ "name": "district", "value": $("[name=district-tab3]").val() });
                            aoData.push({ "name": "country_id", "value":$("[name=country-tab3]").val() });
                            aoData.push({ "name": "expirycertification", "value": 'didNotRecertify' });
                            $.ajax({
                                "dataType": 'json',
                                "type": "POST",
                                "url": sSource,
                                "data": aoData,
                                "success": fnCallback
                            });
                        }
                });

        $('a.toggle-vis-allColumnsTab3').on( 'click', function (e) {
        e.preventDefault(); 
        // Get the column API object
        var columnTab3 = cTable.column( $(this).attr('data-column') ); 
        // Toggle the visibility
        columnTab3.visible( ! columnTab3.visible() );
        $("#provider_wrapper").css("overflow-x","scroll");
        });
        $("#manageColumnsTab3").hide();
        $("#shBtnManageColumnsTab3").click(function(){
            $("#manageColumnsTab3").toggle('fast','linear');
        });
        

	} );
    $('#dateRange').daterangepicker({
        format: 'DD-MM-YYYY',
        startDate: moment().subtract('days', 29),
        endDate: moment(),
        maxDate: moment(),
        ranges: {
            'Today': [moment(), moment()],
            'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
            'Last 7 Days': [moment().subtract('days', 6), moment()],
            'Last 30 Days': [moment().subtract('days', 29), moment()],
            'This Month': [moment().startOf('month'), moment().endOf('month')],
            'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
        },
    });

    function showRegion(str) {
            if (str == "") {
               document.getElementById("Region").innerHTML = "<option value=''>All</option>";
               document.getElementById("District").innerHTML = "<option value=''>All</option>";
            //    document.getElementById("Facility Name").innerHTML = "<option value=''>All</option>";
              return false;
            }else{
                $.post("<?php echo $this->url('provider', array('action' => 'region')); ?>", {q: str},
                function(data) {
                   document.getElementById("Region").innerHTML = data;
                   document.getElementById("District").innerHTML = "<option value=''>All</option>";
                //    document.getElementById("Facility Name").innerHTML = "<option value=''>All</option>";
                });
            }
    }
    function showRegion2(str) {
            if (str == "") {
               document.getElementById("Regioni-tab2").innerHTML = "<option value=''>All</option>";
               document.getElementById("District-tab2").innerHTML = "<option value=''>All</option>";
            //    document.getElementById("Facility Name-tab2").innerHTML = "<option value=''>All</option>";
              return false;
            }else{
                $.post("<?php echo $this->url('provider', array('action' => 'region')); ?>", {q: str},
                function(data) {
                   document.getElementById("Region-tab2").innerHTML = data;
                   document.getElementById("District-tab2").innerHTML = "<option value=''>All</option>";
                //    document.getElementById("Facility Name-tab2").innerHTML = "<option value=''>All</option>";
                });
            }
    }
    function showRegion3(str) {
            if (str == "") {
               document.getElementById("Region-tab3").innerHTML = "<option value=''>All</option>";
               document.getElementById("District-tab3").innerHTML = "<option value=''>All</option>";
            //    document.getElementById("Facility Name-tab3").innerHTML = "<option value=''>All</option>";
              return false;
            }else{
                $.post("<?php echo $this->url('provider', array('action' => 'region')); ?>", {q: str},
                function(data) {
                   document.getElementById("Region-tab3").innerHTML = data;
                   document.getElementById("District-tab3").innerHTML = "<option value=''>All</option>";
                //    document.getElementById("Facility Name-tab3").innerHTML = "<option value=''>All</option>";
                });
            }
    }
    
    function showDistrict(str) {
        if (str == "") {
            document.getElementById("District").innerHTML = "";
            return;
        } else {
            if (window.XMLHttpRequest) {
                // code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            } else {
                // code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("District").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'district')); ?>?q=" + str, true);
            xmlhttp.send();
        }
    }

    function showFacilities(str) {
        if (str == "") {
            document.getElementById("Facility Name").innerHTML = "";
            return;
        } else {
            if (window.XMLHttpRequest) {
                // code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            } else {
                // code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("Facility Name").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'facility')); ?>?q=" + str, true);
            xmlhttp.send();
        }
    }


        function searchAllOrderData(){
            $.blockUI();
            aTable.fnDraw();
            bTable.fnDraw();
            cTable.fnDraw();
            $.unblockUI();
        }

           /* Toggles Color of button */
    function toggleBtnClassTab1(btnObj){
        $(btnObj).toggleClass("btn-default");
        var children = btnObj.childNodes;
        var iconTag = children[1].firstChild;
        $(iconTag).toggleClass("glyphicon-remove");
    }

           /* Toggles Color of button */
    function toggleBtnClassTab2(btnObj){
        $(btnObj).toggleClass("btn-default");
        var children = btnObj.childNodes;
        var iconTag = children[1].firstChild;
        $(iconTag).toggleClass("glyphicon-remove");
    }

           /* Toggles Color of button */
    function toggleBtnClassTab3(btnObj){
        $(btnObj).toggleClass("btn-default");
        var children = btnObj.childNodes;
        var iconTag = children[1].firstChild;
        $(iconTag).toggleClass("glyphicon-remove");
    }

    </script>

