<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
// die("test");
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-4"> <h2> Expiry Certification Reports</h2></div>
        </div>
    </div>
    <div class="main-content">
    <ul class="nav nav-tabs" id="examinationTab" role="tablist">
            <li class="nav-item active">
                <a class="nav-link active" id="upForRecertification-tab" data-toggle="tab" href="#upForRecertification" role="tab" aria-controls="upForRecertification" aria-selected="false" onclick="getReportOnlineTest('upForRecertification');">Up for Recertification</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="remindersSent-tab" data-toggle="tab" href="#remindersSent" role="tab" aria-controls="remindersSent" aria-selected="true" onclick="getReportOnlineTest('remindersSent');">Reminders Sent</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="didNotRecertify-tab" data-toggle="tab" href="#didNotRecertify" role="tab" aria-controls="didNotRecertify" aria-selected="false" onclick="getReportOnlineTest('didNotRecertify');">Did not recertify</a>
            </li>
        </ul>
        <div class="tab-content" id="examinationContent">
            <div class="tab-pane active" id="upForRecertification" role="tabpanel" aria-labelledby="online-tab">
                <div class="widget widget-fullwidth widget-small" style="padding:5px;">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <div class="panel-body" >
                                    
                                    <div id="upForRecertification">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="remindersSent" role="tabpanel" aria-labelledby="practical-tab">
                <div class="widget widget-fullwidth widget-small" style="padding:5px;">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <div class="panel-body" >
                                    
                                    <div id="remindersSent">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="didNotRecertify" role="tabpanel" aria-labelledby="written-tab">
                <div class="widget widget-fullwidth widget-small" style="padding:5px;">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <div class="panel-body" >
                                    <div id="didNotRecertify">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
       
    </div>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

    <script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


    <script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/certification.js'); ?>"></script>
    <script>
    $(document).ready(function () {
        $("#Country").val(1);
        showRegion(1);
        getReportOnlineTest('upForRecertification');
    });
    $('#dateRange').daterangepicker({
        format: 'DD-MM-YYYY',
        startDate: moment().subtract('days', 29),
        endDate: moment(),
        maxDate: moment(),
        ranges: {
            'Today': [moment(), moment()],
            'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
            'Last 7 Days': [moment().subtract('days', 6), moment()],
            'Last 30 Days': [moment().subtract('days', 29), moment()],
            'This Month': [moment().startOf('month'), moment().endOf('month')],
            'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
        },
    });

    function showRegion(str) {
            if (str == "") {
               document.getElementById("Region").innerHTML = "<option value=''>All</option>";
               document.getElementById("District").innerHTML = "<option value=''>All</option>";
               document.getElementById("Facility Name").innerHTML = "<option value=''>All</option>";
              return false;
            }else{
                $.post("<?php echo $this->url('provider', array('action' => 'region')); ?>", {q: str},
                function(data) {
                   document.getElementById("Region").innerHTML = data;
                   document.getElementById("District").innerHTML = "<option value=''>All</option>";
                   document.getElementById("Facility Name").innerHTML = "<option value=''>All</option>";
                });
            }
    }
    
    function showDistrict(str) {
        if (str == "") {
            document.getElementById("District").innerHTML = "";
            return;
        } else {
            if (window.XMLHttpRequest) {
                // code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            } else {
                // code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("District").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'district')); ?>?q=" + str, true);
            xmlhttp.send();
        }
    }

    function showFacilities(str) {
        if (str == "") {
            document.getElementById("Facility Name").innerHTML = "";
            return;
        } else {
            if (window.XMLHttpRequest) {
                // code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            } else {
                // code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("Facility Name").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'facility')); ?>?q=" + str, true);
            xmlhttp.send();
        }
    }

    function getReportOnlineTest(expirycertification){
        $('#'+expirycertification).html('');
        $.blockUI();
        $.post("<?php echo $this->url('certification', array('action' => 'get-expiry-certificate-report')); ?>", {
            expirycertification: expirycertification
        },function(data) {
            $('#'+expirycertification).html(data);
            var table = $('#'+expirycertification+'-table').DataTable({
                "aProcessing": true,
                "aServerSide": true,
                "aaSorting": [],
            });
        });
        $.unblockUI();
    }
    </script>

