<div class="widget widget-fullwidth widget-small" style="padding:5px;">
    <table id="certificateReportTable" class="datatables table table-bordered table-responsive table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
        <thead class="frezz">
            <tr class="allproviders">
                <th style="width:10%;">Tester</th>
                <th style="width:10%;">Professional Registration No.</th>
                <th style="width:10%;">Region</th>
                <th style="width:10%;">District</th>
                <th style="width:10%;">Facility</th>
                <th style="width:10%;">Final Decision</th>
                <th style="width:10%;">Type HIV testing modality/point</th>
                <th style="width:10%;">Current job title</th>
            </tr>
        </thead>
        <tbody class="frezz">
            <?php
                foreach ($this->result as $result) {
                    // \Zend\Debug\Debug::dump($result);die;
            ?>
                <tr>
                    <td><?php echo $this->escapeHtml($result['first_name'] . ' ' . $result['last_name ']); ?></td>
                    <td><?php echo $this->escapeHtml($result['professional_reg_no']); ?></td>
                    <td><?php echo $this->escapeHtml($result['region_name']); ?></td>
                    <td><?php echo $this->escapeHtml($result['district_name']); ?></td>
                    <td><?php echo $this->escapeHtml($result['facility_name']); ?></td>
                    <td><?php echo $this->escapeHtml($result['final_decision']); ?></td>
                    <td><?php echo $this->escapeHtml($result['type_vih_test']); ?></td>
                    <td><?php echo $this->escapeHtml($result['current_jod']); ?></td>
                    
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>