<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<style>
    .center{
        text-align:center;
    }
</style>
<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-8">
                <h2>List of Certifications</h2>
            </div>

        </div>
    </div>

    <div class="main-content">
        <ul class="nav nav-tabs" id="certificationTab" role="tablist">
            <li class="nav-item active">
              <input type="hidden" id="selectdeselect"/>  
              <a class="nav-link active" id="recommended-tab" data-toggle="tab" href="#recommended" role="tab" aria-controls="recommended" aria-selected="true">Recommended for Certification</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" id="to-be-sent-tab" data-toggle="tab" href="#to-be-sent" role="tab" aria-controls="to-be-sent" aria-selected="true">Certificates to be sent</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="certified-tab" data-toggle="tab" href="#certified" role="tab" aria-controls="certified" aria-selected="false">Certified Testers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="pending-tab" data-toggle="tab" href="#pending" role="tab" aria-controls="pending" aria-selected="false">Pending or Failed Testers</a>
            </li>
        </ul>
        <div class="tab-content" id="certificationContent">
          <div class="tab-pane active" id="recommended" role="tabpanel" aria-labelledby="recommended-tab">
            <table id="recommendedTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:100% !important;">
                <thead>
                    <tr>
                        <th></th>
                        <th  style="width:10%;">Professional Registration No <br> (if available) </th>
                        <th  style="width:10%;">Certification Registration no </th>
                        <th  style="width:10%;">Certification ID  </th>
                        <th  style="width:10%;">Provider</th>
                        <th  style="width:10%;">Final Decision</th>
                        <th  style="width:10%;">Certificate Issuer</th>
                        <th  style="width:10%;">Date Certificate Issued</th>
                        <th style="width:10%;">Date Certificate Sent</th>
                        <th style="width:10%;">Type of Certification</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
          </div>
          <div class="tab-pane" id="to-be-sent" role="tabpanel" aria-labelledby="to-be-sent-tab">
            <table id="toBeSentTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:100% !important;">
                <thead>
                    <tr>
                        <th  style="width:10%;">Professional Registration No <br> (if available) </th>
                        <th  style="width:10%;">Certification Registration no </th>
                        <th  style="width:10%;">Certification ID  </th>
                        <th  style="width:10%;">Provider</th>
                        <th  style="width:10%;">Final Decision</th>
                        <th  style="width:10%;">Certificate Issuer</th>
                        <th  style="width:10%;">Date Certificate Issued</th>
                        <th style="width:10%;">Date Certificate Sent</th>
                        <th style="width:10%;">Type of Certification</th> 
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'pdf')) { ?>
                            <th style="width:5%;">Download PDF</th>
                        <?php } ?>
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\CertificationMail', 'index')) { ?>
                            <th style="width:5%;">E-Mail Certificate</th>
                        <?php } ?>
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\CertificationMail', 'index')) { ?>
                            <th style="width:5%;">Update Status</th>
                        <?php } ?>

                    </tr>

                </thead>
                <tbody>

                    <?php foreach ($certifications3 as $certification) : ?>
                        <tr><td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->professional_reg_no); ?></div></td>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->certification_reg_no); ?></div></td>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->certification_id); ?></div></td>
                            <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->last_name . ' ' . $certification->first_name . ' ' . $certification->middle_name); ?></div></td>
                            <td><div style="width:100px;height:40px;overflow:auto; color: red"><?php echo $this->escapeHtml($certification->final_decision); ?></div></td>
                            <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->certification_issuer); ?></div></td>
                            <td><div style="width:100px;height:40px;overflow:auto;"><?php echo date("d-m-Y", strtotime($this->escapeHtml($certification->date_certificate_issued))); ?></div></td>
                            <?php
                            if (isset($certification->date_certificate_sent) && $certification->date_certificate_sent!= null && $certification->date_certificate_sent!= '' && $certification->date_certificate_sent!= '0000-00-00') {
                                echo ' <td><div style="width:100px;height:40px;overflow:auto;">' . date("d-m-Y", strtotime($this->escapeHtml($certification->date_certificate_sent))) . '</div></td>';
                            } else {
                                echo ' <td><div style="width:100px;height:40px;overflow:auto;"></div></td>';
                            };
                            ?>

                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->certification_type); ?></div></td>
                            <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'pdf')) { ?>
                                <?php
                                if (strcasecmp($certification->final_decision, 'Certified') == 0) {

                                    echo "<td><div style='width:80px;height:40px;overflow:auto;'>
                                        <a href=" . $this->url('certification', array('action' => 'pdf'), array('query' => array(base64_encode('id') => base64_encode($certification->id), base64_encode('last') => base64_encode($certification->last_name), base64_encode('first') => base64_encode($certification->first_name), base64_encode('middle') => base64_encode($certification->middle_name), base64_encode('professional_reg_no') => base64_encode($certification->professional_reg_no), base64_encode('certification_id') => base64_encode($certification->certification_id), base64_encode('date_issued') => base64_encode($certification->date_certificate_issued))
                                    )) .
                                    " target='_blank'><span class='glyphicon glyphicon-download-alt'>PDF</span></a> 
                                    </div>
                                </td> ";
                                } else {

                                    echo "<td><div >
                                        <span class='glyphicon glyphicon-download-alt'>PDF</span>
                                    </div>
                                </td> ";
                                }
                                ?>
                            <?php } ?>
                            <?php if ($acl->isAllowed($role, 'Certification\Controller\CertificationMail', 'index')) { ?>
                                <td> <div style='width:120px;height:40px;overflow:auto;'><a href="<?php echo $this->url('certification-mail', array('action' => 'index'), array('query' => array(base64_encode('email') => base64_encode($certification->email), base64_encode('certification_id') => base64_encode($certification->id), base64_encode('provider') => base64_encode($certification->last_name . ' ' . $certification->first_name . ' ' . $certification->middle_name), base64_encode('facility_in_charge_email') => base64_encode($certification->facility_in_charge_email), base64_encode('key2') => base64_encode('key')))); ?>"><span class="glyphicon glyphicon-envelope"></span>&nbsp;Send Certificate</a></div> </td>
                            <?php } ?>  
                            <?php if ($acl->isAllowed($role, 'Certification\Controller\CertificationMail', 'index')) { ?>
                                <td> <div style='width:120px;height:40px;overflow:auto;' onclick="if (!confirm('Do you really want to mark this certificate as sent?')) {
                                            return false;
                                        }" name="via_mail"><a  href="<?php echo $this->url('certification', array('action' => 'index'), array('query' => array(base64_encode('certification_id') => base64_encode($certification->id), base64_encode('key') => base64_encode('key')))); ?>"><span class="glyphicon glyphicon-send"></span>&nbsp;Mark as sent</a></div> </td>
                                      <?php } ?>  
                        </tr>
                        <?php
                    endforeach;
                    ?>
                </tbody>
            </table>
          </div>
          <div class="tab-pane fade" id="certified" role="tabpanel" aria-labelledby="certified-tab">
            <table id="certifiedTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget"  style="width:100% !important;">
                <thead>
                    <tr >
                        <th  style="width:10%;">Professional Registration No(if available </th>
                        <th  style="width:10%;">Certification Registration no </th>
                        <th  style="width:10%;">Certification ID  </th>
                        <th  style="width:10%;">Provider</th>
                        <th  style="width:10%;">Final Decision</th>
                        <th  style="width:10%;">Certificate Issuer</th>
                        <th  style="width:10%;">Date Certificate Issued</th>
                        <th style="width:10%;">Date Certificate Sent</th>
                        <th style="width:10%;">Type of Certification</th> 
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'edit')) { ?>
                            <th style="width:5%;">Edit</th>
                        <?php } ?>
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'pdf')) { ?>
                            <th style="width:5%;">PDF</th>
                        <?php } ?>
                    </tr>

                </thead>
                <tbody>

                    <?php foreach ($certifications as $certification) : ?>
                        <tr><td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->professional_reg_no); ?></div></td>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->certification_reg_no); ?></div></td>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->certification_id); ?></div></td>
                            <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->last_name . ' ' . $certification->first_name . ' ' . $certification->middle_name); ?></div></td>
                            <td><div style="width:100px;height:40px;overflow:auto; color: red"><?php echo $this->escapeHtml($certification->final_decision); ?></div></td>
                            <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->certification_issuer); ?></div></td>
                            <td><div style="width:100px;height:40px;overflow:auto;"><?php echo date("d-m-Y", strtotime($this->escapeHtml($certification->date_certificate_issued))); ?></div></td>
                            <?php
                            if (isset($certification->date_certificate_sent) && $certification->date_certificate_sent!= null && $certification->date_certificate_sent!= '' && $certification->date_certificate_sent!= '0000-00-00') {
                                echo ' <td><div style="width:100px;height:40px;overflow:auto;">' . date("d-m-Y", strtotime($this->escapeHtml($certification->date_certificate_sent))) . '</div></td>';
                            } else {
                                echo ' <td><div style="width:100px;height:40px;overflow:auto;"></div></td>';
                            };
                            ?>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->certification_type); ?></div></td>
                            <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'edit')) { ?>
                                <td>
                                    <div style="width:80px;height:40px;overflow:auto;">
                                        <a href="<?php echo $this->url('certification', array('action' => 'edit', 'id' => base64_encode($certification->id))); ?>"><span class="glyphicon glyphicon-pencil">Edit</span></a> 
                                    </div>
                                </td>
                            <?php } ?>

                            <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'pdf')) { ?>
                                <?php
                                if (strcasecmp($certification->final_decision, 'Certified') == 0) {

                                    echo "<td><div style='width:80px;height:40px;overflow:auto;'>
                                        <a href=" . $this->url('certification', array('action' => 'pdf'), array('query' => array(base64_encode('id') => base64_encode($certification->id), base64_encode('last') => base64_encode($certification->last_name), base64_encode('first') => base64_encode($certification->first_name), base64_encode('middle') => base64_encode($certification->middle_name), base64_encode('professional_reg_no') => base64_encode($certification->professional_reg_no), base64_encode('certification_id') => base64_encode($certification->certification_id), base64_encode('date_issued') => base64_encode($certification->date_certificate_issued))
                                    )) . " target='_blank'><span class='glyphicon glyphicon-download-alt'>PDF</span></a> 
                                    </div>
                                </td> ";
                                } else {

                                    echo "<td><div >
                                        <span class='glyphicon glyphicon-download-alt'>PDF</span>
                                    </div>
                                </td> ";
                                }
                                ?>
                            <?php } ?>

                        </tr>
                        <?php
                    endforeach;
                    ?>
                </tbody>
            </table>
          </div>
          <div class="tab-pane fade" id="pending" role="tabpanel" aria-labelledby="pending-tab">
            <table id="pendingTable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget"  style="width:100% !important;">
                <thead>
                    <tr>
                        <th  style="width:100% !important;">Professional Registration No.<br>(if available) </th>
                        <th  style="width:30%;">Certification Registration no. </th>
                        <th  style="width:30%;">Certification ID  </th>
                        <th  style="width:10%;">Provider</th>
                        <th  style="width:10%;">Final Decision</th>
                        <!--<th  style="width:10%;">Certificate Issuer</th>-->
                        <!--<th  style="width:10%;">Date Certificate Issued</th>-->
                        <!--<th style="width:10%;">Date Certificate Sent</th>-->
                        <th style="width:10%;">Type of Certification</th> 
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'edit')) { ?>
                            <th style="width:5%;">Edit</th>
                        <?php } ?>
                    </tr>

                </thead>
                <tbody>

                    <?php foreach ($certifications2 as $certification) : ?>
                        <tr>
                        <td><?php echo $this->escapeHtml($certification->professional_reg_no); ?></td>
                            <td><?php echo $this->escapeHtml($certification->certification_reg_no); ?></td>
                            <td><?php echo $this->escapeHtml($certification->certification_id); ?></td>
                            <td><?php echo $this->escapeHtml($certification->last_name . ' ' . $certification->first_name . ' ' . $certification->middle_name); ?></td>
                            <td style="color: red"><?php echo $this->escapeHtml($certification->final_decision); ?></td>
                            <!--<td><div style="width:180px;height:40px;overflow:auto;"><?php // echo $this->escapeHtml($certification->certification_issuer);  ?></div></td>-->
                            <!--<td><div style="width:100px;height:40px;overflow:auto;"><?php // echo date("d-m-Y", strtotime($this->escapeHtml($certification->date_certificate_issued)));  ?></div></td>-->
                            <?php
//                            if (isset($certification->date_certificate_sent) && $certification->date_certificate_sent!= null && $certification->date_certificate_sent!= '' && $certification->date_certificate_sent!= '0000-00-00') {
//                                echo ' <td><div style="width:100px;height:40px;overflow:auto;">' . date("d-m-Y", strtotime($this->escapeHtml($certification->date_certificate_sent))) . '</div></td>';
//                            } else {
//                                echo ' <td><div style="width:100px;height:40px;overflow:auto;"></div></td>';
//                            };
                            ?>
                            <td><?php echo $this->escapeHtml($certification->certification_type); ?></td>
                            <?php if ($acl->isAllowed($role, 'Certification\Controller\Certification', 'edit')) { ?>
                                <td>
                                    
                                        <a href="<?php echo $this->url('certification', array('action' => 'edit', 'id' => base64_encode($certification->id))); ?>"><span class="glyphicon glyphicon-pencil">Edit</span></a> 
                                    
                                </td>
                            <?php } ?>


                        </tr>
                        <?php
                    endforeach;
                    ;
                    ?>
                </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" language="javascript" >
$('#certificationTab a').on('click', function (e) {
  e.preventDefault()
  $(this).tab('show')
})

var recommendedTable = null;
approvalRow = [];
$(document).ready(function () {
    recommendedForCertificateInit();
    toBeSentInit();
    certifiedInit();
    pendingInit();
});

function recommendedForCertificateInit(){
    recommendedTable = $('#recommendedTable').DataTable({
        "bScrollCollapse": false,
        "bRetrieve": false,
        "bDestroy": true,
        "pageLength": 50,
        "aoColumns": [
                {"sClass":"center","bSortable":false},
		{"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":""}
        ],
        "aaSorting": [[ 1, "asc" ]],
        "fnDrawCallback": function( oSettings ) {
            $('input:checkbox').each(function () {
                if($.inArray(this.value, approvalRow)!= -1){
                    $('#'+this.id).prop('checked',true);
                }
                if($('#selectdeselect').val() == 'deselect'){
                    $('#'+this.id).prop('checked',false);
                }
            });
        },
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?php echo $this->url('certification',array('action' => 'recommended')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
            $.ajax({
                "dataType": 'json',
                "type": "POST",
                "url": sSource,
                "data": aoData,
                "success": fnCallback
            });
        }
    });
}

function toBeSentInit(){
    $('#toBeSentTable').dataTable();
}
function certifiedInit(){
    $('#certifiedTable').dataTable();
}
function pendingInit(){
    $('#pendingTable').dataTable();
}

function selectForApproval(obj){
    var rowId = $(obj).attr('id');
    var rowValue = $(obj).attr('value');
    if($('#'+rowId).is(':checked')){
       approvalRow.push(rowValue);
    }else{
       var examIndex = approvalRow.indexOf(rowValue);
       approvalRow.splice(examIndex, 1);
    }
    if(approvalRow.length == 0){
        $('#status,.manageApproval').hide();
        $('.selectdeselect').attr('onclick','selectForAllApproval()');
        $('.selectdeselect').text('Select All');
    }else{
        $('#status,.manageApproval').show();
        $('.selectdeselect').attr('onclick','deSelectForAllApporval()');
        $('.selectdeselect').text('Deselect All');
    }
    $('.selectedRows').html(approvalRow.length+' Row(s) Selected');
}

function selectForAllApproval(){
    approvalRow = [];  
    $('#selectdeselect').val('select');
    $('.approvalRow').prop('checked',true);
    var approvalIDs = $("#recommendedTable input:checkbox:checked").map(function(){
        return $(this).val();
      }).get();
    approvalRow = approvalIDs;
    if(approvalRow.length > 0){
        $('#status,.manageApproval').show();
        $('.selectdeselect').attr('onclick','deSelectForAllApporval()');
        $('.selectdeselect').text('Deselect All');
        $('.selectedRows').html(approvalRow.length+' Row(s) Selected');
    }else{
      alert('Data not available');
    }
}

function deSelectForAllApporval(){
    approvalRow = [];
    $('#status,.manageApproval').hide(); 
    $('#selectdeselect').val('deselect');
    $('.approvalRow').prop('checked',false);
    $('.selectdeselect').attr('onclick','selectForAllApproval()');
    $('.selectdeselect').text('Select All');
    $('.selectedRows').html(approvalRow.length+' Row(s) Selected');
}

function manageApproval(){
   if(approvalRow.length == 0){
        alert('Please select atleast one exam and then submit');
        return false;
    }else if($.trim($('#status').val()) == ''){
        alert('Please select status');
        return false;
    }else{
        $.post("<?php echo $this->url('certification',array('action'=>'approval')); ?>", {approvalRow:approvalRow,status:$('#status').val()},
        function(data){
            deSelectForAllApporval();
            recommendedTable.draw();
        });
    }
}

//Insert a raw HTML into data table
var count_elem = document.getElementById('recommendedTable');
var div = document.createElement('div');
div.innerHTML = '<span class="selectedRows">0  Row(s) Selected</span>&nbsp;&nbsp;&nbsp;&nbsp;<a class="btn btn-dark selectdeselect" href="javascript:void(0);" onclick="selectForAllApproval();" style="padding:4px;">Select All</a>&nbsp;&nbsp;&nbsp;&nbsp;<select id="status" title="Select Status" style="display:none;margin-right:1%;"><option value=""> -- Select -- </optin><option value="approved">Approve</optin><option value="rejected">Reject</optin></select><a class="btn btn-primary manageApproval" href="javascript:void(0);" onclick="manageApproval();" style="display:none;padding:4px;">Submit</a>';
count_elem.parentNode.insertBefore(div, count_elem);
</script>