<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/jasny-bootstrap.min.css'); ?>"/>

<style>
    label{
        font-weight: bold;
        font-size: 20px;
    }
</style>


<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-8">
                <h2>PDF Settings</h2>
            </div>
            <div class="col-sm-4">
                <?php if ($acl->isAllowed($role, 'Certification\Controller\Provider', 'add')) { ?>
                    <a href="<?php echo $this->url('certification', array('action' => 'pdf'), array('query' => array(base64_encode('last') => base64_encode('SARRI'), base64_encode('first') => base64_encode('HUBERT'), base64_encode('middle') => base64_encode('JASSIE JAMES'), base64_encode('professional_reg_no') => base64_encode('Ab-37-eg'), base64_encode('certification_id') => base64_encode(date('Y') . '-C000'), base64_encode('date_issued') => base64_encode(date('Y-m-d'))))); ?>" class="btn btn-success pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Test a PDF</a>
                <?php } ?>

            </div>
        </div>
    </div>

    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form role="form" class="form-horizontal" name="pdf-setting" id="pdf-setting" method="post" action="<?php echo $this->url('certification', array('action' => 'pdf-setting')); ?>" enctype="multipart/form-data" autocomplete="off" onsubmit="return validateForm()">
                                <div class="form-group">
                                    <div class="col-lg-3">
                                        <label for="" class=" control-label">Logo Left</label>
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                                <img src="" alt="Logo image"/>
                                                <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=No image"/>
                                            </div>
                                            <div>
                                                <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
                                                    <input type="file" id="logo_left" name="logo_left" title="Please select logo image" >
                                                </span>
                                            </div>
                                            <div class="box-body">
                                                Make sure the image is in <code>PNG format</code> and has a maximum size of: <code>425x352 pixels</code>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-lg-6">
                                        <label for="" class=" control-label">text relating to the ministry of supervision</label>
                                        <textarea rows="5" cols="60" id="header_text" name="header_text" maxlength="163"></textarea>
                                        <div class="box-body"> <code>Warning !</code> the number of characters is limited to <code>163.</code>  </div>

                                        <p class="btn btn-success" style="margin-top: 10px;" id="edit_header_text"  name ="edit_header_text" onclick="Edit();">Edit header text</p> 
                                        <span class="pull-right" id="characters" style="margin-top: 10px;" ></span> 
                                    </div>

                                    <div class="col-lg-3">
                                        <label for="" class="control-label">Logo Right</label>
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                                <img src="" alt="Logo image"/>
                                                <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=No image"/>
                                            </div>
                                            <div>
                                                <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
                                                    <input type="file" id="logo_right" name="logo_right" title="Please select logo image" >
                                                </span>
                                            </div>
                                            <div class="box-body">
                                                Make sure the image is in <code>PNG format</code> and has maximum a size of: <code>425x352 pixels</code> 
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-offset-5">
                                        <button type="submit" class="btn  btn-space btn-primary">VALIDATE</button>
                                        <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('certification', array('action' => 'pdf-setting')); ?>" >CANCEL</a> 
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script>
                                            var msg_logo_left = '<?php echo $this->msg_logo_left ?>';
                                            var msg_logo_right = '<?php echo $this->msg_logo_right; ?>';
                                            var msg_header_text = '<?php echo $this->msg_header_text; ?>';
</script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/pdfSetting.js'); ?>"></script>

<script>
                                            function Edit() {
                                                if (window.XMLHttpRequest) {
                                                    // code for IE7+, Firefox, Chrome, Opera, Safari
                                                    xmlhttp = new XMLHttpRequest();
                                                } else {  // code for IE6, IE5
                                                    xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                                                }
                                                xmlhttp.onreadystatechange = function () {
                                                    if (this.readyState == 4 && this.status == 200) {

                                                        if (window.DOMParser) {
                                                            // code for modern browsers
                                                            parser = new DOMParser();
                                                            htmlDoc = parser.parseFromString(this.responseText, "text/html");
                                                        } else {
                                                            // code for old IE browsers
                                                            htmlDoc = new ActiveXObject("Microsoft.HTMLDOM");
                                                            htmlDoc.async = false;
                                                            htmlDoc.load(text); 
                                                        }
//                                                       
                                                        var data = htmlDoc.getElementById("header_text").value;
                                                        document.getElementById("header_text").innerHTML = data;
                                                    }
                                                }
                                                xmlhttp.open("GET", "<?php echo $this->url('certification', array('action' => 'header-text')); ?>", true);
                                                xmlhttp.send();
                                            }
</script>

