<?php

use Zend\Debug\Debug;
// Debug::dump($provider);die;

// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {
    
}

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('RT CERTIFICATION');
$pdf->SetTitle('Personnel Certificate by RTCQI');
$pdf->SetSubject('Certificate');
$pdf->SetKeywords('RTCQI, HIV, Certificate, HIV Testing, RT CERTIFICATE');


// set margins
$pdf->SetMargins(10, 20, 10, true);
$pdf->SetHeaderMargin(0);
$pdf->SetFooterMargin(0);

// remove default footer
$pdf->setPrintFooter(false);

// set auto page breaks
//$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__) . '/lang/eng.php')) {
    require_once(dirname(__FILE__) . '/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// ---------------------------------------------------------
// set font
$pdf->SetFont('Helvetica', '', 20);
$pdf->setFontSubsetting(false);
// remove default header
$pdf->setPrintHeader(false);

// add a page
$pdf->AddPage('L', 'A4');

// -- set new background ---
$pdf->SetAutoPageBreak(false, 0);
// set bacground image
$img_file = dirname(__CLASS__) . 'public/assets/img/microsoft-word-certificate-borders.png';
$pdf->Image($img_file, 0, 0, 295, 209, '', '', '', false, 300, '', false, false, 0);
// set the starting point for the page content
$pdf->setPageMark();

$signatureText = ((isset($config_info['translate-register-title'])) && trim($config_info['translate-register-title'])!="")?$config_info['translate-register-title']:'Registrar';

$header_text = '<div style="color:#555555;text-align:center;font-size:'.$this->header_text_font_size.'px"><span>' . $this->header_text . '</span></div>';

$certificate_title = '';

// $tester='<div style="color:#4B77BE; font-size:70%; text-align:center;">&nbsp;&nbsp;'.strtoupper($first).' '. strtoupper($middle).' '. strtoupper($last).'&nbsp;&nbsp;</div>';
$text_content='
<div style="font-size:75%;text-align:left; line-height: 1.5;">
    <b>
    <br>
    Hereby Certifies That</b>
    <i>
            <br>
            <u>'.strtoupper($first).' '. strtoupper($middle).' '. strtoupper($last).'</u>
            <br><b>
            Having Successfully Fulfilled the Requirements of the Health Laboratory Practitioners"
            <br> 
            Council 
            <br> 
            Is Certified to be Competent in the Area of 
            <br>
        </b>
    </i>
    <br>
    <span style="text-align:center;" align="center">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <u style=" color:#EC7C30;font-size:25px;text-align:center;font-weight:800;"><b>HIV Rapid Testing</b></u>
    </span>
    <br>
    <i>
        <b>
            <span style="text-align:left;">
                <br>
                    Valid :
                    <u><span style=" color:#4B77BE;"> '.date("d-M-Y", strtotime($date_end_validity ." -{$config_info['month-valid']} month")).'</span> </u>
                        through 
                    <u><span style=" color:#4B77BE;">'.date("d-M-Y", strtotime($date_end_validity)) .'</span></u>
                    <br>
                        Professional Registration Number : <u><span style=" color:#4B77BE;">'.$professional_reg_no.'</span></u>
                    <br>
                    License No.: 
                    <u>
                        <span style=" color:#4B77BE; ">'.$certification_id.'</span>
                    </u>
            </span>
        </b>
    </i>
    <br>
    .......................
    <span style=" font-size:15px; ">'.$config_info['registrar-name'].'</b> '.$config_info['registrar-title'].'</span>
    <li>&nbsp;&nbsp;&nbsp;&nbsp;<code><b><span style=" font-size:15px; ">'.ucwords($signatureText).'</span></b></code></li>
    </div>';
    
// set different text position
$pdf->writeHTMLCell(0, 0, 10, 28, $header_text, 0, 0, 0, true, 'J', true);
$pdf->writeHTMLCell(0, 0, 15, 35, $certificate_title, 0, 0, 0, true, 'J', true);
// $pdf->writeHTMLCell(0, 0, 05, 68, $tester, 0, 0, 0, true, 'J', true);
$pdf->writeHTMLCell(0, 0, 40, 60, $text_content, 0, 0, 0, true, 'J', true);

$img_file = $img_file2 = $signature = "";

if(file_exists(dirname(__CLASS__) . 'public/uploads/logo/logo_cert1.png')){
    $img_file = dirname(__CLASS__) . 'public/uploads/logo/logo_cert1.png';

} else if(file_exists(dirname(__CLASS__) . 'public/assets/img/logo_cert1.png')){
    $img_file = dirname(__CLASS__) . 'public/assets/img/logo_cert1.png';
}

if(file_exists(dirname(__CLASS__) . 'public/uploads/logo/logo_cert2.png')){
    $img_file2 = dirname(__CLASS__) . 'public/uploads/logo/logo_cert2.png';

}else if(file_exists(dirname(__CLASS__) . 'public/assets/img/logo_cert2.png')){
    $img_file2 = dirname(__CLASS__) . 'public/assets/img/logo_cert2.png';
}

if(file_exists(dirname(__CLASS__) . 'public/uploads/digital_signature/'.$config_info['registrar-digital-signature'])){
    $signature = dirname(__CLASS__) . 'public/uploads/digital_signature/'.$config_info['registrar-digital-signature'];
}

$pathname = dirname(__CLASS__) . 'public/uploads' . DIRECTORY_SEPARATOR . "tester-proile" . DIRECTORY_SEPARATOR . $provider['providerId'] . DIRECTORY_SEPARATOR . 'pic';

if(isset($showProfile) && $showProfile == 'yes'){
    $pic = $pathname.DIRECTORY_SEPARATOR.$provider['profile_picture'];
    
    if(file_exists($pic)){
        $pdf->Image($pic, 237, 140, 40, 40, '', '', '', false, 300, '', false, false, 14);
    }   
}

$pdf->Image($img_file, 30, 28, 30, 23, '', '', '', false, 300, '', false, false, 0);

$pdf->Image($img_file2, 245, 28, 30, 23, '', '', '', false, 300, '', false, false, 0);

$pdf->Image($signature, 45, 147, 33, 18, '', '', '', false, 300, '', false, false, 0);
$pdf->SetAlpha(1);
///---------------------------------------------------------
//Close and output PDF document
$pdf->Output(ucfirst($last) . '' . ucfirst($first) . '' . ucfirst($middle) . '_HIVRT_Certification_' . date('Y') . '.pdf', 'I');
exit;
//============================================================+
// END OF FILE
//============================================================+