<?php
use Laminas\Session\Container;
$sessionLogin = new Container('credo');

$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<style>
    #shBtnManageColumns{
        font-size: 17px;
        font-weight: 600;
    }
   
</style>
<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-4"> <h2>Certification Reports</h2></div>
        </div>
    </div>
    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >
                            <form action="<?php $this->url('certification', array('action' => 'xls')); ?>" name="form" method="post" >
                                <div class=" form-group col-lg-6">
                                    <label for="date" class="col-sm-6 control-label">Date Range</label>
                                    <input type="text" placeholder="Select Date Range" class="form-control" id="dateRange" name="dateRange" readonly>
                                </div>
                                <div class="form-group col-lg-6"> 
                                    <label>Final Decision</label>
                                    <select class="form-control" name="decision" id="decision">
                                        <option value="">All</option>
                                        <option value="Certified">Certified</option>
                                        <option value="Pending">Pending</option>
                                        <option value="Failed">Failed</option>
                                    </select></div>
                                    <div class="form-group col-lg-6"> 
                                        <label>Type HIV testing modality/point</label>
                                        <select class="form-control" name="typeHIV" id="typeHIV">
                                            <option value="">All</option>
                                            <option value="ART clinic">ART clinic</option>
                                            <option value="Community">Community</option>
                                            <option value="IPD">IPD</option>
                                            <option value="LAB">LAB</option>
                                            <option value="OPD">OPD</option>
                                            <option value="PITC">PITC</option>
                                            <option value="PMTCT">PMTCT</option>
                                            <option value="STI clinic">STI clinic</option>
                                            <option value="TB clinic">TB clinic</option>
                                            <option value="VCT/HTC">VCT/HTC</option>

                                        </select>
                                    </div>

                                    <div class="form-group col-lg-6"> 
                                        <label>Current job title</label>
                                        <select class="form-control" name="jobTitle" id="jobTitle">
                                            <option value="">All</option>
                                            <option value="Assistant Medical Officer">Assistant Medical Officer</option>
                                            <option value="Counselor">Counselor</option>
                                            <option value="Health assistant">Health assistant</option>
                                            <option value="Health attendant">Health attendant</option>
                                            <option value="Lab Assistant">Lab Assistant</option>
                                            <option value="Lab Scientist">Lab Scientist</option>
                                            <option value="Lab technician">Lab technician</option>
                                            <option value="Lab technologist">Lab technologist</option>
                                            <option value="Medical doctor">Medical doctor</option>
                                            <option value="Midwife">Midwife</option>
                                            <option value="Nurse">Nurse</option>
                                            <option value="Nurse assistant">Nurse assistant</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-lg-6" style="display:none;"> 
                                        <label>Country</label>
                                        <select class="form-control" name="country" id="country" onchange="showRegion(this.value)">
                                            <option value="">All</option>
                                            <?php
                                            foreach ($countries as $key => $country) {
                                                echo ' <option value="' . $key . '">' . $country . '</option>';
                                            };
                                            ?>
                                        </select>
                                    </div>
                                    <div class="form-group col-lg-6"> 
                                        <label>Region</label>
                                        <select class="form-control" name="region" id="Region" onchange="showDistrict(this.value)">
                                            <option value="">All</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-lg-6"> 
                                        <label>District</label>
                                        <select class="form-control" name="district" id="District" onchange="showFacilities(this.value)">
                                            <option value="">All</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-lg-6" id="District"> 
                                        <label>Facility</label>
                                        <select class="form-control" name="facility" id="facility">
                                            <option value="">All</option>
                                        </select>
                                    </div>
                                    
                                    <div class="form-group col-lg-6"> 
                                        <label>Exclude Tester Name</label>
                                        <select class="form-control" name="exclude_tester_name" id="exclude_tester_name">
                                            <option value="">Please choose exclude tester name</option>
                                            <option value="yes">Yes</option>
                                            <option value="no">No</option>
                                        </select>
                                    </div>
                                    <div class="row" style="text-align:center;">
                                        <div class="form-group col-lg-12" style="margin-top: 30px">
                                            <a href="javascript:void(0)"  onclick="searchAllOrderData();" class="btn btn-primary">GET REPORT</a>
                                            <button class="btn btn-primary" type="submit">DOWNLOAD REPORT</button> 
                                            <a class="btn  btn-space btn-danger" role="button" style="margin-top: 5px" href="<?php echo $this->url('certification', array('action' => 'xls')); ?>" >CLEAR</a>
                                        </div>
                                    </div>
                            </form>
                            <div id="certificateReport">
                            <div class="well container">
                                    <div class="row" style="margin-bottom:15px;margin-left:9px;">
                                    <h3>Manage Columns  &nbsp;<a href="javascript:void(0)" id="shBtnManageColumns">Show/hide</a></h3> 
                                    </div>
                                    <div id="manageColumns">
                                    </div>
                                    </div>
                            <table id="certificateReportTable" class="datatables table table-bordered table-responsive table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                                <thead class="frezz">
                                <tr class="allrecertifications">
                                        <th style="width:10%;">Tester</th>
                                        <th style="width:10%;">Professional Registration No.</th>
                                        <th style="width:10%;">Region</th>
                                        <th style="width:10%;">District</th>
                                        <th style="width:10%;">Facility</th>
                                        <th style="width:10%;">Final Decision</th>
                                        <th style="width:10%;">Type HIV testing modality/point</th>
                                        <th style="width:10%;">Current job title</th>
                                    </tr>
                                </thead>
                                <tbody class="frezz">
                                
                                </tbody>
                            </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

    <script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


    <script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/certification.js'); ?>"></script>
    <script>
        oTable = null;
    $(document).ready(function () {
        $("#Country").val(1);
        showRegion(1);

        var listOfColumns = '';
        $('tr.allrecertifications').each(function(){  
            $(this).find('th').each(function(index){
                listOfColumns+='<a class="toggle-vis-allrecertifications btn btn-primary btn-sm" data-column="'+index+'" onclick="toggleBtnClass(this)"> <span class="btn-label"><i class="glyphicon glyphicon-ok"></i></span> '+$(this).text()+'</a> &nbsp;'
            });
        }); 
        $("#manageColumns").html(listOfColumns);

        oTable=$('#certificateReportTable').dataTable({
	"bAutoWidth": false,
        "bProcessing": true,
        "bServerSide": true,
		"bStateSave": true,
         "aoColumns": [
		<?php echo $editAction;?>
            ],
	"aaSorting": [[0, "asc" ]],
        "sAjaxSource": "<?php echo $this->url('certification',array('action' => 'get-certificate-reports')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
                aoData.push({ "name": "dateRange", "value": $("#dateRange").val() });
                aoData.push({ "name": "decision", "value": $("#decision").val() });
                aoData.push({ "name": "typeHIV", "value": $("#typeHIV").val() });
                aoData.push({ "name": "jobTitle", "value": $("#jobTitle").val() });
                aoData.push({ "name": "exclude_tester_name", "value": $("#exclude_tester_name").val() });
                aoData.push({ "name": "region", "value": $("#Region").val() });
                aoData.push({ "name": "district", "value": $("#District").val() });
                aoData.push({ "name": "facility_id", "value": $("#facility").val() });
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
       });


       $('a.toggle-vis-allrecertifications').on( 'click', function (e) {
            e.preventDefault(); 
            // Get the column API object
            var column = oTable.column( $(this).attr('data-column') ); 
            // Toggle the visibility
            column.visible( ! column.visible() );
            $("#provider_wrapper").css("overflow-x","scroll");
        });
        $("#manageColumns").hide();
        $("#shBtnManageColumns").click(function(){
            $("#manageColumns").toggle('fast','linear');
        });


    });
    $('#dateRange').daterangepicker({
        format: 'DD-MM-YYYY',
        startDate: moment().subtract('days', 29),
        endDate: moment(),
        maxDate: moment(),
        ranges: {
            'Today': [moment(), moment()],
            'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
            'Last 7 Days': [moment().subtract('days', 6), moment()],
            'Last 30 Days': [moment().subtract('days', 29), moment()],
            'This Month': [moment().startOf('month'), moment().endOf('month')],
            'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
        },
    });

    function searchAllOrderData(){
        $.blockUI();
        oTable.fnDraw();
        $.unblockUI();
    }

    function showRegion(str) {
            if (str == "") {
               document.getElementById("Region").innerHTML = "<option value=''>All</option>";
               document.getElementById("District").innerHTML = "<option value=''>All</option>";
               document.getElementById("Facility Name").innerHTML = "<option value=''>All</option>";
              return false;
            }else{
                $.post("<?php echo $this->url('provider', array('action' => 'region')); ?>", {q: str},
                function(data) {
                   document.getElementById("Region").innerHTML = data;
                   document.getElementById("District").innerHTML = "<option value=''>All</option>";
                   document.getElementById("Facility Name").innerHTML = "<option value=''>All</option>";
                });
            }
    }
    
    function showDistrict(str) {
        if (str == "") {
            document.getElementById("District").innerHTML = "";
            return;
        } else {
            if (window.XMLHttpRequest) {
                // code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            } else {
                // code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("District").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'district')); ?>?q=" + str, true);
            xmlhttp.send();
        }
    }

    function showFacilities(str) {
        if (str == "") {
            document.getElementById("Facility Name").innerHTML = "";
            return;
        } else {
            if (window.XMLHttpRequest) {
                // code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            } else {
                // code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("Facility Name").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "<?php echo $this->url('provider', array('action' => 'facility')); ?>?q=" + str, true);
            xmlhttp.send();
        }
    }

    

       /* Toggles Color of button */
       function toggleBtnClass(btnObj){
        $(btnObj).toggleClass("btn-default");
        var children = btnObj.childNodes;
        var iconTag = children[1].firstChild;
        $(iconTag).toggleClass("glyphicon-remove");
    }
    </script>

