<div class="main-content">
	<div class="row" style="margin-bottom:10px;clear:both;">
        <div class="col-md-12">
            <div class="card ">
                <div class="header">
                    <h3 class="title">Safety Familiarization Course</h3>
                </div>
                <div class="content">
                    <div class="sub" style="text-align: justify;">
                        <p>
                            Welcome to the safety familiarization course,
                            <b>
                                Basic Safety for Clinicians: Protect Yourself; Protect the Patient;
                                Protect the Community
                            </b>
                        </p>
                        <p>
                            This course is part of a CDC safety training curriculum intended for you, the Clinician, to provide a general
                            overview of safety issues in the clinical environment.
                        </p>
                        <p>
                            The videos and photos used in this course are for demonstration purposes only.
                        <p>
                            For specific safety procedures used in your clinic or healthcare facility, refer to your Standard Operating
                            Procedures (SOPs) or speak with your supervisor or safety and occupational health manager.
                        </p>
                        <p>
                            Note: This course will take approximately 60 minutes to complete. You can return to the place where you left
                            off, if you need to leave the course for any reason.
                        </p>
                        <p>
                            <b>
                                This course offers 1.5 professional development credits, and a certificate that can be printed out.
                            </b>
                        </p>
                    </div>
                    <div class="footer">
                        <hr>
                        <div class="stats">
                            <a class="more" href="<?php echo $this->url('test', array('action' => 'index')); ?>">Attend test &nbsp;&nbsp;<i class="fa fa-arrow-right move"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>