<div class="main-content">
	<div class="row" style="margin-bottom:10px;clear:both;">
        <div class="col-md-12">
            <div class="card ">
                <div class="header">
                    <h3 class="title">CDC ILB RT Certification Course</h3>
                </div>
                <div class="content">
                    <div class="sub" style="text-align: justify;">
                        <p>
                            Welcome to the CDC ILB RT Certification Course,
                            <b>
                                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                            </b>
                        </p>
                        <p>
                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                        </p>
                        <p>
                            It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                        <p>
                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                        </p>
                        <p>
                           Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                        </p>
                        <p>
                            <b>
                                When an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                            </b>
                        </p>
                    </div>
                    <div class="footer">
                        <hr>
                        <div class="stats">
                            <a class="more" href="<?php echo $this->url('test', array('action' => 'index')); ?>">Attend test &nbsp;&nbsp;<i class="fa fa-arrow-right move"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>