<div id="practicalExamChart" class="ct-chart"></div>
<script>
Highcharts.chart('practicalExamChart', {
    chart: {
        type: 'column'
    },
    title: {
        text: ''
    },
    subtitle: {
        text: ''
    },
    xAxis: {
        categories: [
            'Sample Testing Score',
            'Direct Observation Score',
            'Practical Total Score'
        ],
        crosshair: true
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Average Score (%)'
        }
    },
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.1f} %</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        }
    },
    series: [{
        name: 'Average Practical Exam Score',
        data: [<?php echo $result;?>]

    }]
});
</script>