<div id="wittenExamChart" class="ct-chart"></div>
<script>
Highcharts.chart('wittenExamChart', {

chart: {
    polar: true,
    type: 'line'
},

accessibility: {
    description: ''
},

title: {
    text: '',
    x: -80
},

pane: {
    size: '80%'
},

xAxis: {
    categories: ['QA', 'RT', 'Safety', 'Specimen', 'Testing Algo', 'Report Keeping', 'EQA PT Points', 'Ethics', 'Inventory'],
    tickmarkPlacement: 'on',
    lineWidth: 0
},

yAxis: {
    gridLineInterpolation: 'polygon',
    lineWidth: 0,
    min: 0
},

tooltip: {
    shared: true,
    pointFormat: '<span style="color:{series.color}">{series.name}: <b>{point.y}</b><br/>'
},

legend: {
    align: 'bottom',
    verticalAlign: 'bottom'
},

series: [{
    name: 'Average Written Exam Score',
    
    data: [<?php echo $result;?>],
   
    pointPlacement: 'on'
}],

responsive: {
    rules: [{
        condition: {
            maxWidth: 500
        },
        chartOptions: {
            legend: {
                align: 'center',
                verticalAlign: 'bottom'
            },
            pane: {
                size: '70%'
            }
        }
    }]
}

});
</script>