<?php
$available = 0;
if(isset($result['facilityResult']) && count($result['facilityResult']) > 0){
    foreach($result['facilityResult'] as $loc){
        if($loc['latitude'] != null && trim($loc['latitude']) != '' && $loc['longitude'] != null && trim($loc['longitude']) != ''){
            $available+=1;
        }
    }
}
if(isset($result['provinceResult']) && count($result['provinceResult']) > 0){
    foreach($result['provinceResult'] as $loc){
        if($loc['latitude'] != null && trim($loc['latitude']) != '' && $loc['longitude'] != null && trim($loc['longitude']) != ''){
            $available+=1;
        }
    }
}
if(isset($result['districtResult']) && count($result['districtResult']) > 0){
    foreach($result['districtResult'] as $loc){
        if($loc['latitude'] != null && trim($loc['latitude']) != '' && $loc['longitude'] != null && trim($loc['longitude']) != ''){
            $available+=1;
        }
    }
}
if($available > 0) { ?>
    <div class="map" id="map" style="height: 100%;width:100%;"></div>
    <script>
	$(document).ready(function() {
			var lat = "<?php echo $configData['latitude']; ?>";
			var log = "<?php echo $configData['longitude']; ?>";
            var zoomLevel = "<?php echo $configData['dashboard_map_zoomlevel'] ?? '4'; ?>";
			
			var LeafIcon = L.Icon.extend({
			});
			var map = L.map('map', {
				zoomControl: false,
				scrollWheelZoom: true,
				inertia: false,
				zoomAnimation: false,
				minZoom: 3,
				maxBounds: [
					[-90.0, -180.0],
					[90.0, 180.0]
				]
			}).setView([lat, log], zoomLevel);
			new L.Control.Zoom({
				position: 'topleft'
			}).addTo(map);
			map._onResize();

			L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
				attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
			}).addTo(map);
			
			// visualize the markers on the map
			<?php
            if(isset($result['facilityResult']) && count($result['facilityResult']) > 0){
                foreach($result['facilityResult'] as $locInfo){
                    if($locInfo['latitude'] != null && trim($locInfo['latitude']) != '' && $locInfo['longitude'] != null && trim($locInfo['longitude']) != ''){
					    $icon = $this->basePath('assets/img/map-points/red.png');
			?>
                        var marker= L.marker(["<?php echo $locInfo['latitude'] ?>", "<?php echo $locInfo['longitude'] ?>"], {
                                icon: new LeafIcon({iconUrl: "<?php echo $icon; ?>"})
                            }).bindPopup("<h5><?php echo ucwords($locInfo['facility_name']);?></h5><span>No. of Certificate : <?php echo $locInfo['locCount']; ?></span>")
                            .addTo(map).on('mouseover', function(e) {
                            this.openPopup();
                        })
                        .on('mouseout', function(e) {
                            this.closePopup();
                        });
			<?php 
                    }
                }
            }
            ?>

            <?php
            if(isset($result['provinceResult']) && count($result['provinceResult']) > 0){
                foreach($result['provinceResult'] as $locInfo){
                    if($locInfo['latitude'] != null && trim($locInfo['latitude']) != '' && $locInfo['longitude'] != null && trim($locInfo['longitude']) != ''){
					    $icon = $this->basePath('assets/img/map-points/green.png');
			?>
                        var marker= L.marker(["<?php echo $locInfo['latitude'] ?>", "<?php echo $locInfo['longitude'] ?>"], {
                                icon: new LeafIcon({iconUrl: "<?php echo $icon; ?>"})
                            }).bindPopup("<h5><?php echo ucwords($locInfo['location_name']);?></h5><span>No. of Certificate : <?php echo $locInfo['regCount']; ?></span>")
                            .addTo(map).on('mouseover', function(e) {
                            this.openPopup();
                        })
                        .on('mouseout', function(e) {
                            this.closePopup();
                        });
			<?php 
                    }
                }
            }
            ?>

            <?php
            if(isset($result['districtResult']) && count($result['districtResult']) > 0){
                foreach($result['districtResult'] as $locInfo){
                    if($locInfo['latitude'] != null && trim($locInfo['latitude']) != '' && $locInfo['longitude'] != null && trim($locInfo['longitude']) != ''){
					    $icon = $this->basePath('assets/img/map-points/yellow.png');
			?>
                        var marker= L.marker(["<?php echo $locInfo['latitude'] ?>", "<?php echo $locInfo['longitude'] ?>"], {
                                icon: new LeafIcon({iconUrl: "<?php echo $icon; ?>"})
                            }).bindPopup("<h5><?php echo ucwords($locInfo['location_name']);?></h5><span>No. of Certificate : <?php echo $locInfo['districtCount']; ?></span>")
                            .addTo(map).on('mouseover', function(e) {
                            this.openPopup();
                        })
                        .on('mouseout', function(e) {
                            this.closePopup();
                        });
			<?php 
                    }
                }
            }
            ?>

	});
</script>
<?php } else { ?>
    <div style="text-align:center;"><h5><strong><?php echo $this->translate('Sorry..Location not available'); ?>.</strong></h5></div>
<?php } ?>