<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<div class="am-content">
	<div class="page-head">
		<h2>Add Online Question Categories</h2>
	</div>
	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-body">
						<form role="form" name="testSection" id="testSection" method="post" action="<?php echo $this->url('test-section', array('action' => 'add')); ?>" autocomplete="off" >
							<div class="form-group col-lg-6">
							<label for="sectionName" class="col-sm-6 control-label">Section Name<span class="mandatory">*</span></label>
								<input type="text" placeholder="Enter section name" class="form-control isRequired" name="sectionName" id="sectionName" title="Please enter the section name" onblur="checkNameValidation('test_sections', 'section_name', this, null, 'Entered category already exist. Please enter an another category.')">
							</div>
							<div class="form-group col-lg-6">
							<label for="sectionSlug" class="col-sm-6 control-label">Section Slug<span class="mandatory">*</span></label>
								<input type="text" placeholder="Enter section slug" class="form-control isRequired" name="sectionSlug" id="sectionSlug" title="Please enter the section slug" onblur="checkNameValidation('test_sections', 'section_slug', this, null, 'Entered category slug already exist. Please enter an another category slug.')">
							</div>
							
							<div class="form-group col-lg-6">
							<label for="sectionDescription" class="col-sm-6 control-label">Section Description<span class="mandatory">*</span></label>
								<textarea type="text" placeholder="Enter section description" class="form-control isRequired" name="sectionDescription" id="sectionDescription" title="Please enter the section description"></textarea>
							</div>
							
							<div class="form-group col-lg-6">
							<label for="status" class="col-sm-6 control-label">Status<span class="mandatory">*</span></label>
								<select class="form-control isRequired" name="status" id="status" title="Please select Section status">
									<option value="">--Select--</option>
									<option value="active">Active</option>
									<option value="inactive">Inactive</option>
								</select>
							</div>
							<div class="spacer  col-lg-12">
								<button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
							<a href="<?php echo $this->url('test-section', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a> 
							</div>
						</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/slug.js'); ?>"></script>
<script type="text/javascript">
	duplicateName = true;
	$(document).ready(function(){
		$("#sectionName").stringToSlug({
			getPut : "#sectionSlug"
		});
	});
    function validateNow() {
		flag = deforayValidator.init({
				formId: 'testSection'
		});
		if (flag) {
				if (duplicateName) {
					document.getElementById('testSection').submit();
				}
		}
    }
	function checkNameValidation(tableName, fieldName, obj, fnct, msg)
    {
        checkValue = document.getElementById(obj.id).value;
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
        function(data) {
            if (data > 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
            }
            else {
                duplicateName = true;
            }
        });
    }
</script>