<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<div class="am-content">
	<div class="page-head">
		<h2>Add Test Section</h2>
	</div>
	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-body">
						<form role="form" name="addFacilityInfo" id="addFacilityInfo" method="post" action="<?php echo $this->url('test-section', array('action' => 'add')); ?>" autocomplete="off" >
							<div class="form-group col-lg-6">
							<label for="sectionName" class="col-sm-3 control-label">Section Name<span class="mandatory">*</span></label>
								<input type="text" placeholder="Enter section name" class="form-control isRequired" name="sectionName" id="sectionName" title="Please enter the section name">
							</div>
							
							<div class="form-group col-lg-6">
							<label for="sectionName" class="col-sm-3 control-label">Status<span class="mandatory">*</span></label>
								<select class="form-control isRequired" name="status" id="status" title="Please select Section status">
									<option value="">--Select--</option>
									<option value="active">Active</option>
									<option value="inactive">Inactive</option>
								</select>
							</div>
							<div class="spacer  col-lg-12">
								<button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
							<a href="<?php echo $this->url('test-section', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a> 
							</div>
						</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
    duplicateName = true;
    
    function validateNow() {
		flag = deforayValidator.init({
				formId: 'addFacilityInfo'
		});
		if (flag) {
				if (duplicateName) {
					document.getElementById('addFacilityInfo').submit();
				}
		}
    }
</script>