<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<div class="am-content">
	<div class="page-head">
		<h2>Edit Online Question Categories</h2>
	</div>
	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<form role="form" name="testSection" id="testSection" method="post" action="<?php echo $this->url('test-section', array('action' => 'edit')); ?>" autocomplete="off">
								<div class="form-group col-lg-6">
									<label for="sectionName" class="col-sm-3 control-label">Section Name<span class="mandatory">*</span></label>
									<input type="text" value="<?php echo $testSectionResult['section_name'];?>" placeholder="Enter section name" class="form-control isRequired" name="sectionName" id="sectionName" title="Please enter the section name" onblur="checkNameValidation('test_sections', 'section_name', this, '<?php echo "section_id##".$testSectionResult['section_id'];?>, 'Entered category already exist. Please enter an another category.')">
								</div>

								<div class="form-group col-lg-6">
									<label for="sectionName" class="col-sm-3 control-label">Status<span class="mandatory">*</span></label>
									<select class="form-control isRequired" name="status" id="status" title="Please select Section status">
										<option value="">--Select--</option>
										<option value="active" <?php echo (isset($testSectionResult['status']) && $testSectionResult['status'] =='active')?"selected='selected'":"";?>>Active</option>
										<option value="inactive" <?php echo (isset($testSectionResult['status']) && $testSectionResult['status'] =='inactive')?"selected='selected'":"";?>>Inactive</option>
									</select>
								</div>
								<div class="spacer  col-lg-12">
									<input type="hidden" name="sectionId" id="sectionId" value="<?php echo base64_encode($testSectionResult['section_id']);?>"/>
									<button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
									<a href="<?php echo $this->url('test-section', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
	duplicateName = true;

	function validateNow() {
		flag = deforayValidator.init({
			formId: 'testSection'
		});
		if (flag) {
			if (duplicateName) {
				document.getElementById('testSection').submit();
			}
		}
	}
	function checkNameValidation(tableName, fieldName, obj, fnct, msg)
    {
        checkValue = document.getElementById(obj.id).value;
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
        function(data) {
            if (data > 0)
            {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
            }
            else {
                duplicateName = true;
            }
        });
    }
</script>