<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;

if ($this->isAllowed($role, 'Application\Controller\TestSectionController', 'edit')) {
  $colspan = true;
  $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
} else {
  $colspan = false;
  $editAction = '{"sClass":"center"},{"sClass":"center"}';
}
?>
<div class="am-content">
  <div class="page-head">
    <div class="row">
      <div class="col-sm-8">
        <h2>Online Question Categories</h2>
      </div>
      <div class="col-sm-4">
        <?php if ($this->isAllowed($role, 'Application\Controller\TestSectionController', 'add')) { ?>
          <a href="<?php echo $this->url('test-section', array('action' => 'add')); ?>" class="btn btn-dark pull-right" style="margin-left: 5px;">&nbsp;Add Online Question Categories</a>
        <?php } ?>
      </div>
    </div>
  </div>
  <div class="main-content">
    <div class="widget widget-fullwidth widget-small" style="padding:5px;width:100%;">
      <table id="testSection" class="table table-bordered table-striped table-hover table-fw-widget" style="width:100%;">
        <thead>
          <tr>
            <th style="width:20%;">Categories</th>
            <th style="width:95%;">Status</th>
            <?php if ($this->isAllowed($role, 'Application\Controller\TestSectionController', 'edit')) { ?>
              <th style="width:95%;">Action</th>
            <?php } ?>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td colspan="<?php echo ($colspan) ? 3 : 2; ?>" class="dataTables_empty">Loading data from server</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/datatables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
<script type="text/javascript">
  table = null;
  $(document).ready(function() {
    table = $('#testSection').DataTable({
      "bProcessing": true,
      "bServerSide": true,
      "aoColumns": [<?php echo $editAction; ?>],
      "aaSorting": [
        [0, "ase"]
      ],
      "sAjaxSource": "<?php echo $this->url('test-section', array('action' => 'index')); ?>",
      "fnServerData": function(sSource, aoData, fnCallback) {
        $.ajax({
          "dataType": 'json',
          "type": "POST",
          "url": sSource,
          "data": aoData,
          "success": function(json) {
            $.unblockUI();
            fnCallback(json);
          }
        });
      }
    });
  });
</script>
