<?php
return array(
    'DM' => array(
        'Certification\\Controller\\Certification' => array(
            'pdf-setting' => 'allow',
            'index' => 'allow',
            'add' => 'allow',
            'approval' => 'allow',
            'edit' => 'allow',
            'pdf' => 'allow',
            'xls' => 'allow',
            'header-text' => 'allow',
            'recommend' => 'allow',
        ),
        'Certification\\Controller\\CertificationMail' => array(
            'index' => 'allow',
        ),
        'Application\\Controller\\Common' => array(
            'audit-locations' => 'allow',
        ),
        'Certification\\Controller\\Examination' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'pending' => 'allow',
        ),
        'Application\\Controller\\Config' => array(
            'index' => 'allow',
            'edit-global' => 'allow',
        ),
        'Application\\Controller\\Index' => array(
            'index' => 'allow',
        ),
        'Application\\Controller\\Dashboard' => array(
            'index' => 'allow',
            'audi-details' => 'allow',
        ),
        'Application\\Controller\\Email' => array(
            'index' => 'allow',
        ),
        'Application\\Controller\\Facility' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'export-facility' => 'allow',
            'map-province' => 'allow',
            'get-province-list' => 'allow',
            'get-facility-name' => 'allow',
        ),
        'Certification\\Controller\\Provider' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'allow',
            'district' => 'allow',
            'edit' => 'allow',
            'xls' => 'allow',
            'facility' => 'allow',
        ),
        'Application\\Controller\\Roles' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\Users' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\District' => array(
            'index' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\Facility' => array(
            'index' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\Region' => array(
            'index' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\PracticalExam' => array(
            'index' => 'allow',
            'add' => 'allow',
            'attempt' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\Recertification' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'xls' => 'allow',
        ),
        'Certification\\Controller\\Training' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
            'xls' => 'allow',
        ),
        'Certification\\Controller\\TrainingOrganization' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\WrittenExam' => array(
            'index' => 'allow',
            'add' => 'allow',
            'attempt' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
    ),
    'DEO' => array(
        'Certification\\Controller\\Certification' => array(
            'pdf-setting' => 'allow',
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'pdf' => 'allow',
            'xls' => 'allow',
            'header-text' => 'allow',
        ),
        'Certification\\Controller\\CertificationMail' => array(
            'index' => 'allow',
        ),
        'Application\\Controller\\Common' => array(
            'audit-locations' => 'allow',
        ),
        'Certification\\Controller\\Examination' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\Config' => array(
            'index' => 'allow',
            'edit-global' => 'allow',
        ),
        'Application\\Controller\\Index' => array(
            'index' => 'allow',
        ),
        'Application\\Controller\\Dashboard' => array(
            'index' => 'allow',
            'audi-details' => 'allow',
        ),
        'Application\\Controller\\Email' => array(
            'index' => 'allow',
        ),
        'Application\\Controller\\Facility' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'export-facility' => 'allow',
            'map-province' => 'allow',
            'get-province-list' => 'allow',
            'get-facility-name' => 'allow',
        ),
        'Certification\\Controller\\Provider' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'allow',
            'district' => 'allow',
            'edit' => 'allow',
            'xls' => 'allow',
            'facility' => 'allow',
        ),
        'Application\\Controller\\Roles' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\Users' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\District' => array(
            'index' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\Facility' => array(
            'index' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\Region' => array(
            'index' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\PracticalExam' => array(
            'index' => 'allow',
            'add' => 'allow',
            'attempt' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\Recertification' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'xls' => 'allow',
        ),
        'Certification\\Controller\\Training' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
            'xls' => 'allow',
        ),
        'Certification\\Controller\\TrainingOrganization' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\WrittenExam' => array(
            'index' => 'allow',
            'add' => 'allow',
            'attempt' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
    ),
    'CM' => array(
        'Certification\\Controller\\Certification' => array(
            'pdf-setting' => 'allow',
            'index' => 'allow',
            'add' => 'allow',
            'approval' => 'allow',
            'edit' => 'allow',
            'pdf' => 'allow',
            'xls' => 'allow',
            'header-text' => 'allow',
            'recommend' => 'allow',
        ),
        'Certification\\Controller\\CertificationMail' => array(
            'index' => 'allow',
        ),
        'Application\\Controller\\Common' => array(
            'audit-locations' => 'allow',
        ),
        'Certification\\Controller\\Examination' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\Config' => array(
            'index' => 'allow',
            'edit-global' => 'allow',
        ),
        'Application\\Controller\\Index' => array(
            'index' => 'allow',
        ),
        'Application\\Controller\\Dashboard' => array(
            'index' => 'allow',
            'audi-details' => 'allow',
        ),
        'Application\\Controller\\Email' => array(
            'index' => 'allow',
        ),
        'Application\\Controller\\Facility' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'export-facility' => 'allow',
            'map-province' => 'allow',
            'get-province-list' => 'allow',
            'get-facility-name' => 'allow',
        ),
        'Certification\\Controller\\Provider' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'allow',
            'district' => 'allow',
            'edit' => 'allow',
            'xls' => 'allow',
            'facility' => 'allow',
        ),
        'Application\\Controller\\Roles' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\Users' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\District' => array(
            'index' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\Facility' => array(
            'index' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\Region' => array(
            'index' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\PracticalExam' => array(
            'index' => 'allow',
            'add' => 'allow',
            'attempt' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\Recertification' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'xls' => 'allow',
        ),
        'Certification\\Controller\\Training' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
            'xls' => 'allow',
        ),
        'Certification\\Controller\\TrainingOrganization' => array(
            'index' => 'allow',
            'add' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
        'Certification\\Controller\\WrittenExam' => array(
            'index' => 'allow',
            'add' => 'allow',
            'attempt' => 'allow',
            'delete' => 'allow',
            'edit' => 'allow',
        ),
    ),
);
