<?php
use Zend\Session\Container;
$container = new Container('alert');
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/img/favicon.png">
    <title>Dashboard for Quality Improvement of HIV Rapid Testing </title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/stroke-7/style.css'); ?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/jquery.nanoscroller/css/nanoscroller.css'); ?>"/><!--[if lt IE 9]>
    <script src="<?php echo $this->basePath('assets/js/html5shiv.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/respond.min.js'); ?>" type="text/javascript"></script>
    <![endif]-->
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/css/style.css'); ?>" type="text/css"/>
  </head>
  <body class="am-splash-screen">
    <div class="am-wrapper am-login">
      <div class="am-content">
        <div class="main-content">
          <div class="login-container" style="text-align:center;">
            <div class="panel panel-default">
	      <!--get global config logo image-->
              <div class="panel-heading">
		<?php
		$config = $this->GlobalConfigHelper();
		if(isset($config) && count($config)>0 && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo". DIRECTORY_SEPARATOR . $config['logo']))
		{
		  ?>
		  <img src="<?php echo $this->basePath('uploads/logo/'.$config['logo']); ?>" style="width:120px;" alt="logo" class="logo-img">
		  <?php
		}else{
		  ?>
		  <img src="<?php echo $this->basePath('assets/img/logo.png'); ?>" style="width:120px;" alt="logo" class="logo-img">
		  <?php
		}
		?>
		<span>Dashboard for Quality Improvement of HIV Rapid Testing </span>
	      </div>
              <div class="panel-body">
                <form action="<?php echo $this->url('login'); ?>" method="post" class="form-horizontal">
                  <div class="login-form">
                    <div class="form-group">
                      <div class="input-group"><span class="input-group-addon"><i class="icon s7-user"></i></span>
                        <input id="username" name="username" type="text" placeholder="Username" autocomplete="off" class="form-control">
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="input-group"><span class="input-group-addon"><i class="icon s7-lock"></i></span>
                        <input id="password" name="password" type="password" placeholder="Password" class="form-control">
                      </div>
                    </div>
                    <div class="form-group login-submit">
                      <button data-dismiss="modal" type="submit" class="btn btn-primary btn-lg">Log me in</button>
                    </div>
					
                    <div class="form-group footer row" style="display:none;">
                      <div class="col-xs-6"><a href="#">Forgot Password?</a></div>
                      <div class="col-xs-6 remember">
                        <label for="remember">Remember Me</label>
                        <div class="am-checkbox">
                          <input type="checkbox" id="remember">
                          <label for="remember"></label>
                        </div>
                      </div>
                    </div>
					
                  </div>
                </form>
              </div>
            </div>
	      <a href="http://apps.who.int/iris/bitstream/10665/199799/1/9789241508179_eng.pdf" style="text-decoration:underline;">
		  Improving the quality of HIV-Related Point-of Care Testing<br>1 December 2015
	      </a>

          </div>
        </div>
      </div>
    </div>
    <script src="<?php echo $this->basePath('assets/lib/jquery/jquery.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.nanoscroller/javascripts/jquery.nanoscroller.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/main.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/bootstrap/dist/js/bootstrap.min.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript">
      $(document).ready(function(){
      	//initialize the javascript
      	App.init();
      });
      
      $(document).ready(function() {
            <?php
            if (isset($container->alertMsg) && $container->alertMsg != "") {
                ?>
                alert("<?php echo $container->alertMsg; ?>");
                <?php
                $container->alertMsg = "";
                unset($container->alertMsg);
            }
            ?>
      });
    </script>
  </body>
</html>