<?php

use Zend\Debug\Debug;
// Debug::dump($result);die;
?>
<style>
.alert {
    padding-left: 30px;
    margin-left: 15px;
    position: relative;
}
.alert-info {
    color: #31708f;
    background-color: #d9edf7;
    border-color: #bce8f1;
}
.alert-dismissable {
    padding-right: 35px;
}
.alert {
    padding: 15px;
    margin-bottom: 20px;
    border: 1px solid transparent;
    border-radius: 4px;
}
.alert > .fa, .alert > .glyphicon {
    position: absolute;
    left: -15px;
    top: -15px;
    width: 35px;
    height: 35px;
    -webkit-border-radius: 50%;
    -moz-border-radius: 50%;
    border-radius: 50%;
    line-height: 35px;
    text-align: center;
    background: inherit;
    border: inherit;
}
</style>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'); ?>" type="text/css" />
<section class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-8">
                <h2>Modify Mail Template</h2>
            </div>
            <div class="col-sm-4" style=" margin-top: 10px; ">
                <a href="<?php echo $this->url('mail-template',array('action' => 'index')); ?>" class="btn btn-default pull-right action-btn"><i class="fa fa-arrow-left" aria-hidden="true"> Back to Mail Template Configurations</i></a>
            </div>
        </div>
    </div>
    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <!-- form start -->
                            <form role="form" name="updateMailTemplate" id="updateMailTemplate"  method="post" action="<?php echo $this->url('mail-template', array('action' => 'edit')); ?>" autocomplete="off">
                                <div class="form-group col-lg-6">
                                    <label for="mailTitle" class="col-sm-6 control-label">Mail Purpose <span class="mandatory">*</span></label>
                                    <input type="text" class="form-control isRequired" id="mailTitle" name="mailTitle" placeholder="From mail purpose" title="Please enter mail purpose" value="<?php echo $result['mail_title']; ?>"/>
                                </div>

                                <div class="form-group col-lg-6">
                                    <label for="fromName" class="col-sm-6 control-label">Mail Purpose <span class="mandatory">*</span></label>
                                    <select class="form-control isRequired" name="mailPurpose" id="mailPurpose" title="Please select mail purpose">
                                        <option value="">--Select--</option>
                                        <option value="send-online-test-link" <?php echo (isset($result['mail_purpose']) && $result['mail_purpose'] =='send-online-test-link')?"selected='selected'":"";?>>Send Online Test Link</option>
                                        <option value="online-test-mail-fail" <?php echo (isset($result['mail_purpose']) && $result['mail_purpose'] =='online-test-mail-fail')?"selected='selected'":"";?>>Online Test Mail for Fail</option>
                                        <option value="online-test-mail-pass" <?php echo (isset($result['mail_purpose']) && $result['mail_purpose'] =='online-test-mail-pass')?"selected='selected'":"";?>>Online Test Mail for Pass</option>
                                        <option value="certificate-reminder" <?php echo (isset($result['mail_purpose']) && $result['mail_purpose'] =='certificate-reminder')?"selected='selected'":"";?>>Certificate Reminder</option>
                                        <option value="send-certificate" <?php echo (isset($result['mail_purpose']) && $result['mail_purpose'] =='send-certificate')?"selected='selected'":"";?>>Send Certificate</option>
                                    </select>
                                </div>

                                <div class="form-group col-lg-6">
                                    <label for="fromName" class="col-sm-6 control-label">From Name <span class="mandatory">*</span></label>
                                    <input type="text" class="form-control isRequired" id="fromName" name="fromName" placeholder="From Name" title="Please enter from name" value="<?php echo $result["from_name"]; ?>"/>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="fromEmail" class="col-sm-6 control-label">From Email <span class="mandatory">*</span></label>
                                    <input type="text" class="form-control isRequired isEmail" id="fromMail" name="fromMail" placeholder="From Email" title="Please enter from email" value="<?php echo $result["mail_from"]; ?>"/>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="subject" class="col-sm-6 control-label">Subject <span class="mandatory">*</span></label>
                                    <input type="text" class="form-control isRequired" name="subject" id="subject" placeholder="Subject" value="<?php echo $result["mail_subject"]; ?>"/>
                                </div>
                                <div class="form-group col-lg-12">
                                    <label for="mainContent" class="col-sm-5 control-label">Content <span class="mandatory">*</span></label>
                                    <textarea class="form-control isRequired richtextarea" id="mainContent" name="mainContent" placeholder="Enter Message" rows="8" title="Please enter message"><?php echo $result["mail_content"]; ?></textarea>
                                </div>
                                <div class="form-group col-lg-12">
                                    <label for="footer" class="col-sm-5 control-label">Footer Content <span class="mandatory">*</span></label>
                                    <textarea class="form-control isRequired richtextarea" id="footer" name="footer" placeholder="Enter Footer Content" rows="8" title="Please enter footer content"><?php echo $result["mail_footer"]; ?></textarea>
                                </div>

                                <div class="form-group col-lg-6">
                                    <label for="status" class="col-sm-6 control-label">Status<span class="mandatory">*</span></label>
                                    <select class="form-control isRequired" name="status" id="status" title="Please select Section status">
                                        <option value="">--Select--</option>
                                        <option value="active" <?php echo (isset($result['mail_status']) && $result['mail_status'] =='active')?"selected='selected'":"";?>>Active</option>
                                        <option value="inactive" <?php echo (isset($result['mail_status']) && $result['mail_status'] =='inactive')?"selected='selected'":"";?>>Inactive</option>
                                    </select>
                                </div>
                                <div class="form-group col-lg-7">
                                    <div class="alert alert-info alert-dismissable">
                                        <i class="fa fa-info"></i>
                                        <div><b>##USER##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Name of the new user</div>
                                        <div><b>##EMAIL##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Email of the user</div>
                                        <div><b>##PASSWORD##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Password of the user</div>
                                        <div><b>##URL##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp URL for activating the account</div>
                                        <div><b>##URLWITHOUTLINK##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp simple URL(without) for activating the account</div>
                                        <div><b>##TESTNAME##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Name of the Test to be send to tester</div>
                                        <div><b>##SCORE##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Total score earned from the test</div>
                                        <div><b>##CERTIFICATE_NUMBER##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Certificate Number to be display</div>
                                        <div><b>##CERTIFICATE_EXPIRY_DATE##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Certificate expiry date to be display</div>
                                        <div><b>##EXPIRY_HOURS##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Mail expiry hourse from global config</div>
                                        <div><b>##COUNTRY##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Country name should showing from global config</div>
                                    </div>
                                </div>

                                <div class="spacer col-lg-12 text-center">
                                    <input type="hidden" name="mailTempId" id="mailTempId" value="<?php echo base64_encode($result['mail_temp_id']);?>"/>
                                    <input type="button" class="btn btn-primary" value="Update" onclick="validateNow(); return false;">
                                    &nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url('mail-template'); ?>" class="btn btn-default">Cancel</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!-- /.content -->
<script src="<?php echo $this->basePath('assets/js/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'); ?>" type="text/javascript"></script>
<!-- <script src="<?php echo $this->basePath('assets/js/dashboard.js'); ?>" type="text/javascript"></script> -->
<script type="text/javascript">
    $(document).ready(function(){
        $(".richtextarea").wysihtml5();
	});
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'updateMailTemplate'
        });
        if (flag) {
            document.getElementById('updateMailTemplate').submit();
        }
    }
</script>