<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl=$this->layout()->acl;
if ($acl->isAllowed($role, 'Application\Controller\MailTemplate','edit')) {
  $colspan = true;
  $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
}else{
  $colspan = false;
  $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
?>
<div class="am-content">
    <div class="page-head">
        <div class="row">
			<div class="col-sm-8">
			<h2>Mail Templates Configurations</h2>
			</div>
			<div class="col-sm-4">
				<?php if ($acl->isAllowed($role, 'Application\Controller\MailTemplate','add')) { ?>
					<a href="<?php echo $this->url('mail-template',array('action' => 'add'));?>" class="btn btn-dark pull-right" style="margin-left: 5px;">&nbsp;Add New Mail Template</a>
				<?php } ?>
			</div>
        </div>
    </div>
    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <table id="mailTemplate" class="table table-bordered table-hover"  style="width:100%;">
              <thead>
                <tr>
                    <th style="width: 20%;">From Name</th>
                    <th style="width: 20%;">From Mail</th>
                    <th style="width: 25%;">Subject</th>
                    <th style="width: 25%;">Title</th>
                    <th style="width: 5%;">Status</th>
                    <?php if ($acl->isAllowed($role, 'Application\Controller\MailTemplate','edit')) { ?>
                      <th style="width: 5%;">Action</th>
                    <?php }?>
                </tr>
              </thead>
              <tbody>
                <tr>
                    <td colspan="<?php echo ($colspan)?6:5;?>" class="dataTables_empty">Loading data from server</td>
                </tr>
              </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/datatables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
<script type="text/javascript">
    table = null;
    $(document).ready(function () {
    table = $('#mailTemplate').DataTable({
        "bProcessing": true,
        "bServerSide": true,
         "aoColumns": [<?php echo $editAction; ?>],
         "aaSorting": [[ 0, "desc" ]],
         "sAjaxSource": "<?php echo $this->url('mail-template',array('action' => 'index')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
			$.ajax({
				"dataType": 'json',
				"type": "POST",
				"url": sSource,
				"data": aoData,
				"success": function(json){
					$.unblockUI();
					fnCallback(json);
				}
			});
		}
    } );
  });  
</script>