<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Mail Template
<!--<small>Preview</small>-->
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- left column -->
    <div class="">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title"><?php echo $mailhead; ?></h3><div class="pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
            </div><!-- /.box-header -->
            <!-- form start -->
            <form role="form" class="form-horizontal" name="updateMailTemplate" id="updateMailTemplate"  method="post" action="<?php echo $this->url('mail-template', array('action' => 'index')); ?>" autocomplete="off">
                <div class="box-body">
                    <input type="hidden" id="mailTempId" name="mailTempId" value="<?php echo $mailtemplate["mail_temp_id"]; ?>"/>
                    <input type="hidden" id="mailPurpose" name="mailPurpose" value="<?php echo $mailtemplate["mail_purpose"]; ?>"/>
                    <div class="form-group">
                        <label for="fromName" class="col-lg-2 control-label" style="padding-right:4%;">From Name <span class="mandatory">*</span></label>
                        <div class="col-lg-6">
                            <input type="text" class="form-control isRequired" id="fromName" name="fromName" placeholder="From Name" title="Please enter from name" value="<?php echo $mailtemplate["from_name"]; ?>"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="fromEmail" class="col-lg-2 control-label" style="padding-right:4%;">From Email <span class="mandatory">*</span></label>
                        <div class="col-lg-6">
                            <input type="text" class="form-control isRequired isEmail" id="fromMail" name="fromMail" placeholder="From Email" title="Please enter from email" value="<?php echo $mailtemplate["mail_from"]; ?>"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="subject" class="col-lg-2 control-label" style="padding-right:4%;">Subject <span class="mandatory">*</span></label>
                        <div class="col-lg-6">
                            <input type="text" class="form-control isRequired" name="subject" id="subject" placeholder="Subject" value="<?php echo $mailtemplate["mail_subject"]; ?>"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="mainContent" class="col-lg-2 control-label" style="padding-right:4%;">Content <span class="mandatory">*</span></label>
                        <div class="col-lg-8">
                            <textarea class="form-control isRequired richtextarea" id="mainContent" name="mainContent" placeholder="Enter Message" rows="8" title="Please enter message"><?php echo $mailtemplate["mail_content"]; ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="footer" class="col-lg-2 control-label" style="padding-right:4%;">Footer Content <span class="mandatory">*</span></label>
                        <div class="col-lg-8">
                            <textarea class="form-control isRequired richtextarea" id="footer" name="footer" placeholder="Enter Footer Content" rows="8" title="Please enter footer content"><?php echo $mailtemplate["mail_footer"]; ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="footer" class="col-lg-2 control-label" style="padding-right:4%;"></label>
                        <div class="col-lg-8">
                            <div class="alert alert-info alert-dismissable">
                                <i class="fa fa-info"></i>
                               
                                <?php if($mailPurpose=='userActivation') { ?>
                                    <div><b>##USER##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Name of the new user</div>
                                    <div><b>##EMAIL##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Email of the user</div>
                                    <div><b>##PASSWORD##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Password of the user</div>
                                    <div><b>##URL##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp URL for activating the account</div>
                                    <div><b>##URLWITHOUTLINK##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp simple URL(without) for activating the account</div>
                                <?php } else { ?>
                                    <div><b>##USER##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp Name of the new user</div>
                                    <div><b>##URL##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp URL for activating the account</div>
                                    <div><b>##URLWITHOUTLINK##</b>&nbsp&nbsp&nbsp   --- &nbsp&nbsp simple URL(without) for activating the account</div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                    
                </div><!-- /.box-body -->

                <div class="box-footer" style="padding-left:18%;">
                    <input type="button" class="btn btn-primary" value="Update" onclick="validateNow(); return false;">
                    &nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url('admin-home'); ?>" class="btn btn-default">Cancel</a>
                </div>
            </form>

        </div><!-- /.box -->
    </div><!--/.col (left) -->
</section><!-- /.content -->

<script type="text/javascript">
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'updateMailTemplate'
        });
        if (flag) {
            
                $.blockUI();
                document.getElementById('updateMailTemplate').submit();
        }
    }
</script>