<?php
use Zend\Session\Container;
$container = new Container('alert');
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="<?php echo $this->basePath('assets/img/favicon.png'); ?>">
    <title>Malawi Dashboard for Quality Improvement of HIV Rapid Testing </title>
    
    <style type="text/css">
      .mandatory {
        color: red;
      }
    </style>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/bootstrap.min.css'); ?>" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"/>
    <!--[if lt IE 9]>
    <script src="<?php echo $this->basePath('assets/js/html5shiv.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/respond.min.js'); ?>" type="text/javascript"></script>
    <![endif]-->
    
    <script src="<?php echo $this->basePath('assets/lib/jquery/jquery.min.js'); ?>" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/jquery-ui.css'); ?>"/>

  </head>
  <body>
    <div class="am-wrapper">
      <?php echo $this->content; ?>
    </div>
    <script src="<?php echo $this->basePath('assets/lib/bootstrap/dist/js/bootstrap.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/deforayValidation.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript">
      $(document).ready(function() {
            <?php
            if (isset($container->alertMsg) && $container->alertMsg != "") {
                ?>
                alert("<?php echo $container->alertMsg; ?>");
                <?php
                $container->alertMsg = "";
                unset($container->alertMsg);
            }
            ?>
      });
    </script>
  </body>
</html>
