<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">
        <h2>Edit Training</h2>
        <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>

    </div>

    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >
                            <form action="<?php $this->url('training', array('action' => 'edit', 'training_id' => $this->training_id)); ?>" name="form" method="post" onsubmit="return validateForm()">

                                <?php
                                $form->prepare();
                                $form->get('Provider_id')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Tester  Name',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('type_of_competency')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Type of Competency',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('last_training_date')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'date',
                                    'onclick' => 'emptyInput(this)'
                                ]);
                                $form->get('type_of_training')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'Type of Activity/Training',
                                    'onclick' => 'emptyInput(this)'
                                ]);
                                $form->get('length_of_training')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Length of Activity/Training',
                                    'onclick' => 'emptyInput(this)',
                                    'placeholder' => 'Length of Training/Activity'
                                ]);
                                $form->get('training_organization_id')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'Training Organization',
                                    'onclick' => 'emptyInput(this)'
                                ]);
                                $form->get('facilitator')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Name of Facilitator(s)',
                                    'autocomplete' => 'off',
                                    'id' => 'Name of Facilitator(s)',
                                    'onclick' => 'emptyInput(this)'
                                ]);
                                $form->get('date_certificate_issued')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'date2',
                                    'onclick' => 'emptyInput(this)'
                                ]);

                                $form->get('training_certificate')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Training certificate',
                                    'id' => 'Training certificate',
                                    'onclick' => 'emptyInput(this)']);

                                $form->get('Comments')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Comments',
                                    'autocomplete' => 'off',
                                    'id' => 'Comments',
                                    'onclick' => 'emptyInput(this)']);

                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formHidden($form->get('training_id')->setAttribute('class', 'form-control')) ?>
                                <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('Provider_id')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('Provider_id')); ?>
                                    <?= $this->formElementErrors($form->get('Provider_id')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('type_of_competency')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('type_of_competency')); ?>
                                    <?= $this->formElementErrors($form->get('type_of_competency')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('type_of_training')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('type_of_training')); ?>
                                    <?= $this->formElementErrors($form->get('type_of_training')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('last_training_date')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('last_training_date')); ?>
                                    <?= $this->formElementErrors($form->get('last_training_date')); ?></div>
                                <div class = " form-group col-lg-6">
                                    <div class = "input-group">
                                        <?= $this->formLabel($form->get('length_of_training')); ?><span class="mandatory">*</span>
                                        <?= $this->formElement($form->get('length_of_training')); ?>
                                        <?= $this->formElementErrors($form->get('length_of_training')); ?>
                                        <div class = "input-group-btn">
                                            <select class="form-control" style="margin-bottom: -28px; width: 100px;" name="select_time" id="Time" onclick = 'emptyInput(this)'> 
                                                <option value="">--Select--</option>
                                                <option id="Years" value="Years">Year(s)</option>
                                                <option id="Months" value="Months">Month(s)</option>
                                                <option id="Weeks"value="Weeks">Week(s)</option>
                                                <option id="Days" value="Days">Day(s)</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group col-lg-6">  
                                    <?= $this->formLabel($form->get('training_organization_id')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('training_organization_id')); ?>
                                    <?= $this->formElementErrors($form->get('training_organization_id')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('facilitator')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('facilitator')); ?>
                                    <?= $this->formElementErrors($form->get('facilitator')); ?>
                                </div>

                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('training_certificate')); ?>
                                    <?= $this->formElement($form->get('training_certificate')); ?>
                                    <?= $this->formElementErrors($form->get('training_certificate')); ?>       
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('Comments')); ?>
                                    <?= $this->formElement($form->get('Comments')); ?>
                                    <?= $this->formElementErrors($form->get('Comments')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('date_certificate_issued')); ?>
                                    <?= $this->formElement($form->get('date_certificate_issued')); ?>
                                    <?= $this->formElementErrors($form->get('date_certificate_issued')); ?>
                                </div>

                                <div class="form-group col-lg-4" ><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                    <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('training', array('action' => 'index')); ?>" >CANCEL</a> </div>

                                <?php echo $this->form()->closeTag();
                                ?>
                            </form>


                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>



<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script>
                                                var time = "<?php echo $time2; ?>";
</script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/training.js'); ?>"></script>





