<!-- < ?php echo $result;?> -->

<div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <table id="trainingReportTable" class="datatables table table-bordered table-responsive table-condensed table-striped table-hover table-fw-widget" style="width:100%;">
                <thead class="frezz">
                    <tr class="allproviders">
                        <th style="width:10%;">Tester</th>
                        <th style="width:10%;">Professional Registration No.</th>
                        <th style="width:10%;">Region</th>
                        <th style="width:10%;">District</th>
                        <th style="width:10%;">Facility</th>
                        <th style="width:10%;">Type of Competency</th>
                        <th style="width:10%;">Training Organization</th>
                        <th style="width:10%;">Type of Activity/Training</th>
                        <th style="width:10%;">Training certificate</th>
                        <th style="width:10%;">Type HIV testing modality/point</th>
                        <th style="width:10%;">Current job title</th>
                        
                    </tr>
                </thead>
                <tbody class="frezz">
                    <?php
                        foreach ($this->result as $training) {
                            // \Zend\Debug\Debug::dump($training);die;
                    ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($training['first_name'] . ' ' . $training['last_name ']); ?></td>
                            <td><?php echo $this->escapeHtml($training['professional_reg_no']); ?></td>
                            <td><?php echo $this->escapeHtml($training['region_name']); ?></td>
                            <td><?php echo $this->escapeHtml($training['district_name']); ?></td>
                            <td><?php echo $this->escapeHtml($training['facility_name']); ?></td>
                            <td><?php echo $this->escapeHtml($training['type_of_competency']); ?></td>
                            <td><?php echo $this->escapeHtml($training['training_organization_name']); ?></td>
                            <td><?php echo $this->escapeHtml($training['type_of_training']); ?></td>
                            <td><?php echo $this->escapeHtml($training['training_certificate']); ?></td>
                            <td><?php echo $this->escapeHtml($training['type_vih_test']); ?></td>
                            <td><?php echo $this->escapeHtml($training['current_jod']); ?></td>
                            
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>