<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;



if ($this->isAllowed($role, 'Certification\Controller\TrainingController', 'edit') && $this->isAllowed($role, 'Certification\Controller\TrainingController', 'delete')) {

    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false},{"sClass":"center","bSortable":false},{"sClass":"center","bSortable":false},{"sClass":"center","bSortable":false}';
} else if ($this->isAllowed($role, 'Certification\Controller\TrainingController', 'delete')) {

    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false},{"sClass":"center","bSortable":false},{"sClass":"center","bSortable":false}';
} else if ($this->isAllowed($role, 'Certification\Controller\TrainingController', 'edit')) {
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false},{"sClass":"center","bSortable":false},{"sClass":"center","bSortable":false}';
} else {

    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false},{"sClass":"center","bSortable":false},{"sClass":"center","bSortable":false},{"sClass":"center","bSortable":false}';
}


?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>" />

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<style>
    #shBtnManageColumns {
        font-size: 17px;
        font-weight: 600;
    }

    .well {
        width: 100%;
    }
</style>
<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>List of Trainings</h2>
            </div>
            <div class="col-sm-4">
                <?php if ($this->isAllowed($role, 'Certification\Controller\TrainingController', 'add')) { ?>
                    <a href="<?php echo $this->url('training', array('action' => 'add')); ?>" class="btn btn-dark pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Add Training</a>
                <?php } ?>

            </div>
        </div>
    </div>
    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="well container">
                <div class="row" style="margin-bottom:15px;margin-left:9px;">
                    <h3>Manage Columns &nbsp;<a href="javascript:void(0)" id="shBtnManageColumns">Show/hide</a></h3>
                </div>
                <div id="manageColumns">
                </div>
            </div>
            <table id="trainingDatatable" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
                <thead>
                    <tr class="alltraining">
                        <th>Certification Registration No</th>
                        <th>professional registration no</th>
                        <th>Certification ID</th>
                        <th>Tester</th>
                        <th>Type of Competency</th>
                        <th>Type of Activity/Training</th>
                        <th>Date of last Training/Activity</th>
                        <th>Length of Training/Activity</th>
                        <th style="width: 10%;">Training organization</th>
                        <th style="width: 10%;">Type of Training organization</th>
                        <th style="width: 10%;">Name of Facilitator(s)</th>
                        <th style="width: 6%;">Training certificate(if available)</th>
                        <th>Date certificate issued (if available)</th>

                        <!--<th style="width: 10%;" >Comments</th>-->
                        <?php if ($this->isAllowed($role, 'Certification\Controller\TrainingController', 'edit')) { ?>
                            <th>Edit</th>
                        <?php } ?>
                        <?php if ($this->isAllowed($role, 'Certification\Controller\TrainingController', 'delete')) { ?>
                            <th>Delete</th>
                        <?php } ?>
                    </tr>

                </thead>
                <tbody>


                    <tr>
                        <td colspan="15" class="dataTables_empty">Loading data from server</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>

<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" language="javascript">
    oTable = null;
    $(document).ready(function() {


        var listOfColumns = '';
        $('tr.alltraining').each(function() {
            $(this).find('th').each(function(index) {
                listOfColumns += '<a class="toggle-vis btn btn-primary btn-sm" data-column="' + index + '" style="margin-top: 5px;" onclick="toggleBtnClass(this)"> <span class="btn-label"><i class="glyphicon glyphicon-ok"></i></span> ' + $(this).text() + '</a> &nbsp;'
            });
        });
        $("#manageColumns").html(listOfColumns);

        oTable = $('#trainingDatatable').DataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "bStateSave": true,
            "aoColumns": [
                <?php echo $editAction; ?>
            ],
            "aaSorting": [
                [0, "asc"]
            ],
            "sAjaxSource": "<?php echo $this->url('training', array('action' => 'index')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });


        // var table = $('#trainingDatatable').DataTable({
        //     "aProcessing": true,
        //     "aServerSide": true,
        //     "aaSorting": [],
        // });

        $('a.toggle-vis').on('click', function(e) {
            e.preventDefault();
            // Get the column API object
            var column = oTable.column($(this).attr('data-column'));
            // Toggle the visibility
            column.visible(!column.visible());
            $("#provider_wrapper").css("overflow-x", "scroll");
        });
        $("#manageColumns").hide();
        $("#shBtnManageColumns").click(function() {
            $("#manageColumns").toggle('fast', 'linear');
        });

    });

    /* Toggles Color of button */
    function toggleBtnClass(btnObj) {
        $(btnObj).toggleClass("btn-default");
        var children = btnObj.childNodes;
        var iconTag = children[1].firstChild;
        $(iconTag).toggleClass("glyphicon-remove");
    }
</script>
