<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">
        <div class="row">
            <div class="col-sm-8">
                <h2>Add A new Training organization</h2>
            </div>
            <div class="col-sm-4 ">
                <?php // if ($acl->isAllowed($role, 'Application\Controller\Facility', 'add')) {  ?>
                <a href="<?php echo $this->url('training-organization', array('action' => 'index')); ?>" class="btn btn-success pull-right" style="margin-left: 5px;"><i class="fa fa-list"></i>&nbsp;List of Trainings Organizations</a>
                <?php // }  ?>

            </div>
        </div>
        <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>

    </div>

    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >



                            <form action="<?php $this->url('training-organization', array('action' => 'add')); ?>" name="form" method="post" onsubmit="return validateForm()">
                                <?php
//                        $form->setAttribute('action', $this->url('training-organization', array('action' => 'add')));
                                $form->prepare();
                                $form->get('training_organization_name')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Training Organization Name',
                                    'autocomplete' => 'off',
                                    'id' => 'Training Organization Name',
                                    'onclick' => 'inputOrgaName()',
//                           
                                ]);

                                $form->get('type_organization')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'Type of Organization',
                                    'onclick' => 'inputOrgaType()',
                                ]);

                                $form->get('submit')->setAttributes([
//                            
                                ]);


                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formHidden($form->get('training_organization_id')->setAttribute('class', 'form-control')) ?>
                                <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('training_organization_name')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('training_organization_name')); ?>
                                    <?= $this->formElementErrors($form->get('training_organization_name')); ?>
                                </div>

                                <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('type_organization')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('type_organization')); ?>
                                    <?= $this->formElementErrors($form->get('type_organization')); ?>
                                </div>

                                <div class="row" style="margin-left: 18px;"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                    <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('training-organization', array('action' => 'index')); ?>" >CANCEL</a> </div>
                                    <?php echo $this->form()->closeTag(); ?>

                            </form>

                        </div>
                    </div>

                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>



<script type = "text/javascript" src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/personnel_certification/organisation.js'); ?>"></script>





