<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
?>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>list of Training organizations</h2>
            </div>
            <div class="col-sm-4">
                <?php if ($acl->isAllowed($role, 'Certification\Controller\TrainingOrganization', 'add')) { ?>
                    <a href="<?php echo $this->url('training-organization', array('action' => 'add')); ?>" class="btn btn-dark pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Add Training Organization</a>
                <?php } ?>

            </div>
        </div>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <table id="example" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" style="width:65%;">
                <thead>
                    <tr>

                        <th style="width:50%;">Training Organization </th>
                        <th>Type of Training Organization </th>

                        <?php if ($acl->isAllowed($role, 'Certification\Controller\TrainingOrganization', 'edit')) { ?>
                            <th>Edit</th>
                        <?php } ?>
                        <?php if ($acl->isAllowed($role, 'Certification\Controller\TrainingOrganization', 'delete')) { ?>
                            <th>Delete</th>
                        <?php } ?>
                    </tr>

                </thead>
                <tbody>
                    
                    <?php foreach ($paginator as $organization) : ?>
                        <tr>
                            <td><div style="overflow:auto;"><?php echo $this->escapeHtml($organization->training_organization_name); ?></div>

                            </td>
                            <td><div style="overflow:auto;"><?php echo $this->escapeHtml($organization->type_organization); ?></div>

                            </td>
                            <?php if ($acl->isAllowed($role, 'Certification\Controller\TrainingOrganization', 'edit')) { ?>
                                <td><div style="width:60px;overflow:auto;">
                                        <a href="<?php echo $this->url('training-organization', array('action' => 'edit', 'training_organization_id' => base64_encode($organization->training_organization_id))); ?>"> <span class="glyphicon glyphicon-pencil">&nbsp;Edit</span></a> 
                                    </div>
                                </td>
                            <?php } ?>
                            <?php if ($acl->isAllowed($role, 'Certification\Controller\TrainingOrganization', 'delete')) { ?>
                                <td><div style="overflow:auto;">
                                        <a onclick="if (!confirm('Do you really want to remove ' + '<?php echo $this->escapeHtml($organization->training_organization_name); ?>' + ' ?')) {
                                                    alert('Canceled!');
                                                    return false;
                                                }
                                                ;"  href="<?php echo $this->url('training-organization', array('action' => 'delete', 'training_organization_id' => $organization->training_organization_id)); ?>"> <span class="glyphicon glyphicon-trash">&nbsp;Delete</span></a> 
                                    </div>
                                </td>
                            <?php } ?>
                        </tr>


                    <?php endforeach; ?>               
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src = "<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type = "text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>


<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" language="javascript" >
                                    $(document).ready(function () {

                                        $('#example').dataTable({
                                            "aProcessing": true,
                                            "aServerSide": true,
                                        })
                                    });
</script>


