<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">
        <h2>Edit a ReCertification</h2>
        <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>

    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >
                            <form action="<?php $this->url('recertification', array('action' => 'edit', 'recertification_id' => $this->recertification_id)); ?>" name="form" method="post" onsubmit="return validateForm()">
                                <?php
                                $form->prepare();

                                $form->get('due_date')->setAttributes([
                                    'class' => 'form-control',
                                    'id' => 'date',
                                    'autocomplete' => 'off',
                                    'onclick' => 'emptyInput(this)',
                                ]);
                                $form->get('provider_id')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Provider',
                                    'onclick' => 'emptyInput(this)',
                                ]);

                                $form->get('reminder_type')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Type Of Reminder',
                                    'onclick' => 'emptyInput(this)',
                                ]);

                                $form->get('reminder_sent_to')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Reminder Send To',
                                    'onclick' => 'emptyInput(this)',
                                ]);

                                $form->get('name_of_recipient')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'Name Of Recipient',
                                    'onclick' => 'emptyInput(this)',
                                ]);
                                $form->get('date_reminder_sent')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off',
                                    'id' => 'date2',
                                    'onclick' => 'emptyInput(this)',
                                ]);


                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formHidden($form->get('recertification_id')->setAttribute('class', 'form-control')) ?>
                                <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('due_date')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('due_date')); ?>
                                    <?= $this->formElementErrors($form->get('due_date')); ?>
                                </div>
                                <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('provider_id')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('provider_id')); ?>
                                    <?= $this->formElementErrors($form->get('provider_id')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('reminder_type')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('reminder_type')); ?>
                                    <?= $this->formElementErrors($form->get('reminder_type')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('reminder_sent_to')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('reminder_sent_to')); ?>
                                    <?= $this->formElementErrors($form->get('reminder_sent_to')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('name_of_recipient')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('name_of_recipient')); ?>
                                    <?= $this->formElementErrors($form->get('name_of_recipient')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('date_reminder_sent')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('date_reminder_sent')); ?>
                                    <?= $this->formElementErrors($form->get('date_reminder_sent')); ?></div>


                                <div class="form-group col-lg-6" style="margin-top: 30px"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                    <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('recertification', array('action' => 'index')); ?>" >CANCEL</a> </div>
                                    <?php echo $this->form()->closeTag();
                                    ?>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>

</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/personnel_certification/recertification.js'); ?>" type="text/javascript"></script>





