<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$config = $this->globalConfigHelper();
$regionLabel = (isset($config['region']) && trim($config['region']) != '') ? ucwords($config['region']) : 'Regions';
?>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>Edit a <?php echo $regionLabel; ?></h2>
            </div>
            <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>

        </div>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">

            <div>

                <form action="<?php $this->url('region', array('action' => 'edit', 'id' => $this->id)); ?>" name="form" method="post" onsubmit="return validateForm()">
                    <?php
                    $form->prepare();
                    $form->get('country')->setAttributes([
                        'class' => 'form-control',
                        'id' => 'Country',
                        'onclick' => 'emptyInput(this)'
                    ]);

                    $form->get('location_name')->setAttributes([
                        'class' => 'form-control',
                        'placeholder' => $regionLabel . ' Name',
                        'autocomplete' => 'off',
                        'id' => 'Region Name',
                        'onclick' => 'emptyInput(this)',
                        'onblur' => 'checkNameValidation("location_details","location_name", this, "location_id##' . $this->location_id . '", "The region name that you entered already exist..Please enter different region name")'
                    ]);
                    $form->get('location_code')->setAttributes([
                        'class' => 'form-control',
                        'placeholder' => 'Province Code',
                        'autocomplete' => 'off',
                        'id' => 'location_code',
                        'onclick' => 'emptyInput(this)',
                        'onblur' => 'checkNameValidation("location_details","location_code", this, "location_id##' . $this->location_id . '", "The region code that you entered already exist..Please enter different region code")'
                    ]);
                    $form->get('latitude')->setAttributes([
                        'class' => 'form-control',
                        'placeholder' => 'Latitude',
                        'autocomplete' => 'off',
                        'id' => 'latitude',
                        'onclick' => 'emptyInput(this)',
                    ]);
                    $form->get('longitude')->setAttributes([
                        'class' => 'form-control',
                        'placeholder' => 'Longitude',
                        'autocomplete' => 'off',
                        'id' => 'longitude',
                        'onclick' => 'emptyInput(this)',
                    ]);

                    $form->get('submit')->setAttributes([]);


                    echo $this->form()->openTag($form);
                    ?>
                    <?php echo $this->formHidden($form->get('location_id')->setAttribute('class', 'form-control')) ?>
                    <div class="row" style="display:none;">
                        <div class="form-group col-lg-6">
                            <?= $this->formLabel($form->get('country')); ?><span class="mandatory">*</span>
                            <?= $this->formElement($form->get('country')); ?>
                            <?php // $this->formElementErrors($form->get('country')); 
                            ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-lg-6">
                            <?= $this->formLabel($form->get('location_name')); ?><span class="mandatory">*</span>
                            <?= $this->formElement($form->get('location_name')); ?>
                            <?php // $this->formElementErrors($form->get('location_name')); 
                            ?>
                        </div>
                        <div class="form-group col-lg-6">
                            <?= $this->formLabel($form->get('location_code')); ?>
                            <?= $this->formElement($form->get('location_code')); ?>
                            <?php // $this->formElementErrors($form->get('location_code')); 
                            ?>
                        </div>
                        <div class="form-group col-lg-6">
                            <?= $this->formLabel($form->get('latitude')); ?>
                            <?= $this->formElement($form->get('latitude')); ?>
                            <?php // $this->formElementErrors($form->get('latitude')); 
                            ?>
                        </div>
                        <div class="form-group col-lg-6">
                            <?= $this->formLabel($form->get('longitude')); ?>
                            <?= $this->formElement($form->get('longitude')); ?>
                            <?php // $this->formElementErrors($form->get('longitude')); 
                            ?>
                        </div>
                    </div>
                    <div class="col-sm-3" style="margin-top: 30px; margin-left: 5px">
                        <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                        <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('region', array('action' => 'index')); ?>">CANCEL</a>
                    </div>
                    <?php echo $this->form()->closeTag(); ?>

                </form>
            </div>

            <div style="margin-top:120px;"></div>
        </div>
    </div>
</div>
<script>
    regionLabel = '<?php echo $regionLabel; ?>';
</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/personnel_certification/region.js'); ?>" type="text/javascript"></script>
<script>
    function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
        checkValue = document.getElementById(obj.id).value;
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
                tableName: tableName,
                fieldName: fieldName,
                value: checkValue,
                fnct: fnct
            },
            function(data) {
                if (data > 0) {
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                } else {
                    duplicateName = true;
                }
            });
    }
</script>
