<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1.0" name="viewport">

	<title>RT Tester Certification</title>
	<meta content="" name="descriptison">
	<meta content="" name="keywords">

	<!-- Favicons -->
	<link href="assets/img/favicon.png" rel="icon">
	<link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

	<!-- Vendor CSS Files -->
	<link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<link href="/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
	<link href="/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
	<link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
	<link href="/assets/vendor/venobox/venobox.css" rel="stylesheet">
	<link href="/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">

	<!-- Template Main CSS File -->
	<link href="/assets/css/home-style.css" rel="stylesheet">

	<!-- =======================================================
  * Template Name: Lumia - v2.0.0
  * Template URL: https://bootstrapmade.com/lumia-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

	<!-- ======= Header ======= -->
	<header id="header" class="fixed-top d-flex align-items-center">
		<div class="container d-flex align-items-center">

			<div class="logo mr-auto">
				<h1><a href="/">Tester Certification</a></h1>
				<!-- Uncomment below if you prefer to use an image logo -->
				<!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
			</div>

			<nav class="nav-menu d-none d-lg-block">
				<ul>
					<li class="active"><a href="#header">Home</a></li>
					<li><a href="#testimonials">About</a></li>
					<li><a href="#contact">Contact Us</a></li>
					<li><a href="/login">Login</a></li>

				</ul>
			</nav><!-- .nav-menu -->

		</div>
	</header><!-- End Header -->

	<!-- ======= Hero Section ======= -->
	<section id="hero" class="d-flex flex-column justify-content-center align-items-center">
		<div class="container text-center text-md-left" data-aos="fade-up">
			<h1>Tester <span>Certification</span></h1>
			<h2>Online Platform to manage tester certifications</h2>
			<a href="#about" class="btn-get-started scrollto">Learn More</a>
		</div>
	</section><!-- End Hero -->

	<main id="main">

		<br><br>

		<!-- ======= Counts Section ======= -->
		<section id="counts" class="counts">
			<div class="container">

				<div class="row">

					<div class="col-lg-3 col-6">
						<div class="count-box">
							<i class="icofont-simple-smile"></i>
							<span data-toggle="counter-up"><?php echo $quickStats['certified'] ?></span>
							<p>Certified</p>
						</div>
					</div>

					<div class="col-lg-3 col-6">
						<div class="count-box">
							<i class="icofont-document-folder"></i>
							<span data-toggle="counter-up"><?php echo $quickStats['upForCertification'] ?></span>
							<p>Up for Recertification</p>
						</div>
					</div>

					<div class="col-lg-3 col-6 mt-5 mt-lg-0">
						<div class="count-box">
							<i class="icofont-live-support"></i>
							<span data-toggle="counter-up"><?php echo $quickStats['expired'] ?></span>
							<p>Expired</p>
						</div>
					</div>

					<div class="col-lg-3 col-6 mt-5 mt-lg-0">
						<div class="count-box">
							<i class="icofont-users-alt-5"></i>
							<span data-toggle="counter-up"><?php echo $quickStats['pending'] ?></span>
							<p>Pending/Failed</p>
						</div>
					</div>

				</div>

			</div>
		</section><!-- End Counts Section -->



		<!-- ======= Testimonials Section ======= -->
		<section id="testimonials" class="testimonials section-bg">
			<div class="container">

				<div class="section-title">
					<h2>Lorem Ipsum</h2>
					<p>Necessitatibus eius consequatur ex aliquid fuga eum quidem</p>
				</div>

				<div class="owl-carousel testimonials-carousel">

					<div style="max-height:240px !important;overflow:hidden !important;margin:1px;"> <img src="/uploads/home/banners/DSC_4942-cropped.jpg" /> </div>
					<div style="max-height:240px !important;overflow:hidden !important;margin:1px;"> <img src="/uploads/home/banners/DSC_5148.jpg" /> </div>
					<div style="max-height:240px !important;overflow:hidden !important;margin:1px;"> <img src="/uploads/home/banners/DSC_4962.jpg" /> </div>
					<div style="max-height:240px !important;overflow:hidden !important;margin:1px;"> <img src="/uploads/home/banners/DSC_4899.jpg" /> </div>
					<div style="max-height:240px !important;overflow:hidden !important;margin:1px;"> <img src="/uploads/home/banners/DSC_4897.jpg" /> </div>



				</div>

			</div>
		</section><!-- End Testimonials Section -->

		<!-- ======= About Section ======= -->
		<section id="about">

			<div class="container">

				<div class="row">
					<div class="col-lg-6">
						<img src="/assets/img/stages.png" class="img-fluid" alt="">
					</div>
					<div class="col-lg-6 pt-4 pt-lg-0">
						<h3>National Certification Program</h3>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
						</p>
						<ul>
							<li><i class="bx bx-check-double"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
							<li><i class="bx bx-check-double"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
						</ul>
					</div>
				</div>

			</div>
		</section><!-- End About Section -->


		<br><br>
		<!-- ======= Services Section ======= -->
		<section id="services" class="services section-bg">
			<div class="container">

				<div class="section-title">
					<h2>Lorem Ipsum</h2>
					<p>Necessitatibus eius consequatur ex aliquid fuga eum quidem</p>
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="icon-box">
							<i class="icofont-computer"></i>
							<h4><a href="#">Lorem Ipsum</a></h4>
							<p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>
						</div>
					</div>
					<div class="col-md-6 mt-4 mt-lg-0">
						<div class="icon-box">
							<i class="icofont-chart-bar-graph"></i>
							<h4><a href="#">Dolor Sitema</a></h4>
							<p>Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata</p>
						</div>
					</div>
					<div class="col-md-6 mt-4">
						<div class="icon-box">
							<i class="icofont-image"></i>
							<h4><a href="#">Sed ut perspiciatis</a></h4>
							<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
						</div>
					</div>
					<div class="col-md-6 mt-4">
						<div class="icon-box">
							<i class="icofont-settings"></i>
							<h4><a href="#">Nemo Enim</a></h4>
							<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
						</div>
					</div>
					<div class="col-md-6 mt-4">
						<div class="icon-box">
							<i class="icofont-earth"></i>
							<h4><a href="#">Magni Dolore</a></h4>
							<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>
						</div>
					</div>
					<div class="col-md-6 mt-4">
						<div class="icon-box">
							<i class="icofont-tasks-alt"></i>
							<h4><a href="#">Eiusmod Tempor</a></h4>
							<p>Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi</p>
						</div>
					</div>
				</div>

			</div>
		</section><!-- End Services Section -->



		<!-- ======= Team Section ======= -->
		<section id="team" class="team">
			<div class="container">

				<div class="section-title">
					<h2>Lorem Ipsum</h2>
					<p>Sit sint consectetur velit quos quisquam cupiditate nemo qui</p>
				</div>

				<div class="row">
					<div class="col-lg-4 col-md-6 d-flex align-items-stretch">
						<div class="member">
							<img src="assets/img/team/team-1.jpg" alt="">
							<h4>Walt Whitman</h4>
							<span>Lab Tech</span>
							<p>
								Magni qui quod omnis unde et eos fuga et exercitationem. Odio veritatis perspiciatis quaerat qui aut aut aut
							</p>
						</div>
					</div>

					<div class="col-lg-4 col-md-6 d-flex align-items-stretch">
						<div class="member">
							<img src="assets/img/team/team-2.jpg" alt="">
							<h4>Robert Frost</h4>
							<span>Lab Manager</span>
							<p>
								Repellat fugiat adipisci nemo illum nesciunt voluptas repellendus. In architecto rerum rerum temporibus
							</p>
						</div>
					</div>

					<div class="col-lg-4 col-md-6 d-flex align-items-stretch">
						<div class="member">
							<img src="assets/img/team/team-3.jpg" alt="">
							<h4>William Wordsworth</h4>
							<span>Lab Tech</span>
							<p>
								Voluptas necessitatibus occaecati quia. Earum totam consequuntur qui porro et laborum toro des clara
							</p>
						</div>
					</div>

				</div>

			</div>
		</section><!-- End Team Section -->

		<!-- ======= Contact Section ======= -->
		<section id="contact" class="contact section-bg">
			<div class="container">

				<div class="section-title">
					<h2>Contact</h2>
					<p>Magnam dolores commodi suscipit eius consequatur ex aliquid fuga</p>
				</div>


				<div class="row mt-5 justify-content-center">
					<div class="col-lg-10">
						<form action="forms/contact.php" method="post" role="form" class="php-email-form">
							<div class="form-row">
								<div class="col-md-6 form-group">
									<input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
									<div class="validate"></div>
								</div>
								<div class="col-md-6 form-group">
									<input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
									<div class="validate"></div>
								</div>
							</div>
							<div class="form-group">
								<input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
								<div class="validate"></div>
							</div>
							<div class="form-group">
								<textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
								<div class="validate"></div>
							</div>
							<div class="mb-3">
								<div class="loading">Loading</div>
								<div class="error-message"></div>
								<div class="sent-message">Your message has been sent. Thank you!</div>
							</div>
							<div class="text-center"><button type="submit">Send Message</button></div>
						</form>
					</div>

				</div>

			</div>
		</section><!-- End Contact Section -->

	</main><!-- End #main -->

	<!-- ======= Footer ======= -->
	<footer id="footer">

		<div class="footer-top">
			<div class="container">
				<div class="row">

					<div class="col-lg-3 col-md-6 footer-contact">
						<h3>Lorem Ipsum</h3>
						<p>
							111 Test Street <br>
							New York, NY 535022<br>
							United States <br><br>
							<strong>Email:</strong> test@example.org<br>
						</p>
					</div>

					<div class="col-lg-2 col-md-6 footer-links">
						<h4>Useful Links</h4>
						<ul>
							<li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
							<li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
							<li><i class="bx bx-chevron-right"></i> <a href="#">Login</a></li>
							<li><i class="bx bx-chevron-right"></i> <a href="#">Contact</a></li>
						</ul>
					</div>

					<div class="col-lg-3 col-md-6 footer-links">
						<h4>Our Partners</h4>
						<ul>
							<li><i class="bx bx-chevron-right"></i> <a href="#">Partner 1</a></li>
							<li><i class="bx bx-chevron-right"></i> <a href="#">Partner 2</a></li>
						</ul>
					</div>

					<div class="col-lg-4 col-md-6 footer-newsletter">
						<h4>Lorem Ipsum</h4>
						<p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
						<form action="" method="post">
							<input type="email" name="email"><input type="submit" value="Subscribe">
						</form>
					</div>

				</div>
			</div>
		</div>

		<div class="container d-md-flex py-4">

			<div class="mr-md-auto text-center text-md-left">
				<div class="copyright">
					&copy; Copyright <strong><span>RT CERT</span></strong>. All Rights Reserved
				</div>
			</div>
		</div>
	</footer><!-- End Footer -->

	<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

	<!-- Vendor JS Files -->

	<script src="/assets/vendor/jquery/jquery.min.js"></script>
	<script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
	<script src="/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
	<script src="assets/vendor/php-email-form/validate.js"></script>
	<script src="/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
	<script src="/assets/vendor/counterup/counterup.min.js"></script>
	<script src="/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
	<script src="/assets/vendor/venobox/venobox.min.js"></script>
	<script src="/assets/vendor/owl.carousel/owl.carousel.min.js"></script>

	<!-- Template Main JS File -->
	<script src="assets/js/home.js"></script>

	<script>
		if (window.self == window.top) {
			(function(i, s, o, g, r, a, m) {
				i['GoogleAnalyticsObject'] = r;
				i[r] = i[r] || function() {
					(i[r].q = i[r].q || []).push(arguments)
				}, i[r].l = 1 * new Date();
				a = s.createElement(o), m = s.getElementsByTagName(o)[0];
				a.async = 1;
				a.src = g;
				m.parentNode.insertBefore(a, m)
			})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
			ga('create', 'UA-55234356-4', 'auto');
			ga('send', 'pageview');
		}
	</script>
</body>

</html>