<?php
// \Zend\Debug\Debug::dump($result['config']);die;
$totalNumberOfQuestion = count($result['questions']);
$totalNumberOfExamination = count($result['examination']);
$tdCount = $totalNumberOfQuestion/13;
$tsecTdCount = round($totalNumberOfExamination/5);
// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {

    //Page header
    public function setHeading(){}

    public function Header() {}

    // Page footer
    public function Footer()
    {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', '', 8);
        // Page number
        $this->Cell(0, 10,  'HIV Tester Certification - Written Examination Sheet', 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}

/* create new PDF document */
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, array(280,200),PDF_PAGE_FORMAT, true, 'UTF-8', false);

/* set document information */
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('RT Certification Team');
$pdf->SetTitle('RT Certification Examination Sheet');
// $pdf->SetSubject('Airtel Vt');
$pdf->SetKeywords('TCPDF, PDF, RT Certification, RT Cert');

/* set margins */
$pdf->SetMargins(5, 5, 5);
$pdf->SetHeaderMargin(0);
$pdf->SetFooterMargin(0);

/* remove default footer */
$pdf->setPrintFooter(false);

/* set auto page breaks */
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

/* set image scale factor */
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

/* set some language-dependent strings (optional) */
if (@file_exists(dirname(__FILE__) . '/lang/eng.php')) {
    require_once(dirname(__FILE__) . '/lang/eng.php');
    $pdf->setLanguageArray($l);
}

/* set font */
$pdf->SetFont('helvetica', '', 13);
$pdf->setFontSubsetting(false);

/* remove default header */
$pdf->setPrintHeader(false);
$pdf->SetMargins(05, 05, 05, true);

/* add a page */
$pdf->AddPage();
$logoImg = 'hi';
/* Logo file check */
if(isset($result['config']) && $result['config'] != ''){
    if (!file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo" . DIRECTORY_SEPARATOR . 'logo_cert1.png') && !is_dir(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo" . DIRECTORY_SEPARATOR . 'logo_cert1.png')) {
        $logoImg = '<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=No image" />';
    } else {
        $logoImg = '<img width="70" src="/uploads/logo/logo_cert1.png" />';
    }
}
$tbl = '';
$tbl .= '<table style="width:100%;" border="0" cellpadding="2"  align="center">';
    if(isset($result['config']) && $result['config'] != ''){
        $tbl .= '<tr align="center">';
            $tbl .= '<td style="width:100%;margin-bottom:25px;" align="center">'.$logoImg.'</td>';
        $tbl .= '</tr>';
    }
    $tbl .= '<tr align="center">';
        $tbl .= '<td style="width:100%;margin-bottom:25px;" align="center"><h5>HIV Tester Certification - Written Examination Sheet</h5></td>';
    $tbl .= '</tr>';
    $tbl .= '<tr align="center">';
        $tbl .= '<td style="width:100%;" align="center">
                    <table border="0" align="center" cellpadding="2" style="width:100%;">
                        <tr>
                            <td style="width:100%;">
                                <table style="width:100%;" cellpadding="2" border="0" align="center">
                                    <tr align="center">
                                        <td align="left" style="width:100%;font-size:12px;"><span style="font-weight: bold;">TESTER INFORMATION </span><span style="font-style: italic;">(All Capital letters)</span><br></td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:100%;font-size:12px;">Last Name ........................................... First Name: ........................................... Middle Name: ........................................... </td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:100%;font-size:12px;">Professional registration number (if available): ................................... Certification ID (if available): .................................... </td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:100%;font-size:12px;">Date of last training: ........../ ............/ ............. Length of training (days/weeks): ................................................................... </td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:100%;font-size:12px;">Time worked as tester to date (Years or months): ................................................................................................................. </td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:100%;font-size:12px;">Phone: ............................................................... Email (if available): .................................................................................... </td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:100%;font-size:12px;font-weight: bold;font-style: italic;"><br>Written Examination Instructions</td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:100%;font-size:12px;font-style: italic;">
                                            <ul>
                                                <li>Complete the Examination Information section before you begin the examination. Failure to do so will result in not scoring your test.</li>
                                                <li>For each question, indicate the question code and the write the letter of the correct statement in the column labelled “Your answer”.</li>
                                                <li>Make sure to answer <span style="font-weight: bold;text-decoration: underline;">all</span> the questions. Each correct answer will receive <span style="font-weight: bold;">one (1) point.</span> Incorrect answers or questions left unanswered will be scored <span style="font-weight: bold;">zero (0) point.</span> A total score of <span style="font-weight: bold;">80% (or 20 points)</span> or <span style="font-weight: bold;">higher</span> is required to pass the examination. </li>
                                                <li>Before turning in your examination sheet, verify that you have answered all the questions, indicated your name, the date and signed the examination sheet.</li>
                                            </ul>
                                        </td>
                                    </tr>';
                                    if($tdCount == 0){
                                        $tbl .='<tr align="center">
                                            <td align="center" style="width:100%;"><br>';
                                            $tbl .= '<table style="width:100%;" border="1" cellpadding="2"  align="center">
                                            <thead>
                                                <tr align="center" style="background-color:#f1f1f1;">
                                                    <th align="center" style="width:15%;font-size:14px;"><b>S/N</b></th>
                                                    <th align="center" style="width:25%;font-size:14px;"><b>Question Code</b></th>
                                                    <th align="center" style="width:30%;font-size:14px;"><b>Your answer</b></th>
                                                    <th align="center" style="width:30%;font-size:14px;background-color:#BFBFBF;"><b>Correct Answer</b></th>
                                                </tr>
                                            </thead><tbody>';
                                            foreach($result['questions'] as $sno=>$qRow){
                                                $tbl .= '<tr cellpadding="2">';
                                                    $tbl .= '<td align="center" style="width:15%;font-size:13px;"><br><b>'.$sno.'</b></td>';
                                                    $tbl .= '<td align="center" style="width:25%;font-size:13px;background-color:#f1f1f1;"><b></b></td>';
                                                    $tbl .= '<td align="center" style="width:30%;font-size:13px;"></td>';
                                                    $tbl .= '<td align="center" style="width:30%;font-size:13px;background-color:#BFBFBF;"></td>';
                                                $tbl .= '</tr>';
                                            }
                                        $tbl .= '</tbody></table>
                                            </td>
                                        </tr>';
                                    }else if($tdCount >= 1){
                                        $tbl .='<tr align="center">
                                            <td align="center" style="width:50%;"><br>
                                                <table style="width:100%;" border="1" cellpadding="2" align="center">
                                                    <thead>
                                                        <tr align="center" style="background-color:#f1f1f1;">
                                                            <th align="center" style="width:15%;font-size:14px;"><b>S/N</b></th>
                                                            <th align="center" style="width:25%;font-size:14px;"><b>Question Code</b></th>
                                                            <th align="center" style="width:30%;font-size:14px;"><b>Your answer</b></th>
                                                            <th align="center" style="width:30%;font-size:14px;background-color:#BFBFBF;"><b>Correct Answer</b></th>
                                                        </tr>
                                                    </thead><tbody>';
                                                    $halfCount = 0;
                                                    for($i=1;$i<=ceil($totalNumberOfQuestion/2);$i++){
                                                        $tbl .= '<tr cellpadding="2">';
                                                            $tbl .= '<td align="center" style="width:15%;font-size:13px;"><br><b>'.$i.'</b></td>';
                                                            $tbl .= '<td align="center" style="width:25%;font-size:13px;background-color:#f1f1f1;"><b></b></td>';
                                                            $tbl .= '<td align="center" style="width:30%;font-size:13px;"></td>';
                                                            $tbl .= '<td align="center" style="width:30%;font-size:13px;background-color:#BFBFBF;"></td>';
                                                        $tbl .= '</tr>';
                                                        $halfCount = round($i);
                                                    }
                                                $tbl .= '</tbody></table>
                                            </td>';
                                            if($halfCount < $totalNumberOfQuestion){
                                                $tbl .='<td align="center" style="width:50%;"><br>
                                                    <table style="width:100%;" border="1" cellpadding="2" align="center">
                                                        <thead>
                                                            <tr align="center" style="background-color:#f1f1f1;">
                                                                <th align="center" style="width:15%;font-size:14px;"><b>S/N</b></th>
                                                                <th align="center" style="width:25%;font-size:14px;"><b>Question Code</b></th>
                                                                <th align="center" style="width:30%;font-size:14px;"><b>Your answer</b></th>
                                                                <th align="center" style="width:30%;font-size:14px;background-color:#BFBFBF;"><b>Correct Answer</b></th>
                                                            </tr>
                                                        </thead><tbody>';
                                                        for($j=($halfCount+1);$j<=$totalNumberOfQuestion;$j++){
                                                            $tbl .= '<tr cellpadding="2">';
                                                                $tbl .= '<td align="center" style="width:15%;font-size:13px;"><br><b>'.round($j).'</b></td>';
                                                                $tbl .= '<td align="center" style="width:25%;font-size:13px;background-color:#f1f1f1;"><b></b></td>';
                                                                $tbl .= '<td align="center" style="width:30%;font-size:13px;"></td>';
                                                                $tbl .= '<td align="center" style="width:30%;font-size:13px;background-color:#BFBFBF;"></td>';
                                                            $tbl .= '</tr>';
                                                        }
                                                    $tbl .= '</tbody></table>
                                                </td>';
                                            }
                                        $tbl.='</tr>';
                                    }
                                    $tbl .='<tr align="center">
                                        <td align="left" style="width:100%;font-size:12px;"><br><br>Signature of Tester: ................................................................... Examination date: .................../ .................../ .................. <br></td>
                                    </tr>';
                                    if($tsecTdCount <= 1 ){
                                        $tbl .='<tr align="center">
                                            <td align="center" style="width:100%;"><br><br>';
                                                $tbl .= '<table style="width:100%;" border="1" cellpadding="2"  align="center">
                                                    <tr border="1" align="center" style="background-color:#0000;">
                                                        <td align="center" style="color:white;"><h5>Score to be summarized by proctor or evaluator only</h5></td>
                                                    </tr>
                                                    <thead>
                                                        <tr align="center" style="background-color:#f1f1f1;">
                                                            <th align="center" style="width:60%;font-size:14px;"><br><br><b>Section Title</b></th>
                                                            <th align="center" style="width:20%;font-size:14px;"><b>Total Points Obtained</b></th>
                                                            <th align="center" style="width:20%;font-size:14px;background-color:#BFBFBF;"><b>Points Expected</b></th>
                                                        </tr>
                                                    </thead><tbody>';
                                                    $totalPonts = 0;
                                                    foreach($result['examination'] as $sno=>$qRow){
                                                        $tbl .= '<tr cellpadding="2">';
                                                            $tbl .= '<td align="center" style="width:60%;font-size:13px;"><br>'.$qRow['section_name'].'</td>';
                                                            $tbl .= '<td align="center" style="width:20%;font-size:13px;"></td>';
                                                            $tbl .= '<td align="center" style="width:20%;font-size:13px;background-color:#BFBFBF;">'.$qRow['total'].'</td>';
                                                        $tbl .= '</tr>';
                                                        $totalPonts+=$qRow['total'];
                                                    }
                                                $tbl .= '</tbody>
                                                <tfoot border="1">
                                                    <tr border="1">
                                                        <td align="center" style="width:60%;font-size:13px;background-color:#BFBFBF;"></td>
                                                        <td align="center" style="width:20%;font-size:13px;"></td>
                                                        <td align="center" style="width:20%;font-size:13px;background-color:#BFBFBF;">'.$totalPonts.'</td>
                                                    </tr>
                                                </tfoot></table>
                                            </td>
                                        </tr>';
                                    }else if($tsecTdCount >= 2){
                                        if(($totalNumberOfExamination/2) < $totalNumberOfExamination){
                                            $tbl .= '<tr align="center" border="1" style="background-color:#0000;">
                                                <td align="center" style="color:white;width:100%;"><h5>Score to be summarized by proctor or evaluator only</h5></td>
                                            </tr>';
                                        }
                                        $tbl .='<tr align="center">
                                            <td align="center" style="width:50%;"><br>';
                                                $tbl .= '<table style="width:100%;" border="1" cellpadding="2"  align="center">';
                                                    if(($totalNumberOfExamination/2) > $totalNumberOfExamination){
                                                        $tbl .= '<tr align="center" style="background-color:#0000;">
                                                            <td align="center" style="color:white;"><h5>Score to be summarized by proctor or evaluator only</h5></td>
                                                        </tr>';
                                                    }
                                                    $tbl .= '<thead>
                                                        <tr align="center" style="background-color:#f1f1f1;">
                                                            <th align="center" style="width:50%;font-size:14px;"><br><br><b>Section Title</b></th>
                                                            <th align="center" style="width:25%;font-size:14px;"><b>Total Points Obtained</b></th>
                                                            <th align="center" style="width:25%;font-size:14px;background-color:#BFBFBF;"><b>Points Expected</b></th>
                                                        </tr>
                                                    </thead><tbody>';
                                                    $totalPonts = 0;$halfExamCount = 0;
                                                    for($k=0;$k<=($totalNumberOfExamination/2);$k++){
                                                        $tbl .= '<tr cellpadding="2">';
                                                            $tbl .= '<td align="center" style="width:50%;font-size:13px;"><br>'.$result['examination'][$k]['section_name'].'</td>';
                                                            $tbl .= '<td align="center" style="width:25%;font-size:13px;"></td>';
                                                            $tbl .= '<td align="center" style="width:25%;font-size:13px;background-color:#BFBFBF;">'.$result['examination'][$k]['total'].'</td>';
                                                        $tbl .= '</tr>';
                                                        $totalPonts+=$result['examination'][$k]['total'];
                                                        $halfExamCount = $k;
                                                    }
                                                $tbl .= '</tbody>';
                                                if($halfExamCount >= $totalNumberOfExamination){
                                                    $tbl .= '<tfoot border="1">
                                                        <tr border="1">
                                                            <td align="center" style="width:50%;font-size:13px;background-color:#BFBFBF;"></td>
                                                            <td align="center" style="width:25%;font-size:13px;"></td>
                                                            <td align="center" style="width:25%;font-size:13px;background-color:#BFBFBF;">'.$totalPonts.'</td>
                                                        </tr>
                                                    </tfoot>';
                                                }
                                                $tbl .= '</table>
                                            </td>';
                                            if($halfExamCount < $totalNumberOfExamination){
                                                $tbl .= '<td align="center" style="width:50%;"><br>';
                                                    $tbl .= '<table style="width:100%;" border="1" cellpadding="2"  align="center">
                                                        <thead>
                                                            <tr align="center" style="background-color:#f1f1f1;">
                                                                <th align="center" style="width:50%;font-size:14px;"><br><br><b>Section Title</b></th>
                                                                <th align="center" style="width:25%;font-size:14px;"><b>Total Points Obtained</b></th>
                                                                <th align="center" style="width:25%;font-size:14px;background-color:#BFBFBF;"><b>Points Expected</b></th>
                                                            </tr>
                                                        </thead><tbody>';
                                                        for($l=($halfExamCount+1);$l<$totalNumberOfExamination;$l++){
                                                            $tbl .= '<tr cellpadding="2">';
                                                                $tbl .= '<td align="center" style="width:50%;font-size:13px;"><br>'.$result['examination'][$l]['section_name'].'</td>';
                                                                $tbl .= '<td align="center" style="width:25%;font-size:13px;"></td>';
                                                                $tbl .= '<td align="center" style="width:25%;font-size:13px;background-color:#BFBFBF;">'.$result['examination'][$l]['total'].'</td>';
                                                            $tbl .= '</tr>';
                                                            $totalPonts+=$result['examination'][$l]['total'];
                                                        }
                                                    $tbl .= '</table>
                                                </td>';
                                            }
                                        $tbl.='</tr></tbody>
                                        <tfoot border="1">
                                            <tr border="1" style="height:80%;">
                                                <td align="center" style="width:75%;height:80%;font-size:13px;background-color:#BFBFBF;"></td>
                                                <td align="center" style="width:12.5%;height:80%;font-size:13px;"></td>
                                                <td align="center" style="width:12.5%;height:80%;font-size:13px;background-color:#BFBFBF;">'.$totalPonts.'</td>
                                            </tr>
                                        </tfoot>';
                                    }
                                    $tbl.='<tr align="center">
                                        <td align="left" style="width:100%;font-size:12px;"><br><br><b>Total Points obtained: ............................ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Final score obtained: (............../25)*100 =...................% </b></td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:100%;font-size:12px;"><b>Performance recommendation: Satisfactory (≥80%)  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Unsatisfactory (&lt;80%)</b></td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:100%;font-size:12px;">Name and Signature of Proctor/Evaluator: ............................................ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Date: ............../ ............../ .............. </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                <br><br></td>';
    $tbl .= '</tr>';
$tbl .= '</table>';
    
$pdf->writeHTML($tbl);

$pdf->Output(ucfirst('RT Certification') . '_RTCert_Examination_'.date('dMY') . '.pdf', 'I');
exit;