<?php
// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {
    public function Header() {
        $this->SetFont('helveticaI Bold', 'B', 10);
        $this->writeHTMLCell(0,0,10,8,strtoupper($this->firstText), 0, 0, 0, true, 'C', true);
        $this->SetFont('helveticaI Bold', 'B', 8);
        $this->writeHTMLCell(0,0,10,14,strtoupper($this->title), 0, 0, 0, true, 'C', true);
        $this->SetFont('helveticaI Bold', 'B', 7);
        $this->writeHTMLCell(0,0,10,20,strtoupper($this->heading), 0, 0, 0, true, 'C', true);
        $this->SetFont('helveticaI Bold', 'B', 10);
        $this->writeHTMLCell(0,0,10,26,strtoupper($this->secondText), 0, 0, 0, true, 'C', true);
    }
    public static function getPageContentHeight(\TCPDF $pdf, $page)
    {
        // get total height of the page in user units
        $totalHeight = $pdf->getPageHeight($page) / $pdf->getScaleFactor();
        $margin = $pdf->getMargins();
        $pdfHeight->$totalHeight - $margin['bottom'] - $margin['top'];
    }

}

/* create new PDF document */
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, array(280,200),PDF_PAGE_FORMAT, true, 'UTF-8', false);

/* set document information */
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('RT Certification Team');
$pdf->SetTitle('RT Certification');
// $pdf->SetSubject('Airtel Vt');
$pdf->SetKeywords('TCPDF, PDF, RT Certification, RT Cert');

/* set margins */
$pdf->SetMargins(5, 5, 5);
$pdf->SetHeaderMargin(0);
$pdf->SetFooterMargin(0);

/* remove default footer */
$pdf->setPrintFooter(false);

/* set auto page breaks */
$pdf->SetAutoPageBreak(true, PDF_MARGIN_BOTTOM);

/* set image scale factor */
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

/* set some language-dependent strings (optional) */
if (@file_exists(dirname(__FILE__) . '/lang/eng.php')) {
    require_once(dirname(__FILE__) . '/lang/eng.php');
    $pdf->setLanguageArray($l);
}

/* set font */
$pdf->SetFont('helvetica', '', 13);
$pdf->setFontSubsetting(false);

/* remove default header */
$pdf->setPrintHeader(false);
$pdf->SetMargins(12, 12, 12, true);

/* add a page */
$pdf->AddPage();

$tbl = '';
$tbl .= '<table style="width:100%;" border="0" cellpadding="2"  align="center">';
    $tbl .= '<tr align="center">';
        $tbl .= '<td style="width:100%;" align="center"><h3>'.$result['ptpDetails']['title'].'</h3><br></td>';
    $tbl .= '</tr>';
    $tbl .= '<tr align="center">';
        $tbl .= '<td style="width:100%;" align="center">';
            $tbl .= '<table style="width:100%;" border="1" cellpadding="2"  align="center">
                <tr align="center">
                    <td align="center" style="width:5%;font-size:14px;"><b>S/N</b></td>
                    <td align="center" style="width:11%;font-size:14px;"><b>Question Code</b></td>
                    <td align="center" style="width:85%;font-size:14px;"><b>Questions</b></td>
                </tr>';
                foreach($result['questions'] as $sno=>$qRow){
                $tbl .= '<tr cellpadding="2">';
                    $tbl .= '<td align="center" style="width:5%;font-size:13px;"><br><b>'.$sno.'</b></td>';
                    $tbl .= '<td align="center" style="width:11%;font-size:13px;"><b>'.$qRow['questionList']['question_code'].'</b></td>';
                    $tbl .= '<td align="left" style="width:85%;font-size:13px;"><b>'.$qRow['questionList']['question'].'</b>';
                        foreach($qRow['optionList'] as $row) {
                            $tbl .= '<li>'.trim($row).'</li>';
                        }
                    $tbl .='</td>';
                $tbl .= '</tr>';
                }
            $tbl .= '</table>
        </td>
    </tr>';
$tbl .= '</table>';
    
$pdf->writeHTML($tbl);

$pdf->Output(ucfirst('RT Certification') . '_RTCert_Set-' .$ptpId[1] .'_'.date('dMY') . '.pdf', 'I');
exit;