<?php
use Application\Service\CommonService;
use Zend\Session\Container;

$common = new CommonService();
// \Zend\Debug\Debug::dump($ptpId);die;
// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {

    //Page header
    public function setHeading($firstText,$title,$heading,$secondText,$logo) {
        $this->firstText = $firstText;
        $this->heading = $heading;
        $this->title = $title;
        $this->secondText = $secondText;
        $this->logo = $logo;
      }

    public function Header() {
        if (trim($this->logo) != "") {
            if (file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo_image" . DIRECTORY_SEPARATOR . $this->logo)) {
                $image_file = UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo_image" . DIRECTORY_SEPARATOR . $this->logo;
                $this->Image($image_file, 15, 10, 15, '', '', '', 'T', false, 300, '', false, false, 0, false, false, false);
            }
        }
        $this->SetFont('helveticaI Bold', 'B', 10);
        $this->writeHTMLCell(0,0,10,8,strtoupper($this->firstText), 0, 0, 0, true, 'C', true);
        $this->SetFont('helveticaI Bold', 'B', 8);
        $this->writeHTMLCell(0,0,10,14,strtoupper($this->title), 0, 0, 0, true, 'C', true);
        $this->SetFont('helveticaI Bold', 'B', 7);
        $this->writeHTMLCell(0,0,10,20,strtoupper($this->heading), 0, 0, 0, true, 'C', true);
        $this->SetFont('helveticaI Bold', 'B', 10);
        $this->writeHTMLCell(0,0,10,26,strtoupper($this->secondText), 0, 0, 0, true, 'C', true);
    }
    public static function getPageContentHeight(\TCPDF $pdf, $page)
    {
        // get total height of the page in user units
        $totalHeight = $pdf->getPageHeight($page) / $pdf->getScaleFactor();
        $margin = $pdf->getMargins();
        $pdfHeight->$totalHeight - $margin['bottom'] - $margin['top'];
    }

}

/* create new PDF document */
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, array(280,200),PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->setHeading('RT Certification', 'RT Cert', 'Title','Second Title','logo.png');


/* set document information */
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('RT Certification Team');
$pdf->SetTitle('RT Certification');
// $pdf->SetSubject('Airtel Vt');
$pdf->SetKeywords('TCPDF, PDF, RT Certification, RT Cert');

/* set margins */
$pdf->SetMargins(5, 5, 5);
$pdf->SetHeaderMargin(0);
$pdf->SetFooterMargin(0);

/* remove default footer */
$pdf->setPrintFooter(false);

/* set auto page breaks */
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

/* set image scale factor */
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

/* set some language-dependent strings (optional) */
if (@file_exists(dirname(__FILE__) . '/lang/eng.php')) {
    require_once(dirname(__FILE__) . '/lang/eng.php');
    $pdf->setLanguageArray($l);
}

/* set font */
$pdf->SetFont('helvetica', '', 13);
$pdf->setFontSubsetting(false);

/* remove default header */
$pdf->setPrintHeader(false);
$pdf->SetMargins(12, 12, 12, true);

/* add a page */
$pdf->AddPage();
$tbl = '';
$tbl .= '<table style="width:100%;" border="0" cellpadding="2"  align="center">';
    $tbl .= '<tr align="center">';
        $tbl .= '<td style="width:100%;" align="center"><h1>'.$result['ptpDetails']['title'].'</h1></td>';
    $tbl .= '</tr>';
    $tbl .= '<tr align="center">';
        $tbl .= '<td style="width:100%;" align="center">
                    <table border="1" align="center" cellpadding="2" style="width:100%;">
                        <tr>
                            <td style="width:100%;">
                                <table style="width:100%;" cellpadding="2" border="0" align="center">
                                    <tr align="center">
                                        <td align="left" style="font-size:14px;"><u>TESTER IDENTIFICATION</u><br></td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:25%;font-size:13px;">Registration No</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                        <td align="left" style="width:25%;font-size:13px;">Last Name (Surname)*</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:25%;font-size:13px;">First Name*</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                        <td align="left" style="width:25%;font-size:13px;">Middle Name (3rd name)</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:25%;font-size:13px;">Province*</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                        <td align="left" style="width:25%;font-size:13px;">Districts*</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:25%;font-size:13px;">Type of HIV Test Modality/Point*</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                        <td align="left" style="width:25%;font-size:13px;">Phone*</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:25%;font-size:13px;">Email*</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                        <td align="left" style="width:25%;font-size:13px;">Prefered Contact Method*</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:25%;font-size:13px;">Current Job Title*</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                        <td align="left" style="width:25%;font-size:13px;">Facility Name*</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:25%;font-size:13px;">Time Worked As Tester*</td>
                                        <td align="left" style="width:25%;font-size:13px;">___________________<br></td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td style="width:100%;">
                                <table style="width:100%;" cellpadding="2" border="0" align="center">
                                    <tr align="center">
                                        <td align="left" style="font-size:14px;"><u>TESTING SITE IN CHARGE</u><br></td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:14.6%;font-size:13px;">Full Name*</td>
                                        <td align="left" style="width:24.6%;font-size:13px;">___________________<br></td>
                                        <td align="left" style="width:10.6%;font-size:13px;">Phone*</td>
                                        <td align="left" style="width:18.6%;font-size:13px;">______________<br></td>
                                        <td align="left" style="width:10.6%;font-size:13px;">Email*</td>
                                        <td align="left" style="width:18.6%;font-size:13px;">______________<br></td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td style="width:100%;">
                                <table style="width:100%;" cellpadding="2" border="0" align="center">
                                    <tr align="center">
                                        <td align="left" style="font-size:14px;"><u>FACILITY IN CHARGE</u><br></td>
                                    </tr>
                                    <tr align="center">
                                        <td align="left" style="width:14.6%;font-size:13px;">Full Name*</td>
                                        <td align="left" style="width:24.6%;font-size:13px;">___________________<br></td>
                                        <td align="left" style="width:10.6%;font-size:13px;">Phone*</td>
                                        <td align="left" style="width:18.6%;font-size:13px;">______________<br></td>
                                        <td align="left" style="width:10.6%;font-size:13px;">Email*</td>
                                        <td align="left" style="width:18.6%;font-size:13px;">______________<br></td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                <br><br></td>';
    $tbl .= '</tr>
    <tr align="center">
        <td align="left" style="font-size:14px;"><u>ANSWER THE FOLLOWING QUESTIONS</u><br></td>
    </tr>';
    foreach($result['questions'] as $sno=>$qRow){
        $tbl .= '<tr cellpadding="2">';
        $tbl .= '<td align="left" style="width:5%;font-size:13px;"><br><b>'.$sno.'</b></td>';
        $tbl .= '<td align="left" style="width:95%;font-size:13px;"><b>'.$qRow['questionList']['question'].'</b></td>';
        $tbl .= '</tr>';
        
        for($i=0;$i<count($qRow['optionList']);$i++) {
            $tbl .= '<tr cellpadding="2">';
            $tbl .= '<td align="left" style="width:50%;font-size:13px;">'.$qRow['optionList'][$i].'</td>';
            if(isset($qRow['optionList'][($i+1)])){
                $tbl .= '<td align="left" style="width:50%;font-size:13px;">'.$qRow['optionList'][($i+1)].'</td>';
                $i++;
            }
            $tbl .= '</tr>';
        }
        $tbl.='<tr cellpadding="2"><td style="width:100%;font-size:05px;" colspan="2"><hr></td></tr>';
    }
    
$tbl .= '</table>';
    
$pdf->writeHTML($tbl);

$pdf->Output(ucfirst('RT Certification') . '_RTCert_Set-' .$ptpId[1] .'_'.date('dMY') . '.pdf', 'I');
exit;