<?php
// \Zend\Debug\Debug::dump($ptpResult);die;
use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;

if ($this->isAllowed($role, 'Application\Controller\PrintTestPdfController', 'view-pdf-question')) {
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center inline","bSortable":false}';
} else {
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
?>

<style>
    .inline {
        display: inline-flex;
    }

    .action-btn {
        margin-left: 10px !important;
    }
</style>
<!-- DATA TABLES -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>" />
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<div class="am-content">
    <!-- Content Header (Page header) -->
    <div class="page-head">
        <div class="row">
            <div class="col-sm-8">
                <h2>View PDF Questions</h2>
            </div>
            <div class="col-sm-4" style=" margin-top: 10px; ">
                <a href="<?php echo $this->url('print-test-pdf', array('action' => 'index')); ?>" class="btn btn-default pull-right action-btn"><i class="fa fa-arrow-left" aria-hidden="true"> Back to Print Written Test</i></a>
                <?php if ($this->isAllowed($role, 'Application\Controller\PrintTestPdfController', 'examination')) { ?>
                    <a href="<?php echo $this->url('print-test-pdf', array('action' => 'examination', 'id' => $ptpId)); ?>" class="btn btn-success pull-right action-btn" target="_blank"><i class="fa fa-print" aria-hidden="true"> Examination Sheet</i></a>
                <?php } ?>
            </div>
        </div>
    </div>
    <!-- Main content -->
    <div class="main-content">
        <div class="widget-fullwidth widget-small" style="padding:5px;width:100%;">
            <table id="printTestPdfTable" class="table table-bordered table-striped table-hover table-fw-widget">
                <thead>
                    <tr>
                        <th style="width:50%">Title</th>
                        <th style="width:10%">Number of Participant</th>
                        <th style="width:10%">Variant No</th>
                        <th style="width:100%">Test Created By</th>
                        <th style="width:100%">Created On</th>
                        <?php if ($this->isAllowed($role, 'Application\Controller\PrintTestPdfController', 'print-pdf-question')) { ?>
                            <th style="width:10%;display: table-cell;">Action</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="6" class="dataTables_empty">Loading data from server</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<!-- <script type="text/javascript" src="< ?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script> -->
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
    duplicateName = true;
    /* Table initialisation */
    oTable = null;

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'testSection'
        });
        if (flag) {
            if (duplicateName) {
                document.getElementById('testSection').submit();
            }
        }
    }
    $(document).ready(function() {
        oTable = $('#printTestPdfTable').dataTable({
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [
                <?php echo $editAction; ?>
            ],
            "sAjaxSource": "<?php echo $this->url('print-test-pdf', array('action' => 'view-pdf-question')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                // aoData.push({ "name": "pdfTestDate", "value": $("#pdfTestDate").val() });
                // aoData.push({ "name": "pdfTitle", "value": $("#pdfTitle").val() });
                aoData.push({
                    "name": "ptpId",
                    "value": <?php echo $ptpResult['ptp_id']; ?>
                });
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });

        $('#pdfTestDate').daterangepicker({
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                },
                startDate: moment().subtract(29, 'days'),
                endDate: moment()
            },
            function(start, end) {
                $('#pdfTestDate').val(start.format('DD-MMM-YYYY') + ' to ' + end.format('DD-MMM-YYYY'))
            }
        )
    });

    function reDraw() {
        oTable.fnDraw();
    }

    $("#resetValues").click(function() {
        $("#pdfTestDate").val('');
        oTable.fnDraw();
    });
</script>
